GO
	PRINT N'START TRANSFERING PAID BY VALUE TO PARTY'
GO
	IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE UPPER(TABLE_NAME) = 'TBLCTCONTRACTCOST') 
	BEGIN
		IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE UPPER(TABLE_NAME) = 'TBLCTCONTRACTCOST' AND UPPER(COLUMN_NAME) = 'STRPARTY') 
		BEGIN
			EXEC
			('
				ALTER table tblCTContractCost
				ADD strParty NVARCHAR(50) COLLATE Latin1_General_CI_AS
			')
			EXEC
			('
				UPDATE tblCTContractCost SET strParty = strPaidBy
				UPDATE tblCTContractCost SET strPaidBy = NULL
			')
		END		
	END
GO
	PRINT N'END TRANSFERING PAID BY VALUE TO PARTY'
GO