UnitTestEngine.testModel({
    name: 'Inventory.model.Category',
    base: 'iRely.BaseEntity',
    idProperty: 'intCategoryId',
    dependencies: ["Inventory.model.CategoryAccount", "Inventory.model.CategoryLocation", "Inventory.model.CategoryTax", "Inventory.model.CategoryVendor", "Inventory.model.CategoryUOM", "Ext.data.Field"],
    fields: [{
        "name": "intCategoryId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strCategoryCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strInventoryType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intLineOfBusinessId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intCostingMethod",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strInventoryTracking",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblStandardQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strGLDivisionNumber",
        "type": "string",
        "allowNull": false
    }, {
        "name": "ysnSalesAnalysisByTon",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "strMaterialFee",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intMaterialItemId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "ysnAutoCalculateFreight",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intFreightItemId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strERPItemClass",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblLifeTime",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblBOMItemShrinkage",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblBOMItemUpperTolerance",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblBOMItemLowerTolerance",
        "type": "float",
        "allowNull": false
    }, {
        "name": "ysnScaled",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnOutputItemMandatory",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "strConsumptionMethod",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strBOMItemType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strShortName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "imgReceiptImage",
        "type": "string",
        "allowNull": false
    }, {
        "name": "imgWIPImage",
        "type": "string",
        "allowNull": false
    }, {
        "name": "imgFGImage",
        "type": "string",
        "allowNull": false
    }, {
        "name": "imgShipImage",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblLaborCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblOverHead",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblPercentage",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strCostDistributionMethod",
        "type": "string",
        "allowNull": false
    }, {
        "name": "ysnSellable",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnYieldAdjustment",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnWarehouseTracked",
        "type": "boolean",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strCategoryCode",
            "type": "presence"
        }, {
            "field": "strInventoryType",
            "type": "presence"
        }]
    ]
});