Inventory.TestUtils.testModel({
    name: 'Inventory.model.Commodity',
    base: 'iRely.BaseEntity',
    idProperty: 'intCommodityId',
    dependencies: ["Inventory.model.CommodityUnitMeasure", "Inventory.model.CommodityAccount", "Inventory.model.CommodityClass", "Inventory.model.CommodityGrade", "Inventory.model.CommodityOrigin", "Inventory.model.CommodityProductLine", "Inventory.model.CommodityProductType", "Inventory.model.CommodityRegion", "Inventory.model.CommoditySeason", "Ext.data.Field"],
    fields: [{
        "name": "intCommodityId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strCommodityCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "ysnExchangeTraded",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intFutureMarketId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intDecimalDPR",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblConsolidateFactor",
        "type": "float",
        "allowNull": false
    }, {
        "name": "ysnFXExposure",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "dblPriceCheckMin",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblPriceCheckMax",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strCheckoffTaxDesc",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strCheckoffAllState",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strInsuranceTaxDesc",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strInsuranceAllState",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmCropEndDateCurrent",
        "type": "date",
        "allowNull": false
    }, {
        "name": "dtmCropEndDateNew",
        "type": "date",
        "allowNull": false
    }, {
        "name": "strEDICode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intScheduleStoreId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intScheduleDiscountId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intScaleAutoDistId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "ysnAllowLoadContracts",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "dblMaxUnder",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblMaxOver",
        "type": "float",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strCommodityCode",
            "type": "presence"
        }]
    ]
});