UnitTestEngine.testModel({
    name: 'Inventory.model.FiscalPeriod',
    base: 'iRely.BaseEntity',
    idProperty: 'intGLFiscalYearPeriodId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intGLFiscalYearPeriodId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strFiscalYear",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strPeriod",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmStartDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "dtmEndDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "ysnOpen",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnINVOpen",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnStatus",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intFiscalYearId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intStartMonth",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strStartMonth",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intEndMonth",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strEndMonth",
        "type": "string",
        "allowNull": false
    }],
    validators: [
        []
    ]
});