UnitTestEngine.testModel({
    name: 'Inventory.model.FuelType',
    base: 'iRely.BaseEntity',
    idProperty: 'intFuelTypeId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intFuelTypeId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intRinFuelCategoryId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRinFeedStockId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intBatchNumber",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intEndingRinGallons",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strEquivalenceValue",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intRinFuelId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRinProcessId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRinFeedStockUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblFeedStockFactor",
        "type": "float",
        "allowNull": false
    }, {
        "name": "ysnRenewableBiomass",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "dblPercentDenaturant",
        "type": "float",
        "allowNull": false
    }, {
        "name": "ysnDeductDenaturant",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "strFuelCategory",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strRinFuelTypeCodeId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strFeedStock",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strFuelCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strProcessCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strFeedStockUOM",
        "type": "string",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strFuelCategory",
            "type": "presence"
        }, {
            "field": "strFeedStock",
            "type": "presence"
        }, {
            "field": "strFuelCode",
            "type": "presence"
        }, {
            "field": "strProcessCode",
            "type": "presence"
        }, {
            "field": "strFeedStockUOM",
            "type": "presence"
        }]
    ]
});