Inventory.TestUtils.testModel({
    name: 'Inventory.model.FuelType',
    base: 'iRely.BaseEntity',
    idProperty: 'intFuelTypeId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intFuelTypeId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intRinFuelCategoryId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRinFeedStockId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intBatchNumber",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intEndingRinGallons",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strEquivalenceValue",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intRinFuelId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRinProcessId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRinFeedStockUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblFeedStockFactor",
        "type": "float",
        "allowNull": false
    }, {
        "name": "ysnRenewableBiomass",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "dblPercentDenaturant",
        "type": "float",
        "allowNull": false
    }, {
        "name": "ysnDeductDenaturant",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "strRinFuelTypeCodeId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strRinFeedStockId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strRinFuelId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strRinProcessId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strRinFeedStockUOMId",
        "type": "string",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "intFuelTypeId",
            "type": "presence"
        }, {
            "field": "intRinFuelCategoryId",
            "type": "presence"
        }, {
            "field": "intRinFeedStockId",
            "type": "presence"
        }, {
            "field": "intRinFuelId",
            "type": "presence"
        }, {
            "field": "intRinProcessId",
            "type": "presence"
        }, {
            "field": "intRinFeedStockUOMId",
            "type": "presence"
        }]
    ]
});