Inventory.TestUtils.testModel({
    name: "Inventory.model.InventoryValuation",
    base: "Ext.data.Model",
    idProperty: "intItemId",
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intInventoryValuationKeyId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intInventoryTransactionId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strItemNo",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strItemDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intCategoryId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strCategroy",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intItemLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strLocationName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intSubLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strSubLocationName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intStorageLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strStorageLocationName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "strTransactionForm",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strTransactionId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblQuantity",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblBeginningBalance",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblValue",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblRunningBalance",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strBatchId",
        "type": "string",
        "allowNull": false
    }],
    validators: [
        []
    ]
});