UnitTestEngine.testModel({
    name: 'Inventory.model.ItemStockDetailPricing',
    base: 'Ext.data.Model',
    idProperty: 'intItemUnitMeasureId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intItemPricingId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strUpcCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intItemPricingId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intItemLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strLocationName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strLocationType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intItemUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strUnitMeasure",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strUnitType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "ysnStockUnit",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnAllowPurchase",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnAllowSale",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "dblUnitQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblAmountPercent",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblSalePrice",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblMSRPPrice",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strPricingMethod",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblLastCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblStandardCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblAverageCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblEndMonthCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intDecimalPlaces",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }],
    validators: [
        []
    ]
});