Inventory.TestUtils.testModel({
    name: "Inventory.model.ItemStock",
    base: "iRely.BaseEntity",
    idProperty: "intItemStockId",
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intItemStockId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intItemLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblOnOrder",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblInTransitInbound",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblUnitOnHand",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblInTransitOutbound",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblBackOrder",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblOrderCommitted",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblUnitStorage",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblConsignedPurchase",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblConsignedSale",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblUnitReserved",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblLastCountRetail",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblAvailable",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblCalculatedBackOrder",
        "type": "float",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strLocationName",
            "type": "presence"
        }]
    ]
});