UnitTestEngine.testModel({
    name: 'Inventory.model.ItemUOM',
    base: 'iRely.BaseEntity',
    idProperty: 'intItemUOMId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intItemUOMId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblUnitQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblSellQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strUpcCode",
        "type": "string",
        "allowNull": true
    }, {
        "name": "strLongUPCCode",
        "type": "string",
        "allowNull": true
    }, {
        "name": "ysnStockUnit",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnStockUOM",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnAllowPurchase",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnAllowSale",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "dblLength",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblWidth",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblHeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblVolume",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblMaxQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strUnitMeasure",
        "type": "string",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strUnitMeasure",
            "type": "presence"
        }]
    ]
});