UnitTestEngine.testModel({
    name: 'Inventory.model.ItemSpecialPricing',
    base: 'iRely.BaseEntity',
    idProperty: 'intItemSpecialPricingId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intItemSpecialPricingId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intItemLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strPromotionType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmBeginDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "dtmEndDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "intItemUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblUnit",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strDiscountBy",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblDiscount",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblUnitAfterDiscount",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblDiscountThruQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblDiscountThruAmount",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblAccumulatedQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblAccumulatedAmount",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strLocationName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strUnitMeasure",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strUPC",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intCurrencyId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strCurrency",
        "type": "string",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strLocationName",
            "type": "presence"
        }, {
            "field": "strPromotionType",
            "type": "presence"
        }, {
            "field": "strUnitMeasure",
            "type": "presence"
        }, {
            "field": "dblUnit",
            "type": "presence"
        }, {
            "field": "dblDiscount",
            "type": "presence"
        }, {
            "field": "dblUnitAfterDiscount",
            "type": "presence"
        }, {
            "field": "dtmBeginDate",
            "type": "presence"
        }]
    ]
});