UnitTestEngine.testModel({
    name: 'Inventory.model.ReceiptItemTax',
    base: 'iRely.BaseEntity',
    idProperty: 'intInventoryReceiptItemTaxId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intInventoryReceiptItemTaxId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intInventoryReceiptItemId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intTaxGroupMasterId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intTaxGroupId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intTaxCodeId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intTaxClassId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strTaxableByOtherTaxes",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strCalculationMethod",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblRate",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblTax",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblAdjustedTax",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intTaxAccountId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "ysnTaxAdjusted",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnTaxOnly",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnSeparateOnInvoice",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnCheckoffTax",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "strTaxCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strUnitMeasure",
        "type": "string",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "intTaxCodeId",
            "type": "presence"
        }]
    ]
});