Inventory.TestUtils.testModel({
    name: "Inventory.model.ShipmentItemLot",
    base: "iRely.BaseEntity",
    idProperty: "intInventoryShipmentItemLotId",
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intInventoryShipmentItemLotId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intInventoryShipmentItemId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intLotId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblQuantityShipped",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblLotQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblAvailableQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intItemUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intWeightUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblGrossWeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblTareWeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblNetWeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strWarehouseCargoNumber",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strLotId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strUnitMeasure",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblWeightPerQty",
        "type": "float",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strLotId",
            "type": "presence"
        }]
    ]
});