UnitTestEngine.testModel({
    name: 'Inventory.model.Shipment',
    base: 'iRely.BaseEntity',
    idProperty: 'intInventoryShipmentId',
    dependencies: ["Inventory.model.ShipmentItem", "Inventory.model.ShipmentCharge", "Ext.data.Field"],
    fields: [{
        "name": "intInventoryShipmentId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strShipmentNumber",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmShipDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "intOrderType",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intSourceType",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strReferenceNumber",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmRequestedArrivalDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "intShipFromLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intEntityCustomerId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intShipToLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intFreightTermId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intCurrencyId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strBOLNumber",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intShipViaId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strVessel",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strProNumber",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strDriverId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strSealNumber",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strDeliveryInstruction",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmAppointmentTime",
        "type": "date",
        "allowNull": false
    }, {
        "name": "dtmDepartureTime",
        "type": "date",
        "allowNull": false
    }, {
        "name": "dtmArrivalTime",
        "type": "date",
        "allowNull": false
    }, {
        "name": "dtmDeliveredDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "dtmFreeTime",
        "type": "date",
        "allowNull": false
    }, {
        "name": "strReceivedBy",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strComment",
        "type": "string",
        "allowNull": false
    }, {
        "name": "ysnPosted",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intEntityId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intCreatedUserId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strOrderType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strShipFromAddress",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strShipToAddress",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intShipToCompanyLocationId",
        "type": "int",
        "allowNull": true
    }],
    validators: [
        [{
            "field": "dtmShipDate",
            "type": "presence"
        }, {
            "field": "intOrderType",
            "type": "presence"
        }, {
            "field": "intShipFromLocationId",
            "type": "presence"
        }, {
            "field": "intFreightTermId",
            "type": "presence"
        }, {
            "field": "intCurrencyId",
            "type": "presence"
        }]
    ]
});