Inventory.TestUtils.testModel({
    name: 'Inventory.model.Sku',
    base: 'iRely.BaseEntity',
    idProperty: 'intSKUId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intSKUId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intExternalSystemId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strSKU",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intSKUStatusId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strLotCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strSerialNo",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblQuantity",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dtmReceiveDate",
        "type": "date",
        "allowNull": true
    }, {
        "name": "dtmProductionDate",
        "type": "date",
        "allowNull": true
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intContainerId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intOwnerId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strLastUpdateBy",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmLastUpdateOn",
        "type": "date",
        "allowNull": true
    }, {
        "name": "intLotId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intReasonId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strComment",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intParentSKUId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblWeightPerUnit",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intWeightPerUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intUnitPerLayer",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intLayerPerPallet",
        "type": "int",
        "allowNull": false
    }, {
        "name": "ysnSanitized",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "strBatch",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strSKU",
            "type": "presence"
        }]
    ]
});