Inventory.TestUtils.testModel({
    name: "Inventory.model.StorageLocation",
    base: "iRely.BaseEntity",
    idProperty: "intStorageLocationId",
    dependencies: ["Inventory.model.StorageLocationCategory", "Inventory.model.StorageLocationMeasurement", "Inventory.model.StorageLocationSku", "Inventory.model.StorageLocationContainer", "Ext.data.Field"],
    fields: [{
        "name": "intStorageLocationId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intStorageUnitTypeId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intSubLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intParentStorageLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "ysnAllowConsume",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnAllowMultipleItem",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnAllowMultipleLot",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnMergeOnMove",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnCycleCounted",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "ysnDefaultWHStagingUnit",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intRestrictionId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strUnitGroup",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblMinBatchSize",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblBatchSize",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intBatchSizeUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intSequence",
        "type": "int",
        "allowNull": true
    }, {
        "name": "ysnActive",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intRelativeX",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRelativeY",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intRelativeZ",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intCommodityId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblPackFactor",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblEffectiveDepth",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblUnitPerFoot",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblResidualUnit",
        "type": "float",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strName",
            "type": "presence"
        }, {
            "field": "intLocationId",
            "type": "presence"
        }, {
            "field": "intSubLocationId",
            "type": "presence"
        }]
    ]
});