UnitTestEngine.testModel({
    name: 'Inventory.model.StorageMeasurementReadingConversion',
    base: 'iRely.BaseEntity',
    idProperty: 'intStorageMeasurementReadingConversionId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intStorageMeasurementReadingConversionId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intStorageMeasurementReadingId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intCommodityId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intStorageLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intSubLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblAirSpaceReading",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblCashPrice",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strCommodity",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strItemNo",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strStorageLocationName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strSubLocationName",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblEffectiveDepth",
        "type": "float",
        "allowNull": false
    }, {
        "name": "strUnitMeasure",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblUnitPerFoot",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblResidualUnit",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblValue",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblGainLoss",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblOnHand",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblNewOnHand",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblVariance",
        "type": "float",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strItemNo",
            "type": "presence"
        }, {
            "field": "strStorageLocationName",
            "type": "presence"
        }]
    ]
});