Inventory.TestUtils.testModel({
    name: 'Inventory.model.StorageUnitType',
    base: 'iRely.BaseEntity',
    idProperty: 'intStorageUnitTypeId',
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intStorageUnitTypeId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "strStorageUnitType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strInternalCode",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intCapacityUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblMaxWeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "ysnAllowPick",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intDimensionUnitMeasureId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblHeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblDepth",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblWidth",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intPalletStack",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intPalletColumn",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intPalletRow",
        "type": "int",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strStorageUnitType",
            "type": "presence"
        }]
    ]
});