Inventory.TestUtils.testModel({
    name: "Inventory.model.TransferDetail",
    base: "iRely.BaseEntity",
    idProperty: "intInventoryTransferDetailId",
    dependencies: ["Ext.data.Field"],
    fields: [{
        "name": "intInventoryTransferDetailId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intInventoryTransferId",
        "type": "int",
        "allowNull": false
    }, {
        "name": "intSourceId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intItemId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intLotId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intFromSubLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intToSubLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intFromStorageLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intToStorageLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblQuantity",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intItemUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intItemWeightUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblGrossWeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblTareWeight",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intNewLotId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strNewLotId",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblCost",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intTaxCodeId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblFreightRate",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblFreightAmount",
        "type": "float",
        "allowNull": false
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strItemNo",
        "type": "string",
        "allowNull": false
    }, {
        "name": "strUnitMeasure",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dblTaxAmount",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblOriginalAvailableQty",
        "type": "float",
        "allowNull": false
    }, {
        "name": "dblOriginalStorageQty",
        "type": "float",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "strItemNo",
            "type": "presence"
        }, {
            "field": "dblQuantity",
            "type": "presence"
        }]
    ]
});