Inventory.TestUtils.testModel({
    name: 'Inventory.model.Transfer',
    base: 'iRely.BaseEntity',
    idProperty: 'intInventoryTransferId',
    dependencies: ["Inventory.model.TransferDetail", "Inventory.model.TransferNote", "Ext.data.Field"],
    fields: [{
        "name": "intInventoryTransferId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strTransferNo",
        "type": "string",
        "allowNull": false
    }, {
        "name": "dtmTransferDate",
        "type": "date",
        "allowNull": false
    }, {
        "name": "strTransferType",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intSourceType",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intTransferredById",
        "type": "int",
        "allowNull": true
    }, {
        "name": "strDescription",
        "type": "string",
        "allowNull": false
    }, {
        "name": "intFromLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intToLocationId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "ysnShipmentRequired",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intStatusId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intShipViaId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intFreightUOMId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "ysnPosted",
        "type": "boolean",
        "allowNull": false
    }, {
        "name": "intCreatedUserId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intEntityId",
        "type": "int",
        "allowNull": true
    }, {
        "name": "intSort",
        "type": "int",
        "allowNull": true
    }, {
        "name": "dblTaxAmount",
        "type": "float",
        "allowNull": false
    }],
    validators: [
        [{
            "field": "dtmTransferDate",
            "type": "presence"
        }, {
            "field": "strTransferType",
            "type": "presence"
        }, {
            "field": "intFromLocationId",
            "type": "presence"
        }, {
            "field": "intToLocationId",
            "type": "presence"
        }, {
            "field": "intStatusId",
            "type": "presence"
        }]
    ]
});