/*
 * File: app/view/Commodity.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.Commodity', {
    extend: 'Ext.window.Window',
    alias: 'widget.commodity',

    requires: [
        'Inventory.view.Filter',
        'Inventory.view.StatusbarPaging',
        'Ext.toolbar.Separator',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Number',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.column.CheckColumn',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.toolbar.Paging'
    ],

    height: 635,
    hidden: false,
    minHeight: 635,
    minWidth: 950,
    width: 950,
    layout: 'fit',
    collapsible: true,
    iconCls: 'small-icon-i21',
    title: 'Commodity',
    maximizable: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    width: 588,
                    layout: {
                        type: 'hbox',
                        padding: '0 0 0 1'
                    },
                    items: [
                        {
                            xtype: 'button',
                            height: 57,
                            itemId: 'btnNew',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-new',
                            scale: 'large',
                            tabIndex: -1,
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            height: 57,
                            itemId: 'btnSave',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-save',
                            scale: 'large',
                            tabIndex: -1,
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            height: 57,
                            itemId: 'btnFind',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-search',
                            scale: 'large',
                            tabIndex: -1,
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            height: 57,
                            itemId: 'btnDelete',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-delete',
                            scale: 'large',
                            tabIndex: -1,
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            height: 57,
                            itemId: 'btnUndo',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-undo',
                            scale: 'large',
                            tabIndex: -1,
                            text: 'Undo'
                        },
                        {
                            xtype: 'tbseparator',
                            height: 30
                        },
                        {
                            xtype: 'button',
                            height: 57,
                            itemId: 'btnClose',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-close',
                            scale: 'large',
                            tabIndex: -1,
                            text: 'Close'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    autoShow: true,
                    height: 350,
                    itemId: 'frmCommodity',
                    margin: -1,
                    width: 450,
                    bodyBorder: false,
                    bodyPadding: 5,
                    header: false,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            flex: 1,
                            itemId: 'tabCommodity',
                            activeTab: 0,
                            plain: true,
                            items: [
                                {
                                    xtype: 'panel',
                                    bodyPadding: 10,
                                    title: 'Commodity',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1.1,
                                                    margins: '0 5 0 0 ',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'txtCommodityCode',
                                                            fieldLabel: 'Commodity Code',
                                                            labelWidth: 140
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'txtDescription',
                                                            fieldLabel: 'Description',
                                                            labelWidth: 140
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            itemId: 'txtDecimalsOnDpr',
                                                            fieldLabel: 'Decimals on DPR',
                                                            labelWidth: 140,
                                                            hideTrigger: true
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'numberfield',
                                                                    itemId: 'txtConsolidateFactor',
                                                                    fieldLabel: 'Consolidate Factor',
                                                                    labelWidth: 140,
                                                                    hideTrigger: true
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'chkFxExposure',
                                                                    fieldLabel: 'FX Exposure',
                                                                    labelWidth: 164
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'numberfield',
                                                                    itemId: 'txtPriceChecksMin',
                                                                    width: 280,
                                                                    fieldLabel: 'Price Checks - Min',
                                                                    labelWidth: 140,
                                                                    hideTrigger: true
                                                                },
                                                                {
                                                                    xtype: 'numberfield',
                                                                    flex: 1,
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'txtPriceChecksMax',
                                                                    fieldLabel: 'Max',
                                                                    labelWidth: 60,
                                                                    hideTrigger: true
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'combobox',
                                                                    itemId: 'cboCheckoffTaxDesc',
                                                                    width: 280,
                                                                    fieldLabel: 'Checkoff Tax Desc',
                                                                    labelWidth: 140
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    flex: 1,
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'cboCheckoffTaxAllStates',
                                                                    fieldLabel: 'All States',
                                                                    labelWidth: 60
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'combobox',
                                                                    itemId: 'cboInsuranceTaxDesc',
                                                                    width: 280,
                                                                    fieldLabel: 'Insurance Tax Desc',
                                                                    labelWidth: 140
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    flex: 1,
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'cboInsuranceTaxAllStates',
                                                                    fieldLabel: 'All States',
                                                                    labelWidth: 60
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'datefield',
                                                                    itemId: 'dtmCropEndDateCurrent',
                                                                    width: 280,
                                                                    fieldLabel: 'Crop End Date Current',
                                                                    labelWidth: 140
                                                                },
                                                                {
                                                                    xtype: 'datefield',
                                                                    flex: 1,
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'dtmCropEndDateNew',
                                                                    fieldLabel: 'New',
                                                                    labelWidth: 60
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'txtEdiCode',
                                                            fieldLabel: 'EDI Code',
                                                            labelWidth: 140
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'numberfield',
                                                                    itemId: 'txtDefaultScheduleStore',
                                                                    width: 280,
                                                                    fieldLabel: 'Default Schedule Store',
                                                                    labelWidth: 140,
                                                                    hideTrigger: true
                                                                },
                                                                {
                                                                    xtype: 'numberfield',
                                                                    flex: 1,
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'txtDefaultScheduleDiscount',
                                                                    fieldLabel: 'Discount',
                                                                    labelWidth: 60,
                                                                    hideTrigger: true
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    itemId: 'txtTextPurchase',
                                                                    width: 200,
                                                                    fieldLabel: 'Text Purchase',
                                                                    labelWidth: 140
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    margins: '0 5',
                                                                    itemId: 'txtTextSales',
                                                                    width: 135,
                                                                    fieldLabel: 'Text Sales',
                                                                    labelWidth: 70
                                                                },
                                                                {
                                                                    xtype: 'numberfield',
                                                                    flex: 1,
                                                                    itemId: 'txtTextFees',
                                                                    fieldLabel: 'Text Fees',
                                                                    labelWidth: 60,
                                                                    hideTrigger: true
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'txtAgItemNumber',
                                                            width: 280,
                                                            fieldLabel: 'AG Item Number',
                                                            labelWidth: 140
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 1,
                                                            itemId: 'cboScaleAutoDistDefault',
                                                            fieldLabel: 'Scale Auto Dist Default',
                                                            labelWidth: 140
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    itemId: 'chkRequireLoadNoAtKiosk',
                                                                    fieldLabel: 'Require Load No at Kiosk',
                                                                    labelWidth: 140
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    flex: 1,
                                                                    margins: '0 0 0 15',
                                                                    itemId: 'chkAllowVariety',
                                                                    fieldLabel: 'Allow Variety',
                                                                    labelWidth: 80
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    itemId: 'chkAllowLoadContracts',
                                                                    fieldLabel: 'Allow Load Contracts',
                                                                    labelWidth: 140
                                                                },
                                                                {
                                                                    xtype: 'numberfield',
                                                                    flex: 1,
                                                                    margins: '0 0 0 15',
                                                                    itemId: 'txtMaximumUnder',
                                                                    fieldLabel: 'Max Under',
                                                                    labelWidth: 65,
                                                                    hideTrigger: true
                                                                },
                                                                {
                                                                    xtype: 'numberfield',
                                                                    flex: 1,
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'txtMaximumOver',
                                                                    fieldLabel: 'Max Over',
                                                                    labelWidth: 55,
                                                                    hideTrigger: true
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            margins: '0 0 5 0',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'combobox',
                                                                    itemId: 'cboPatronageCategory',
                                                                    width: 280,
                                                                    fieldLabel: 'Patronage Category',
                                                                    labelWidth: 140
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    flex: 1,
                                                                    margins: '0 0 0 5',
                                                                    itemId: 'cboPatronageCategoryDirect',
                                                                    fieldLabel: 'Direct',
                                                                    labelWidth: 60
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    margins: '0 1 0 5',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'UOM',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'advancefiltergrid',
                                            flex: 1,
                                            itemId: 'grdUom',
                                            margin: -1,
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    itemId: 'tlbGridOptions',
                                                    layout: {
                                                        type: 'hbox',
                                                        padding: '0 0 0 1'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDelete',
                                                            iconCls: 'small-delete',
                                                            tabIndex: -1,
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'filter'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'strFieldName',
                                                    text: 'UOM',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'strFieldName',
                                                    text: 'Weight Per Pack',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    text: 'Stock Unit'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 159,
                                                    text: 'Allow Purchase in Stock Unit'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 153,
                                                    text: 'Allow Sale in Stock Unit'
                                                }
                                            ],
                                            viewConfig: {
                                                itemId: 'grvUom'
                                            },
                                            selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                mode: 'SINGLE'
                                            })
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'fit',
                                    title: 'Commodity Group',
                                    items: [
                                        {
                                            xtype: 'advancefiltergrid',
                                            itemId: 'grdCommodityGroup',
                                            margin: -1,
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    itemId: 'tlbGridOptions',
                                                    layout: {
                                                        type: 'hbox',
                                                        padding: '0 0 0 1'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDelete',
                                                            iconCls: 'small-delete',
                                                            tabIndex: -1,
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'filter'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Level'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Commodity Group',
                                                    flex: 1
                                                }
                                            ],
                                            viewConfig: {
                                                itemId: 'grvCommodityGroup'
                                            },
                                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                                            })
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    bodyPadding: 5,
                                    title: 'Attribute',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'advancefiltergrid',
                                                    flex: 1,
                                                    itemId: 'grdOrigin',
                                                    title: 'Origins',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            itemId: 'tlbGridOptions',
                                                            layout: {
                                                                type: 'hbox',
                                                                padding: '0 0 0 1'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnDelete',
                                                                    iconCls: 'small-delete',
                                                                    tabIndex: -1,
                                                                    text: 'Delete'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveUp',
                                                                    iconCls: 'small-up',
                                                                    tabIndex: -1,
                                                                    text: 'Up'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveDown',
                                                                    iconCls: 'small-down',
                                                                    tabIndex: -1,
                                                                    text: 'Down'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Origin',
                                                            flex: 1
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'grvOrigin'
                                                    },
                                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                    })
                                                },
                                                {
                                                    xtype: 'advancefiltergrid',
                                                    flex: 1,
                                                    margins: '0 0 0 5',
                                                    itemId: 'grdProductType',
                                                    title: 'Product Types',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            itemId: 'tlbGridOptions',
                                                            layout: {
                                                                type: 'hbox',
                                                                padding: '0 0 0 1'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnDelete',
                                                                    iconCls: 'small-delete',
                                                                    tabIndex: -1,
                                                                    text: 'Delete'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveUp',
                                                                    iconCls: 'small-up',
                                                                    tabIndex: -1,
                                                                    text: 'Up'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveDown',
                                                                    iconCls: 'small-down',
                                                                    tabIndex: -1,
                                                                    text: 'Down'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Product Type',
                                                            flex: 1
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'grvProductType'
                                                    },
                                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                    })
                                                },
                                                {
                                                    xtype: 'advancefiltergrid',
                                                    flex: 1,
                                                    margins: '0 0 0 5',
                                                    itemId: 'grdRegion',
                                                    title: 'Regions',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            itemId: 'tlbGridOptions',
                                                            layout: {
                                                                type: 'hbox',
                                                                padding: '0 0 0 1'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnDelete',
                                                                    iconCls: 'small-delete',
                                                                    tabIndex: -1,
                                                                    text: 'Delete'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveUp',
                                                                    iconCls: 'small-up',
                                                                    tabIndex: -1,
                                                                    text: 'Up'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveDown',
                                                                    iconCls: 'small-down',
                                                                    tabIndex: -1,
                                                                    text: 'Down'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Region',
                                                            flex: 1
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'grvRegion'
                                                    },
                                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                    })
                                                },
                                                {
                                                    xtype: 'advancefiltergrid',
                                                    flex: 1,
                                                    margins: '0 0 0 5',
                                                    itemId: 'grdClassVarient',
                                                    title: 'Classes and Varients',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            itemId: 'tlbGridOptions',
                                                            layout: {
                                                                type: 'hbox',
                                                                padding: '0 0 0 1'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnDelete',
                                                                    iconCls: 'small-delete',
                                                                    tabIndex: -1,
                                                                    text: 'Delete'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveUp',
                                                                    iconCls: 'small-up',
                                                                    tabIndex: -1,
                                                                    text: 'Up'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveDown',
                                                                    iconCls: 'small-down',
                                                                    tabIndex: -1,
                                                                    text: 'Down'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Class/Varient',
                                                            flex: 1
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'grvClassVarient'
                                                    },
                                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                    })
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            margins: '5 0 0 0',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'advancefiltergrid',
                                                    flex: 1,
                                                    itemId: 'grdSeason',
                                                    title: 'Seasons',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            itemId: 'tlbGridOptions',
                                                            layout: {
                                                                type: 'hbox',
                                                                padding: '0 0 0 1'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnDelete',
                                                                    iconCls: 'small-delete',
                                                                    tabIndex: -1,
                                                                    text: 'Delete'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveUp',
                                                                    iconCls: 'small-up',
                                                                    tabIndex: -1,
                                                                    text: 'Up'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveDown',
                                                                    iconCls: 'small-down',
                                                                    tabIndex: -1,
                                                                    text: 'Down'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Season',
                                                            flex: 1
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'grvSeason'
                                                    },
                                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                    })
                                                },
                                                {
                                                    xtype: 'advancefiltergrid',
                                                    flex: 1,
                                                    margins: '0 0 0 5',
                                                    itemId: 'grdGrade',
                                                    title: 'Grades',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            itemId: 'tlbGridOptions',
                                                            layout: {
                                                                type: 'hbox',
                                                                padding: '0 0 0 1'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnDelete',
                                                                    iconCls: 'small-delete',
                                                                    tabIndex: -1,
                                                                    text: 'Delete'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveUp',
                                                                    iconCls: 'small-up',
                                                                    tabIndex: -1,
                                                                    text: 'Up'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveDown',
                                                                    iconCls: 'small-down',
                                                                    tabIndex: -1,
                                                                    text: 'Down'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Grade',
                                                            flex: 1
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'grvGrade'
                                                    },
                                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                    })
                                                },
                                                {
                                                    xtype: 'advancefiltergrid',
                                                    flex: 1,
                                                    margins: '0 0 0 5',
                                                    itemId: 'grdProductLine',
                                                    title: 'Product Lines',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            itemId: 'tlbGridOptions',
                                                            layout: {
                                                                type: 'hbox',
                                                                padding: '0 0 0 1'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnDelete',
                                                                    iconCls: 'small-delete',
                                                                    tabIndex: -1,
                                                                    text: 'Delete'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveUp',
                                                                    iconCls: 'small-up',
                                                                    tabIndex: -1,
                                                                    text: 'Up'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMoveDown',
                                                                    iconCls: 'small-down',
                                                                    tabIndex: -1,
                                                                    text: 'Down'
                                                                }
                                                            ]
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'Product Line',
                                                            flex: 1
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'grvProductLine'
                                                    },
                                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                    })
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    margins: '0 0 0 5'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'fit',
                                    title: 'Quality Specifications',
                                    items: [
                                        {
                                            xtype: 'advancefiltergrid',
                                            itemId: 'grdQuality',
                                            margin: -1,
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    itemId: 'tlbGridOptions',
                                                    layout: {
                                                        type: 'hbox',
                                                        padding: '0 0 0 1'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDelete',
                                                            iconCls: 'small-delete',
                                                            tabIndex: -1,
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'filter'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Grade',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Description',
                                                    flex: 2
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Unit',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 60,
                                                    align: 'right',
                                                    text: 'Min Value'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 60,
                                                    align: 'right',
                                                    text: 'Max Value'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 55,
                                                    text: 'Discount'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 80,
                                                    align: 'right',
                                                    text: 'Discount Basis'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 60,
                                                    align: 'right',
                                                    text: 'Discount'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Per Currency/Unit'
                                                }
                                            ],
                                            viewConfig: {
                                                itemId: 'grvQuality'
                                            },
                                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                                            })
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'BOT',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'advancefiltergrid',
                                            flex: 1,
                                            itemId: 'grdBoardOfTrade',
                                            margin: -1,
                                            title: 'Board of Trade',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    itemId: 'tlbGridOptions',
                                                    layout: {
                                                        type: 'hbox',
                                                        padding: '0 0 0 1'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDelete',
                                                            iconCls: 'small-delete',
                                                            tabIndex: -1,
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'filter'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Board of Trade',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Default BOT',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Hedged By',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Price Currency',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Price UOM',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Hedge UOM',
                                                    flex: 1
                                                }
                                            ],
                                            viewConfig: {
                                                itemId: 'grvBoardOfTrade'
                                            },
                                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                                            })
                                        },
                                        {
                                            xtype: 'advancefiltergrid',
                                            flex: 1,
                                            margins: '5 0 0 0',
                                            itemId: 'grdBoardOfTradeOptions',
                                            margin: -1,
                                            title: 'Board of Trade Options',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    itemId: 'tlbGridOptions',
                                                    layout: {
                                                        type: 'hbox',
                                                        padding: '0 0 0 1'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDelete',
                                                            iconCls: 'small-delete',
                                                            tabIndex: -1,
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'filter'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Board of Trade',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'BOT Month Code',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'BOT Month Name',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    text: 'Expired'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    text: 'Start Date'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    text: 'End Date'
                                                }
                                            ],
                                            viewConfig: {
                                                itemId: 'grvBoardOfTradeOptions'
                                            },
                                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                                            })
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'fit',
                                    title: 'GL Accounts',
                                    items: [
                                        {
                                            xtype: 'advancefiltergrid',
                                            itemId: 'grdGlAccounts',
                                            margin: -1,
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    itemId: 'tlbGridOptions',
                                                    layout: {
                                                        type: 'hbox',
                                                        padding: '0 0 0 1'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDelete',
                                                            iconCls: 'small-delete',
                                                            tabIndex: -1,
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'tbseparator'
                                                        },
                                                        {
                                                            xtype: 'filter'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Location',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Account Type',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Account Id',
                                                    flex: 1
                                                }
                                            ],
                                            viewConfig: {
                                                itemId: 'grvGlAccounts'
                                            },
                                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                                            })
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'ipagingstatusbar101',
                            itemId: 'tlbStatusbarPaging',
                            flex: 1,
                            dock: 'bottom'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});