/*
 * File: app/view/ContractDocument.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.ContractDocument', {
    extend: 'Ext.window.Window',
    alias: 'widget.contractdocument',

    requires: [
        'Inventory.view.ContractDocumentViewModel',
        'Inventory.view.StatusbarPaging1',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'contractdocument'
    },
    height: 250,
    hidden: false,
    maxHeight: 250,
    minHeight: 250,
    minWidth: 400,
    width: 400,
    layout: 'fit',
    collapsible: true,
    iconCls: 'small-icon-i21',
    title: 'Contract Document',
    maximizable: true,

    items: [
        {
            xtype: 'form',
            autoShow: true,
            height: 350,
            itemId: 'frmContractDocument',
            margin: -1,
            width: 450,
            bodyBorder: false,
            bodyPadding: 10,
            header: false,
            trackResetOnLoad: true,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    width: 588,
                    layout: {
                        type: 'hbox',
                        padding: '0 0 0 1'
                    },
                    items: [
                        {
                            xtype: 'button',
                            tabIndex: -1,
                            height: 57,
                            itemId: 'btnNew',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-new',
                            scale: 'large',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            tabIndex: -1,
                            height: 57,
                            itemId: 'btnSave',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-save',
                            scale: 'large',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            tabIndex: -1,
                            height: 57,
                            itemId: 'btnSearch',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-search',
                            scale: 'large',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            tabIndex: -1,
                            height: 57,
                            itemId: 'btnDelete',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-delete',
                            scale: 'large',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            tabIndex: -1,
                            height: 57,
                            itemId: 'btnUndo',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-undo',
                            scale: 'large',
                            text: 'Undo'
                        },
                        {
                            xtype: 'tbseparator',
                            height: 30
                        },
                        {
                            xtype: 'button',
                            tabIndex: -1,
                            height: 57,
                            itemId: 'btnClose',
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-close',
                            scale: 'large',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    itemId: 'pagingtoolbar',
                    flex: 1,
                    dock: 'bottom'
                }
            ],
            items: [
                {
                    xtype: 'container',
                    flex: 1.25,
                    margin: '0 5 0 0',
                    width: 1014,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'txtDocumentName',
                            fieldLabel: 'Document Name',
                            labelWidth: 105
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtDescription',
                            fieldLabel: 'Description',
                            labelWidth: 105
                        },
                        {
                            xtype: 'gridcombobox',
                            columns: [
                                {
                                    dataIndex: 'intDocumentId',
                                    dataType: 'numeric',
                                    text: 'Document Id',
                                    hidden: true
                                },
                                {
                                    dataIndex: 'strDocumentName',
                                    dataType: 'string',
                                    text: 'Document Name',
                                    flex: 1
                                },
                                {
                                    dataIndex: 'strDescription',
                                    dataType: 'string',
                                    text: 'Description',
                                    flex: 1
                                },
                                {
                                    dataIndex: 'ysnStandard',
                                    dataType: 'boolean',
                                    text: 'Standard',
                                    flex: 1
                                }
                            ],
                            itemId: 'cboCommodity',
                            width: 170,
                            fieldLabel: 'Commodity',
                            labelWidth: 105,
                            displayField: 'strDocumentName',
                            valueField: 'intDocumentId'
                        },
                        {
                            xtype: 'checkboxfield',
                            itemId: 'chkStandard',
                            fieldLabel: 'Standard',
                            labelWidth: 105
                        }
                    ]
                }
            ]
        }
    ]

});