/*
 * File: app/view/FuturesExchange.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.FuturesExchange', {
    extend: 'Ext.window.Window',
    alias: 'widget.futuresexchange',

    requires: [
        'Inventory.view.FuturesExchangeViewModel',
        'Inventory.view.StatusbarPaging',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.form.Label',
        'Ext.form.field.TextArea',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'futuresexchange'
    },
    height: 390,
    hidden: false,
    maxHeight: 390,
    minHeight: 385,
    minWidth: 475,
    width: 475,
    layout: 'fit',
    collapsible: true,
    iconCls: 'small-icon-i21',
    title: 'Futures Exchange',
    maximizable: true,

    items: [
        {
            xtype: 'form',
            reference: 'frmFuturesExchange',
            autoShow: true,
            height: 350,
            margin: -1,
            width: 450,
            bodyBorder: false,
            bodyPadding: 10,
            header: false,
            trackResetOnLoad: true,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    width: 588,
                    layout: {
                        type: 'hbox',
                        padding: '0 0 0 1'
                    },
                    items: [
                        {
                            xtype: 'button',
                            reference: 'btnNew',
                            tabIndex: -1,
                            height: 57,
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-new',
                            scale: 'large',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            reference: 'btnSave',
                            tabIndex: -1,
                            height: 57,
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-save',
                            scale: 'large',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            reference: 'btnSearch',
                            tabIndex: -1,
                            height: 57,
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-search',
                            scale: 'large',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            reference: 'btnDelete',
                            tabIndex: -1,
                            height: 57,
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-delete',
                            scale: 'large',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            reference: 'btnUndo',
                            tabIndex: -1,
                            height: 57,
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-undo',
                            scale: 'large',
                            text: 'Undo'
                        },
                        {
                            xtype: 'tbseparator',
                            height: 30
                        },
                        {
                            xtype: 'button',
                            reference: 'btnClose',
                            tabIndex: -1,
                            height: 57,
                            width: 45,
                            iconAlign: 'top',
                            iconCls: 'large-close',
                            scale: 'large',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    reference: 'pagingtoolbar',
                    flex: 1,
                    dock: 'bottom'
                }
            ],
            items: [
                {
                    xtype: 'container',
                    flex: 1.25,
                    margin: '0 5 0 0',
                    width: 1014,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'txtExchangeCode',
                            width: 170,
                            fieldLabel: 'Exchange Code',
                            labelWidth: 95
                        },
                        {
                            xtype: 'textfield',
                            reference: 'txtExchangeName',
                            width: 170,
                            fieldLabel: 'Exchange Name',
                            labelWidth: 95
                        },
                        {
                            xtype: 'container',
                            height: 58,
                            margin: '0 0 5 0 ',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    padding: '3 0 0 0',
                                    width: 78,
                                    text: 'Address:'
                                },
                                {
                                    xtype: 'container',
                                    width: 22,
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'button',
                                            reference: 'btnAddressMap',
                                            tabIndex: -1,
                                            style: {
                                                background: 'transparent',
                                                borderColor: 'transparent'
                                            },
                                            iconCls: 'small-map'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    flex: 1,
                                    reference: 'txtAddress',
                                    height: 58,
                                    hideLabel: true,
                                    labelWidth: 0
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '0 0 5 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1.2,
                                    reference: 'cboZipCode',
                                    fieldLabel: 'Zip/Postal Code',
                                    labelWidth: 95
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'txtCity',
                                    margin: '0 0 0 5',
                                    fieldLabel: 'City',
                                    labelWidth: 50
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '0 0 5 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1.2,
                                    reference: 'txtState',
                                    fieldLabel: 'State/Province',
                                    labelWidth: 95
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    reference: 'cboCountry',
                                    margin: '0 0 0 5',
                                    fieldLabel: 'Country',
                                    labelWidth: 50
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '0 0 5 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1.2,
                                    reference: 'txtPhone',
                                    fieldLabel: 'Phone',
                                    labelWidth: 95
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'txtFax',
                                    margin: '0 0 0 5',
                                    fieldLabel: 'Fax',
                                    labelWidth: 50
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 22,
                            margin: '0 0 5 0 ',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    padding: '3 0 0 0',
                                    width: 78,
                                    text: 'Website:'
                                },
                                {
                                    xtype: 'container',
                                    width: 22,
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'button',
                                            reference: 'btnWebsite',
                                            tabIndex: -1,
                                            style: {
                                                background: 'transparent',
                                                borderColor: 'transparent'
                                            },
                                            iconAlign: 'right',
                                            iconCls: 'small-web'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'txtWebsite',
                                    hideLabel: true,
                                    labelWidth: 0
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 22,
                            margin: '0 0 5 0 ',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    padding: '3 0 0 0',
                                    width: 78,
                                    text: 'Email:'
                                },
                                {
                                    xtype: 'container',
                                    width: 22,
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'button',
                                            reference: 'btnEmail',
                                            tabIndex: -1,
                                            style: {
                                                background: 'transparent',
                                                borderColor: 'transparent'
                                            },
                                            iconCls: 'small-email'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'txtEmail',
                                    hideLabel: true,
                                    labelWidth: 0
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});