/*
 * File: app/view/InventoryTransfer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.InventoryTransfer', {
    extend: 'Ext.window.Window',
    alias: 'widget.inventorytransfer',

    requires: [
        'Inventory.view.Filter1',
        'Inventory.view.StatusbarPaging1',
        'Ext.form.Panel',
        'Ext.toolbar.Separator',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.form.Label',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Number',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    height: 700,
    hidden: false,
    minHeight: 510,
    minWidth: 860,
    width: 950,
    layout: 'fit',
    collapsible: true,
    iconCls: 'small-icon-i21',
    title: 'Inventory Transfer',
    defaultFocus: 'cboTransferredBy',
    maximizable: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'form',
                        height: 350,
                        itemId: 'frmInventoryTransfer',
                        margin: -1,
                        width: 450,
                        layout: 'fit',
                        bodyPadding: 5,
                        dockedItems: [
                            {
                                xtype: 'toolbar',
                                dock: 'top',
                                formBind: true,
                                itemId: 'payBillsDetailToolbar',
                                width: 588,
                                layout: {
                                    type: 'hbox',
                                    padding: '0 0 0 1'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnNew',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-new',
                                        scale: 'large',
                                        text: 'New'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnSave',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-save',
                                        scale: 'large',
                                        text: 'Save'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnSearch',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-search',
                                        scale: 'large',
                                        text: 'Search'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnDelete',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-delete',
                                        scale: 'large',
                                        text: 'Delete'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnUndo',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-undo',
                                        scale: 'large',
                                        text: 'Undo'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnPrint',
                                        width: 52,
                                        iconAlign: 'top',
                                        iconCls: 'large-print',
                                        scale: 'large',
                                        text: 'Print'
                                    },
                                    {
                                        xtype: 'tbseparator',
                                        height: 30
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnPost',
                                        width: 52,
                                        iconAlign: 'top',
                                        iconCls: 'large-post',
                                        scale: 'large',
                                        text: 'Post'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        hidden: true,
                                        itemId: 'btnUnpost',
                                        width: 52,
                                        iconAlign: 'top',
                                        iconCls: 'large-unpost',
                                        scale: 'large',
                                        text: 'Unpost'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnNotes',
                                        width: 50,
                                        iconAlign: 'top',
                                        iconCls: 'large-notes',
                                        scale: 'large',
                                        text: 'Notes'
                                    },
                                    {
                                        xtype: 'tbseparator',
                                        height: 30
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnClose',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-close',
                                        scale: 'large',
                                        text: 'Close'
                                    }
                                ]
                            },
                            {
                                xtype: 'ipagingstatusbar',
                                dock: 'bottom'
                            }
                        ],
                        items: [
                            {
                                xtype: 'tabpanel',
                                itemId: 'tabInventoryTransfer',
                                activeTab: 0,
                                plain: true,
                                items: [
                                    {
                                        xtype: 'panel',
                                        bodyPadding: 5,
                                        title: 'Details',
                                        layout: {
                                            type: 'vbox',
                                            align: 'stretch'
                                        },
                                        items: [
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'stretch'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'vbox',
                                                            align: 'stretch'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'container',
                                                                layout: {
                                                                    type: 'vbox',
                                                                    align: 'stretch'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'combobox',
                                                                        flex: 1,
                                                                        itemId: 'cboTransferType',
                                                                        fieldLabel: 'Transfer Type',
                                                                        labelWidth: 90
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        flex: 1,
                                                                        itemId: 'cboTransferredBy',
                                                                        fieldLabel: 'Transferred By',
                                                                        labelWidth: 90
                                                                    },
                                                                    {
                                                                        xtype: 'container',
                                                                        flex: 1,
                                                                        margin: '0 0 5 0 ',
                                                                        layout: {
                                                                            type: 'hbox',
                                                                            align: 'stretch'
                                                                        },
                                                                        items: [
                                                                            {
                                                                                xtype: 'datefield',
                                                                                flex: 1,
                                                                                itemId: 'dtmTransferDate',
                                                                                fieldLabel: 'Transfer Date',
                                                                                labelWidth: 90
                                                                            },
                                                                            {
                                                                                xtype: 'checkboxfield',
                                                                                itemId: 'chkShipmentRequired',
                                                                                margin: '0 0 0 5',
                                                                                fieldLabel: 'Shipment Required',
                                                                                labelWidth: 110
                                                                            }
                                                                        ]
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        flex: 1,
                                                                        itemId: 'txtTransferNumber',
                                                                        fieldLabel: 'Transfer No',
                                                                        labelWidth: 90
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                flex: 1,
                                                                itemId: 'txtDescription',
                                                                fieldLabel: 'Description',
                                                                labelWidth: 90
                                                            },
                                                            {
                                                                xtype: 'container',
                                                                layout: {
                                                                    type: 'vbox',
                                                                    align: 'stretch'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'combobox',
                                                                        flex: 1,
                                                                        itemId: 'cboFromLocation',
                                                                        fieldLabel: 'From Location',
                                                                        labelWidth: 90
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        flex: 1,
                                                                        itemId: 'cboToLocation',
                                                                        fieldLabel: 'To Location',
                                                                        labelWidth: 90
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'vbox',
                                                            align: 'stretch'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                itemId: 'pnlFreight',
                                                                margin: '0 0 0 5',
                                                                bodyPadding: 5,
                                                                title: 'Freight & Taxes',
                                                                layout: {
                                                                    type: 'vbox',
                                                                    align: 'stretch'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboCarrier',
                                                                        fieldLabel: 'Carrier',
                                                                        labelWidth: 120
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboFreightUOM',
                                                                        fieldLabel: 'Freight UOM',
                                                                        labelWidth: 120
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboAccountCategory',
                                                                        fieldLabel: 'Account Category',
                                                                        labelWidth: 120
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboAccountID',
                                                                        fieldLabel: 'Account ID',
                                                                        labelWidth: 120
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtAccountDescription',
                                                                        fieldLabel: 'Account Description',
                                                                        labelWidth: 120
                                                                    },
                                                                    {
                                                                        xtype: 'numberfield',
                                                                        itemId: 'txtTaxAmount',
                                                                        fieldLabel: 'Tax Amount',
                                                                        labelWidth: 120,
                                                                        hideTrigger: true
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'advancefiltergrid',
                                                flex: 1.2,
                                                reference: 'grdInventoryTransfer',
                                                itemId: 'grdInventoryTransfer',
                                                margin: '7 0 0 0',
                                                dockedItems: [
                                                    {
                                                        xtype: 'toolbar',
                                                        dock: 'top',
                                                        itemId: 'tlbToolbarGrid',
                                                        layout: {
                                                            type: 'hbox',
                                                            padding: '0 0 0 1'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                margin: '0 7 0 5',
                                                                text: 'Items'
                                                            },
                                                            {
                                                                xtype: 'tbseparator'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnAddItem',
                                                                iconCls: 'small-add',
                                                                text: 'Add'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnEditItem',
                                                                iconCls: 'small-edit',
                                                                text: 'Edit'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnRemoveItem',
                                                                iconCls: 'small-delete',
                                                                text: 'Remove'
                                                            },
                                                            {
                                                                xtype: 'tbseparator'
                                                            },
                                                            {
                                                                xtype: 'filter1'
                                                            }
                                                        ]
                                                    }
                                                ],
                                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                    selType: 'checkboxmodel'
                                                }),
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colItemNumber',
                                                        width: 100,
                                                        dataIndex: 'strItemNumber',
                                                        text: 'Item No.'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colDescription',
                                                        width: 150,
                                                        dataIndex: 'strDescription',
                                                        text: 'Description'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colLotID',
                                                        width: 100,
                                                        dataIndex: 'strLotID',
                                                        text: 'Lot ID'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colFromSubLocation',
                                                        width: 110,
                                                        dataIndex: 'strFromSubLocation',
                                                        text: 'From Sub Location'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colFromStorage',
                                                        width: 88,
                                                        dataIndex: 'strFromStorage',
                                                        text: 'From Storage'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colToSubLocation',
                                                        width: 96,
                                                        dataIndex: 'strToSubLocation',
                                                        text: 'To Sub Location'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colToStorage',
                                                        width: 88,
                                                        dataIndex: 'strToStorage',
                                                        text: 'To Storage'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQuantity',
                                                        width: 65,
                                                        align: 'right',
                                                        dataIndex: 'dblQuantity',
                                                        text: 'Quantity',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colUOM',
                                                        width: 70,
                                                        dataIndex: 'strUOM',
                                                        text: 'UOM'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colWeightUOM',
                                                        width: 75,
                                                        dataIndex: 'strWeightUOM',
                                                        text: 'Weight UOM'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colGross',
                                                        width: 65,
                                                        align: 'right',
                                                        dataIndex: 'dblGross',
                                                        text: 'Gross',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colTare',
                                                        width: 65,
                                                        align: 'right',
                                                        dataIndex: 'dblTare',
                                                        text: 'Tare',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colNet',
                                                        width: 65,
                                                        align: 'right',
                                                        dataIndex: 'dblNet',
                                                        text: 'Net',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colNewLotID',
                                                        width: 75,
                                                        dataIndex: 'strNewLotID',
                                                        text: 'New Lot ID'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colCost',
                                                        width: 65,
                                                        align: 'right',
                                                        dataIndex: 'dblCost',
                                                        text: 'Cost',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colCreditAccount',
                                                        width: 90,
                                                        dataIndex: 'strCreditAccount',
                                                        text: 'Credit Account'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colCreditAccountDescription',
                                                        width: 90,
                                                        dataIndex: 'strCreditAccountDescription',
                                                        text: 'Description'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colDebitAccount',
                                                        width: 90,
                                                        dataIndex: 'strDebitAccount',
                                                        text: 'Debit Account'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colDebitAccountDescription',
                                                        width: 90,
                                                        dataIndex: 'strDebitAccountDescription',
                                                        text: 'Description'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        dataIndex: 'strTaxCode',
                                                        itemId: 'colTaxCode',
                                                        width: 69,
                                                        text: 'Tax Code'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colTaxAmount',
                                                        width: 85,
                                                        align: 'right',
                                                        dataIndex: 'dblTaxAmount',
                                                        text: 'Tax Amount',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colFreightRate',
                                                        width: 85,
                                                        align: 'right',
                                                        dataIndex: 'dblFreightRate',
                                                        text: 'Freight Rate',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colFreightAmount',
                                                        width: 100,
                                                        align: 'right',
                                                        dataIndex: 'dblFreightAmount',
                                                        text: 'Freight Amount',
                                                        format: '0,000.##'
                                                    }
                                                ],
                                                plugins: [
                                                    Ext.create('Ext.grid.plugin.CellEditing', {
                                                        pluginId: 'cepItem',
                                                        clicksToEdit: 1
                                                    })
                                                ],
                                                viewConfig: {
                                                    itemId: 'grvInventoryTransfer'
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'Notes',
                                        layout: {
                                            type: 'vbox',
                                            align: 'stretch'
                                        },
                                        items: [
                                            {
                                                xtype: 'advancefiltergrid',
                                                flex: 1,
                                                itemId: 'grdNotes',
                                                margin: -1,
                                                dockedItems: [
                                                    {
                                                        xtype: 'toolbar',
                                                        dock: 'top',
                                                        itemId: 'tlbGridOptions',
                                                        layout: {
                                                            type: 'hbox',
                                                            padding: '0 0 0 1'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnAddNotes',
                                                                iconCls: 'small-add',
                                                                text: 'Add'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnRemoveNotes',
                                                                iconCls: 'small-delete',
                                                                text: 'Remove'
                                                            },
                                                            {
                                                                xtype: 'tbseparator'
                                                            },
                                                            {
                                                                xtype: 'filter1'
                                                            }
                                                        ]
                                                    }
                                                ],
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colNoteLocation',
                                                        dataIndex: 'string',
                                                        text: 'Location',
                                                        flex: 1
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colNoteType',
                                                        dataIndex: 'string',
                                                        text: 'Note Type',
                                                        flex: 1
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colNote',
                                                        dataIndex: 'string',
                                                        text: 'Notes',
                                                        flex: 3
                                                    }
                                                ],
                                                viewConfig: {
                                                    itemId: 'grvNotes'
                                                },
                                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                    selType: 'checkboxmodel'
                                                }),
                                                plugins: [
                                                    {
                                                        ptype: 'cellediting',
                                                        pluginId: 'cepNote',
                                                        clicksToEdit: 1
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: 'fit',
                                        title: 'Attachments',
                                        items: [
                                            {
                                                xtype: 'attachmentgrid',
                                                itemId: 'grdAttachment',
                                                margin: -1,
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        dataIndex: 'string',
                                                        text: 'String'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    }

});