/*
 * File: app/view/InventoryShipment.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.InventoryShipment', {
    extend: 'Ext.window.Window',
    alias: 'widget.inventoryshipment',

    requires: [
        'Inventory.view.Filter1',
        'Inventory.view.StatusbarPaging1',
        'Ext.form.Panel',
        'Ext.toolbar.Separator',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.grid.Panel',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.grid.column.Action',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.View',
        'Ext.form.Label',
        'Ext.toolbar.Paging'
    ],

    height: 700,
    hidden: false,
    minHeight: 510,
    minWidth: 860,
    width: 1100,
    layout: 'fit',
    collapsible: true,
    iconCls: 'small-icon-i21',
    title: 'Inventory Shipment',
    defaultFocus: 'cboVendorId',
    maximizable: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'form',
                        height: 350,
                        itemId: 'frmInventoryShipment',
                        margin: -1,
                        width: 450,
                        layout: 'fit',
                        bodyPadding: 5,
                        dockedItems: [
                            {
                                xtype: 'toolbar',
                                dock: 'top',
                                formBind: true,
                                itemId: 'payBillsDetailToolbar',
                                width: 588,
                                layout: {
                                    type: 'hbox',
                                    padding: '0 0 0 1'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnNew',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-new',
                                        scale: 'large',
                                        text: 'New'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnSave',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-save',
                                        scale: 'large',
                                        text: 'Save'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnSearch',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-search',
                                        scale: 'large',
                                        text: 'Search'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnDelete',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-delete',
                                        scale: 'large',
                                        text: 'Delete'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnUndo',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-undo',
                                        scale: 'large',
                                        text: 'Undo'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnPrint',
                                        width: 52,
                                        iconAlign: 'top',
                                        iconCls: 'large-print',
                                        scale: 'large',
                                        text: 'Print'
                                    },
                                    {
                                        xtype: 'tbseparator',
                                        height: 30
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnShip',
                                        width: 52,
                                        iconAlign: 'top',
                                        iconCls: 'large-generate-invoice',
                                        scale: 'large',
                                        text: 'Ship'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnDuplicate',
                                        width: 59,
                                        iconAlign: 'top',
                                        iconCls: 'large-duplicate',
                                        scale: 'large',
                                        text: 'Duplicate'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        hidden: true,
                                        itemId: 'btnUnpost',
                                        width: 52,
                                        iconAlign: 'top',
                                        iconCls: 'large-unpost',
                                        scale: 'large',
                                        text: 'Unpost'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnCustomer',
                                        width: 61,
                                        iconAlign: 'top',
                                        iconCls: 'large-customer',
                                        scale: 'large',
                                        text: 'Customer'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnInventory',
                                        width: 60,
                                        iconAlign: 'top',
                                        iconCls: 'large-pallet',
                                        scale: 'large',
                                        text: 'Inventory'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnNotes',
                                        width: 50,
                                        iconAlign: 'top',
                                        iconCls: 'large-notes',
                                        scale: 'large',
                                        text: 'Notes'
                                    },
                                    {
                                        xtype: 'tbseparator',
                                        height: 30
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnClose',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-close',
                                        scale: 'large',
                                        text: 'Close'
                                    }
                                ]
                            },
                            {
                                xtype: 'ipagingstatusbar',
                                dock: 'bottom'
                            }
                        ],
                        items: [
                            {
                                xtype: 'tabpanel',
                                itemId: 'tabInventoryShipment',
                                activeTab: 0,
                                plain: true,
                                items: [
                                    {
                                        xtype: 'panel',
                                        bodyPadding: 5,
                                        title: 'Details',
                                        layout: {
                                            type: 'vbox',
                                            align: 'stretch'
                                        },
                                        items: [
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'stretch'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        flex: 3,
                                                        layout: {
                                                            type: 'hbox',
                                                            align: 'stretch'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'container',
                                                                flex: 1,
                                                                margin: '0 5 0 0',
                                                                layout: {
                                                                    type: 'vbox',
                                                                    align: 'stretch'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtBOLNumber',
                                                                        fieldLabel: 'BOL No',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'datefield',
                                                                        itemId: 'dtmShipDate',
                                                                        fieldLabel: 'Ship Date',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboOrderType',
                                                                        fieldLabel: 'Order Type',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtReferenceNumber',
                                                                        fieldLabel: 'Reference Number',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'datefield',
                                                                        itemId: 'dtmRequestedArrival',
                                                                        fieldLabel: 'Requested Arrival',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboShipFromAddress',
                                                                        fieldLabel: 'Ship From Address',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboShipToAddress',
                                                                        fieldLabel: 'Ship To Address',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboCustomer',
                                                                        fieldLabel: 'Customer',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'gridcombobox',
                                                                        itemId: 'cboCarrier',
                                                                        fieldLabel: 'Carrier',
                                                                        labelWidth: 110
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'container',
                                                                flex: 1,
                                                                margin: '0 0 0 5',
                                                                layout: {
                                                                    type: 'vbox',
                                                                    align: 'stretch'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'gridcombobox',
                                                                        itemId: 'cboStagingLocation',
                                                                        fieldLabel: 'Staging Location',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtDockDoor',
                                                                        fieldLabel: 'Dock Door',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtSealNumber',
                                                                        fieldLabel: 'Seal Number',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtProNumber',
                                                                        fieldLabel: 'Pro Number',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtVehicleNumber',
                                                                        fieldLabel: 'Vehicle Number',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtDriverID',
                                                                        fieldLabel: 'Driver ID',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboFreightTerms',
                                                                        fieldLabel: 'Freight Terms',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtAppointmentTime',
                                                                        fieldLabel: 'Appointment Time',
                                                                        labelWidth: 110
                                                                    },
                                                                    {
                                                                        xtype: 'gridcombobox',
                                                                        itemId: 'txtArrivalTime',
                                                                        fieldLabel: 'Arrival Time',
                                                                        labelWidth: 110
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'container',
                                                                flex: 1,
                                                                margin: '0 0 0 5',
                                                                layout: {
                                                                    type: 'vbox',
                                                                    align: 'stretch'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtDepartureTime',
                                                                        fieldLabel: 'Departure Time',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtComments',
                                                                        fieldLabel: 'Comments',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtDeliveryInstructions',
                                                                        fieldLabel: 'Delivery Instructions',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'datefield',
                                                                        itemId: 'dtmDelivered',
                                                                        fieldLabel: 'Delivered Date',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'datefield',
                                                                        itemId: 'dtmFreeTime',
                                                                        fieldLabel: 'Free Time',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'textfield',
                                                                        itemId: 'txtNonPrintableRemarks',
                                                                        fieldLabel: 'NonPrintable Remarks',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'combobox',
                                                                        itemId: 'cboShipType',
                                                                        fieldLabel: 'Ship Type',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'checkboxfield',
                                                                        itemId: 'chkShipOrder',
                                                                        fieldLabel: 'Ship Order',
                                                                        labelWidth: 125
                                                                    },
                                                                    {
                                                                        xtype: 'checkboxfield',
                                                                        itemId: 'chkRptTaxes',
                                                                        fieldLabel: 'Rpt Taxes',
                                                                        labelWidth: 125
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        margin: '0 0 0 5',
                                                        layout: {
                                                            type: 'vbox',
                                                            align: 'stretch'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtSplit',
                                                                fieldLabel: 'Split',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtSalesperson',
                                                                fieldLabel: 'Salesperson',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtServiceCharge',
                                                                fieldLabel: 'Service Charge',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtPriceLevel',
                                                                fieldLabel: 'Price Level',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtReleaseNumber',
                                                                fieldLabel: 'Release Number',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtReceivedBy',
                                                                fieldLabel: 'Received By',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtAccountStatus',
                                                                fieldLabel: 'Account Status',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtOrderTotal',
                                                                fieldLabel: 'Order Total',
                                                                labelWidth: 110
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                itemId: 'txtShipTotal',
                                                                fieldLabel: 'Ship Total',
                                                                labelWidth: 110
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'advancefiltergrid',
                                                flex: 1.2,
                                                reference: 'grdInventoryShipment',
                                                itemId: 'grdInventoryShipment',
                                                margin: '7 0 0 0',
                                                dockedItems: [
                                                    {
                                                        xtype: 'toolbar',
                                                        dock: 'top',
                                                        itemId: 'tlbToolbarGrid',
                                                        layout: {
                                                            type: 'hbox',
                                                            padding: '0 0 0 1'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnEditInventoryReceipt',
                                                                iconCls: 'small-edit',
                                                                text: 'Edit'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnDeleteInventoryReceipt',
                                                                iconCls: 'small-delete',
                                                                text: 'Delete'
                                                            },
                                                            {
                                                                xtype: 'tbseparator'
                                                            },
                                                            {
                                                                xtype: 'filter1'
                                                            }
                                                        ]
                                                    }
                                                ],
                                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                    selType: 'checkboxmodel'
                                                }),
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colItemNo',
                                                        width: 100,
                                                        dataIndex: 'strItemNo',
                                                        text: 'Item No.',
                                                        editor: {
                                                            xtype: 'gridcombobox',
                                                            columns: [
                                                                {
                                                                    dataIndex: 'intItemId',
                                                                    dataType: 'numeric',
                                                                    text: 'Item Id',
                                                                    hidden: true
                                                                },
                                                                {
                                                                    dataIndex: 'strItemNo',
                                                                    dataType: 'string',
                                                                    text: 'Item Number',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    dataIndex: 'strType',
                                                                    dataType: 'string',
                                                                    text: 'Item Type',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    dataIndex: 'strDescription',
                                                                    dataType: 'string',
                                                                    text: 'Description',
                                                                    flex: 1
                                                                }
                                                            ],
                                                            itemId: 'cboItem',
                                                            displayField: 'strItemNo',
                                                            valueField: 'strItemNo'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colDescription',
                                                        width: 175,
                                                        dataIndex: 'strDescription',
                                                        text: 'Description'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colSubLocation',
                                                        width: 90,
                                                        dataIndex: 'strDescription',
                                                        text: 'Sublocation'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colLotTracking',
                                                        width: 100,
                                                        dataIndex: 'strDescription',
                                                        text: 'Lot Tracking'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered',
                                                        width: 80,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Ordered',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colOpenReceive',
                                                        width: 105,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Open to Receive',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colReceived',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Received',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colUOM',
                                                        width: 76,
                                                        dataIndex: 'strDescription',
                                                        text: 'UOM',
                                                        editor: {
                                                            xtype: 'gridcombobox',
                                                            columns: [
                                                                {
                                                                    dataIndex: 'intUnitMeasureId',
                                                                    dataType: 'numeric',
                                                                    text: 'Unit Of Measure ID',
                                                                    hidden: true
                                                                },
                                                                {
                                                                    dataIndex: 'strUnitMeasure',
                                                                    dataType: 'string',
                                                                    text: 'Unit Measure',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    dataIndex: 'strUnitType',
                                                                    dataType: 'string',
                                                                    text: 'Unit Type',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    dataIndex: 'ysnDefault',
                                                                    dataType: 'boolean',
                                                                    text: 'Default',
                                                                    flex: 1
                                                                }
                                                            ],
                                                            itemId: 'cboItemUOM',
                                                            displayField: 'strUnitMeasure',
                                                            valueField: 'strUnitMeasure'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colPackages',
                                                        width: 72,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Packages',
                                                        format: '0,000.##',
                                                        editor: {
                                                            xtype: 'numberfield',
                                                            itemId: 'txtPackages'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colPackageType',
                                                        width: 85,
                                                        dataIndex: 'strDescription',
                                                        text: 'Package Type',
                                                        editor: {
                                                            xtype: 'gridcombobox',
                                                            columns: [
                                                                {
                                                                    dataIndex: 'intPackTypeId',
                                                                    dataType: 'numeric',
                                                                    text: 'Pack Type Id',
                                                                    hidden: true
                                                                },
                                                                {
                                                                    dataIndex: 'strPackName',
                                                                    dataType: 'string',
                                                                    text: 'Pack Name',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    dataIndex: 'strDescription',
                                                                    dataType: 'string',
                                                                    text: 'Description',
                                                                    flex: 1
                                                                }
                                                            ],
                                                            itemId: 'cboItemPackType',
                                                            displayField: 'strPackName',
                                                            valueField: 'strPackName'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        itemId: 'colUnitCost',
                                                        width: 95,
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Unit Cost',
                                                        editor: {
                                                            xtype: 'numberfield',
                                                            itemId: 'txtUnitCost'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'actioncolumn',
                                                        itemId: 'colTaxDetails',
                                                        align: 'center',
                                                        menuText: 'Tax Details',
                                                        text: 'Tax Details',
                                                        altText: 'View',
                                                        items: [
                                                            {
                                                                altText: 'View',
                                                                iconCls: 'small-edit',
                                                                tooltip: 'View Tax Details'
                                                            }
                                                        ]
                                                    }
                                                ],
                                                plugins: [
                                                    Ext.create('Ext.grid.plugin.CellEditing', {
                                                        pluginId: 'cepItem',
                                                        clicksToEdit: 1
                                                    })
                                                ],
                                                viewConfig: {
                                                    itemId: 'grvInventoryReceipt'
                                                }
                                            },
                                            {
                                                xtype: 'advancefiltergrid',
                                                flex: 1,
                                                reference: 'grdLotTracking',
                                                itemId: 'grdLotTracking',
                                                margin: '7 0 0 0',
                                                dockedItems: [
                                                    {
                                                        xtype: 'toolbar',
                                                        dock: 'top',
                                                        itemId: 'tlbToolbarGrid',
                                                        layout: {
                                                            type: 'hbox',
                                                            padding: '0 0 0 1'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'label',
                                                                margin: '0 7 0 5',
                                                                text: 'Lot Tracking'
                                                            },
                                                            {
                                                                xtype: 'tbseparator'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnEditInventoryReceipt',
                                                                margin: '0 0 0 5',
                                                                iconCls: 'small-edit',
                                                                text: 'Edit'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnDeleteInventoryReceipt',
                                                                iconCls: 'small-delete',
                                                                text: 'Delete'
                                                            },
                                                            {
                                                                xtype: 'tbseparator'
                                                            },
                                                            {
                                                                xtype: 'filter1'
                                                            }
                                                        ]
                                                    }
                                                ],
                                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                    selType: 'checkboxmodel'
                                                }),
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        width: 100,
                                                        dataIndex: 'strItemNo',
                                                        text: 'Item No.'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        width: 175,
                                                        dataIndex: 'strDescription',
                                                        text: 'Parent Lot ID'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colItemNo2',
                                                        width: 100,
                                                        dataIndex: 'strDescription',
                                                        text: 'Lot ID'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colItemNo5',
                                                        width: 100,
                                                        dataIndex: 'strDescription',
                                                        text: 'Container No'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered',
                                                        width: 80,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Quantity',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        itemId: 'colItemNo6',
                                                        width: 75,
                                                        dataIndex: 'strDescription',
                                                        text: 'UOM'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered1',
                                                        width: 105,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'No. of Units',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered2',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Unit UOM',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered6',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Units/Pallet',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered7',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Gross Weight',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered8',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Tare Weight',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered9',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Net Weight',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered10',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Wt. per Unit UOM',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered11',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Stated Gross Per Unit',
                                                        format: '0,000.##'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        dataType: 'numeric',
                                                        itemId: 'colQtyOrdered12',
                                                        width: 81,
                                                        align: 'right',
                                                        dataIndex: 'dblQtyOrdered',
                                                        text: 'Stated Tare Per Unit',
                                                        format: '0,000.##'
                                                    }
                                                ],
                                                plugins: [
                                                    Ext.create('Ext.grid.plugin.CellEditing', {
                                                        clicksToEdit: 1
                                                    })
                                                ],
                                                viewConfig: {
                                                    itemId: 'grvLotTracking'
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'Notes',
                                        layout: {
                                            type: 'vbox',
                                            align: 'stretch'
                                        },
                                        items: [
                                            {
                                                xtype: 'advancefiltergrid',
                                                flex: 1,
                                                itemId: 'grdNotes',
                                                margin: -1,
                                                dockedItems: [
                                                    {
                                                        xtype: 'toolbar',
                                                        dock: 'top',
                                                        itemId: 'tlbGridOptions',
                                                        layout: {
                                                            type: 'hbox',
                                                            padding: '0 0 0 1'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnDeleteNotes',
                                                                iconCls: 'small-delete',
                                                                text: 'Delete'
                                                            },
                                                            {
                                                                xtype: 'tbseparator'
                                                            },
                                                            {
                                                                xtype: 'filter1'
                                                            }
                                                        ]
                                                    }
                                                ],
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        dataIndex: 'string',
                                                        itemId: 'colNoteLocation',
                                                        text: 'Location',
                                                        flex: 1
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        dataIndex: 'string',
                                                        itemId: 'colNoteType',
                                                        text: 'Note Type',
                                                        flex: 1
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        dataIndex: 'string',
                                                        itemId: 'colNote',
                                                        text: 'Notes',
                                                        flex: 3
                                                    }
                                                ],
                                                viewConfig: {
                                                    itemId: 'grvNotes'
                                                },
                                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                    selType: 'checkboxmodel'
                                                }),
                                                plugins: [
                                                    {
                                                        ptype: 'cellediting',
                                                        pluginId: 'cepNote',
                                                        clicksToEdit: 1
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: 'fit',
                                        title: 'Attachments',
                                        items: [
                                            {
                                                xtype: 'attachmentgrid',
                                                itemId: 'grdBillAttachment',
                                                margin: -1,
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        dataIndex: 'string',
                                                        text: 'String'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    }

});