/*
 * File: app/view/ItemPricingViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.ItemPricingViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.icitempricing',

    config: {
        binding: {
            cboLocation: {
                value: '{current.intLocationId}',
                store: '{Location}'
            },
            cboUnitMeasure: {
                value: '{current.intItemUnitMeasureId}',
                store: '{itemUOM}',
                defaultFilters: [{
                    column: 'intItemId',
                    value: '{current.intItemId}'
                }]
            },
            txtUPC: '{current.strUPC}',
            txtSalePrice: '{current.dblSalePrice}',
            txtRetailPrice: '{current.dblRetailPrice}',
            txtWholesalePrice: '{current.dblWholesalePrice}',
            txtLargeVolumePrice: '{current.dblLargeVolumePrice}',
            txtMsrp: '{current.dblMSRPPrice}',
            cboPricingMethod: {
                value: '{current.strPricingMethod}',
                store: '{PricingMethods}'
            },
            txtAmountPercent: {
                value: '{current.dblAmountPercent}',
                fieldLabel: '{getAmountPercentLabel}',
                readOnly: '{getAmountPercentReadOnly}'
            },
            txtLastCost: '{current.dblLastCost}',
            txtStandardCost: '{current.dblStandardCost}',
            txtAverageCost: '{current.dblMovingAverageCost}',
            txtEndofMonthCost: '{current.dblEndMonthCost}',
            dtpBeginDate: '{current.dtmBeginDate}',
            dtpEndDate: '{current.dtmEndDate}'
        }
    },

    setupContext : function(options){
        var me = this,
            win = options.window,
            store = Ext.create('Inventory.store.ItemPricing', { pageSize: 1 });


        win.context = Ext.create('iRely.mvvm.Engine', {
            window : win,
            store  : store,
            binding: me.config.binding,
            createRecord: {
                fn: me.createRecord,
                scope: me
            }
        });

        return win.context;
    },

    show : function(config) {
        "use strict";

        var me = this,
            win = this.getView();

        if (config) {
            win.show();

            var context = me.setupContext( { window : win } );
            me.intItemId = config.id;
            if (config.action === 'new') {
                context.data.addRecord();
            } else {
                var filter = [{
                    column: 'intItemId',
                    value: config.id
                }];
                context.data.load({
                    filters: filter
                });
            }
        }
    },

    createRecord: function(config, action) {
        var me = this;
        var today = new Date();
        var record = Ext.create('Inventory.model.ItemPricing');
        record.set('intItemId', me.intItemId);
        record.set('ysnActive', true);
        if (app.DefaultLocation > 0)
            record.set('intLocationId', app.DefaultLocation);
        record.set('dtmBeginDate', today);
        action(record);
    },

    onUOMSelect: function(combo, records, eOpts) {
        if (records.length <= 0)
            return;

        var win = combo.up('window');
        var current = win.viewModel.data.current;
        current.set('strUPC', records[0].get('strUpcCode'));
    },

    init: function(application) {
        this.control({
            "#cboUnitMeasure": {
                select: this.onUOMSelect
            }
        })
    }
});
