/*
 * File: app/view/Statusbar.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.Statusbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.statusbar',

    requires: [
        'Inventory.view.StatusbarViewModel',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.form.Label',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'statusbar'
    },
    reference: 'tlbStatusbar',
    width: 1265,

    layout: {
        type: 'hbox',
        padding: '0 0 0 1'
    },
    items: [
        {
            xtype: 'button',
            reference: 'btnHelp',
            tabIndex: -1,
            iconCls: 'small-help',
            tooltip: 'Click to get help on this screen'
        },
        {
            xtype: 'button',
            reference: 'btnSupport',
            tabIndex: -1,
            iconCls: 'small-support',
            tooltip: 'Click for support on this screen'
        },
        {
            xtype: 'button',
            reference: 'btnFieldName',
            tabIndex: -1,
            iconCls: 'small-light-bulb-off',
            tooltip: 'Click to display table/field name tooltips'
        },
        {
            xtype: 'tbseparator'
        },
        {
            xtype: 'label',
            reference: 'lblReady',
            margin: '0 5',
            text: 'Ready'
        },
        {
            xtype: 'tbfill'
        }
    ]

});