/*
 * File: app/view/StorageMeasurementReading.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Inventory.view.StorageMeasurementReading', {
    extend: 'Ext.window.Window',
    alias: 'widget.storagemeasurementreading',

    requires: [
        'Inventory.view.StatusbarPaging1',
        'Ext.form.Panel',
        'Ext.toolbar.Separator',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging'
    ],

    height: 550,
    hidden: false,
    minHeight: 550,
    minWidth: 500,
    width: 500,
    layout: 'fit',
    collapsible: true,
    iconCls: 'small-icon-i21',
    title: 'Storage Measurement Reading',
    maximizable: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'form',
                        autoShow: true,
                        itemId: 'frmStorageMeasurementReading',
                        margin: -1,
                        bodyPadding: 3,
                        trackResetOnLoad: true,
                        layout: {
                            type: 'vbox',
                            align: 'stretch'
                        },
                        dockedItems: [
                            {
                                xtype: 'toolbar',
                                dock: 'top',
                                width: 588,
                                layout: {
                                    type: 'hbox',
                                    padding: '0 0 0 1'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnNew',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-new',
                                        scale: 'large',
                                        text: 'New'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnSave',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-save',
                                        scale: 'large',
                                        text: 'Save'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnSearch',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-search',
                                        scale: 'large',
                                        text: 'Search'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnDelete',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-delete',
                                        scale: 'large',
                                        text: 'Delete'
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnUndo',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-undo',
                                        scale: 'large',
                                        text: 'Undo'
                                    },
                                    {
                                        xtype: 'tbseparator',
                                        height: 30
                                    },
                                    {
                                        xtype: 'button',
                                        tabIndex: -1,
                                        height: 57,
                                        itemId: 'btnClose',
                                        width: 45,
                                        iconAlign: 'top',
                                        iconCls: 'large-close',
                                        scale: 'large',
                                        text: 'Close'
                                    }
                                ]
                            },
                            {
                                xtype: 'ipagingstatusbar',
                                flex: 1,
                                dock: 'bottom'
                            }
                        ],
                        items: [
                            {
                                xtype: 'tabpanel',
                                flex: 1,
                                itemId: 'tabStorageMeasurementReading',
                                activeTab: 0,
                                plain: true,
                                items: [
                                    {
                                        xtype: 'panel',
                                        bodyPadding: 5,
                                        title: 'Details',
                                        layout: {
                                            type: 'vbox',
                                            align: 'stretch'
                                        },
                                        items: [
                                            {
                                                xtype: 'combobox',
                                                itemId: 'cboLocation',
                                                fieldLabel: 'Location',
                                                labelWidth: 55
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '0 0 5 0',
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'stretch'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'datefield',
                                                        flex: 1,
                                                        itemId: 'dtmDate',
                                                        margin: '0 5 0 0',
                                                        fieldLabel: 'Date',
                                                        labelWidth: 55
                                                    },
                                                    {
                                                        xtype: 'numberfield',
                                                        flex: 1,
                                                        itemId: 'txtReadingNumber',
                                                        fieldLabel: 'Reading No',
                                                        labelWidth: 80
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'advancefiltergrid',
                                                flex: 1,
                                                itemId: 'grdStorageMeasurementReading',
                                                title: 'Conversion',
                                                dockedItems: [
                                                    {
                                                        xtype: 'toolbar',
                                                        dock: 'top',
                                                        itemId: 'tlbGridOptions',
                                                        layout: {
                                                            type: 'hbox',
                                                            padding: '0 0 0 1'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnInsert',
                                                                iconCls: 'small-add',
                                                                text: 'Insert'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnRemove',
                                                                iconCls: 'small-delete',
                                                                text: 'Remove'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                tabIndex: -1,
                                                                itemId: 'btnQuality',
                                                                iconCls: 'small-view',
                                                                text: 'Quality'
                                                            }
                                                        ]
                                                    }
                                                ],
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        width: 75,
                                                        text: 'Commodity'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        text: 'Item'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        text: 'Storage Location'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        text: 'Sub Location'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        text: 'Effective Depth'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        text: 'Air Space Reading'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        text: 'Cash Price'
                                                    }
                                                ],
                                                viewConfig: {
                                                    itemId: 'grvStorageMeasurementReading'
                                                },
                                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                                    selType: 'checkboxmodel'
                                                })
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    }

});