GO
	PRINT 'START FIX DELIVERY SHEET SPLIT'
	IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE UPPER(TABLE_NAME) = 'TBLSCDELIVERYSHEET')
	BEGIN
		EXEC
		('
			UPDATE tblSCDeliverySheet SET intSplitId = NULL
			WHERE intSplitId NOT IN (SELECT intSplitId FROM tblEMEntitySplit)
		')
	END
	PRINT 'END FIX DELIVERY SHEET SPLIT'
GO