--THIS WILL UPDATE EXISTING VOUCHER'S PAY TO ADDRESS
GO
IF (EXISTS(SELECT 1 FROM tblAPBill WHERE intPayToAddressId IS NULL))
BEGIN
	UPDATE A
		SET A.intPayToAddressId = A.intShipFromId
	FROM tblAPBill A
	WHERE intPayToAddressId IS NULL
END
GO