GO
PRINT N'START: SETTING VOUCHER PAYABLE DEFAULT DATA'
IF NOT EXISTS(SELECT 1 FROM tblAPVoucherPayable)
BEGIN
	EXEC uspAPUpdateStagingPayable DEFAULT, DEFAULT
END
PRINT N'SUCCESS: SETTING VOUCHER PAYABLE DEFAULT DATA'
GO