CREATE TABLE [dbo].[tblMFBudget]
(
    [intBudgetId] INT NOT NULL IDENTITY(1,1), 
	[intYear] INT NOT NULL, 
	[intLocationId] INT NOT NULL,
    [intItemId] INT NOT NULL, 
    [intBudgetTypeId] INT NOT NULL, 
    [dblJan] NUMERIC(18, 6) NULL,
	[dblFeb] NUMERIC(18, 6) NULL,
	[dblMar] NUMERIC(18, 6) NULL,
	[dblApr] NUMERIC(18, 6) NULL,
	[dblMay] NUMERIC(18, 6) NULL,
	[dblJun] NUMERIC(18, 6) NULL,
	[dblJul] NUMERIC(18, 6) NULL,
	[dblAug] NUMERIC(18, 6) NULL,
	[dblSep] NUMERIC(18, 6) NULL,
	[dblOct] NUMERIC(18, 6) NULL,
	[dblNov] NUMERIC(18, 6) NULL,
	[dblDec] NUMERIC(18, 6) NULL,
	[dblYTD] NUMERIC(18, 6) NULL,
	[ysnConfirmed] BIT NOT NULL CONSTRAINT [DF_tblMFBudgetDefault_ysnConfirmed] DEFAULT 0,
	[intConfirmedByMonth] INT NOT NULL CONSTRAINT [DF_tblMFBudgetDefault_intConfirmedByMonth] DEFAULT 0,
	[intConfirmedUserId] [int] NULL,
	[dtmConfirmedDate] [datetime] NULL,
	[intCreatedUserId] [int] NULL,
	[dtmCreated] [datetime] NULL ,
	[intLastModifiedUserId] [int] NULL,
	[dtmLastModified] [datetime] NULL ,	 
    [intConcurrencyId] INT NULL CONSTRAINT [DF_tblMFBudget_intConcurrencyId] DEFAULT 0,
	intCompanyId INT NULL,
	CONSTRAINT [PK_tblMFBudget_intBudgetId] PRIMARY KEY ([intBudgetId]),
	CONSTRAINT [FK_tblMFBudget_tblSMCompanyLocation_intCompanyLocationId_intLocationId] FOREIGN KEY ([intLocationId]) REFERENCES [tblSMCompanyLocation]([intCompanyLocationId]),
	CONSTRAINT [FK_tblMFBudget_tblICItem_intItemId] FOREIGN KEY ([intItemId]) REFERENCES [tblICItem]([intItemId]),
	CONSTRAINT [FK_tblMFBudget_tblMFBudgetType_intBudgetTypeId] FOREIGN KEY ([intBudgetTypeId]) REFERENCES [tblMFBudgetType]([intBudgetTypeId]),
)

GO