:r .\PostDeployment\001_EMEntityPortalMenu.sql
:r .\PostDeployment\002_UpdateMenuuEntityType.sql
:r .\PostDeployment\003_FixVendorBadData.sql
:r .\PostDeployment\004_MoveFuturesBrokerData.sql
:r .\PostDeployment\005_MoveForwardingAgentData.sql
:r .\PostDeployment\006_MoveTerminalData.sql
:r .\PostDeployment\007_MoveShippingLineData.sql
:r .\PostDeployment\008_MoveTruckerData.sql
:r .\PostDeployment\009_UpdateEntityContactTypeData.sql
:r .\PostDeployment\010_UpdateVendorAccountNumber.sql
:r .\PostDeployment\011_FixEntityLocationNullTerms.sql
:r .\PostDeployment\012_DeleteOldTables.sql
:r .\PostDeployment\013_SetDefaultLocationToActive.sql
:r .\PostDeployment\014_UpdateCustomerPricingLevel.sql
:r .\PostDeployment\015_UpdateEntityTariffType.sql
:r .\PostDeployment\016_MoveCustomerAccountStatusToNewTable.sql
:r .\PostDeployment\017_MoveSplitCategoryToNewTable.sql
:r .\PostDeployment\018_UpdateRoleId_ForEntityCredential.sql
:r .\PostDeployment\019_RemoveEmailToParentEntity.sql
:r .\PostDeployment\020_DefaultDataForEntityImportSchemaCSV.sql
:r .\PostDeployment\021_MoveCustomerMessageToEntity.sql
:r .\PostDeployment\5_FixUserIdDataEntry.sql ---used entry = 'Update DB UserId From Parent Entity' on tblEMEntityPreferences

:r .\PostDeployment\022_DefaultDataForContactTypeAndImport.sql
:r .\PostDeployment\023_RenameEntityContactEmailDistribution.sql
:r .\PostDeployment\024_delete_old_entity_table.sql
:r .\PostDeployment\025_UpdatePhoneNumberAndCreateBackup.sql
:r .\PostDeployment\028_MassCountryFormat.sql
:r .\PostDeployment\026_ImportPhoneNumbersToNewTable.sql
:r .\PostDeployment\027_MassUpdatePhoneNumber.sql
:r .\PostDeployment\029_FillInPhoneAndMobile.sql
:r .\PostDeployment\030-FixSalesperson.sql
:r .\PostDeployment\024_CleanOrphanCustomerGroup.sql
:r .\PostDeployment\031_UpdatePhoneAreaLength.sql
:r .\PostDeployment\032_MigrateVendorApprovalList.sql
:r .\PostDeployment\033_UpdateUserSecurityAdmin.sql
:r .\PostDeployment\034_EntityClassData.sql
:r .\PostDeployment\035_EncryptEFTAccountNumber.sql
:r .\PostDeployment\034_UpdateEntityEmail.sql
:r .\PostDeployment\036_MoveTheTermsPerType.sql
:r .\PostDeployment\037_DefaultDataLocationPayee.sql

:r .\PostDeployment\039_MoveDefaultTermsToVendorTerm.sql
:r .\PostDeployment\Migrate_Data_1710_Moving_Format_UserSec_Ent.sql
:r .\PostDeployment\1730_Fix_SplitTypeEntry.sql
:r .\PostDeployment\DataMigration\1710_1720_CCSite_migration.sql
:r .\PostDeployment\DataMigration\1740_Moving_Farm_Info_to_Location.sql
:r .\PostDeployment\1740_Activate_Default_Contact.sql
:r .\PostDeployment\1810_Set_Default_Language.sql
:r .\PostDeployment\1810_Fix_Check_Payee_Name.sql