CREATE TABLE [dbo].[cfcusmst] (
    [cfcus_card_no]               CHAR (16)      NOT NULL,
    [cfcus_card_desc]             CHAR (20)      NULL,
    [cfcus_ar_cus_no]             CHAR (10)      NOT NULL,
    [cfcus_dsc_days]              SMALLINT       NULL,
    [cfcus_dsc_schd]              CHAR (2)       NULL,
    [cfcus_ivc_cyc]               CHAR (1)       NULL,
    [cfcus_sls_id]                CHAR (3)       NULL,
    [cfcus_bonus_comm_dt]         INT            NULL,
    [cfcus_bonus_comm_rt]         DECIMAL (6, 5) NULL,
    [cfcus_reg_comm_rt]           DECIMAL (6, 5) NULL,
    [cfcus_ar_itm_no_1]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_2]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_3]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_4]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_5]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_6]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_7]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_8]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_9]           CHAR (10)      NULL,
    [cfcus_ar_itm_no_10]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_11]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_12]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_13]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_14]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_15]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_16]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_17]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_18]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_19]          CHAR (10)      NULL,
    [cfcus_ar_itm_no_20]          CHAR (10)      NULL,
    [cfcus_fet_yn_1]              CHAR (1)       NULL,
    [cfcus_fet_yn_2]              CHAR (1)       NULL,
    [cfcus_fet_yn_3]              CHAR (1)       NULL,
    [cfcus_fet_yn_4]              CHAR (1)       NULL,
    [cfcus_fet_yn_5]              CHAR (1)       NULL,
    [cfcus_fet_yn_6]              CHAR (1)       NULL,
    [cfcus_fet_yn_7]              CHAR (1)       NULL,
    [cfcus_fet_yn_8]              CHAR (1)       NULL,
    [cfcus_fet_yn_9]              CHAR (1)       NULL,
    [cfcus_fet_yn_10]             CHAR (1)       NULL,
    [cfcus_fet_yn_11]             CHAR (1)       NULL,
    [cfcus_fet_yn_12]             CHAR (1)       NULL,
    [cfcus_fet_yn_13]             CHAR (1)       NULL,
    [cfcus_fet_yn_14]             CHAR (1)       NULL,
    [cfcus_fet_yn_15]             CHAR (1)       NULL,
    [cfcus_fet_yn_16]             CHAR (1)       NULL,
    [cfcus_fet_yn_17]             CHAR (1)       NULL,
    [cfcus_fet_yn_18]             CHAR (1)       NULL,
    [cfcus_fet_yn_19]             CHAR (1)       NULL,
    [cfcus_fet_yn_20]             CHAR (1)       NULL,
    [cfcus_set_yn_1]              CHAR (1)       NULL,
    [cfcus_set_yn_2]              CHAR (1)       NULL,
    [cfcus_set_yn_3]              CHAR (1)       NULL,
    [cfcus_set_yn_4]              CHAR (1)       NULL,
    [cfcus_set_yn_5]              CHAR (1)       NULL,
    [cfcus_set_yn_6]              CHAR (1)       NULL,
    [cfcus_set_yn_7]              CHAR (1)       NULL,
    [cfcus_set_yn_8]              CHAR (1)       NULL,
    [cfcus_set_yn_9]              CHAR (1)       NULL,
    [cfcus_set_yn_10]             CHAR (1)       NULL,
    [cfcus_set_yn_11]             CHAR (1)       NULL,
    [cfcus_set_yn_12]             CHAR (1)       NULL,
    [cfcus_set_yn_13]             CHAR (1)       NULL,
    [cfcus_set_yn_14]             CHAR (1)       NULL,
    [cfcus_set_yn_15]             CHAR (1)       NULL,
    [cfcus_set_yn_16]             CHAR (1)       NULL,
    [cfcus_set_yn_17]             CHAR (1)       NULL,
    [cfcus_set_yn_18]             CHAR (1)       NULL,
    [cfcus_set_yn_19]             CHAR (1)       NULL,
    [cfcus_set_yn_20]             CHAR (1)       NULL,
    [cfcus_sst_yn_1]              CHAR (1)       NULL,
    [cfcus_sst_yn_2]              CHAR (1)       NULL,
    [cfcus_sst_yn_3]              CHAR (1)       NULL,
    [cfcus_sst_yn_4]              CHAR (1)       NULL,
    [cfcus_sst_yn_5]              CHAR (1)       NULL,
    [cfcus_sst_yn_6]              CHAR (1)       NULL,
    [cfcus_sst_yn_7]              CHAR (1)       NULL,
    [cfcus_sst_yn_8]              CHAR (1)       NULL,
    [cfcus_sst_yn_9]              CHAR (1)       NULL,
    [cfcus_sst_yn_10]             CHAR (1)       NULL,
    [cfcus_sst_yn_11]             CHAR (1)       NULL,
    [cfcus_sst_yn_12]             CHAR (1)       NULL,
    [cfcus_sst_yn_13]             CHAR (1)       NULL,
    [cfcus_sst_yn_14]             CHAR (1)       NULL,
    [cfcus_sst_yn_15]             CHAR (1)       NULL,
    [cfcus_sst_yn_16]             CHAR (1)       NULL,
    [cfcus_sst_yn_17]             CHAR (1)       NULL,
    [cfcus_sst_yn_18]             CHAR (1)       NULL,
    [cfcus_sst_yn_19]             CHAR (1)       NULL,
    [cfcus_sst_yn_20]             CHAR (1)       NULL,
    [cfcus_lc1_yn_1]              CHAR (1)       NULL,
    [cfcus_lc1_yn_2]              CHAR (1)       NULL,
    [cfcus_lc1_yn_3]              CHAR (1)       NULL,
    [cfcus_lc1_yn_4]              CHAR (1)       NULL,
    [cfcus_lc1_yn_5]              CHAR (1)       NULL,
    [cfcus_lc1_yn_6]              CHAR (1)       NULL,
    [cfcus_lc1_yn_7]              CHAR (1)       NULL,
    [cfcus_lc1_yn_8]              CHAR (1)       NULL,
    [cfcus_lc1_yn_9]              CHAR (1)       NULL,
    [cfcus_lc1_yn_10]             CHAR (1)       NULL,
    [cfcus_lc1_yn_11]             CHAR (1)       NULL,
    [cfcus_lc1_yn_12]             CHAR (1)       NULL,
    [cfcus_lc1_yn_13]             CHAR (1)       NULL,
    [cfcus_lc1_yn_14]             CHAR (1)       NULL,
    [cfcus_lc1_yn_15]             CHAR (1)       NULL,
    [cfcus_lc1_yn_16]             CHAR (1)       NULL,
    [cfcus_lc1_yn_17]             CHAR (1)       NULL,
    [cfcus_lc1_yn_18]             CHAR (1)       NULL,
    [cfcus_lc1_yn_19]             CHAR (1)       NULL,
    [cfcus_lc1_yn_20]             CHAR (1)       NULL,
    [cfcus_lc2_yn_1]              CHAR (1)       NULL,
    [cfcus_lc2_yn_2]              CHAR (1)       NULL,
    [cfcus_lc2_yn_3]              CHAR (1)       NULL,
    [cfcus_lc2_yn_4]              CHAR (1)       NULL,
    [cfcus_lc2_yn_5]              CHAR (1)       NULL,
    [cfcus_lc2_yn_6]              CHAR (1)       NULL,
    [cfcus_lc2_yn_7]              CHAR (1)       NULL,
    [cfcus_lc2_yn_8]              CHAR (1)       NULL,
    [cfcus_lc2_yn_9]              CHAR (1)       NULL,
    [cfcus_lc2_yn_10]             CHAR (1)       NULL,
    [cfcus_lc2_yn_11]             CHAR (1)       NULL,
    [cfcus_lc2_yn_12]             CHAR (1)       NULL,
    [cfcus_lc2_yn_13]             CHAR (1)       NULL,
    [cfcus_lc2_yn_14]             CHAR (1)       NULL,
    [cfcus_lc2_yn_15]             CHAR (1)       NULL,
    [cfcus_lc2_yn_16]             CHAR (1)       NULL,
    [cfcus_lc2_yn_17]             CHAR (1)       NULL,
    [cfcus_lc2_yn_18]             CHAR (1)       NULL,
    [cfcus_lc2_yn_19]             CHAR (1)       NULL,
    [cfcus_lc2_yn_20]             CHAR (1)       NULL,
    [cfcus_lc3_yn_1]              CHAR (1)       NULL,
    [cfcus_lc3_yn_2]              CHAR (1)       NULL,
    [cfcus_lc3_yn_3]              CHAR (1)       NULL,
    [cfcus_lc3_yn_4]              CHAR (1)       NULL,
    [cfcus_lc3_yn_5]              CHAR (1)       NULL,
    [cfcus_lc3_yn_6]              CHAR (1)       NULL,
    [cfcus_lc3_yn_7]              CHAR (1)       NULL,
    [cfcus_lc3_yn_8]              CHAR (1)       NULL,
    [cfcus_lc3_yn_9]              CHAR (1)       NULL,
    [cfcus_lc3_yn_10]             CHAR (1)       NULL,
    [cfcus_lc3_yn_11]             CHAR (1)       NULL,
    [cfcus_lc3_yn_12]             CHAR (1)       NULL,
    [cfcus_lc3_yn_13]             CHAR (1)       NULL,
    [cfcus_lc3_yn_14]             CHAR (1)       NULL,
    [cfcus_lc3_yn_15]             CHAR (1)       NULL,
    [cfcus_lc3_yn_16]             CHAR (1)       NULL,
    [cfcus_lc3_yn_17]             CHAR (1)       NULL,
    [cfcus_lc3_yn_18]             CHAR (1)       NULL,
    [cfcus_lc3_yn_19]             CHAR (1)       NULL,
    [cfcus_lc3_yn_20]             CHAR (1)       NULL,
    [cfcus_lc4_yn_1]              CHAR (1)       NULL,
    [cfcus_lc4_yn_2]              CHAR (1)       NULL,
    [cfcus_lc4_yn_3]              CHAR (1)       NULL,
    [cfcus_lc4_yn_4]              CHAR (1)       NULL,
    [cfcus_lc4_yn_5]              CHAR (1)       NULL,
    [cfcus_lc4_yn_6]              CHAR (1)       NULL,
    [cfcus_lc4_yn_7]              CHAR (1)       NULL,
    [cfcus_lc4_yn_8]              CHAR (1)       NULL,
    [cfcus_lc4_yn_9]              CHAR (1)       NULL,
    [cfcus_lc4_yn_10]             CHAR (1)       NULL,
    [cfcus_lc4_yn_11]             CHAR (1)       NULL,
    [cfcus_lc4_yn_12]             CHAR (1)       NULL,
    [cfcus_lc4_yn_13]             CHAR (1)       NULL,
    [cfcus_lc4_yn_14]             CHAR (1)       NULL,
    [cfcus_lc4_yn_15]             CHAR (1)       NULL,
    [cfcus_lc4_yn_16]             CHAR (1)       NULL,
    [cfcus_lc4_yn_17]             CHAR (1)       NULL,
    [cfcus_lc4_yn_18]             CHAR (1)       NULL,
    [cfcus_lc4_yn_19]             CHAR (1)       NULL,
    [cfcus_lc4_yn_20]             CHAR (1)       NULL,
    [cfcus_lc5_yn_1]              CHAR (1)       NULL,
    [cfcus_lc5_yn_2]              CHAR (1)       NULL,
    [cfcus_lc5_yn_3]              CHAR (1)       NULL,
    [cfcus_lc5_yn_4]              CHAR (1)       NULL,
    [cfcus_lc5_yn_5]              CHAR (1)       NULL,
    [cfcus_lc5_yn_6]              CHAR (1)       NULL,
    [cfcus_lc5_yn_7]              CHAR (1)       NULL,
    [cfcus_lc5_yn_8]              CHAR (1)       NULL,
    [cfcus_lc5_yn_9]              CHAR (1)       NULL,
    [cfcus_lc5_yn_10]             CHAR (1)       NULL,
    [cfcus_lc5_yn_11]             CHAR (1)       NULL,
    [cfcus_lc5_yn_12]             CHAR (1)       NULL,
    [cfcus_lc5_yn_13]             CHAR (1)       NULL,
    [cfcus_lc5_yn_14]             CHAR (1)       NULL,
    [cfcus_lc5_yn_15]             CHAR (1)       NULL,
    [cfcus_lc5_yn_16]             CHAR (1)       NULL,
    [cfcus_lc5_yn_17]             CHAR (1)       NULL,
    [cfcus_lc5_yn_18]             CHAR (1)       NULL,
    [cfcus_lc5_yn_19]             CHAR (1)       NULL,
    [cfcus_lc5_yn_20]             CHAR (1)       NULL,
    [cfcus_lc6_yn_1]              CHAR (1)       NULL,
    [cfcus_lc6_yn_2]              CHAR (1)       NULL,
    [cfcus_lc6_yn_3]              CHAR (1)       NULL,
    [cfcus_lc6_yn_4]              CHAR (1)       NULL,
    [cfcus_lc6_yn_5]              CHAR (1)       NULL,
    [cfcus_lc6_yn_6]              CHAR (1)       NULL,
    [cfcus_lc6_yn_7]              CHAR (1)       NULL,
    [cfcus_lc6_yn_8]              CHAR (1)       NULL,
    [cfcus_lc6_yn_9]              CHAR (1)       NULL,
    [cfcus_lc6_yn_10]             CHAR (1)       NULL,
    [cfcus_lc6_yn_11]             CHAR (1)       NULL,
    [cfcus_lc6_yn_12]             CHAR (1)       NULL,
    [cfcus_lc6_yn_13]             CHAR (1)       NULL,
    [cfcus_lc6_yn_14]             CHAR (1)       NULL,
    [cfcus_lc6_yn_15]             CHAR (1)       NULL,
    [cfcus_lc6_yn_16]             CHAR (1)       NULL,
    [cfcus_lc6_yn_17]             CHAR (1)       NULL,
    [cfcus_lc6_yn_18]             CHAR (1)       NULL,
    [cfcus_lc6_yn_19]             CHAR (1)       NULL,
    [cfcus_lc6_yn_20]             CHAR (1)       NULL,
    [cfcus_lc7_yn_1]              CHAR (1)       NULL,
    [cfcus_lc7_yn_2]              CHAR (1)       NULL,
    [cfcus_lc7_yn_3]              CHAR (1)       NULL,
    [cfcus_lc7_yn_4]              CHAR (1)       NULL,
    [cfcus_lc7_yn_5]              CHAR (1)       NULL,
    [cfcus_lc7_yn_6]              CHAR (1)       NULL,
    [cfcus_lc7_yn_7]              CHAR (1)       NULL,
    [cfcus_lc7_yn_8]              CHAR (1)       NULL,
    [cfcus_lc7_yn_9]              CHAR (1)       NULL,
    [cfcus_lc7_yn_10]             CHAR (1)       NULL,
    [cfcus_lc7_yn_11]             CHAR (1)       NULL,
    [cfcus_lc7_yn_12]             CHAR (1)       NULL,
    [cfcus_lc7_yn_13]             CHAR (1)       NULL,
    [cfcus_lc7_yn_14]             CHAR (1)       NULL,
    [cfcus_lc7_yn_15]             CHAR (1)       NULL,
    [cfcus_lc7_yn_16]             CHAR (1)       NULL,
    [cfcus_lc7_yn_17]             CHAR (1)       NULL,
    [cfcus_lc7_yn_18]             CHAR (1)       NULL,
    [cfcus_lc7_yn_19]             CHAR (1)       NULL,
    [cfcus_lc7_yn_20]             CHAR (1)       NULL,
    [cfcus_lc8_yn_1]              CHAR (1)       NULL,
    [cfcus_lc8_yn_2]              CHAR (1)       NULL,
    [cfcus_lc8_yn_3]              CHAR (1)       NULL,
    [cfcus_lc8_yn_4]              CHAR (1)       NULL,
    [cfcus_lc8_yn_5]              CHAR (1)       NULL,
    [cfcus_lc8_yn_6]              CHAR (1)       NULL,
    [cfcus_lc8_yn_7]              CHAR (1)       NULL,
    [cfcus_lc8_yn_8]              CHAR (1)       NULL,
    [cfcus_lc8_yn_9]              CHAR (1)       NULL,
    [cfcus_lc8_yn_10]             CHAR (1)       NULL,
    [cfcus_lc8_yn_11]             CHAR (1)       NULL,
    [cfcus_lc8_yn_12]             CHAR (1)       NULL,
    [cfcus_lc8_yn_13]             CHAR (1)       NULL,
    [cfcus_lc8_yn_14]             CHAR (1)       NULL,
    [cfcus_lc8_yn_15]             CHAR (1)       NULL,
    [cfcus_lc8_yn_16]             CHAR (1)       NULL,
    [cfcus_lc8_yn_17]             CHAR (1)       NULL,
    [cfcus_lc8_yn_18]             CHAR (1)       NULL,
    [cfcus_lc8_yn_19]             CHAR (1)       NULL,
    [cfcus_lc8_yn_20]             CHAR (1)       NULL,
    [cfcus_lc9_yn_1]              CHAR (1)       NULL,
    [cfcus_lc9_yn_2]              CHAR (1)       NULL,
    [cfcus_lc9_yn_3]              CHAR (1)       NULL,
    [cfcus_lc9_yn_4]              CHAR (1)       NULL,
    [cfcus_lc9_yn_5]              CHAR (1)       NULL,
    [cfcus_lc9_yn_6]              CHAR (1)       NULL,
    [cfcus_lc9_yn_7]              CHAR (1)       NULL,
    [cfcus_lc9_yn_8]              CHAR (1)       NULL,
    [cfcus_lc9_yn_9]              CHAR (1)       NULL,
    [cfcus_lc9_yn_10]             CHAR (1)       NULL,
    [cfcus_lc9_yn_11]             CHAR (1)       NULL,
    [cfcus_lc9_yn_12]             CHAR (1)       NULL,
    [cfcus_lc9_yn_13]             CHAR (1)       NULL,
    [cfcus_lc9_yn_14]             CHAR (1)       NULL,
    [cfcus_lc9_yn_15]             CHAR (1)       NULL,
    [cfcus_lc9_yn_16]             CHAR (1)       NULL,
    [cfcus_lc9_yn_17]             CHAR (1)       NULL,
    [cfcus_lc9_yn_18]             CHAR (1)       NULL,
    [cfcus_lc9_yn_19]             CHAR (1)       NULL,
    [cfcus_lc9_yn_20]             CHAR (1)       NULL,
    [cfcus_lc10_yn_1]             CHAR (1)       NULL,
    [cfcus_lc10_yn_2]             CHAR (1)       NULL,
    [cfcus_lc10_yn_3]             CHAR (1)       NULL,
    [cfcus_lc10_yn_4]             CHAR (1)       NULL,
    [cfcus_lc10_yn_5]             CHAR (1)       NULL,
    [cfcus_lc10_yn_6]             CHAR (1)       NULL,
    [cfcus_lc10_yn_7]             CHAR (1)       NULL,
    [cfcus_lc10_yn_8]             CHAR (1)       NULL,
    [cfcus_lc10_yn_9]             CHAR (1)       NULL,
    [cfcus_lc10_yn_10]            CHAR (1)       NULL,
    [cfcus_lc10_yn_11]            CHAR (1)       NULL,
    [cfcus_lc10_yn_12]            CHAR (1)       NULL,
    [cfcus_lc10_yn_13]            CHAR (1)       NULL,
    [cfcus_lc10_yn_14]            CHAR (1)       NULL,
    [cfcus_lc10_yn_15]            CHAR (1)       NULL,
    [cfcus_lc10_yn_16]            CHAR (1)       NULL,
    [cfcus_lc10_yn_17]            CHAR (1)       NULL,
    [cfcus_lc10_yn_18]            CHAR (1)       NULL,
    [cfcus_lc10_yn_19]            CHAR (1)       NULL,
    [cfcus_lc10_yn_20]            CHAR (1)       NULL,
    [cfcus_lc11_yn_1]             CHAR (1)       NULL,
    [cfcus_lc11_yn_2]             CHAR (1)       NULL,
    [cfcus_lc11_yn_3]             CHAR (1)       NULL,
    [cfcus_lc11_yn_4]             CHAR (1)       NULL,
    [cfcus_lc11_yn_5]             CHAR (1)       NULL,
    [cfcus_lc11_yn_6]             CHAR (1)       NULL,
    [cfcus_lc11_yn_7]             CHAR (1)       NULL,
    [cfcus_lc11_yn_8]             CHAR (1)       NULL,
    [cfcus_lc11_yn_9]             CHAR (1)       NULL,
    [cfcus_lc11_yn_10]            CHAR (1)       NULL,
    [cfcus_lc11_yn_11]            CHAR (1)       NULL,
    [cfcus_lc11_yn_12]            CHAR (1)       NULL,
    [cfcus_lc11_yn_13]            CHAR (1)       NULL,
    [cfcus_lc11_yn_14]            CHAR (1)       NULL,
    [cfcus_lc11_yn_15]            CHAR (1)       NULL,
    [cfcus_lc11_yn_16]            CHAR (1)       NULL,
    [cfcus_lc11_yn_17]            CHAR (1)       NULL,
    [cfcus_lc11_yn_18]            CHAR (1)       NULL,
    [cfcus_lc11_yn_19]            CHAR (1)       NULL,
    [cfcus_lc11_yn_20]            CHAR (1)       NULL,
    [cfcus_lc12_yn_1]             CHAR (1)       NULL,
    [cfcus_lc12_yn_2]             CHAR (1)       NULL,
    [cfcus_lc12_yn_3]             CHAR (1)       NULL,
    [cfcus_lc12_yn_4]             CHAR (1)       NULL,
    [cfcus_lc12_yn_5]             CHAR (1)       NULL,
    [cfcus_lc12_yn_6]             CHAR (1)       NULL,
    [cfcus_lc12_yn_7]             CHAR (1)       NULL,
    [cfcus_lc12_yn_8]             CHAR (1)       NULL,
    [cfcus_lc12_yn_9]             CHAR (1)       NULL,
    [cfcus_lc12_yn_10]            CHAR (1)       NULL,
    [cfcus_lc12_yn_11]            CHAR (1)       NULL,
    [cfcus_lc12_yn_12]            CHAR (1)       NULL,
    [cfcus_lc12_yn_13]            CHAR (1)       NULL,
    [cfcus_lc12_yn_14]            CHAR (1)       NULL,
    [cfcus_lc12_yn_15]            CHAR (1)       NULL,
    [cfcus_lc12_yn_16]            CHAR (1)       NULL,
    [cfcus_lc12_yn_17]            CHAR (1)       NULL,
    [cfcus_lc12_yn_18]            CHAR (1)       NULL,
    [cfcus_lc12_yn_19]            CHAR (1)       NULL,
    [cfcus_lc12_yn_20]            CHAR (1)       NULL,
    [cfcus_prc_var_1]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_2]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_3]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_4]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_5]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_6]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_7]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_8]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_9]             DECIMAL (6, 5) NULL,
    [cfcus_prc_var_10]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_11]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_12]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_13]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_14]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_15]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_16]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_17]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_18]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_19]            DECIMAL (6, 5) NULL,
    [cfcus_prc_var_20]            DECIMAL (6, 5) NULL,
    [cfcus_bill_itm_no_1]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_2]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_3]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_4]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_5]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_6]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_7]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_8]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_9]         CHAR (10)      NULL,
    [cfcus_bill_itm_no_10]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_11]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_12]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_13]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_14]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_15]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_16]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_17]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_18]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_19]        CHAR (10)      NULL,
    [cfcus_bill_itm_no_20]        CHAR (10)      NULL,
    [cfcus_remote_add_on_amt]     DECIMAL (6, 5) NULL,
    [cfcus_own_use_yn]            CHAR (1)       NULL,
    [cfcus_exp_itm_no]            CHAR (10)      NULL,
    [cfcus_billing_site]          CHAR (15)      NULL,
    [cfcus_prt_time_yn]           CHAR (1)       NULL,
    [cfcus_terms]                 TINYINT        NULL,
    [cfcus_acct_stat]             CHAR (1)       NULL,
    [cfcus_card_locked_yn]        CHAR (1)       NULL,
    [cfcus_card_pin_no]           CHAR (4)       NULL,
    [cfcus_card_exp_yymm]         SMALLINT       NULL,
    [cfcus_card_valid_vnid]       CHAR (1)       NULL,
    [cfcus_card_no_cards]         TINYINT        NULL,
    [cfcus_card_limited_code]     TINYINT        NULL,
    [cfcus_card_fuel_code]        TINYINT        NULL,
    [cfcus_card_tier_code]        CHAR (1)       NULL,
    [cfcus_card_odom_code]        CHAR (1)       NULL,
    [cfcus_card_wc_code]          CHAR (1)       NULL,
    [cfcus_split_no]              CHAR (4)       NULL,
    [cfcus_card_man_code]         TINYINT        NULL,
    [cfcus_card_ship_cat]         TINYINT        NULL,
    [cfcus_card_profile_no]       INT            NULL,
    [cfcus_card_pos_site]         TINYINT        NULL,
    [cfcus_card_veh_control]      TINYINT        NULL,
    [cfcus_card_custom_pin]       INT            NULL,
    [cfcus_use_pp_xfer_cost_yn]   CHAR (1)       NULL,
    [cfcus_ext_remote_add_on_amt] DECIMAL (6, 5) NULL,
    [cfcus_user_id]               CHAR (16)      NULL,
    [cfcus_user_rev_dt]           INT            NULL,
    [A4GLIdentity]                NUMERIC (9)    IDENTITY (1, 1) NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [Icfcusmst0]
    ON [dbo].[cfcusmst]([cfcus_card_no] ASC);


GO
CREATE NONCLUSTERED INDEX [Icfcusmst1]
    ON [dbo].[cfcusmst]([cfcus_ar_cus_no] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[cfcusmst] TO PUBLIC
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[cfcusmst] TO PUBLIC
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[cfcusmst] TO PUBLIC
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[cfcusmst] TO PUBLIC
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[cfcusmst] TO PUBLIC
    AS [dbo];

