CREATE TABLE [dbo].[gactlmst] (
    [gactl_key]                      TINYINT         NOT NULL,
    [gactl_password]                 CHAR (16)       NULL,
    [gactl_gl_rev_dt]                INT             NULL,
    [gactl_forms_co_yn]              CHAR (1)        NULL,
    [gactl_multi_prices_yn]          CHAR (1)        NULL,
    [gactl_multi_bot_yn]             CHAR (1)        NULL,
    [gactl_req_mkt_zone_yn]          CHAR (1)        NULL,
    [gactl_auto_archive_eod]         CHAR (1)        NULL,
    [gactl_next_eod_run_no]          SMALLINT        NULL,
    [gactl_stl_on_wet_ind]           CHAR (1)        NULL,
    [gactl_elevator_shrk_yn]         CHAR (1)        NULL,
    [gactl_prc_on_close_yn]          CHAR (1)        NULL,
    [gactl_ap_interfaced_yn]         CHAR (1)        NULL,
    [gactl_ag_interfaced_yn]         CHAR (1)        NULL,
    [gactl_ar_update_ind]            CHAR (1)        NULL,
    [gactl_ar_cred_itm_no]           CHAR (13)       NULL,
    [gactl_rice_first_pos]           CHAR (1)        NULL,
    [gactl_gapayp_pgm]               CHAR (8)        NULL,
    [gactl_export_position_yn]       CHAR (1)        NULL,
    [gactl_export_systemid]          CHAR (7)        NULL,
    [gactl_gl_ga_ap]                 DECIMAL (16, 8) NULL,
    [gactl_adv_pct]                  DECIMAL (5, 2)  NULL,
    [gactl_stor_desc_1]              CHAR (12)       NULL,
    [gactl_stor_desc_2]              CHAR (12)       NULL,
    [gactl_stor_desc_3]              CHAR (12)       NULL,
    [gactl_stor_desc_4]              CHAR (12)       NULL,
    [gactl_stor_desc_5]              CHAR (12)       NULL,
    [gactl_stor_desc_6]              CHAR (12)       NULL,
    [gactl_stor_desc_7]              CHAR (12)       NULL,
    [gactl_stor_desc_8]              CHAR (12)       NULL,
    [gactl_last_str_chr_rev_dt]      INT             NULL,
    [gactl_roll_stor_type]           TINYINT         NULL,
    [gactl_include_stor_type]        TINYINT         NULL,
    [gactl_unpd_stor_type]           TINYINT         NULL,
    [gactl_print_stmt_bal_lu]        CHAR (1)        NULL,
    [gactl_gb_adb_yn]                CHAR (1)        NULL,
    [gactl_auto_pur_cnt_no_yn]       CHAR (1)        NULL,
    [gactl_auto_sls_cnt_no_yn]       CHAR (1)        NULL,
    [gactl_apply_unprc_cnt_yn]       CHAR (1)        NULL,
    [gactl_dp_cnts_yn]               CHAR (1)        NULL,
    [gactl_dp_cnts_max_un_yn]        CHAR (1)        NULL,
    [gactl_cnt_fut_csh_ind]          CHAR (1)        NULL,
    [gactl_cnt_use_slsmn_yn]         CHAR (1)        NULL,
    [gactl_req_adv_tie_cnt_yn]       CHAR (1)        NULL,
    [gactl_num_cnts_to_prt]          TINYINT         NULL,
    [gactl_cnt_early_days]           TINYINT         NULL,
    [gactl_bb_cnt_yn]                CHAR (1)        NULL,
    [gactl_bb_sls_cus_no]            CHAR (10)       NULL,
    [gactl_bb_sls_margin]            DECIMAL (9, 5)  NULL,
    [gactl_multi_chk_prtrs_yn]       CHAR (1)        NULL,
    [gactl_cash_prc_by_loc_yn]       CHAR (1)        NULL,
    [gactl_in_transit_owned_yn]      CHAR (1)        NULL,
    [gactl_use_dest_wgts_yn]         CHAR (1)        NULL,
    [gactl_num_tp_to_prt]            TINYINT         NULL,
    [gactl_last_inv_no]              CHAR (8)        NULL,
    [gactl_last_pur_tp_no]           INT             NULL,
    [gactl_last_sls_tp_no]           INT             NULL,
    [gactl_last_pur_cnt_no]          INT             NULL,
    [gactl_last_sls_cnt_no]          INT             NULL,
    [gactl_last_pur_rail_ref_no]     INT             NULL,
    [gactl_last_sls_rail_ref_no]     INT             NULL,
    [gactl_last_dpa_cnt]             INT             NULL,
    [gactl_last_defer_cnt_no]        INT             NULL,
    [gactl_disc_on_stl_yn]           CHAR (1)        NULL,
    [gactl_strg_on_stl_yn]           CHAR (1)        NULL,
    [gactl_offsite_owned_ynv]        CHAR (1)        NULL,
    [gactl_target_type_x_desc]       CHAR (7)        NULL,
    [gactl_max_csh_rcpt_adj]         DECIMAL (7, 2)  NULL,
    [gactl_overfill_rail_yn]         CHAR (1)        NULL,
    [gactl_num_ivcs_to_prt]          TINYINT         NULL,
    [gactl_create_rail_billed_adv_y] CHAR (1)        NULL,
    [gactl_cross_apply_hedges_yn]    CHAR (1)        NULL,
    [gactl_eod_in_process_yn]        CHAR (1)        NULL,
    [gactl_eom_in_trans_inv_yn]      CHAR (1)        NULL,
    [gactl_office_copy_yn]           CHAR (1)        NULL,
    [gactl_office_copy_printer]      CHAR (80)       NULL,
    [gactl_req_mkt_sign_yn]          CHAR (1)        NULL,
    [gactl_frt_surchg_yno]           CHAR (1)        NULL,
    [gactl_frt_surchg_pct]           DECIMAL (5, 2)  NULL,
    [gactl_wthhld_pct]               DECIMAL (4, 2)  NULL,
    [gactl_brok_calc_sc]             CHAR (1)        NULL,
    [gactl_user_id]                  CHAR (16)       NULL,
    [gactl_user_rev_dt]              INT             NULL,
    [gact2_stl_comment1]             CHAR (60)       NULL,
    [gact2_stl_comment2]             CHAR (60)       NULL,
    [gact2_stl_comment3]             CHAR (60)       NULL,
    [gact2_stl_comment4]             CHAR (60)       NULL,
    [gact2_dpr_refrsh_mins]          DECIMAL (5, 2)  NULL,
    [gact2_dpr_com1]                 CHAR (3)        NULL,
    [gact2_dpr_com2]                 CHAR (3)        NULL,
    [gact2_dpr_com3]                 CHAR (3)        NULL,
    [gact2_dpr_com4]                 CHAR (3)        NULL,
    [gact2_dpr_com5]                 CHAR (3)        NULL,
    [gact2_last_hdlp_rev_dt]         INT             NULL,
    [gact2_last_dpru_rev_dt]         INT             NULL,
    [gact3_per1_desc]                CHAR (12)       NULL,
    [gact3_per1_rev_dt]              INT             NULL,
    [gact3_per2_desc]                CHAR (12)       NULL,
    [gact3_per2_rev_dt]              INT             NULL,
    [gact3_per3_desc]                CHAR (12)       NULL,
    [gact3_per3_rev_dt]              INT             NULL,
    [gact3_per4_desc]                CHAR (12)       NULL,
    [gact3_per4_rev_dt]              INT             NULL,
    [gact3_per5_desc]                CHAR (12)       NULL,
    [gact3_per5_rev_dt]              INT             NULL,
    [gact3_basis_yyyymm_1]           INT             NULL,
    [gact3_basis_yyyymm_2]           INT             NULL,
    [gact3_basis_yyyymm_3]           INT             NULL,
    [gact3_basis_yyyymm_4]           INT             NULL,
    [gact3_basis_yyyymm_5]           INT             NULL,
    [gact3_basis_yyyymm_6]           INT             NULL,
    [gact3_basis_yyyymm_7]           INT             NULL,
    [gact3_basis_yyyymm_8]           INT             NULL,
    [gact4_last_int_calc_rev_dt]     INT             NULL,
    [gact4_int_from_rev_dt_1]        INT             NULL,
    [gact4_int_from_rev_dt_2]        INT             NULL,
    [gact4_int_from_rev_dt_3]        INT             NULL,
    [gact4_int_from_rev_dt_4]        INT             NULL,
    [gact4_int_from_rev_dt_5]        INT             NULL,
    [gact4_int_from_rev_dt_6]        INT             NULL,
    [gact4_int_from_rev_dt_7]        INT             NULL,
    [gact4_int_from_rev_dt_8]        INT             NULL,
    [gact4_int_from_rev_dt_9]        INT             NULL,
    [gact4_int_from_rev_dt_10]       INT             NULL,
    [gact4_int_thru_rev_dt_1]        INT             NULL,
    [gact4_int_thru_rev_dt_2]        INT             NULL,
    [gact4_int_thru_rev_dt_3]        INT             NULL,
    [gact4_int_thru_rev_dt_4]        INT             NULL,
    [gact4_int_thru_rev_dt_5]        INT             NULL,
    [gact4_int_thru_rev_dt_6]        INT             NULL,
    [gact4_int_thru_rev_dt_7]        INT             NULL,
    [gact4_int_thru_rev_dt_8]        INT             NULL,
    [gact4_int_thru_rev_dt_9]        INT             NULL,
    [gact4_int_thru_rev_dt_10]       INT             NULL,
    [gact4_int_rt_1]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_2]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_3]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_4]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_5]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_6]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_7]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_8]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_9]                 DECIMAL (7, 4)  NULL,
    [gact4_int_rt_10]                DECIMAL (7, 4)  NULL,
    [gact4_int_adj_stl_ind]          CHAR (1)        NULL,
    [gact4_dpr_cnt_dates_yncm]       CHAR (1)        NULL,
    [gact4_cnt_yyyymm_1]             INT             NULL,
    [gact4_cnt_yyyymm_2]             INT             NULL,
    [gact4_cnt_yyyymm_3]             INT             NULL,
    [gact4_cnt_yyyymm_4]             INT             NULL,
    [gact4_cnt_yyyymm_5]             INT             NULL,
    [gact4_cnt_yyyymm_6]             INT             NULL,
    [gact4_cnt_yyyymm_7]             INT             NULL,
    [gact4_cnt_yyyymm_8]             INT             NULL,
    [gact4_cnt_yyyymm_9]             INT             NULL,
    [gact4_cnt_yyyymm_10]            INT             NULL,
    [gact4_cnt_yyyymm_11]            INT             NULL,
    [gact4_cnt_yyyymm_12]            INT             NULL,
    [gact4_lds_rev_dt_1]             INT             NULL,
    [gact4_lds_rev_dt_2]             INT             NULL,
    [gact4_lds_rev_dt_3]             INT             NULL,
    [gact4_lds_rev_dt_4]             INT             NULL,
    [gact4_lds_rev_dt_5]             INT             NULL,
    [gact4_lds_rev_dt_6]             INT             NULL,
    [gact4_lds_rev_dt_7]             INT             NULL,
    [gact4_lds_rev_dt_8]             INT             NULL,
    [gact4_lds_rev_dt_9]             INT             NULL,
    [gact5_grd_wgt_desc_1]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_2]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_3]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_4]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_5]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_6]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_7]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_8]           CHAR (20)       NULL,
    [gact5_grd_wgt_desc_9]           CHAR (20)       NULL,
    [gact5_grd_wgt_type_1]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_2]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_3]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_4]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_5]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_6]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_7]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_8]           CHAR (1)        NULL,
    [gact5_grd_wgt_type_9]           CHAR (1)        NULL,
    [gact6_rail_pur_comment1]        CHAR (60)       NULL,
    [gact6_rail_pur_comment2]        CHAR (60)       NULL,
    [gact6_rail_pur_comment3]        CHAR (60)       NULL,
    [gact6_rail_pur_comment4]        CHAR (60)       NULL,
    [gact6_rail_pur_comment5]        CHAR (60)       NULL,
    [gact7_opt_desc_1]               CHAR (35)       NULL,
    [gact7_opt_desc_2]               CHAR (35)       NULL,
    [gact7_opt_desc_3]               CHAR (35)       NULL,
    [gact7_opt_desc_4]               CHAR (35)       NULL,
    [gact7_opt_desc_5]               CHAR (35)       NULL,
    [gact7_opt_desc_6]               CHAR (35)       NULL,
    [gact7_opt_bs_1_1]               CHAR (1)        NULL,
    [gact7_opt_bs_1_2]               CHAR (1)        NULL,
    [gact7_opt_bs_1_3]               CHAR (1)        NULL,
    [gact7_opt_bs_1_4]               CHAR (1)        NULL,
    [gact7_opt_bs_2_1]               CHAR (1)        NULL,
    [gact7_opt_bs_2_2]               CHAR (1)        NULL,
    [gact7_opt_bs_2_3]               CHAR (1)        NULL,
    [gact7_opt_bs_2_4]               CHAR (1)        NULL,
    [gact7_opt_bs_3_1]               CHAR (1)        NULL,
    [gact7_opt_bs_3_2]               CHAR (1)        NULL,
    [gact7_opt_bs_3_3]               CHAR (1)        NULL,
    [gact7_opt_bs_3_4]               CHAR (1)        NULL,
    [gact7_opt_bs_4_1]               CHAR (1)        NULL,
    [gact7_opt_bs_4_2]               CHAR (1)        NULL,
    [gact7_opt_bs_4_3]               CHAR (1)        NULL,
    [gact7_opt_bs_4_4]               CHAR (1)        NULL,
    [gact7_opt_bs_5_1]               CHAR (1)        NULL,
    [gact7_opt_bs_5_2]               CHAR (1)        NULL,
    [gact7_opt_bs_5_3]               CHAR (1)        NULL,
    [gact7_opt_bs_5_4]               CHAR (1)        NULL,
    [gact7_opt_bs_6_1]               CHAR (1)        NULL,
    [gact7_opt_bs_6_2]               CHAR (1)        NULL,
    [gact7_opt_bs_6_3]               CHAR (1)        NULL,
    [gact7_opt_bs_6_4]               CHAR (1)        NULL,
    [gact7_opt_pc_1_1]               CHAR (1)        NULL,
    [gact7_opt_pc_1_2]               CHAR (1)        NULL,
    [gact7_opt_pc_1_3]               CHAR (1)        NULL,
    [gact7_opt_pc_1_4]               CHAR (1)        NULL,
    [gact7_opt_pc_2_1]               CHAR (1)        NULL,
    [gact7_opt_pc_2_2]               CHAR (1)        NULL,
    [gact7_opt_pc_2_3]               CHAR (1)        NULL,
    [gact7_opt_pc_2_4]               CHAR (1)        NULL,
    [gact7_opt_pc_3_1]               CHAR (1)        NULL,
    [gact7_opt_pc_3_2]               CHAR (1)        NULL,
    [gact7_opt_pc_3_3]               CHAR (1)        NULL,
    [gact7_opt_pc_3_4]               CHAR (1)        NULL,
    [gact7_opt_pc_4_1]               CHAR (1)        NULL,
    [gact7_opt_pc_4_2]               CHAR (1)        NULL,
    [gact7_opt_pc_4_3]               CHAR (1)        NULL,
    [gact7_opt_pc_4_4]               CHAR (1)        NULL,
    [gact7_opt_pc_5_1]               CHAR (1)        NULL,
    [gact7_opt_pc_5_2]               CHAR (1)        NULL,
    [gact7_opt_pc_5_3]               CHAR (1)        NULL,
    [gact7_opt_pc_5_4]               CHAR (1)        NULL,
    [gact7_opt_pc_6_1]               CHAR (1)        NULL,
    [gact7_opt_pc_6_2]               CHAR (1)        NULL,
    [gact7_opt_pc_6_3]               CHAR (1)        NULL,
    [gact7_opt_pc_6_4]               CHAR (1)        NULL,
    [gact8_eom_print_loc_ynm]        CHAR (1)        NULL,
    [gact8_eom_cash_or_fut_prc]      CHAR (1)        NULL,
    [gact8_eom_dp_basis_deliv_yn]    CHAR (1)        NULL,
    [gact8_eom_thru_due_rev_dt_1]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_2]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_3]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_4]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_5]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_6]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_7]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_8]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_9]    INT             NULL,
    [gact8_eom_thru_due_rev_dt_10]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_11]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_12]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_13]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_14]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_15]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_16]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_17]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_18]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_19]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_20]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_21]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_22]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_23]   INT             NULL,
    [gact8_eom_thru_due_rev_dt_24]   INT             NULL,
    [gact8_eom_gl_rev_dt]            INT             NULL,
    [gact8_dpr_path]                 CHAR (80)       NULL,
    [gact8_edi_path]                 CHAR (80)       NULL,
    [gact8_cwb_path]                 CHAR (80)       NULL,
    [gact8_eom_reset_str_pos_yn]     CHAR (1)        NULL,
    [gact8_scale_cutoff_rev_dt]      INT             NULL,
    [gact9_rail_sls_comment1]        CHAR (60)       NULL,
    [gact9_rail_sls_comment2]        CHAR (60)       NULL,
    [gact9_rail_sls_comment3]        CHAR (60)       NULL,
    [gact9_rail_sls_comment4]        CHAR (60)       NULL,
    [gact9_rail_sls_comment5]        CHAR (60)       NULL,
    [gact0_ivc_comment1]             CHAR (60)       NULL,
    [gact0_ivc_comment2]             CHAR (60)       NULL,
    [gact0_ivc_comment3]             CHAR (60)       NULL,
    [gac60_equip_type_1]             TINYINT         NULL,
    [gac60_equip_type_2]             TINYINT         NULL,
    [gac60_equip_type_3]             TINYINT         NULL,
    [gac60_equip_type_4]             TINYINT         NULL,
    [gac60_equip_type_5]             TINYINT         NULL,
    [gac60_equip_type_6]             TINYINT         NULL,
    [gac60_equip_type_7]             TINYINT         NULL,
    [gac60_equip_type_8]             TINYINT         NULL,
    [gac60_equip_type_9]             TINYINT         NULL,
    [gac60_equip_type_10]            TINYINT         NULL,
    [gac60_equip_type_11]            TINYINT         NULL,
    [gac60_equip_type_12]            TINYINT         NULL,
    [gac60_equip_type_13]            TINYINT         NULL,
    [gac60_equip_type_14]            TINYINT         NULL,
    [gac60_equip_type_15]            TINYINT         NULL,
    [gac60_equip_type_16]            TINYINT         NULL,
    [gac60_equip_type_17]            TINYINT         NULL,
    [gac60_equip_type_18]            TINYINT         NULL,
    [gac60_equip_type_19]            TINYINT         NULL,
    [gac60_equip_type_20]            TINYINT         NULL,
    [gac60_equip_desc_1]             CHAR (15)       NULL,
    [gac60_equip_desc_2]             CHAR (15)       NULL,
    [gac60_equip_desc_3]             CHAR (15)       NULL,
    [gac60_equip_desc_4]             CHAR (15)       NULL,
    [gac60_equip_desc_5]             CHAR (15)       NULL,
    [gac60_equip_desc_6]             CHAR (15)       NULL,
    [gac60_equip_desc_7]             CHAR (15)       NULL,
    [gac60_equip_desc_8]             CHAR (15)       NULL,
    [gac60_equip_desc_9]             CHAR (15)       NULL,
    [gac60_equip_desc_10]            CHAR (15)       NULL,
    [gac60_equip_desc_11]            CHAR (15)       NULL,
    [gac60_equip_desc_12]            CHAR (15)       NULL,
    [gac60_equip_desc_13]            CHAR (15)       NULL,
    [gac60_equip_desc_14]            CHAR (15)       NULL,
    [gac60_equip_desc_15]            CHAR (15)       NULL,
    [gac60_equip_desc_16]            CHAR (15)       NULL,
    [gac60_equip_desc_17]            CHAR (15)       NULL,
    [gac60_equip_desc_18]            CHAR (15)       NULL,
    [gac60_equip_desc_19]            CHAR (15)       NULL,
    [gac60_equip_desc_20]            CHAR (15)       NULL,
    [gac60_surcharge_pct]            DECIMAL (5, 2)  NULL,
    [gac60_bill_surcharge_pct]       DECIMAL (5, 2)  NULL,
    [gac60_user_id]                  CHAR (16)       NULL,
    [gac60_user_rev_dt]              CHAR (8)        NULL,
    [gac61_line_1]                   CHAR (70)       NULL,
    [gac61_line_2]                   CHAR (70)       NULL,
    [gac61_line_3]                   CHAR (70)       NULL,
    [gac61_line_4]                   CHAR (70)       NULL,
    [gac61_line_5]                   CHAR (70)       NULL,
    [gac61_user_id]                  CHAR (16)       NULL,
    [gac61_user_rev_dt]              CHAR (8)        NULL,
    [gactp_multi_prtr_desc]          CHAR (20)       NULL,
    [gactp_chk_printer_name]         CHAR (80)       NULL,
    [gactp_stl_printer_name]         CHAR (80)       NULL,
    [gactp_last_chk_no]              INT             NULL,
    [gactp_last_stl_ref_no]          INT             NULL,
    [gactp_cbk_no]                   CHAR (2)        NULL,
    [gactp_chk_prt_ynpc]             CHAR (1)        NULL,
    [gactp_use_tbl_chk_no_yn]        CHAR (1)        NULL,
    [gactp_check_format_cs]          CHAR (1)        NULL,
    [gactp_laser_down_lines]         TINYINT         NULL,
    [gactp_stl_copies]               TINYINT         NULL,
    [A4GLIdentity]                   NUMERIC (9)     IDENTITY (1, 1) NOT NULL,
    [gactl_limit_adv_pct]            SMALLINT        NULL,
    [gac21_use_udt_drv_yn]           CHAR (1)        NULL,
    [gac21_end_udt_in_yn]            CHAR (1)        NULL,
    [gac21_end_udt_ot_yn]            CHAR (1)        NULL,
    [gac21_end_udt_gr_yn]            CHAR (1)        NULL,
    [gac21_err_on_cnt_exists_in_asw] CHAR (1)        NULL,
    [gac21_err_on_cnt_exists_ot_asw] CHAR (1)        NULL,
    [gac21_dflt_drv_on_yn]           CHAR (1)        NULL,
    [gac21_set_weigher]              CHAR (1)        NULL,
    [gac21_ask_no_axels_yn]          CHAR (1)        NULL,
    [gac21_ded_frt_yna]              CHAR (1)        NULL,
    [gac21_req_bin_ynw]              CHAR (1)        NULL,
    [gac21_req_drv_id_ynr]           CHAR (1)        NULL,
    [gac21_req_trk_id_ynr]           CHAR (1)        NULL,
    [gac21_req_ref_no_yn]            CHAR (1)        NULL,
    [gac21_req_cus_cmt_yn]           CHAR (1)        NULL,
    [gac21_req_un_prc_on_spot_yn]    CHAR (1)        NULL,
    [gac21_enable_on_scr_keyb]       CHAR (1)        NULL,
    [gac21_use_led_sign_yn]          CHAR (1)        NULL,
    [gac21_time_thread_delay]        CHAR (3)        NULL,
    [gac21_weight_thread_delay]      CHAR (3)        NULL,
    [gac21_grad_readings]            CHAR (1)        NULL,
    [gac21_in_readings]              CHAR (1)        NULL,
    [gac21_out_readings]             CHAR (1)        NULL,
    [gac21_autmtc_weight_retries]    TINYINT         NULL,
    [gac21_scale_house_edit_info]    CHAR (1)        NULL,
    [gac21_upd_to_tic_yn]            CHAR (1)        NULL,
    [gac21_req_hauler_on_frt]        CHAR (1)        NULL,
    [gac21_split_cus_by_inv]         CHAR (1)        NULL,
    [gac21_use_gacom_auto_dist_yn]   CHAR (1)        NULL,
    [gactl_crd_password]             CHAR (16)       NULL,
    [gac60_crd_chk_sls_yn]           CHAR (1)        NULL,
    [gac60_crd_chk_ovr_yn]           CHAR (1)        NULL,
    [gac60_ovr_notify_email]         CHAR (80)       NULL,
    CONSTRAINT [k_gactlmst] PRIMARY KEY NONCLUSTERED ([gactl_key] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [Igactlmst0]
    ON [dbo].[gactlmst]([gactl_key] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[gactlmst] TO PUBLIC
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[gactlmst] TO PUBLIC
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[gactlmst] TO PUBLIC
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[gactlmst] TO PUBLIC
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[gactlmst] TO PUBLIC
    AS [dbo];

