CREATE TABLE [dbo].[prempmst] (
    [premp_emp]                     CHAR (10)       NOT NULL,
    [premp_last_name]               CHAR (20)       NOT NULL,
    [premp_first_name]              CHAR (20)       NOT NULL,
    [premp_initial]                 CHAR (1)        NOT NULL,
    [premp_extension]               CHAR (5)        NOT NULL,
    [premp_alt_fld1]                CHAR (20)       NULL,
    [premp_alt_fld2]                CHAR (20)       NULL,
    [premp_alt_fld3]                CHAR (20)       NULL,
    [premp_alt_fld4]                CHAR (20)       NULL,
    [premp_addr1]                   CHAR (30)       NULL,
    [premp_addr2]                   CHAR (30)       NULL,
    [premp_city]                    CHAR (22)       NULL,
    [premp_state]                   CHAR (2)        NULL,
    [premp_zip]                     CHAR (10)       NULL,
    [premp_work_state]              CHAR (2)        NULL,
    [premp_ssn]                     INT             NOT NULL,
    [premp_phone]                   CHAR (15)       NULL,
    [premp_nickname]                CHAR (10)       NULL,
    [premp_rate]                    DECIMAL (11, 4) NULL,
    [premp_dept]                    CHAR (4)        NOT NULL,
    [premp_employment]              CHAR (1)        NULL,
    [premp_status]                  CHAR (1)        NULL,
    [premp_pay_type]                CHAR (1)        NULL,
    [premp_pay_cycle]               CHAR (1)        NULL,
    [premp_last_chk_dt]             INT             NULL,
    [premp_std_hrs]                 DECIMAL (6, 2)  NULL,
    [premp_wks_worked]              DECIMAL (4, 2)  NULL,
    [premp_vac_awards_calcd_yn]     CHAR (1)        NULL,
    [premp_vac_awards_anniv_ytd_ay] CHAR (1)        NULL,
    [premp_vac_method]              TINYINT         NULL,
    [premp_vac_std_accrual]         DECIMAL (8, 4)  NULL,
    [premp_vac_curr_accrual]        DECIMAL (7, 4)  NULL,
    [premp_vac_elig_dt]             INT             NULL,
    [premp_vac_award_yn]            CHAR (1)        NULL,
    [premp_vac_award_dt]            INT             NULL,
    [premp_vac_carried]             DECIMAL (7, 4)  NULL,
    [premp_vac_earned]              DECIMAL (7, 4)  NULL,
    [premp_vac_hrs_pd]              DECIMAL (5, 2)  NULL,
    [premp_sic_awards_calcd_yn]     CHAR (1)        NULL,
    [premp_sic_awards_anniv_ytd_ay] CHAR (1)        NULL,
    [premp_sic_method]              TINYINT         NULL,
    [premp_sic_std_accrual]         DECIMAL (8, 4)  NULL,
    [premp_sic_curr_accrual]        DECIMAL (7, 4)  NULL,
    [premp_sic_elig_dt]             INT             NULL,
    [premp_sic_award_yn]            CHAR (1)        NULL,
    [premp_sic_award_dt]            INT             NULL,
    [premp_sic_carried]             DECIMAL (7, 4)  NULL,
    [premp_sic_earned]              DECIMAL (7, 4)  NULL,
    [premp_sic_hrs_pd]              DECIMAL (5, 2)  NULL,
    [premp_per_awards_calcd_yn]     CHAR (1)        NULL,
    [premp_per_awards_anniv_ytd_ay] CHAR (1)        NULL,
    [premp_per_method]              TINYINT         NULL,
    [premp_per_std_accrual]         DECIMAL (8, 4)  NULL,
    [premp_per_curr_accrual]        DECIMAL (7, 4)  NULL,
    [premp_per_elig_dt]             INT             NULL,
    [premp_per_award_yn]            CHAR (1)        NULL,
    [premp_per_award_dt]            INT             NULL,
    [premp_per_carried]             DECIMAL (7, 4)  NULL,
    [premp_per_earned]              DECIMAL (7, 4)  NULL,
    [premp_per_hrs_pd]              DECIMAL (5, 2)  NULL,
    [premp_job_title]               CHAR (15)       NULL,
    [premp_eeo_code]                TINYINT         NULL,
    [premp_race]                    CHAR (1)        NULL,
    [premp_sex]                     CHAR (1)        NULL,
    [premp_marital_status]          CHAR (1)        NULL,
    [premp_spouse]                  CHAR (30)       NULL,
    [premp_emer_contact]            CHAR (30)       NULL,
    [premp_emer_phone]              CHAR (15)       NULL,
    [premp_doctor]                  CHAR (30)       NULL,
    [premp_doctor_phone]            CHAR (15)       NULL,
    [premp_birth_dt]                INT             NULL,
    [premp_term_dt]                 INT             NULL,
    [premp_term_code]               CHAR (2)        NULL,
    [premp_orig_hire_dt]            INT             NULL,
    [premp_last_hire_dt]            INT             NULL,
    [premp_last_review_dt]          INT             NULL,
    [premp_next_review_dt]          INT             NULL,
    [premp_last_raise_dt]           INT             NULL,
    [premp_beg_leave_dt]            INT             NULL,
    [premp_end_leave_dt]            INT             NULL,
    [premp_pay_periods]             TINYINT         NULL,
    [premp_pension_dt]              INT             NULL,
    [premp_insur_dt]                INT             NULL,
    [premp_gl_dist_code]            CHAR (1)        NULL,
    [premp_dir_dep_bank]            CHAR (4)        NULL,
    [premp_dir_dep_acct]            CHAR (17)       NULL,
    [premp_tax_id_1]                CHAR (7)        NULL,
    [premp_tax_id_2]                CHAR (7)        NULL,
    [premp_tax_id_3]                CHAR (7)        NULL,
    [premp_tax_id_4]                CHAR (7)        NULL,
    [premp_tax_id_5]                CHAR (7)        NULL,
    [premp_tax_id_6]                CHAR (7)        NULL,
    [premp_tax_id_7]                CHAR (7)        NULL,
    [premp_tax_id_8]                CHAR (7)        NULL,
    [premp_tax_id_9]                CHAR (7)        NULL,
    [premp_tax_id_10]               CHAR (7)        NULL,
    [premp_tax_id_11]               CHAR (7)        NULL,
    [premp_tax_id_12]               CHAR (7)        NULL,
    [premp_tax_id_13]               CHAR (7)        NULL,
    [premp_tax_id_14]               CHAR (7)        NULL,
    [premp_tax_id_15]               CHAR (7)        NULL,
    [premp_tax_id_16]               CHAR (7)        NULL,
    [premp_tax_active_yn_1]         CHAR (1)        NULL,
    [premp_tax_active_yn_2]         CHAR (1)        NULL,
    [premp_tax_active_yn_3]         CHAR (1)        NULL,
    [premp_tax_active_yn_4]         CHAR (1)        NULL,
    [premp_tax_active_yn_5]         CHAR (1)        NULL,
    [premp_tax_active_yn_6]         CHAR (1)        NULL,
    [premp_tax_active_yn_7]         CHAR (1)        NULL,
    [premp_tax_active_yn_8]         CHAR (1)        NULL,
    [premp_tax_active_yn_9]         CHAR (1)        NULL,
    [premp_tax_active_yn_10]        CHAR (1)        NULL,
    [premp_tax_active_yn_11]        CHAR (1)        NULL,
    [premp_tax_active_yn_12]        CHAR (1)        NULL,
    [premp_tax_active_yn_13]        CHAR (1)        NULL,
    [premp_tax_active_yn_14]        CHAR (1)        NULL,
    [premp_tax_active_yn_15]        CHAR (1)        NULL,
    [premp_tax_active_yn_16]        CHAR (1)        NULL,
    [premp_tax_exempts_1]           TINYINT         NULL,
    [premp_tax_exempts_2]           TINYINT         NULL,
    [premp_tax_exempts_3]           TINYINT         NULL,
    [premp_tax_exempts_4]           TINYINT         NULL,
    [premp_tax_exempts_5]           TINYINT         NULL,
    [premp_tax_exempts_6]           TINYINT         NULL,
    [premp_tax_exempts_7]           TINYINT         NULL,
    [premp_tax_exempts_8]           TINYINT         NULL,
    [premp_tax_exempts_9]           TINYINT         NULL,
    [premp_tax_exempts_10]          TINYINT         NULL,
    [premp_tax_exempts_11]          TINYINT         NULL,
    [premp_tax_exempts_12]          TINYINT         NULL,
    [premp_tax_exempts_13]          TINYINT         NULL,
    [premp_tax_exempts_14]          TINYINT         NULL,
    [premp_tax_exempts_15]          TINYINT         NULL,
    [premp_tax_exempts_16]          TINYINT         NULL,
    [premp_tax_addl_code_pa_1]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_2]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_3]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_4]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_5]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_6]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_7]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_8]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_9]      CHAR (1)        NULL,
    [premp_tax_addl_code_pa_10]     CHAR (1)        NULL,
    [premp_tax_addl_code_pa_11]     CHAR (1)        NULL,
    [premp_tax_addl_code_pa_12]     CHAR (1)        NULL,
    [premp_tax_addl_code_pa_13]     CHAR (1)        NULL,
    [premp_tax_addl_code_pa_14]     CHAR (1)        NULL,
    [premp_tax_addl_code_pa_15]     CHAR (1)        NULL,
    [premp_tax_addl_code_pa_16]     CHAR (1)        NULL,
    [premp_tax_addl_pct_amt_1]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_2]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_3]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_4]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_5]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_6]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_7]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_8]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_9]      DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_10]     DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_11]     DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_12]     DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_13]     DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_14]     DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_15]     DECIMAL (9, 2)  NULL,
    [premp_tax_addl_pct_amt_16]     DECIMAL (9, 2)  NULL,
    [premp_tax_reserve_4]           CHAR (80)       NULL,
    [premp_ded_code_1]              CHAR (3)        NULL,
    [premp_ded_code_2]              CHAR (3)        NULL,
    [premp_ded_code_3]              CHAR (3)        NULL,
    [premp_ded_code_4]              CHAR (3)        NULL,
    [premp_ded_code_5]              CHAR (3)        NULL,
    [premp_ded_code_6]              CHAR (3)        NULL,
    [premp_ded_code_7]              CHAR (3)        NULL,
    [premp_ded_code_8]              CHAR (3)        NULL,
    [premp_ded_code_9]              CHAR (3)        NULL,
    [premp_ded_code_10]             CHAR (3)        NULL,
    [premp_ded_code_11]             CHAR (3)        NULL,
    [premp_ded_code_12]             CHAR (3)        NULL,
    [premp_ded_code_13]             CHAR (3)        NULL,
    [premp_ded_code_14]             CHAR (3)        NULL,
    [premp_ded_code_15]             CHAR (3)        NULL,
    [premp_ded_code_16]             CHAR (3)        NULL,
    [premp_ded_code_17]             CHAR (3)        NULL,
    [premp_ded_code_18]             CHAR (3)        NULL,
    [premp_ded_code_19]             CHAR (3)        NULL,
    [premp_ded_code_20]             CHAR (3)        NULL,
    [premp_ded_type_1]              CHAR (1)        NULL,
    [premp_ded_type_2]              CHAR (1)        NULL,
    [premp_ded_type_3]              CHAR (1)        NULL,
    [premp_ded_type_4]              CHAR (1)        NULL,
    [premp_ded_type_5]              CHAR (1)        NULL,
    [premp_ded_type_6]              CHAR (1)        NULL,
    [premp_ded_type_7]              CHAR (1)        NULL,
    [premp_ded_type_8]              CHAR (1)        NULL,
    [premp_ded_type_9]              CHAR (1)        NULL,
    [premp_ded_type_10]             CHAR (1)        NULL,
    [premp_ded_type_11]             CHAR (1)        NULL,
    [premp_ded_type_12]             CHAR (1)        NULL,
    [premp_ded_type_13]             CHAR (1)        NULL,
    [premp_ded_type_14]             CHAR (1)        NULL,
    [premp_ded_type_15]             CHAR (1)        NULL,
    [premp_ded_type_16]             CHAR (1)        NULL,
    [premp_ded_type_17]             CHAR (1)        NULL,
    [premp_ded_type_18]             CHAR (1)        NULL,
    [premp_ded_type_19]             CHAR (1)        NULL,
    [premp_ded_type_20]             CHAR (1)        NULL,
    [premp_ded_active_yn_1]         CHAR (1)        NULL,
    [premp_ded_active_yn_2]         CHAR (1)        NULL,
    [premp_ded_active_yn_3]         CHAR (1)        NULL,
    [premp_ded_active_yn_4]         CHAR (1)        NULL,
    [premp_ded_active_yn_5]         CHAR (1)        NULL,
    [premp_ded_active_yn_6]         CHAR (1)        NULL,
    [premp_ded_active_yn_7]         CHAR (1)        NULL,
    [premp_ded_active_yn_8]         CHAR (1)        NULL,
    [premp_ded_active_yn_9]         CHAR (1)        NULL,
    [premp_ded_active_yn_10]        CHAR (1)        NULL,
    [premp_ded_active_yn_11]        CHAR (1)        NULL,
    [premp_ded_active_yn_12]        CHAR (1)        NULL,
    [premp_ded_active_yn_13]        CHAR (1)        NULL,
    [premp_ded_active_yn_14]        CHAR (1)        NULL,
    [premp_ded_active_yn_15]        CHAR (1)        NULL,
    [premp_ded_active_yn_16]        CHAR (1)        NULL,
    [premp_ded_active_yn_17]        CHAR (1)        NULL,
    [premp_ded_active_yn_18]        CHAR (1)        NULL,
    [premp_ded_active_yn_19]        CHAR (1)        NULL,
    [premp_ded_active_yn_20]        CHAR (1)        NULL,
    [premp_ded_freq_1]              CHAR (1)        NULL,
    [premp_ded_freq_2]              CHAR (1)        NULL,
    [premp_ded_freq_3]              CHAR (1)        NULL,
    [premp_ded_freq_4]              CHAR (1)        NULL,
    [premp_ded_freq_5]              CHAR (1)        NULL,
    [premp_ded_freq_6]              CHAR (1)        NULL,
    [premp_ded_freq_7]              CHAR (1)        NULL,
    [premp_ded_freq_8]              CHAR (1)        NULL,
    [premp_ded_freq_9]              CHAR (1)        NULL,
    [premp_ded_freq_10]             CHAR (1)        NULL,
    [premp_ded_freq_11]             CHAR (1)        NULL,
    [premp_ded_freq_12]             CHAR (1)        NULL,
    [premp_ded_freq_13]             CHAR (1)        NULL,
    [premp_ded_freq_14]             CHAR (1)        NULL,
    [premp_ded_freq_15]             CHAR (1)        NULL,
    [premp_ded_freq_16]             CHAR (1)        NULL,
    [premp_ded_freq_17]             CHAR (1)        NULL,
    [premp_ded_freq_18]             CHAR (1)        NULL,
    [premp_ded_freq_19]             CHAR (1)        NULL,
    [premp_ded_freq_20]             CHAR (1)        NULL,
    [premp_ded_calc_code_1]         CHAR (1)        NULL,
    [premp_ded_calc_code_2]         CHAR (1)        NULL,
    [premp_ded_calc_code_3]         CHAR (1)        NULL,
    [premp_ded_calc_code_4]         CHAR (1)        NULL,
    [premp_ded_calc_code_5]         CHAR (1)        NULL,
    [premp_ded_calc_code_6]         CHAR (1)        NULL,
    [premp_ded_calc_code_7]         CHAR (1)        NULL,
    [premp_ded_calc_code_8]         CHAR (1)        NULL,
    [premp_ded_calc_code_9]         CHAR (1)        NULL,
    [premp_ded_calc_code_10]        CHAR (1)        NULL,
    [premp_ded_calc_code_11]        CHAR (1)        NULL,
    [premp_ded_calc_code_12]        CHAR (1)        NULL,
    [premp_ded_calc_code_13]        CHAR (1)        NULL,
    [premp_ded_calc_code_14]        CHAR (1)        NULL,
    [premp_ded_calc_code_15]        CHAR (1)        NULL,
    [premp_ded_calc_code_16]        CHAR (1)        NULL,
    [premp_ded_calc_code_17]        CHAR (1)        NULL,
    [premp_ded_calc_code_18]        CHAR (1)        NULL,
    [premp_ded_calc_code_19]        CHAR (1)        NULL,
    [premp_ded_calc_code_20]        CHAR (1)        NULL,
    [premp_ded_dep_bank_1]          CHAR (4)        NULL,
    [premp_ded_dep_bank_2]          CHAR (4)        NULL,
    [premp_ded_dep_bank_3]          CHAR (4)        NULL,
    [premp_ded_dep_bank_4]          CHAR (4)        NULL,
    [premp_ded_dep_bank_5]          CHAR (4)        NULL,
    [premp_ded_dep_bank_6]          CHAR (4)        NULL,
    [premp_ded_dep_bank_7]          CHAR (4)        NULL,
    [premp_ded_dep_bank_8]          CHAR (4)        NULL,
    [premp_ded_dep_bank_9]          CHAR (4)        NULL,
    [premp_ded_dep_bank_10]         CHAR (4)        NULL,
    [premp_ded_dep_bank_11]         CHAR (4)        NULL,
    [premp_ded_dep_bank_12]         CHAR (4)        NULL,
    [premp_ded_dep_bank_13]         CHAR (4)        NULL,
    [premp_ded_dep_bank_14]         CHAR (4)        NULL,
    [premp_ded_dep_bank_15]         CHAR (4)        NULL,
    [premp_ded_dep_bank_16]         CHAR (4)        NULL,
    [premp_ded_dep_bank_17]         CHAR (4)        NULL,
    [premp_ded_dep_bank_18]         CHAR (4)        NULL,
    [premp_ded_dep_bank_19]         CHAR (4)        NULL,
    [premp_ded_dep_bank_20]         CHAR (4)        NULL,
    [premp_ded_amt_pct_1]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_2]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_3]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_4]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_5]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_6]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_7]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_8]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_9]           DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_10]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_11]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_12]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_13]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_14]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_15]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_16]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_17]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_18]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_19]          DECIMAL (6, 2)  NULL,
    [premp_ded_amt_pct_20]          DECIMAL (6, 2)  NULL,
    [premp_ded_arrears_1]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_2]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_3]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_4]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_5]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_6]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_7]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_8]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_9]           DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_10]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_11]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_12]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_13]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_14]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_15]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_16]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_17]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_18]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_19]          DECIMAL (7, 2)  NULL,
    [premp_ded_arrears_20]          DECIMAL (7, 2)  NULL,
    [premp_ded_limit_1]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_2]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_3]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_4]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_5]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_6]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_7]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_8]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_9]             DECIMAL (11, 2) NULL,
    [premp_ded_limit_10]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_11]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_12]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_13]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_14]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_15]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_16]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_17]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_18]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_19]            DECIMAL (11, 2) NULL,
    [premp_ded_limit_20]            DECIMAL (11, 2) NULL,
    [premp_ded_ref_no_1]            CHAR (20)       NULL,
    [premp_ded_ref_no_2]            CHAR (20)       NULL,
    [premp_ded_ref_no_3]            CHAR (20)       NULL,
    [premp_ded_ref_no_4]            CHAR (20)       NULL,
    [premp_ded_ref_no_5]            CHAR (20)       NULL,
    [premp_ded_ref_no_6]            CHAR (20)       NULL,
    [premp_ded_ref_no_7]            CHAR (20)       NULL,
    [premp_ded_ref_no_8]            CHAR (20)       NULL,
    [premp_ded_ref_no_9]            CHAR (20)       NULL,
    [premp_ded_ref_no_10]           CHAR (20)       NULL,
    [premp_ded_ref_no_11]           CHAR (20)       NULL,
    [premp_ded_ref_no_12]           CHAR (20)       NULL,
    [premp_ded_ref_no_13]           CHAR (20)       NULL,
    [premp_ded_ref_no_14]           CHAR (20)       NULL,
    [premp_ded_ref_no_15]           CHAR (20)       NULL,
    [premp_ded_ref_no_16]           CHAR (20)       NULL,
    [premp_ded_ref_no_17]           CHAR (20)       NULL,
    [premp_ded_ref_no_18]           CHAR (20)       NULL,
    [premp_ded_ref_no_19]           CHAR (20)       NULL,
    [premp_ded_ref_no_20]           CHAR (20)       NULL,
    [premp_ded_dd_acct_type_1]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_2]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_3]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_4]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_5]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_6]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_7]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_8]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_9]      CHAR (1)        NULL,
    [premp_ded_dd_acct_type_10]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_11]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_12]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_13]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_14]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_15]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_16]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_17]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_18]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_19]     CHAR (1)        NULL,
    [premp_ded_dd_acct_type_20]     CHAR (1)        NULL,
    [premp_ern_code_1]              CHAR (3)        NULL,
    [premp_ern_code_2]              CHAR (3)        NULL,
    [premp_ern_code_3]              CHAR (3)        NULL,
    [premp_ern_code_4]              CHAR (3)        NULL,
    [premp_ern_code_5]              CHAR (3)        NULL,
    [premp_ern_code_6]              CHAR (3)        NULL,
    [premp_ern_code_7]              CHAR (3)        NULL,
    [premp_ern_code_8]              CHAR (3)        NULL,
    [premp_ern_code_9]              CHAR (3)        NULL,
    [premp_ern_code_10]             CHAR (3)        NULL,
    [premp_ern_active_yn_1]         CHAR (1)        NULL,
    [premp_ern_active_yn_2]         CHAR (1)        NULL,
    [premp_ern_active_yn_3]         CHAR (1)        NULL,
    [premp_ern_active_yn_4]         CHAR (1)        NULL,
    [premp_ern_active_yn_5]         CHAR (1)        NULL,
    [premp_ern_active_yn_6]         CHAR (1)        NULL,
    [premp_ern_active_yn_7]         CHAR (1)        NULL,
    [premp_ern_active_yn_8]         CHAR (1)        NULL,
    [premp_ern_active_yn_9]         CHAR (1)        NULL,
    [premp_ern_active_yn_10]        CHAR (1)        NULL,
    [premp_ern_freq_1]              CHAR (1)        NULL,
    [premp_ern_freq_2]              CHAR (1)        NULL,
    [premp_ern_freq_3]              CHAR (1)        NULL,
    [premp_ern_freq_4]              CHAR (1)        NULL,
    [premp_ern_freq_5]              CHAR (1)        NULL,
    [premp_ern_freq_6]              CHAR (1)        NULL,
    [premp_ern_freq_7]              CHAR (1)        NULL,
    [premp_ern_freq_8]              CHAR (1)        NULL,
    [premp_ern_freq_9]              CHAR (1)        NULL,
    [premp_ern_freq_10]             CHAR (1)        NULL,
    [premp_ern_amount_1]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_2]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_3]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_4]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_5]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_6]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_7]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_8]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_9]            DECIMAL (9, 2)  NULL,
    [premp_ern_amount_10]           DECIMAL (9, 2)  NULL,
    [premp_std_vac_mult]            DECIMAL (4, 2)  NULL,
    [premp_std_sic_mult]            DECIMAL (4, 2)  NULL,
    [premp_std_per_mult]            DECIMAL (4, 2)  NULL,
    [premp_multiple_depts_9]        TINYINT         NULL,
    [premp_prwcc_code]              CHAR (6)        NULL,
    [premp_multiple_wccs_9]         TINYINT         NULL,
    [premp_tax_ms]                  CHAR (1)        NULL,
    [premp_dd_prenote_yn]           CHAR (1)        NULL,
    [premp_dd_acct_type_cs]         CHAR (1)        NULL,
    [premp_pension_flag_9]          TINYINT         NULL,
    [premp_gl1]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct1]                 DECIMAL (5, 2)  NULL,
    [premp_gl2]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct2]                 DECIMAL (5, 2)  NULL,
    [premp_gl3]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct3]                 DECIMAL (5, 2)  NULL,
    [premp_gl4]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct4]                 DECIMAL (5, 2)  NULL,
    [premp_gl5]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct5]                 DECIMAL (5, 2)  NULL,
    [premp_gl6]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct6]                 DECIMAL (5, 2)  NULL,
    [premp_gl7]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct7]                 DECIMAL (5, 2)  NULL,
    [premp_gl8]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct8]                 DECIMAL (5, 2)  NULL,
    [premp_gl9]                     DECIMAL (16, 8) NULL,
    [premp_gl_pct9]                 DECIMAL (5, 2)  NULL,
    [premp_gl10]                    DECIMAL (16, 8) NULL,
    [premp_gl_pct10]                DECIMAL (5, 2)  NULL,
    [premp_gl11]                    DECIMAL (16, 8) NULL,
    [premp_gl_pct11]                DECIMAL (5, 2)  NULL,
    [premp_gl12]                    DECIMAL (16, 8) NULL,
    [premp_gl_pct12]                DECIMAL (5, 2)  NULL,
    [premp_hourly_glpcts_9]         TINYINT         NULL,
    [premp_newhire_credit_yn]       CHAR (1)        NULL,
    [premp_user_id]                 CHAR (16)       NULL,
    [premp_user_rev_dt]             INT             NULL,
    [A4GLIdentity]                  NUMERIC (9)     IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [k_prempmst] PRIMARY KEY NONCLUSTERED ([premp_emp] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [Iprempmst0]
    ON [dbo].[prempmst]([premp_emp] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [Iprempmst1]
    ON [dbo].[prempmst]([premp_last_name] ASC, [premp_first_name] ASC, [premp_initial] ASC, [premp_extension] ASC, [premp_emp] ASC);


GO
CREATE NONCLUSTERED INDEX [Iprempmst2]
    ON [dbo].[prempmst]([premp_ssn] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [Iprempmst3]
    ON [dbo].[prempmst]([premp_dept] ASC, [premp_emp] ASC);


GO
GRANT DELETE
    ON OBJECT::[dbo].[prempmst] TO PUBLIC
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[prempmst] TO PUBLIC
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[prempmst] TO PUBLIC
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[prempmst] TO PUBLIC
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[prempmst] TO PUBLIC
    AS [dbo];

