GO
	PRINT 'BEGIN FRD DELETE ORPHAN BUDGET'
GO

IF EXISTS (SELECT TOP 1 1 FROM sys.columns WHERE NAME  = N'intBudgetCode' AND OBJECT_ID = OBJECT_ID(N'tblFRBudget')) 
BEGIN
    DELETE tblFRBudget WHERE intBudgetCode NOT IN (SELECT intBudgetCode FROM tblGLBudgetCode)
END
GO

GO
	PRINT 'END FRD DELETE ORPHAN BUDGET'
GO