/*******************  BEGIN UPDATING canned panels on table Panel Column*******************/
print('/*******************  BEGIN UPDATING canned panels column *******************/')
print('/*******************  CREATE TEMPORARY table for canned panels column *******************/')
Create TABLE #TampCannedPanelColumn 
(
	[intPanelColumnId] [int] NOT NULL,
	[intPanelId] [int] NOT NULL,
	[strColumn] [nvarchar](max) NULL,
	[strCaption] [nvarchar](max) NULL,
	[intWidth] [smallint] NOT NULL,
	[strAlignment] [nvarchar](max) NULL,
	[strArea] [nvarchar](max) NULL,
	[strFooter] [nvarchar](max) NULL,
	[strFormat] [nvarchar](max) NULL,
	[intSort] [smallint] NOT NULL,
	[strFormatTrue] [nvarchar](max) NULL,
	[strFormatFalse] [nvarchar](max) NULL,
	[strDrillDownColumn] [nvarchar](max) NULL,
	[ysnVisible] [bit] NOT NULL,
	[strType] [nvarchar](max) NULL,
	[strAxis] [nvarchar](max) NULL,
	[strUserName] [nvarchar](max) NULL,
	[intUserId] [int] NOT NULL,
	[intDonut] [smallint] NOT NULL,
	[intMinInterval] [smallint] NOT NULL,
	[intMaxInterval] [smallint] NOT NULL,
	[intStepInterval] [smallint] NOT NULL,
	[strIntervalFormat] [nvarchar](max) NULL,
	[ysnHiddenColumn] [bit] NOT NULL,	
	[intCannedPanelId] [int] NOT NULL	 	
)

print('/*******************  BEGIN INSERTING canned panels on temporary panel column table  *******************/')
INSERT INTO #TampCannedPanelColumn VALUES (1, 27, N'glhst_acct1_8', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'glhstmst.glhst_acct1_8', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 27)
INSERT INTO #TampCannedPanelColumn VALUES (2, 29, N'glije_acct_no', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 29)
INSERT INTO #TampCannedPanelColumn VALUES (3, 28, N'glije_acct_no', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 28)
INSERT INTO #TampCannedPanelColumn VALUES (4, 27, N'glhst_acct9_16', N'Profit Center', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 27)
INSERT INTO #TampCannedPanelColumn VALUES (5, 29, N'glije_date', N'Date', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 29)
INSERT INTO #TampCannedPanelColumn VALUES (6, 28, N'glije_date', N'Date', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 28)
INSERT INTO #TampCannedPanelColumn VALUES (7, 27, N'glact_desc', N'GL Desc', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 27)
INSERT INTO #TampCannedPanelColumn VALUES (8, 29, N'glije_src_sys', N'Source System', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 29)
INSERT INTO #TampCannedPanelColumn VALUES (9, 28, N'glije_src_sys', N'Source System', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 28)
INSERT INTO #TampCannedPanelColumn VALUES (10, 27, N'Amount', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 27)
INSERT INTO #TampCannedPanelColumn VALUES (11, 29, N'glije_ref', N'Reference', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 29)
INSERT INTO #TampCannedPanelColumn VALUES (12, 28, N'glije_ref', N'Reference', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 28)
INSERT INTO #TampCannedPanelColumn VALUES (13, 29, N'glije_doc', N'Document #', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 29)
INSERT INTO #TampCannedPanelColumn VALUES (14, 28, N'glije_doc', N'Document #', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 28)
INSERT INTO #TampCannedPanelColumn VALUES (15, 26, N'glhst_acct1_8', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (16, 29, N'glije_amt', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 29)
INSERT INTO #TampCannedPanelColumn VALUES (17, 28, N'glije_amt', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 28)
INSERT INTO #TampCannedPanelColumn VALUES (18, 26, N'glhst_acct9_16', N'Profit Center', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (19, 26, N'glhst_ref', N'Reference', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (20, 26, N'glhst_period', N'Period', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (21, 26, N'glhst_trans_dt', N'Transaction Date', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (22, 26, N'glhst_src_id', N'Source ID', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (23, 26, N'glhst_src_seq', N'Source Sequence', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (24, 26, N'glhst_dr_cr_ind', N'Credit/Debit', 25, N'Left', N'', N'', N'', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (25, 26, N'glhst_jrnl_no', N'Journal #', 25, N'Left', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (26, 26, N'glhst_doc', N'Document #', 25, N'Left', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (27, 26, N'Amount', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (28, 26, N'glhst_units', N'Units', 25, N'Left', N'', N'', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 26)
INSERT INTO #TampCannedPanelColumn VALUES (29, 30, N'glact_acct1_8', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'glhst_acct1_8', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 30)
INSERT INTO #TampCannedPanelColumn VALUES (30, 30, N'glact_acct9_16', N'Profit Center', 25, N'Left', N'', N'', N'', 3, N'', N'', N'glhst_acct9_16', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 30)
INSERT INTO #TampCannedPanelColumn VALUES (31, 30, N'glact_desc', N'Description', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 30)
INSERT INTO #TampCannedPanelColumn VALUES (32, 31, N'glact_desc', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 31)
INSERT INTO #TampCannedPanelColumn VALUES (33, 31, N'Amount', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 31)
INSERT INTO #TampCannedPanelColumn VALUES (34, 33, N'glact_desc', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 33)
INSERT INTO #TampCannedPanelColumn VALUES (35, 33, N'Amount', N'Amount', 25, N'Left', N'', N' ', N'$####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 33)
INSERT INTO #TampCannedPanelColumn VALUES (36, 32, N'glact_desc', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 32)
INSERT INTO #TampCannedPanelColumn VALUES (37, 32, N'Amount', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 32)
INSERT INTO #TampCannedPanelColumn VALUES (38, 34, N'glact_desc', N'GL Acct', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 34)
INSERT INTO #TampCannedPanelColumn VALUES (39, 34, N'Amount', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 34)
INSERT INTO #TampCannedPanelColumn VALUES (40, 37, N'apcbk_desc', N'Checkbook Name', 25, N'Left', N'', N'', N' ', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'design', 0, 0, 0, 0, 0, NULL, 0, 37)
INSERT INTO #TampCannedPanelColumn VALUES (41, 37, N'apcbk_no', N'Checkbook #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 37)
INSERT INTO #TampCannedPanelColumn VALUES (42, 36, N'apchk_cbk_no', N'Checkbook #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (43, 37, N'apcbk_bal', N'Checkbook Balance', 25, N'Left', N'', N'Sum', N'$####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 37)
INSERT INTO #TampCannedPanelColumn VALUES (44, 36, N'apchk_rev_dt', N'Date', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (45, 36, N'apchk_vnd_no', N'Vendor #', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (46, 36, N'apchk_name', N'Check Name', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (47, 36, N'apchk_chk_amt', N'Check Amount', 25, N'Left', N'', N'Sum', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (48, 36, N'apchk_disc_amt', N'Discount Amount', 25, N'Left', N'', N'Sum', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (49, 36, N'apchk_gl_rev_dt', N'GL Date', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (50, 36, N'apchk_cleared_ind', N'Cleared ?', 25, N'Left', N'', N'', N'  ', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (51, 36, N'apchk_clear_rev_dt', N'Cleared Date', 25, N'Left', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (52, 36, N'apchk_src_sys', N'Source', 25, N'Left', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 36)
INSERT INTO #TampCannedPanelColumn VALUES (53, 35, N'apchk_rev_dt', N'Date', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 35)
INSERT INTO #TampCannedPanelColumn VALUES (54, 35, N'apchk_name', N'Check Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 35)
INSERT INTO #TampCannedPanelColumn VALUES (55, 38, N'apivc_ivc_no', N'Invoice #', 10, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 38)
INSERT INTO #TampCannedPanelColumn VALUES (56, 35, N'apchk_chk_amt', N'Check Amount', 25, N'Left', N'', N'Sum', N'$####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 35)
INSERT INTO #TampCannedPanelColumn VALUES (57, 38, N'apivc_ivc_rev_dt', N'Invoice Date', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 38)
INSERT INTO #TampCannedPanelColumn VALUES (58, 38, N'apivc_vnd_no', N'Vendor #', 25, N'Left', N'', N'', N'', 4, N'', N'', N'apivc_vnd_no', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 38)
INSERT INTO #TampCannedPanelColumn VALUES (59, 38, N'ssvnd_name', N'Vendor Name', 25, N'Left', N'', N'', N'', 5, N'', N'', N'ssvnd_name', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 38)
INSERT INTO #TampCannedPanelColumn VALUES (60, 38, N'Amount', N'Amount', 25, N'Left', N'', N'Sum', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 38)
INSERT INTO #TampCannedPanelColumn VALUES (61, 38, N'apivc_chk_rev_dt', N'Check Date', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 38)
INSERT INTO #TampCannedPanelColumn VALUES (62, 38, N'apivc_trans_type', N'Transaction Type', 10, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 38)
INSERT INTO #TampCannedPanelColumn VALUES (63, 43, N'agstm_ivc_no', N'Invoice #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'agstm_ivc_no', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 43)
INSERT INTO #TampCannedPanelColumn VALUES (64, 44, N'agcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 44)
INSERT INTO #TampCannedPanelColumn VALUES (65, 42, N'agstm_bill_to_cus', N'Bill To #', 25, N'Left', N'', N'', N' ', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 42)
INSERT INTO #TampCannedPanelColumn VALUES (66, 46, N'agcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 46)
INSERT INTO #TampCannedPanelColumn VALUES (67, 43, N'agstm_ship_rev_dt', N'Ship Date', 25, N'Right', N'', N'', N'Date', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 43)
INSERT INTO #TampCannedPanelColumn VALUES (68, 43, N'Profit Percent', N'Profit Percent', 25, N'Right', N'', N'', N'##.###%', 5, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 43)
INSERT INTO #TampCannedPanelColumn VALUES (69, 44, N'Amount', N'Amount', 25, N'Right', N'', N'Sum', N'$####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 44)
INSERT INTO #TampCannedPanelColumn VALUES (70, 42, N'agitm_desc', N'Item/Product', 25, N'Left', N'', N'', N'', 2, N'', N'', N'agitm_desc', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 42)
INSERT INTO #TampCannedPanelColumn VALUES (71, 42, N'agitm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 3, N'', N'', N'agitm_loc_no', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 42)
INSERT INTO #TampCannedPanelColumn VALUES (72, 42, N'agitm_un_on_hand', N'On Hand Inventory', 25, N'Right', N'', N'Sum', N'####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 42)
INSERT INTO #TampCannedPanelColumn VALUES (73, 47, N'Future', N'', 25, N'Right', N'', N'', N'$####.00', 2, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 47)
INSERT INTO #TampCannedPanelColumn VALUES (74, 45, N'agitm_no', N'Item#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (75, 47, N'Current', N'', 25, N'Right', N'', N'', N'$####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 47)
INSERT INTO #TampCannedPanelColumn VALUES (76, 45, N'agitm_desc', N'Item/Product', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (77, 47, N'30days', N'31-60 Days', 25, N'Right', N'', N'', N'$####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 47)
INSERT INTO #TampCannedPanelColumn VALUES (78, 45, N'agitm_pak_desc', N'Package', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (79, 47, N'60days', N'61-90 Days', 25, N'Right', N'', N'', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 47)
INSERT INTO #TampCannedPanelColumn VALUES (80, 45, N'agitm_class', N'Class', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (81, 47, N'90days', N'91-120 Days', 25, N'Right', N'', N'', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 47)
INSERT INTO #TampCannedPanelColumn VALUES (82, 47, N'120days', N'Over 120 Days', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 47)
INSERT INTO #TampCannedPanelColumn VALUES (83, 45, N'agitm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (84, 45, N'agitm_last_un_cost', N'Last Unit Cost', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (85, 48, N'agcnt_cus_no', N'Customer#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'agcnt_cus_no', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 48)
INSERT INTO #TampCannedPanelColumn VALUES (86, 45, N'agitm_avg_un_cost', N'Average Unit Cost', 25, N'Right', N'', N'', N'$####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (87, 48, N'agcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 48)
INSERT INTO #TampCannedPanelColumn VALUES (88, 45, N'agitm_un_on_hand', N'Units On Hand Qty', 25, N'Right', N'', N'Sum', N'####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 45)
INSERT INTO #TampCannedPanelColumn VALUES (89, 48, N'agcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 48)
INSERT INTO #TampCannedPanelColumn VALUES (90, 48, N'agcnt_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'agcnt_loc_no', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 48)
INSERT INTO #TampCannedPanelColumn VALUES (91, 48, N'agcnt_cnt_no', N'Contract #', 25, N'Left', N'', N'Count', N'', 7, N'', N'', N'agcnt_cnt_no', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 48)
INSERT INTO #TampCannedPanelColumn VALUES (92, 48, N'agcnt_un_bal', N'Unit Balance', 25, N'Right', N'', N'Sum', N'####.00', 14, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 48)
INSERT INTO #TampCannedPanelColumn VALUES (93, 51, N'agitm_no', N'Item#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'agitm_no', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 51)
INSERT INTO #TampCannedPanelColumn VALUES (94, 51, N'agitm_desc', N'Item/Product', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 51)
INSERT INTO #TampCannedPanelColumn VALUES (95, 50, N'agcnt_cus_no', N'Customer#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (96, 51, N'agitm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'agitm_loc_no', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 51)
INSERT INTO #TampCannedPanelColumn VALUES (97, 50, N'agcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (98, 51, N'agitm_un_on_hand', N'Units On Hand Qty', 25, N'Right', N'', N'Sum', N'####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 51)
INSERT INTO #TampCannedPanelColumn VALUES (99, 50, N'agcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (100, 50, N'agcnt_slsmn_id', N'Salesperson ID', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (101, 50, N'agcnt_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (102, 50, N'agcnt_cnt_no', N'Contract #', 25, N'Left', N'', N'Count', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (103, 50, N'agcnt_cnt_rev_dt', N'Contract Date', 25, N'Right', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (104, 50, N'agcnt_due_rev_dt', N'Due Date', 25, N'Right', N'', N'', N'', 9, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (105, 50, N'agcnt_itm_or_cls', N'Item or Class', 25, N'Left', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (106, 50, N'agcnt_prc_lvl', N'Price Level', 25, N'Left', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (107, 50, N'agcnt_ppd_yndm', N'Prepaid', 25, N'Left', N'', N'', N'Yes/No', 12, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, NULL, 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (108, 50, N'agcnt_un_orig', N'Original Units', 25, N'Right', N'', N'Sum', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (109, 50, N'agcnt_un_bal', N'Unit Balance', 25, N'Right', N'', N'Sum', N'####.00', 14, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 50)
INSERT INTO #TampCannedPanelColumn VALUES (110, 52, N'agord_cus_no', N'Customer#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 52)
INSERT INTO #TampCannedPanelColumn VALUES (111, 52, N'agord_ord_no', N'Order#', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 52)
INSERT INTO #TampCannedPanelColumn VALUES (112, 52, N'agord_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 52)
INSERT INTO #TampCannedPanelColumn VALUES (113, 52, N'agord_ord_rev_dt', N'Order Date', 25, N'Right', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 52)
INSERT INTO #TampCannedPanelColumn VALUES (114, 52, N'agord_itm_no', N'Item #', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 52)
INSERT INTO #TampCannedPanelColumn VALUES (115, 52, N'agord_pkg_sold', N'Packages Sold', 25, N'Right', N'', N'', N'####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 52)
INSERT INTO #TampCannedPanelColumn VALUES (116, 49, N'agstm_bill_to_cus', N'Bill To Customer', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (117, 49, N'agstm_ivc_no', N'Invoice #', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (118, 49, N'agstm_ship_rev_dt', N'Ship Date', 25, N'Right', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (119, 49, N'agstm_itm_no', N'Item #', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (120, 49, N'agstm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (121, 49, N'agstm_class', N'Class Code', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (122, 49, N'agstm_un', N'Units Sold', 25, N'Right', N'', N'', N'####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (123, 49, N'agstm_un_prc', N'Unit Price', 25, N'Right', N'', N'', N'$####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (124, 49, N'agstm_sls', N'Sales Amount', 25, N'Right', N'', N'', N'$####.00', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (125, 49, N'agstm_un_cost', N'Unit Costs', 25, N'Right', N'', N'', N'$####.00', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (126, 49, N'agstm_cgs', N'Costs Amount', 25, N'Right', N'', N'', N'$####.00', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (127, 49, N'agstm_slsmn_id', N'Salesperson', 25, N'Left', N'', N'', N'', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (128, 49, N'agstm_pak_desc', N'Package Desc', 25, N'Left', N'', N'', N'', 14, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (129, 49, N'agstm_un_desc', N'Unit Desc', 25, N'Left', N'', N'', N'', 15, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (130, 49, N'unit margins', N'Unit Margins', 25, N'Right', N'', N'', N'$####.000', 16, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (131, 49, N'Profit Amount', N'Profit Amount', 25, N'Right', N'', N'', N'$###0.000', 17, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (132, 49, N'Profit Percent', N'Profit Percent', 25, N'Right', N'', N'', N'##.###%', 18, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 49)
INSERT INTO #TampCannedPanelColumn VALUES (133, 53, N'agitm_no', N'Item #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (134, 53, N'agitm_desc', N'Item Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (135, 53, N'agitm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (136, 53, N'agitm_un_desc', N'Unit Desc', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (137, 53, N'agitm_un_on_hand', N'On Hand', 25, N'Right', N'', N'Sum', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (138, 53, N'agitm_un_pend_ivcs', N'Pending Invoices', 25, N'Right', N'', N'Sum', N'####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (139, 53, N'agitm_un_on_order', N'On Order', 25, N'Right', N'', N'Sum', N'####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (140, 53, N'agitm_un_mfg_in_prs', N'Mfg', 25, N'Right', N'', N'Sum', N'####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (141, 53, N'agitm_un_fert_committed', N'Contracts Committed', 25, N'Right', N'', N'Sum', N'####.00', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (142, 53, N'agitm_un_ord_committed', N'Orders Committed', 25, N'Right', N'', N'Sum', N'####.00', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (143, 53, N'agitm_un_cnt_committed', N'Other Contracts Committed', 25, N'Right', N'', N'Sum', N'####.00', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (144, 53, N'Available', N'Available', 25, N'Right', N'', N'Sum', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 53)
INSERT INTO #TampCannedPanelColumn VALUES (145, 54, N'agitm_no', N'Item #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'agitm_no', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 54)
INSERT INTO #TampCannedPanelColumn VALUES (146, 54, N'agitm_desc', N'Item Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 54)
INSERT INTO #TampCannedPanelColumn VALUES (147, 54, N'agitm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 4, N'', N'', N'agitm_loc_no', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 54)
INSERT INTO #TampCannedPanelColumn VALUES (148, 54, N'Available', N'Available', 25, N'Right', N'', N'Sum', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 54)
INSERT INTO #TampCannedPanelColumn VALUES (149, 55, N'ptitm_itm_no', N'Item Code', 25, N'Left', N'', N'', N'', 2, N'', N'', N'ptitm_itm_no', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 55)
INSERT INTO #TampCannedPanelColumn VALUES (150, 58, N'ptstm_itm_no', N'Item#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 58)
INSERT INTO #TampCannedPanelColumn VALUES (151, 56, N'pttic_cus_no', N'Customer#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 56)
INSERT INTO #TampCannedPanelColumn VALUES (152, 55, N'ptitm_desc', N'Item/Product', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 55)
INSERT INTO #TampCannedPanelColumn VALUES (153, 58, N'ptitm_desc', N'Item/Product', 25, N'Left', N'', N' ', N' ', 3, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 58)
INSERT INTO #TampCannedPanelColumn VALUES (154, 56, N'ptcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 56)
INSERT INTO #TampCannedPanelColumn VALUES (155, 55, N'ptitm_loc_no', N'Loc', 25, N'Left', N'', N'', N' ', 4, N'', N'', N'ptitm_loc_no', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 55)
INSERT INTO #TampCannedPanelColumn VALUES (156, 58, N'Sales', N'Sales', 25, N'Right', N'', N'', N'$###0.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 58)
INSERT INTO #TampCannedPanelColumn VALUES (157, 56, N'ptcus_first_name', N'Customer Name', 25, N'Left', N'', N'', N' ', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 56)
INSERT INTO #TampCannedPanelColumn VALUES (158, 57, N'ptstm_bill_to_cus', N'Bill To Cus', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (159, 55, N'ptitm_on_hand', N'On-Hand Quantity', 25, N'Right', N'', N'Sum', N'####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 55)
INSERT INTO #TampCannedPanelColumn VALUES (160, 56, N'pttic_itm_no', N'Item#', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 56)
INSERT INTO #TampCannedPanelColumn VALUES (161, 57, N'ptstm_ivc_no', N'Invoice #', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (162, 56, N'pttic_qty_orig', N'Quantity', 25, N'Right', N'', N'Sum', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, N'', 0, 56)
INSERT INTO #TampCannedPanelColumn VALUES (163, 57, N'ptstm_ship_rev_dt', N'Ship Date', 25, N'Right', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, N'', 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (164, 56, N'pttic_tic_no', N'Ticket #', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 56)
INSERT INTO #TampCannedPanelColumn VALUES (165, 57, N'ptstm_itm_no', N'Item#', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (166, 56, N'pttic_rev_dt', N'Date', 25, N'Right', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 56)
INSERT INTO #TampCannedPanelColumn VALUES (167, 57, N'ptstm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (168, 57, N'ptstm_class', N'Class Code', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (169, 57, N'ptstm_un', N'Units Sold', 25, N'Right', N'', N'', N'####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (170, 57, N'ptstm_un_prc', N'Unit Price', 25, N'Right', N'', N'', N'$####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (171, 57, N'ptstm_net', N'Sales', 25, N'Right', N'', N'', N'$####.00', 10, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (172, 57, N'ptstm_cgs', N'Costs', 25, N'Right', N'', N'', N'$####.00', 11, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (173, 57, N'ptstm_slsmn_id', N'Salesperson', 25, N'Left', N'', N'', N'', 12, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (174, 57, N'ptstm_pak_desc', N'Package Desc', 25, N'Left', N'', N'', N'', 13, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (175, 57, N'ptstm_un_desc', N'Unit Desc', 25, N'Left', N'', N'', N'', 14, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (176, 57, N'Profit Amount', N'Profit Amount', 25, N'Right', N'', N'', N'$####.00', 15, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (177, 57, N'Profit Percent', N'Profit Percentage', 25, N'Right', N'', N'', N'##.###%', 16, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 57)
INSERT INTO #TampCannedPanelColumn VALUES (178, 61, N'ptstm_bill_to_cus', N'Bill To Cus', 25, N'Left', N'', N'', N'', 2, N'', N'', N'ptstm_bill_to_cus', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 61)
INSERT INTO #TampCannedPanelColumn VALUES (179, 61, N'ptstm_ivc_no', N'Invoice #', 25, N'Left', N'', N'', N'', 3, N'', N'', N'ptstm_ivc_no', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 61)
INSERT INTO #TampCannedPanelColumn VALUES (180, 61, N'ptstm_ship_rev_dt', N'Ship Date', 25, N'Right', N'', N'', N'Date', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 61)
INSERT INTO #TampCannedPanelColumn VALUES (181, 62, N'ptcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 62)
INSERT INTO #TampCannedPanelColumn VALUES (182, 61, N'Profit Percent', N'Profit Percentage', 25, N'Right', N'', N'', N'##.###%', 16, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 61)
INSERT INTO #TampCannedPanelColumn VALUES (183, 62, N'First Name', N'First Name', 25, N'Left', N'', N'', N' ', 3, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 62)
INSERT INTO #TampCannedPanelColumn VALUES (184, 62, N'Customer Code', N'Customer Code', 25, N'Left', N'', N' ', N' ', 4, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 62)
INSERT INTO #TampCannedPanelColumn VALUES (185, 62, N'Sales', N'Sales', 25, N'Right', N'', N'', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 62)
INSERT INTO #TampCannedPanelColumn VALUES (186, 63, N'ptitm_itm_no', N'Item#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (187, 63, N'ptitm_desc', N'Item/Product', 45, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (188, 63, N'ptitm_loc_no', N'Loc', 15, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (189, 63, N'ptitm_class', N'Class', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (190, 63, N'ptitm_unit', N'Unit Desc', 15, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (191, 63, N'ptitm_cost1', N'Last Costs', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (192, 63, N'ptitm_avg_cost', N'Average Costs', 25, N'Right', N'', N'', N'$####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (193, 63, N'ptitm_std_cost', N'Standard Costs', 25, N'Right', N'', N'', N'$####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (194, 63, N'ptitm_on_hand', N'Units On Hand', 25, N'Right', N'', N'', N'####.00', 10, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 63)
INSERT INTO #TampCannedPanelColumn VALUES (195, 64, N'ptcus_cus_no', N'Customer#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 64)
INSERT INTO #TampCannedPanelColumn VALUES (196, 64, N'ptcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 64)
INSERT INTO #TampCannedPanelColumn VALUES (197, 64, N'ptcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 64)
INSERT INTO #TampCannedPanelColumn VALUES (198, 64, N'ptcus_credit_limit', N'Credit Limit', 25, N'Right', N'', N'', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 64)
INSERT INTO #TampCannedPanelColumn VALUES (199, 64, N'Total Balance', N'Total Balance', 25, N'Right', N'', N'', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 64)
INSERT INTO #TampCannedPanelColumn VALUES (200, 64, N'overage', N'Overage', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'petro', 0, 0, 0, 0, 0, NULL, 0, 64)
INSERT INTO #TampCannedPanelColumn VALUES (201, 66, N'ptitm_itm_no', N'Item Code', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 66)
INSERT INTO #TampCannedPanelColumn VALUES (202, 66, N'ptitm_desc', N'Item/Product', 45, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 66)
INSERT INTO #TampCannedPanelColumn VALUES (203, 66, N'ptitm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 66)
INSERT INTO #TampCannedPanelColumn VALUES (204, 66, N'ptitm_on_hand', N'On Hand Quantity', 25, N'Right', N'', N'', N'####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 66)
INSERT INTO #TampCannedPanelColumn VALUES (205, 67, N'Current', N'Current', 25, N'Right', N'', N'', N'$####.00', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 67)
INSERT INTO #TampCannedPanelColumn VALUES (206, 67, N'31-60 Days', N'31-60 Days', 25, N'Right', N'', N'', N'$####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 67)
INSERT INTO #TampCannedPanelColumn VALUES (207, 67, N'61-90 Days', N'61-90 Days', 25, N'Right', N'', N'', N'$####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 67)
INSERT INTO #TampCannedPanelColumn VALUES (208, 67, N'91-120 Days', N'91-120 Days', 25, N'Right', N'', N'', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 67)
INSERT INTO #TampCannedPanelColumn VALUES (209, 67, N'Over 120 Days', N'Over 120 Days', 25, N'Right', N'', N'', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 67)
INSERT INTO #TampCannedPanelColumn VALUES (210, 68, N'ptcus_cus_no', N'Customer Code', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 68)
INSERT INTO #TampCannedPanelColumn VALUES (211, 68, N'ptcus_last_name', N'Last Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 68)
INSERT INTO #TampCannedPanelColumn VALUES (212, 68, N'ptcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 68)
INSERT INTO #TampCannedPanelColumn VALUES (213, 68, N'ptcus_ar_ov120', N'Amount', 25, N'Right', N'', N'Sum', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 68)
INSERT INTO #TampCannedPanelColumn VALUES (214, 69, N'Customer Last Name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 69)
INSERT INTO #TampCannedPanelColumn VALUES (215, 69, N'First Name', N'First Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 69)
INSERT INTO #TampCannedPanelColumn VALUES (216, 69, N'Customer Code', N'Customer Code', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 69)
INSERT INTO #TampCannedPanelColumn VALUES (217, 69, N'Sales', N'Sales', 25, N'Right', N'', N'', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 69)
INSERT INTO #TampCannedPanelColumn VALUES (218, 69, N'Units', N'Units', 25, N'Right', N'', N'', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 69)
INSERT INTO #TampCannedPanelColumn VALUES (219, 62, N'Units', N'Units', 25, N'Right', N'', N'', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 62)
INSERT INTO #TampCannedPanelColumn VALUES (220, 70, N'agstm_itm_no', N'Item #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 70)
INSERT INTO #TampCannedPanelColumn VALUES (221, 70, N'agitm_desc', N'Item/Product', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 70)
INSERT INTO #TampCannedPanelColumn VALUES (222, 70, N'Sales', N'Sales', 25, N'Right', N'', N'', N'$###0.00', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 70)
INSERT INTO #TampCannedPanelColumn VALUES (223, 70, N'Units', N'Units', 25, N'Right', N'', N'', N'####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 70)
INSERT INTO #TampCannedPanelColumn VALUES (224, 58, N'Units', N'Units', 25, N'Right', N'', N'', N'####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 58)
INSERT INTO #TampCannedPanelColumn VALUES (225, 71, N'ptitm_itm_no', N'Item #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 71)
INSERT INTO #TampCannedPanelColumn VALUES (226, 71, N'ptitm_desc', N'Item/Product', 45, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 71)
INSERT INTO #TampCannedPanelColumn VALUES (227, 71, N'ptitm_loc_no', N'Loc', 15, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 71)
INSERT INTO #TampCannedPanelColumn VALUES (228, 71, N'ptitm_unit', N'Unit Desc', 15, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 71)
INSERT INTO #TampCannedPanelColumn VALUES (229, 71, N'ptitm_on_hand', N'On Hand Qty', 25, N'Right', N'', N'', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 71)
INSERT INTO #TampCannedPanelColumn VALUES (230, 71, N'ptitm_last_sale_rev_dt', N'Last Sale Date', 25, N'Right', N'', N'', N'Date', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 71)
INSERT INTO #TampCannedPanelColumn VALUES (231, 72, N'agitm_no', N'Item #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 72)
INSERT INTO #TampCannedPanelColumn VALUES (232, 72, N'agitm_desc', N'Item/Product', 45, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 72)
INSERT INTO #TampCannedPanelColumn VALUES (233, 72, N'agitm_loc_no', N'Loc', 15, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 72)
INSERT INTO #TampCannedPanelColumn VALUES (234, 72, N'agitm_un_desc', N'Unit Desc', 15, N'Left', N'', N'', N' ', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 72)
INSERT INTO #TampCannedPanelColumn VALUES (235, 72, N'agitm_un_on_hand', N'On Hand Qty', 25, N'Right', N'', N'', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 72)
INSERT INTO #TampCannedPanelColumn VALUES (236, 72, N'agitm_last_sale_rev_dt', N'Last Sale Date', 25, N'Right', N'', N'', N'Date', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, NULL, 0, 72)
INSERT INTO #TampCannedPanelColumn VALUES (237, 73, N'apivc_ivc_no', N'Invoice#', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 73)
INSERT INTO #TampCannedPanelColumn VALUES (238, 73, N'apivc_ivc_rev_dt', N'Invoice Date', 25, N'Right', N'', N'', N'Date', 3, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 73)
INSERT INTO #TampCannedPanelColumn VALUES (239, 73, N'apivc_vnd_no', N'Vendor #', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 73)
INSERT INTO #TampCannedPanelColumn VALUES (240, 73, N'ssvnd_name', N'Vendor', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 73)
INSERT INTO #TampCannedPanelColumn VALUES (241, 73, N'amounts', N'Amount Due', 25, N'Right', N'', N'', N'$###0.00', 6, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 73)
INSERT INTO #TampCannedPanelColumn VALUES (242, 73, N'apivc_due_rev_dt', N'Due Date', 25, N'Right', N'', N'', N'Date', 7, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 73)
INSERT INTO #TampCannedPanelColumn VALUES (243, 1, N'agcus_key', N'Customer #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 1)
INSERT INTO #TampCannedPanelColumn VALUES (244, 1, N'agcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 1)
INSERT INTO #TampCannedPanelColumn VALUES (245, 1, N'agcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 1)
INSERT INTO #TampCannedPanelColumn VALUES (246, 1, N'agcus_cred_limit', N'Credit Limit', 25, N'Right', N'', N'', N'$####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 1)
INSERT INTO #TampCannedPanelColumn VALUES (247, 1, N'Total Balance', N'Total Balance', 25, N'Right', N'', N'', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 1)
INSERT INTO #TampCannedPanelColumn VALUES (248, 1, N'Overage', N'Overage', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'master', 0, 0, 0, 0, 0, NULL, 0, 1)
INSERT INTO #TampCannedPanelColumn VALUES (249, 3, N'Store', N'Store', 0, N'Series1AxisX', N'', N'', N'Number', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'design', 0, 0, 0, 0, 0, N'', 0, 3)
INSERT INTO #TampCannedPanelColumn VALUES (250, 2, N'sthss_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 2)
INSERT INTO #TampCannedPanelColumn VALUES (251, 4, N'sthss_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 4)
INSERT INTO #TampCannedPanelColumn VALUES (252, 4, N'sthss_rev_dt', N'Date', 25, N'Right', N'', N'', N'Date', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 4)
INSERT INTO #TampCannedPanelColumn VALUES (253, 7, N'sthss_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 7)
INSERT INTO #TampCannedPanelColumn VALUES (254, 6, N'Store', N'Store', 0, N'Series1AxisX', N'', N'', N'Number', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'design', 0, 0, 0, 0, 0, N'', 0, 6)
INSERT INTO #TampCannedPanelColumn VALUES (255, 5, N'sthss_store_name', N'Store Name', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 5)
INSERT INTO #TampCannedPanelColumn VALUES (256, 5, N'sthss_rev_dt', N'Date', 25, N'Right', N'', N'', N'Date', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 5)
INSERT INTO #TampCannedPanelColumn VALUES (257, 6, N'Customer Count', N'Customer Count', 0, N'Series1AxisY', N'', N'', N'Number', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'design', 0, 0, 0, 0, 0, N'', 0, 6)
INSERT INTO #TampCannedPanelColumn VALUES (258, 7, N'sthss_pmp_id', N'Fuel Product', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 7)
INSERT INTO #TampCannedPanelColumn VALUES (259, 4, N'sthss_key_refund_amt', N'Refund Amount', 25, N'Right', N'', N'', N'$####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 4)
INSERT INTO #TampCannedPanelColumn VALUES (260, 3, N'Cash Over / Short Amount', N'Over / Short Amount', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'design', 0, 0, 0, 0, 0, N'', 0, 3)
INSERT INTO #TampCannedPanelColumn VALUES (261, 2, N'sthss_pmp_desc', N'Fuel Product', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 2)
INSERT INTO #TampCannedPanelColumn VALUES (262, 5, N'sthss_tot_cash_overshort', N'Cash Over / Short', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'cstore', 0, 0, 0, 0, 0, N'', 0, 5)
INSERT INTO #TampCannedPanelColumn VALUES (263, 7, N'Quantity', N'Gallons', 25, N'Right', N'', N'', N'####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 7)
INSERT INTO #TampCannedPanelColumn VALUES (264, 2, N'Sales Amount', N'Sales Amount', 25, N'Right', N'', N'', N'$####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 2)
INSERT INTO #TampCannedPanelColumn VALUES (265, 9, N'sthss_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 9)
INSERT INTO #TampCannedPanelColumn VALUES (266, 9, N'sthss_key_deptno', N'Dept #', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 9)
INSERT INTO #TampCannedPanelColumn VALUES (267, 8, N'sthss_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 8)
INSERT INTO #TampCannedPanelColumn VALUES (268, 9, N'total sales', N'Total Sales', 25, N'Right', N'', N'', N'$####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 9)
INSERT INTO #TampCannedPanelColumn VALUES (269, 8, N'sthss_rev_dt', N'Date', 25, N'Right', N'', N'', N'Date', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 8)
INSERT INTO #TampCannedPanelColumn VALUES (270, 8, N'Total Customers', N'Customer Count', 25, N'Right', N'', N'', N'####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 8)
INSERT INTO #TampCannedPanelColumn VALUES (271, 12, N'stphy_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 12)
INSERT INTO #TampCannedPanelColumn VALUES (272, 13, N'sthss_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 13)
INSERT INTO #TampCannedPanelColumn VALUES (273, 12, N'stphy_rev_dt', N'Date', 25, N'Right', N'', N'', N'Date', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 12)
INSERT INTO #TampCannedPanelColumn VALUES (274, 11, N'stpbk_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 11)
INSERT INTO #TampCannedPanelColumn VALUES (275, 12, N'stphy_shift_no', N'Shift #', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 12)
INSERT INTO #TampCannedPanelColumn VALUES (276, 11, N'stpbk_upcno_x', N'UPC', 25, N'Right', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 11)
INSERT INTO #TampCannedPanelColumn VALUES (277, 12, N'stphy_itm_desc', N'Item', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 12)
INSERT INTO #TampCannedPanelColumn VALUES (278, 11, N'stpbk_item_desc', N'Item Desc', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 11)
INSERT INTO #TampCannedPanelColumn VALUES (279, 13, N'sthss_rev_dt', N'Date', 25, N'Left', N'', N'', N'Date', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 13)
INSERT INTO #TampCannedPanelColumn VALUES (280, 11, N'stpbk_sale_startdate', N'Sale Start Date', 25, N'Right', N'', N'', N'Date', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 11)
INSERT INTO #TampCannedPanelColumn VALUES (281, 13, N'sthss_tot_no_nosales', N'No Sale Transactions', 25, N'Right', N'', N'', N'####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 13)
INSERT INTO #TampCannedPanelColumn VALUES (282, 11, N'stpbk_sale_enddate', N'Sale End Date', 25, N'Right', N'', N'', N'Date', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 11)
INSERT INTO #TampCannedPanelColumn VALUES (283, 12, N'stphy_diff_qty', N'Diff Qty', 25, N'Right', N'', N'', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 12)
INSERT INTO #TampCannedPanelColumn VALUES (284, 11, N'stpbk_sale_price', N'Sale Price', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 11)
INSERT INTO #TampCannedPanelColumn VALUES (285, 10, N'stphy_store_name', N'Store', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (286, 10, N'stphy_rev_dt', N'Date', 25, N'Right', N'', N'', N'Date', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (287, 10, N'stphy_shift_no', N'Shift #', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (288, 10, N'stphy_binloc', N'Bin Loc', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (289, 10, N'stphy_itm_id', N'Item ID', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (290, 10, N'stphy_upc_modno', N'Mod #', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (291, 10, N'stphy_itm_desc', N'Item', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (292, 10, N'stphy_cnt_what_cd', N'Count', 25, N'Left', N'', N'', N'', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (293, 10, N'stphy_pur_qty', N'Pur Qty', 25, N'Right', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (294, 10, N'stphy_sls_qty', N'Sls Qty', 25, N'Right', N'', N'', N'', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (295, 10, N'stphy_end_qty', N'End Qty', 25, N'Right', N'', N'', N'', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (296, 10, N'stphy_diff_qty', N'Diff Qty', 25, N'Right', N'', N'', N'', 14, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (297, 10, N'stphy_stick_rdg', N'Stick Reading', 25, N'Left', N'', N'', N'', 15, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (298, 10, N'stphy_posted_yn', N'Posted?', 25, N'Left', N'', N'', N'', 16, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (299, 10, N'stphy_pending_qty', N'Pending Qty', 25, N'Right', N'', N'', N'', 17, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (300, 10, N'stphy_entered_qty', N'Entered Qty', 25, N'Right', N'', N'', N'', 18, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (301, 10, N'stphy_deptno', N'Dept #', 25, N'Left', N'', N'', N'', 19, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (302, 10, N'stphy_price', N'Price', 25, N'Right', N'', N'', N'', 20, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (303, 10, N'Total Inv', N'Total Inv', 25, N'Right', N'', N'', N'', 21, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 10)
INSERT INTO #TampCannedPanelColumn VALUES (304, 14, N'stith_dpt_id', N'Dept ID', 25, N'Right', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'cstore', 0, 0, 0, 0, 0, N'', 0, 14)
INSERT INTO #TampCannedPanelColumn VALUES (305, 14, N'Quantity', N'Units Sold', 25, N'Right', N'', N'', N'####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'cstore', 0, 0, 0, 0, 0, N'', 0, 14)
INSERT INTO #TampCannedPanelColumn VALUES (306, 39, N'CheckDate', N'Check Date', 0, N'Series1AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 39)
INSERT INTO #TampCannedPanelColumn VALUES (307, 39, N'Amount', N'Amount', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 39)
INSERT INTO #TampCannedPanelColumn VALUES (308, 40, N'Month', N'Month', 0, N'Series1AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 40)
INSERT INTO #TampCannedPanelColumn VALUES (309, 40, N'Month', N'Month', 0, N'Series2AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series2AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 40)
INSERT INTO #TampCannedPanelColumn VALUES (310, 40, N'Amount', N'Revenue Amount', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 40)
INSERT INTO #TampCannedPanelColumn VALUES (311, 40, N'Amount', N'Expense Amount', 0, N'Series2AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series2AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 40)
INSERT INTO #TampCannedPanelColumn VALUES (312, 41, N'Month', N'Month', 0, N'Series1AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 41)
INSERT INTO #TampCannedPanelColumn VALUES (313, 41, N'Month', N'Month', 0, N'Series2AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series2AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 41)
INSERT INTO #TampCannedPanelColumn VALUES (314, 41, N'Amount', N'Assets Amount', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 41)
INSERT INTO #TampCannedPanelColumn VALUES (315, 41, N'Amount', N'Liabilities Amount', 0, N'Series2AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series2AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 41)
INSERT INTO #TampCannedPanelColumn VALUES (316, 46, N'agstm_key_loc_no', N'Location', 0, N'Series1AxisX', N'', N'', N'General', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 46)
INSERT INTO #TampCannedPanelColumn VALUES (317, 46, N'agstm_key_loc_no', N'Location', 0, N'Series2AxisX', N'', N'', N'General', 1, N'', N'', N'', 1, N'Chart', N'Series2AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 46)
INSERT INTO #TampCannedPanelColumn VALUES (318, 46, N'Sales', N'Sales Amount', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 46)
INSERT INTO #TampCannedPanelColumn VALUES (319, 46, N'Costs', N'Costs', 0, N'Series2AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series2AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 46)
INSERT INTO #TampCannedPanelColumn VALUES (320, 65, N'Month', N'Month', 0, N'Series1AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 65)
INSERT INTO #TampCannedPanelColumn VALUES (321, 65, N'Month', N'Month', 0, N'Series2AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series2AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 65)
INSERT INTO #TampCannedPanelColumn VALUES (322, 65, N'Sales', N'Sales', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 65)
INSERT INTO #TampCannedPanelColumn VALUES (323, 65, N'Costs', N'Costs', 0, N'Series2AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series2AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 65)
INSERT INTO #TampCannedPanelColumn VALUES (324, 60, N'Month', N'Month', 0, N'Series1AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 60)
INSERT INTO #TampCannedPanelColumn VALUES (325, 60, N'Month', N'Month', 0, N'Series2AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series2AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 60)
INSERT INTO #TampCannedPanelColumn VALUES (326, 60, N'Sales', N'Sales', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 60)
INSERT INTO #TampCannedPanelColumn VALUES (327, 60, N'Costs', N'Costs', 0, N'Series2AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series2AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 60)
INSERT INTO #TampCannedPanelColumn VALUES (328, 59, N'Location', N'Location', 0, N'Series1AxisX', N'', N'', N'General', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 59)
INSERT INTO #TampCannedPanelColumn VALUES (329, 59, N'Sales', N'Sales', 0, N'Series1AxisY', N'', N'', N'Currency', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 59)
INSERT INTO #TampCannedPanelColumn VALUES (330, 15, N'gaitr_pur_sls_ind', N'P or S', 5, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (331, 15, N'gaitr_loc_no', N'Loc', 6, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (332, 17, N'gacnt_pur_sls_ind', N'P/S', 25, N'Left', N'', N'', N'', 1, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (333, 15, N'gaitr_cus_no', N'Cust#', 15, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (334, 17, N'gacnt_cus_no', N'Customer #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (335, 19, N'gacom_desc', N'Com', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 19)
INSERT INTO #TampCannedPanelColumn VALUES (336, 15, N'agcus_last_name', N'Customer Last Name', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (337, 17, N'agcus_last_name', N'Last Name', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (338, 19, N'gapos_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 19)
INSERT INTO #TampCannedPanelColumn VALUES (339, 15, N'agcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (340, 18, N'gacnt_pur_sls_ind', N'P or S', 25, N'Left', N'', N'', N'', 1, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (341, 17, N'agcus_first_name', N'First Name', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (342, 19, N'gapos_in_house', N'In House', 25, N'Right', N'', N'Sum', N'####.00', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 19)
INSERT INTO #TampCannedPanelColumn VALUES (343, 15, N'gacom_desc', N'Com', 15, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (344, 18, N'gacnt_com_cd', N'Com', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (345, 19, N'gapos_offsite', N'Offsite', 25, N'Right', N'', N'Sum', N'####.00', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 19)
INSERT INTO #TampCannedPanelColumn VALUES (346, 19, N'gapos_sls_in_transit', N'In Transit', 25, N'Right', N'', N'Sum', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 19)
INSERT INTO #TampCannedPanelColumn VALUES (347, 15, N'gaitr_tic_no', N'Ticket', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (348, 18, N'Option Month', N'Option Month', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (349, 17, N'gacnt_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (350, 15, N'gaitr_un_out', N'Units', 25, N'Right', N'', N'Sum', N'####.000', 9, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 15)
INSERT INTO #TampCannedPanelColumn VALUES (351, 18, N'Option Year', N'Option Year', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (352, 17, N'gacnt_com_cd', N'Com', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (353, 18, N'Balance', N'Balance', 25, N'Right', N'', N'', N'$####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (354, 17, N'gacnt_cnt_no', N'Contact #', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (355, 18, N'Price', N'Price', 25, N'Right', N'', N'', N'$####.00', 7, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (356, 17, N'gacnt_seq_no', N'Seq', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (357, 18, N'Extended Amount', N'Ext Amount', 25, N'Right', N'', N'', N'$####.00', 8, N'', N'', N'', 0, N'Grid', N'', N'ag', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (358, 17, N'gacnt_mkt_zone', N'Market Zone', 25, N'Left', N'', N'', N'', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (359, 18, N'WAP', N'WAP', 25, N'Right', N'', N'', N'', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (360, 17, N'gacnt_beg_ship_rev_dt', N'Beg Ship Date', 25, N'Right', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (361, 18, N'WAB', N'WAB', 25, N'Right', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (362, 17, N'gacnt_due_rev_dt', N'Due Date', 25, N'Right', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (363, 18, N'WAF', N'WAF', 25, N'Right', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (364, 17, N'gacnt_pbhcu_ind', N'PBHU', 25, N'Left', N'', N'', N'', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (365, 18, N'gacnt_due_rev_dt', N'Due Date', 25, N'Right', N'', N'', N'', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (366, 17, N'gacnt_un_bal', N'Unit Balance', 25, N'Right', N'', N'Sum', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 17)
INSERT INTO #TampCannedPanelColumn VALUES (367, 18, N'gacnt_cnt_no', N'Contract #', 25, N'Right', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 18)
INSERT INTO #TampCannedPanelColumn VALUES (368, 20, N'gacom_desc', N'Com', 25, N'Left', N'', N'', N'', 2, N'', N'', N'gacommst.gacom_desc', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 20)
INSERT INTO #TampCannedPanelColumn VALUES (369, 20, N'totals', N'Totals', 25, N'Right', N'', N'', N'####.00', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 20)
INSERT INTO #TampCannedPanelColumn VALUES (370, 22, N'gastr_pur_sls_ind', N'P or S', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 22)
INSERT INTO #TampCannedPanelColumn VALUES (371, 22, N'gastr_com_cd', N'Com', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 22)
INSERT INTO #TampCannedPanelColumn VALUES (372, 22, N'gastr_stor_type', N'Type', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 22)
INSERT INTO #TampCannedPanelColumn VALUES (373, 22, N'gastr_cus_no', N'Customer #', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 22)
INSERT INTO #TampCannedPanelColumn VALUES (374, 22, N'gastr_un_bal', N'Unit Balance', 25, N'Right', N'', N'Sum', N'####.00', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 22)
INSERT INTO #TampCannedPanelColumn VALUES (375, 21, N'gahdg_com_cd', N'Com', 25, N'Left', N'', N'', N'', 1, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (376, 21, N'gahdg_broker_no', N'Broker #', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (377, 21, N'gahdg_rev_dt', N'Date', 25, N'Right', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (378, 21, N'gahdg_ref', N'Ref#', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (379, 21, N'gahdg_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (380, 21, N'gahdg_bot_prc', N'BOT Price', 25, N'Right', N'', N'', N'$####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (381, 23, N'gaphs_pur_sls_ind', N'P / S', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (382, 21, N'gahdg_bot_basis', N'BOT Basis', 25, N'Right', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (383, 23, N'gaphs_cus_no', N'Customer Code', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (384, 21, N'gahdg_bot', N'BOT', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (385, 23, N'gaphs_com_cd', N'Com', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (386, 21, N'gahdg_bot_option', N'BOT Option', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (387, 23, N'gaphs_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (388, 21, N'gahdg_long_short_ind', N'L / S', 25, N'Left', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (389, 23, N'gaphs_tic_no', N'Ticket #', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (390, 21, N'gahdg_un_hdg_bal', N'Balance', 25, N'Right', N'', N'Sum', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (391, 23, N'gaphs_cus_ref_no', N'Customer Ref', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (392, 21, N'gahdg_offset_yn', N'Offset?', 25, N'Left', N'', N'', N'Yes/No', 14, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (393, 23, N'gaphs_gross_wgt', N'Gross Weight', 25, N'Right', N'', N'Sum', N'####.00', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (394, 21, N'gahdg_hedge_yyyymm', N'Hedge', 25, N'Right', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 21)
INSERT INTO #TampCannedPanelColumn VALUES (395, 23, N'gaphs_tare_wgt', N'Tare Weight', 25, N'Right', N'', N'Sum', N'####.00', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (396, 23, N'gaphs_gross_un', N'Gross Units', 25, N'Right', N'', N'Sum', N'####.00', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (397, 23, N'gaphs_wet_un', N'Wet Units', 25, N'Right', N'', N'Sum', N'####.00', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (398, 23, N'gaphs_net_un', N'Net Units', 25, N'Right', N'', N'Sum', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (399, 23, N'gaphs_fees', N'Fees', 25, N'Right', N'', N'Sum', N'$####.00', 14, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (400, 23, N'gaphs_dlvry_rev_dt', N'Delivery Date', 25, N'Right', N'', N'', N'', 15, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 23)
INSERT INTO #TampCannedPanelColumn VALUES (401, 16, N'Month', N'Month', 0, N'Series1AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series1AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 16)
INSERT INTO #TampCannedPanelColumn VALUES (402, 16, N'Month', N'Month', 0, N'Series2AxisX', N'', N'', N'Month', 1, N'', N'', N'', 1, N'Chart', N'Series2AxisX', N'master', 0, 0, 0, 0, 0, N'', 0, 16)
INSERT INTO #TampCannedPanelColumn VALUES (403, 16, N'units', N'Purchased Units', 0, N'Series1AxisY', N'', N'', N'Number', 2, N'', N'', N'', 1, N'Chart', N'Series1AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 16)
INSERT INTO #TampCannedPanelColumn VALUES (404, 16, N'units', N'Sales Units', 0, N'Series2AxisY', N'', N'', N'Number', 2, N'', N'', N'', 1, N'Chart', N'Series2AxisY', N'master', 0, 0, 0, 0, 0, N'', 0, 16)
INSERT INTO #TampCannedPanelColumn VALUES (405, 25, N'pxrpt_trans_type', N'Trans Type', 25, N'Left', N'', N'', N'', 1, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (406, 24, N'pxrpt_trans_type', N'Trans Type', 25, N'Left', N'', N'', N'', 1, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (407, 25, N'pxrpt_trans_rev_dt', N'Trans Date', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (408, 24, N'pxrpt_trans_rev_dt', N'Trans Date', 25, N'Left', N'', N'', N'', 2, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (409, 25, N'pxrpt_src_sys', N'Source System', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (410, 24, N'pxrpt_ord_no', N'Order #', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (411, 24, N'pxrpt_car_name', N'Carrier', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (412, 25, N'pxrpt_ord_no', N'Order #', 25, N'Left', N'', N'', N'', 4, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (413, 24, N'pxrpt_cus_name', N'Customer', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (414, 25, N'pxrpt_car_name', N'Carrier', 25, N'Left', N'', N'', N'', 5, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (415, 24, N'pxrpt_cus_state', N'Customer State', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (416, 25, N'pxrpt_cus_name', N'Customer', 25, N'Left', N'', N'', N'', 6, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (417, 24, N'pxrpt_itm_desc', N'Item/Product', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (418, 25, N'pxrpt_cus_state', N'Customer State', 25, N'Left', N'', N'', N'', 7, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (419, 24, N'pxrpt_itm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (420, 25, N'pxrpt_itm_desc', N'Item/Product', 25, N'Left', N'', N'', N'', 8, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (421, 24, N'pxrpt_vnd_name', N'Vendor', 25, N'Left', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (422, 25, N'pxrpt_itm_loc_no', N'Loc', 25, N'Left', N'', N'', N'', 9, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (423, 24, N'pxrpt_vnd_state', N'Vendor State', 25, N'Left', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (424, 25, N'pxrpt_vnd_name', N'Vendor ', 25, N'Left', N'', N'', N'', 10, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (425, 24, N'pxrpt_pur_gross_un', N'Gross Units Purchased', 25, N'Left', N'', N'Sum', N'####.00', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (426, 24, N'pxrpt_pur_net_un', N'Net Units Purchased', 25, N'Left', N'', N'Sum', N'####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (427, 25, N'pxrpt_vnd_state', N'Vendor State', 25, N'Left', N'', N'', N'', 11, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (428, 24, N'pxrpt_pur_fet_amt', N'FET', 25, N'Left', N'', N'Sum', N'$####.00', 14, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (429, 25, N'pxrpt_sls_trans_gals', N'Sales Units', 25, N'Left', N'', N'Sum', N'####.00', 12, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (430, 24, N'pxrpt_pur_set_amt', N'SET', 25, N'Left', N'', N'Sum', N'$####.00', 15, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (431, 25, N'pxrpt_sls_fet_amt', N'FET', 25, N'Left', N'', N'Sum', N'$####.00', 13, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (432, 24, N'pxrpt_pur_sst_amt', N'SST', 25, N'Left', N'', N'Sum', N'$####.00', 16, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (433, 25, N'pxrpt_sls_set_amt', N'SET', 25, N'Left', N'', N'Sum', N'$####.00', 14, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (434, 24, N'pxrpt_pur_lc1_amt', N'LC1', 25, N'Left', N'', N'Sum', N'$####.00', 17, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (435, 25, N'pxrpt_sls_lc1_amt', N'LC1', 25, N'Left', N'', N'Sum', N'$####.00', 15, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (436, 24, N'pxrpt_pur_lc2_amt', N'LC2', 25, N'Left', N'', N'Sum', N'$####.00', 18, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (437, 25, N'pxrpt_sls_lc2_amt', N'LC2', 25, N'Left', N'', N'Sum', N'$####.00', 16, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (438, 24, N'pxrpt_pur_lc3_amt', N'LC3', 25, N'Left', N'', N'Sum', N'$####.00', 19, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (439, 25, N'pxrpt_sls_lc3_amt', N'LC3', 25, N'Left', N'', N'Sum', N'$####.00', 17, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (440, 24, N'pxrpt_pur_lc4_amt', N'LC4', 25, N'Left', N'', N'Sum', N'$####.00', 20, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (441, 25, N'pxrpt_sls_lc4_amt', N'LC4', 25, N'Left', N'', N'Sum', N'$####.00', 18, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (442, 24, N'pxrpt_pur_un_received', N'Units Received', 25, N'Left', N'', N'Sum', N'####.00', 21, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (443, 25, N'pxrpt_itm_dyed_yn', N'Dyed?', 25, N'Left', N'', N'', N'', 19, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (444, 24, N'pxrpt_src_sys', N'Source System', 25, N'Left', N'', N'', N'', 3, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
INSERT INTO #TampCannedPanelColumn VALUES (445, 25, N'pxrpt_cus_acct_stat', N'Cus  Acct Status ', 25, N'Left', N'', N'', N'', 20, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 25)
INSERT INTO #TampCannedPanelColumn VALUES (446, 24, N'pxrpt_itm_dyed_yn', N'Dyed?', 25, N'Left', N'', N'', N'', 22, N'', N'', N'', 0, N'Grid', N'', N'design', 0, 0, 0, 0, 0, N'', 0, 24)
print('/*******************  END INSERTING canned panels on temporary panel column table  *******************/')

print('/*******************  BEGIN DELETE old panel column records  *******************/')

DELETE tblDBPanelColumn WHERE intCannedPanelId != 0

print('/*******************  END DELETE old panel column records  *******************/')


print('/*******************  BEGIN UPDATING canned panels on table Panel Column  *******************/')

DECLARE @intPanelColumnId int
DECLARE @intCannedPanelId int
DECLARE @intCurrentPanelId int

DECLARE db_cursor CURSOR FOR  
SELECT intPanelColumnId, intCannedPanelId FROM #TampCannedPanelColumn
 

OPEN db_cursor   
FETCH NEXT FROM db_cursor INTO @intPanelColumnId, @intCannedPanelId

WHILE @@FETCH_STATUS = 0   
BEGIN
	SET @intCurrentPanelId = (SELECT TOP 1 intPanelId FROM tblDBPanel WHERE intCannedPanelId = @intCannedPanelId)
		
	INSERT INTO [dbo].[tblDBPanelColumn] 
	([intPanelId], [strColumn], [strCaption], [intWidth], [strAlignment], [strArea], [strFooter], [strFormat], [intSort], [strFormatTrue], [strFormatFalse], [strDrillDownColumn], [ysnVisible], [strType], [strAxis], [strUserName], [intUserId], [intDonut], [intMinInterval], [intMaxInterval], [intStepInterval], [strIntervalFormat], [ysnHiddenColumn], [intCannedPanelId])
	SELECT @intCurrentPanelId, [strColumn], [strCaption], [intWidth], [strAlignment], [strArea], [strFooter], [strFormat], [intSort], [strFormatTrue], [strFormatFalse], [strDrillDownColumn], [ysnVisible], [strType], [strAxis], [strUserName], [intUserId], [intDonut], [intMinInterval], [intMaxInterval], [intStepInterval], [strIntervalFormat], [ysnHiddenColumn], [intCannedPanelId]
	FROM #TampCannedPanelColumn 
	WHERE intPanelColumnId = @intPanelColumnId

	
FETCH NEXT FROM db_cursor INTO @intPanelColumnId, @intCannedPanelId
END   

CLOSE db_cursor   
DEALLOCATE db_cursor

DROP TABLE #TampCannedPanelColumn
print('/*******************  END UPDATING canned panels on table Panel Column  *******************/')
/*******************  END UPDATING canned panels on table Panel Column*******************/
GO