CREATE TYPE [dbo].[StagingRadiantISM] AS TABLE(
	[intRowCount] [int] NULL,
	[intStoreLocationId] [int] NULL,
	[strVendorName] [nvarchar](max) NULL,
	[strVendorModelVersion] [nvarchar](max) NULL,
	[intReportSequenceNumber] [int] NULL,
	[intPrimaryReportPeriod] [int] NULL,
	[intSecondaryReportPeriod] [int] NULL,
	[dtmBusinessDate] [datetime] NULL,
	[dtmBeginDate] [datetime] NULL,
	[dtmBeginTime] [datetime] NULL,
	[dtmEndDate] [datetime] NULL,
	[dtmEndTime] [datetime] NULL,
	[strPOSCodeFormat] [nvarchar](max) NULL,
	[strPOSCode] [nvarchar](max) NULL,
	[intPOSCodeModifier] [int] NULL,
	[strItemID] [nvarchar](max) NULL,
	[strDescription] [nvarchar](max) NULL,
	[intMerchandiseCode] [int] NULL,
	[intSellingUnits] [int] NULL,
	[dblActualSalesPrice] [numeric](18, 6) NULL,
	[dblSalesQuantity] [numeric](18, 6) NULL,
	[dblSalesAmount] [numeric](18, 6) NULL,
	[dblDiscountAmount] [numeric](18, 6) NULL,
	[dblDiscountCount] [numeric](18, 6) NULL,
	[dblPromotionAmount] [numeric](18, 6) NULL,
	[dblPromotionCount] [numeric](18, 6) NULL,
	[dblRefundAmount] [numeric](18, 6) NULL,
	[dblRefundCount] [numeric](18, 6) NULL,
	[dblTransactionCount] [numeric](18, 6) NULL
)