CREATE TYPE [dbo].[TFInvoiceTransaction] AS TABLE(
	[intId] [int] NOT NULL,
	[intInvoiceDetailId] [int] NULL,
	[intTaxAuthorityId] [int] NULL,
	[strFormCode] [nvarchar](50) NULL,
	[intReportingComponentId] [int] NULL,
	[strScheduleCode] [nvarchar](50) NULL,
	[strType] [nvarchar](150) NULL,
	[intProductCode] [int] NULL,
	[strProductCode] [nvarchar](20) NULL,
	[intItemId] [int] NULL,
	[dblQtyShipped] [numeric](18, 6) NULL,
	[dblGross] [numeric](18, 6) NULL,
	[dblNet] [numeric](18, 6) NULL,
	[dblBillQty] [numeric](18, 6) NULL,
	[dblTax] [numeric](18, 2) NULL,
	[dblTaxExempt] [numeric](18, 2) NULL,
	[strInvoiceNumber] [nvarchar](50) NULL,
	[strPONumber] [nvarchar](50) NULL,
	[strBillOfLading] [nvarchar](50) NULL,
	[dtmDate] [datetime] NULL,
	[strDestinationCity] [nvarchar](50) NULL,
	[strDestinationState] [nvarchar](50) NULL,
	[strOriginCity] [nvarchar](50) NULL,
	[strOriginState] [nvarchar](50) NULL,
	[strCustomerName] [nvarchar](250) NULL,
	[strCustomerFEIN] [nvarchar](50) NULL,
	[strAccountStatusCode] [nvarchar](50) NULL,
	[strShipVia] [nvarchar](50) NULL,
	[strTransporterLicense] [nvarchar](50) NULL,
	[strTransportationMode] [nvarchar](50) NULL,
	[strTransporterName] [nvarchar](250) NULL,
	[strTransporterFEIN] [nvarchar](50) NULL,
	[strConsignorName] [nvarchar](250) NULL,
	[strConsignorFEIN] [nvarchar](50) NULL,
	[strTaxCode] [nvarchar](200) NULL,
	[strTerminalControlNumber] [nvarchar](50) NULL,
	[strVendorName] [nvarchar](50) NULL,
	[strVendorFederalTaxId] [nvarchar](50) NULL,
	[strHeaderCompanyName] [nvarchar](250) NULL,
	[strHeaderAddress] [nvarchar](max) NULL,
	[strHeaderCity] [nvarchar](50) NULL,
	[strHeaderState] [nvarchar](50) NULL,
	[strHeaderZip] [nvarchar](50) NULL,
	[strHeaderPhone] [nvarchar](50) NULL,
	[strHeaderStateTaxID] [nvarchar](50) NULL,
	[strHeaderFederalTaxID] [nvarchar](50) NULL
)
GO