IF NOT EXISTS(SELECT top 1 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_tblSMEmailRecipient_tblSMActivity')
BEGIN
	ALTER TABLE [tblSMEmailRecipient] WITH NOCHECK ADD CONSTRAINT [FK_tblSMEmailRecipient_tblSMActivity] FOREIGN KEY ([intEmailId]) REFERENCES [tblSMActivity]([intActivityId]) ON DELETE CASCADE
END