
IF(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblICItemOwner'))
BEGIN	
EXEC ('
	WITH CTE 
	AS (
		SELECT	RN = ROW_NUMBER() OVER (PARTITION BY intItemId, intOwnerId ORDER BY intItemOwnerId)
		FROM	tblICItemOwner 
	)
	DELETE FROM CTE WHERE RN > 1
')

END 