PRINT N'BEGIN COMPANY SETUP '
GO
	IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[coctlmst]') AND type IN (N'U')) GOTO Check_Exit;

	IF EXISTS (SELECT TOP 1 1 FROM tblSMCompanySetup)
	BEGIN
		PRINT N'BEGIN UPDATING EXISTING COMPANY SETUP'
			UPDATE tblSMCompanySetup 
			SET strCompanyName = (SELECT TOP 1 coctl_co_name FROM [coctlmst])
		PRINT N'END UPDATING EXISTING COMPANY SETUP'
	END
	ELSE
	BEGIN
		PRINT N'BEGIN INSERTING COMPANY SETUP FROM ORIGIN'
			INSERT INTO tblSMCompanySetup (strCompanyName)
				SELECT TOP 1 coctl_co_name FROM [coctlmst]	
		PRINT N'END INSERTING COMPANY SETUP FROM ORIGIN'
	END
	
	Check_Exit:
GO
PRINT N'END COMPANY SETUP '

GO