GO
-- RUN ONLY FOR SQL SERVER 2019 OR LATER ref: https://stackoverflow.com/a/52940648/13726696
IF ( ISNULL(CAST(SERVERPROPERTY('ProductMajorVersion') AS INT), 0) >= 15 )
    BEGIN
        PRINT 'START: SET SCALAR UDF INLINING TO OFF'
        EXEC ( 'ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = OFF' )
        PRINT 'END: SET SCALAR UDF INLINING TO OFF'
    END
GO