GO
-- RUN ONLY FOR SQL SERVER 2019 OR LATER ref: https://stackoverflow.com/a/52940648/13726696
EXEC ('
IF ( ISNULL(CAST(SERVERPROPERTY(''ProductMajorVersion'') AS INT), 0) >= 15 )
    BEGIN
		PRINT ''START: SET SCALAR UDF INLING TO OFF''
        ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = OFF
		PRINT ''END: SET SCALAR UDF INLING TO OFF''
    END
')
GO