IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE UPPER(TABLE_NAME) = 'TBLSMTRANSACTION')
BEGIN
	IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE UPPER(TABLE_NAME) = 'TBLSMTRANSACTION' AND UPPER(COLUMN_NAME) = 'INTRECORDID')
	BEGIN
		ALTER TABLE tblSMTransaction ADD intRecordId int NULL
		EXEC
		('UPDATE tblSMTransaction SET intRecordId = CONVERT(int, strRecordNo)')
	END
END