CREATE VIEW [dbo].[vyuARCustomerInquiry]
AS 
SELECT intEntityCustomerId          = C.intEntityId
     , intEntityId					= C.intEntityId
	 , intTermsId					= C.intTermsId
	 , strCustomerName				= C.strName
	 , strTerm						= C.strCustomerTerm
	 , strCustomerNumber			= C.strCustomerNumber
	 , strAddress					= C.strAddress
	 , strZipCode					= C.strZipCode
	 , strCity						= C.strCity
	 , strState						= C.strState
	 , strCountry					= C.strCountry
	 , strEmail						= C.strEmail
	 , strPhone1					= C.strPhone1
	 , strPhone2					= C.strPhone2
	 , strBusinessLocation			= C.strLocationName
	 , strInternalNotes				= C.strInternalNotes
	 , strBudgetStatus				= CI.strBudgetStatus
	 , strBillToAddress				= C.strBillToAddress
	 , strBillToCity				= C.strBillToCity
	 , strBillToState				= C.strBillToState
	 , strBillToZipCode				= C.strBillToZipCode
	 , dblYTDSales					= ISNULL(CI.dblYTDSales, CONVERT(NUMERIC(18,6), 0))
	 , dblYDTServiceCharge			= ISNULL(CI.dblYDTServiceCharge, CONVERT(NUMERIC(18,6), 0))
	 , dblHighestAR					= ISNULL(CI.dblHighestAR, CONVERT(NUMERIC(18,6), 0))
	 , dblHighestDueAR				= ISNULL(CI.dblHighestDueAR, CONVERT(NUMERIC(18,6), 0))
	 , dblLastPayment				= ISNULL(CI.dblLastPayment, CONVERT(NUMERIC(18,6), 0))
	 , dblLastYearSales				= ISNULL(CI.dblLastYearSales, CONVERT(NUMERIC(18,6), 0))
	 , dblLastStatement				= ISNULL(CI.dblLastStatement, CONVERT(NUMERIC(18,6), 0))
	 , dblPendingInvoice			= ISNULL(CI.dblPendingInvoice, CONVERT(NUMERIC(18,6), 0))
	 , dblPendingPayment			= ISNULL(CI.dblPendingPayment, CONVERT(NUMERIC(18,6), 0))
	 , dblCreditLimit				= ISNULL(CI.dblCreditLimit, CONVERT(NUMERIC(18,6), 0))
	 , dblFuture					= ISNULL(CI.dblFuture, CONVERT(NUMERIC(18,6), 0))
	 , dbl0Days						= ISNULL(CI.dbl0Days, CONVERT(NUMERIC(18,6), 0))
	 , dbl10Days					= ISNULL(CI.dbl10Days, CONVERT(NUMERIC(18,6), 0))
	 , dbl30Days					= ISNULL(CI.dbl30Days, CONVERT(NUMERIC(18,6), 0))
	 , dbl60Days					= ISNULL(CI.dbl60Days, CONVERT(NUMERIC(18,6), 0))
	 , dbl90Days					= ISNULL(CI.dbl90Days, CONVERT(NUMERIC(18,6), 0))
	 , dbl91Days					= ISNULL(CI.dbl91Days, CONVERT(NUMERIC(18,6), 0))
	 , dblUnappliedCredits			= ISNULL(CI.dblUnappliedCredits, CONVERT(NUMERIC(18,6), 0))
	 , dblPrepaids					= ISNULL(CI.dblPrepaids, CONVERT(NUMERIC(18,6), 0))
	 , dblTotalDue					= ISNULL(CI.dblTotalDue, CONVERT(NUMERIC(18,6), 0))
	 , dblBudgetAmount				= ISNULL(CI.dblBudgetAmount, CONVERT(NUMERIC(18,6), 0))	 
	 , dblThru						= ISNULL(CI.dblThru, CONVERT(NUMERIC(18,6), 0))
	 , dblNextPaymentAmount			= ISNULL(CI.dblNextPaymentAmount, CONVERT(NUMERIC(18,6), 0))
	 , dblAmountPastDue				= ISNULL(CI.dblAmountPastDue, CONVERT(NUMERIC(18,6), 0))
	 , dbl31DaysAmountDue			= ISNULL(CI.dbl60Days, CONVERT(NUMERIC(18,6), 0)) + ISNULL(CI.dbl90Days, CONVERT(NUMERIC(18,6), 0)) + ISNULL(CI.dbl91Days, CONVERT(NUMERIC(18,6), 0))
	 , intRemainingBudgetPeriods	= ISNULL(CI.intRemainingBudgetPeriods, CONVERT(NUMERIC(18,6), 0))
	 , intAveragePaymentDays		= ISNULL(CI.intAveragePaymentDays, CONVERT(NUMERIC(18,6), 0))	 
	 , dtmNextPaymentDate			= CI.dtmNextPaymentDate
	 , dtmLastPaymentDate			= CI.dtmLastPaymentDate
	 , dtmLastStatementDate			= CI.dtmLastStatementDate
	 , dtmBudgetMonth				= CI.dtmBudgetMonth
	 , dtmHighestARDate				= CI.dtmHighestARDate
	 , dtmHighestDueARDate			= CI.dtmHighestDueARDate
FROM vyuARCustomer C
LEFT JOIN vyuARCustomerInquiryReport CI
	ON C.intEntityId = CI.intEntityCustomerId