CREATE VIEW [dbo].[vyuRKCustomDerivativeEntry]
AS
SELECT [Transaction Header] = t.intFutOptTransactionHeaderId
	, [intRowNum] = t.intRowNum
	, [Entry Date] = t.dtmTransactionDate
	, [Internal Trade No.] = t.strInternalTradeNo
	, [Broker Trade No.] = t.strBrokerTradeNo
	, [Filled Date] = t.dtmFilledDate
	, [Instrument] = t.strSelectedInstrumentType
	, [Commodity] = t.strCommodityCode
	, [Future Market Name] = t.strFutMarketName
	, [Broker Name] = t.strName
	, [Brokerage Account] = t.strBrokerageAccount
	, [Buy/Sell] = t.strBuySell
	, [Future Month] = t.strFutureMonth
	, [Rolling Month] = t.strRollingMonth
	, [Option Month] = t.strOptionMonthYear
	, [Option Type] = t.strOptionType
	, [Instrument Type] = t.strInstrumentType
	, [Strike] = t.dblStrike
	, [Contracts] = t.dblGetNoOfContract
	, [Hedge Qty] = t.dblHedgeQty
	, [Open Contract] = t.dblOpenContract
	, [Hedge UOM] = t.strUnitMeasure
	, [Price] = t.dblPrice
	, [Contract Price] = t.dblContractPrice
	, [Location] = t.strLocationName
	, [Status] = t.strStatus
	, [Book] = t.strBook
	, [Sub-Book] = t.strSubBook
	, [Bank] = t.strBankName
	, [Bank Account] = t.strBankAccountNo
	, [Exchange Rate Type] = t.strCurrencyExchangeRateType
	, [Maturity Date] = t.dtmMaturityDate
	, [From Currency] = t.strFromCurrency
	, [To Currency] = t.strToCurrency
	, [Contract Amount] = t.dblContractAmount
	, [Exchange Rate] = t.dblExchangeRate
	, [Match Amount] = t.dblMatchAmount
	, [Spot Rate] = t.dblSpotRate
	, [Liquidation] = t.ysnLiquidation
	, [Swap] = t.ysnSwap
	, [Crush] = t.ysnPreCrush
	, [Notes] = t.strReference
FROM vyuRKFutOptTransaction t