CREATE VIEW dbo.vyuSOSalesOrderDetail
AS
SELECT intSalesOrderDetailId	= D.intSalesOrderDetailId
     , intSalesOrderId			= D.intSalesOrderId
     , strSalesOrderNumber		= H.strSalesOrderNumber
     , intCompanyLocationId		= H.intCompanyLocationId
     , intEntityCustomerId		= H.intEntityCustomerId
     , strCustomerNumber		= H.strCustomerNumber
     , strCustomerName			= H.strCustomerName
     , strLocationName			= L.strLocationName
     , intItemId				= D.intItemId
     , strItemNo				= IC.strItemNo
     , strItemDescription		= D.strItemDescription
     , strLotTracking			= IC.strLotTracking
     , intItemUOMId				= D.intItemUOMId
     , dblUOMConversion			= ISNULL(IU.[dblUnitQty], 0)
     , strUnitMeasure			= U.strUnitMeasure
     , dblQtyOrdered			= D.dblQtyOrdered
     , dblQtyAllocated			= D.dblQtyAllocated
     , dblQtyShipped			= D.dblQtyShipped
     , dblDiscount				= D.dblDiscount
     , intTaxId					= D.intTaxId
     , dblPrice					= D.dblPrice
     , dblTotal					= D.dblTotal
     , strComments				= D.strComments
     , intAccountId				= D.intAccountId
     , intCOGSAccountId			= D.intCOGSAccountId
     , intSalesAccountId		= D.intSalesAccountId
     , intInventoryAccountId	= D.intInventoryAccountId
     , intSubLocationId			= ST.intSubLocationId
     , strSubLocationName		= ST.strSubLocationName
     , intStorageLocationId		= D.intStorageLocationId
     , strStorageLocation		= ST.strName
     , strMaintenanceType		= D.strMaintenanceType
     , strFrequency				= D.strFrequency
     , dtmMaintenanceDate		= D.dtmMaintenanceDate
     , dblMaintenanceAmount		= D.dblMaintenanceAmount
     , dblLicenseAmount			= D.dblLicenseAmount
     , intContractHeaderId		= D.intContractHeaderId
     , intContractDetailId		= D.intContractDetailId
     , strContractNumber		= CH.strContractNumber
     , intContractSeq			= CD.intContractSeq
     , intCommodityId			= IC.intCommodityId
     , ysnProcessed				= H.ysnProcessed
	 , intCurrencyExchangeRateTypeId	= D.intCurrencyExchangeRateTypeId
	 , dblCurrencyExchangeRate	= D.dblCurrencyExchangeRate 
	 , intPriceUOMId			= D.intPriceUOMId 
	 , strPriceUOM				= PriceUOM.strUnitMeasure
	 , strTransactionType		= H.strTransactionType
FROM dbo.tblSOSalesOrderDetail D WITH (NOLOCK)
INNER JOIN vyuSOSalesOrderSearch H WITH (NOLOCK) ON H.intSalesOrderId = D.intSalesOrderId
LEFT JOIN tblSMCompanyLocation L WITH (NOLOCK) ON H.intCompanyLocationId = L.intCompanyLocationId
LEFT JOIN tblICItemUOM IU WITH (NOLOCK) ON D.intItemUOMId = IU.intItemUOMId
LEFT JOIN tblICUnitMeasure U WITH (NOLOCK) ON IU.intUnitMeasureId = U.intUnitMeasureId
LEFT JOIN tblICItem IC WITH (NOLOCK) ON D.intItemId = IC.intItemId
LEFT JOIN vyuICGetStorageLocation ST WITH (NOLOCK) ON D.intStorageLocationId = ST.intStorageLocationId
LEFT JOIN tblCTContractHeader CH WITH (NOLOCK) ON D.intContractHeaderId = CH.intContractHeaderId
LEFT JOIN tblCTContractDetail CD WITH (NOLOCK) ON D.intContractDetailId = CD.intContractDetailId AND CH.intContractHeaderId = CD.intContractHeaderId
LEFT JOIN tblICItemUOM ItemPriceUOM WITH (NOLOCK) ON D.intPriceUOMId = ItemPriceUOM.intItemUOMId
LEFT JOIN tblICUnitMeasure PriceUOM WITH (NOLOCK) ON ItemPriceUOM.intUnitMeasureId = PriceUOM.intUnitMeasureId