--UPDATES THE STATUS OF AR/AP/INVENTORY MODULE IF IT WILL BE OPEN FOR POSTING IN THE FISCAL YEAR SCREEN
GO
	 UPDATE tblGLFiscalYearPeriod SET  ysnAPOpen = 0,	ysnAROpen = 0 ,ysnINVOpen = 0, ysnPROpen = 0 WHERE ysnOpen = 0
GO
