GO
	PRINT N'BEGIN INSERT ACCOUNT TEMPLATE: Accounts Payable'
GO

	DECLARE @GL_intAccountStructureId_Primary AS INT
	SET @GL_intAccountStructureId_Primary = (SELECT TOP 1 intAccountStructureId FROM tblGLAccountStructure WHERE strType = N'Primary')

	IF NOT EXISTS(SELECT TOP 1 1 FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Accounts Payable' AND strType = N'Primary') AND NOT EXISTS(SELECT TOP 1 1 FROM tblGLAccount)
	BEGIN
		INSERT [dbo].[tblGLCOATemplate] ([strAccountTemplateName], [strType], [intConcurrencyId]) VALUES (N'Accounts Payable', N'Primary', 1)
		
		DECLARE @GL_intAccountTemplateId_AccountsPayable AS INT		
		SET @GL_intAccountTemplateId_AccountsPayable = (SELECT TOP 1 intAccountTemplateId FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Accounts Payable' AND strType = N'Primary')			
		
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'10000', N'Check book in Bank', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Cash Accounts' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'18000', N'Supplies', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'20000', N'Accounts Payable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'44000', N'Credit Card Fee', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'55000', N'Purchases Discounts', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Purchases Discounts' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'60000', N'Miscellaneous Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'61500', N'Fee Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'35000', N'Owner''s Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Owners Equities' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'39000', N'Retained Earnings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Retained Earnings' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'72500', N'Tax Expense ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AccountsPayable , N'99000', N'Wash Account', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
	END

GO	
	PRINT N'END INSERT ACCOUNT TEMPLATE: Accounts Payable'
	PRINT N'BEGIN INSERT ACCOUNT TEMPLATE: AG Accounting'
GO
	
	DECLARE @GL_intAccountStructureId_Primary AS INT
	SET @GL_intAccountStructureId_Primary = (SELECT TOP 1 intAccountStructureId FROM tblGLAccountStructure WHERE strType = N'Primary')
	
	IF NOT EXISTS(SELECT TOP 1 1 FROM tblGLCOATemplate WHERE strAccountTemplateName = N'AG Accounting' AND strType = N'Primary') AND NOT EXISTS(SELECT TOP 1 1 FROM tblGLAccount)
	BEGIN
		INSERT [dbo].[tblGLCOATemplate] ([strAccountTemplateName], [strType], [intConcurrencyId]) VALUES (N'AG Accounting', N'Primary', 1)
		
		DECLARE @GL_intAccountTemplateId_AGAccounting AS INT		
		SET @GL_intAccountTemplateId_AGAccounting = (SELECT TOP 1 intAccountTemplateId FROM tblGLCOATemplate WHERE strAccountTemplateName = N'AG Accounting' AND strType = N'Primary')			
		
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'11000', N'Cash Clearing', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Undeposited Funds' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'12000', N'Accounts Receivable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Receivables' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'13000', N'Prepaid Credits', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Prepaids' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'14000', N'Prepaid Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Prepaids' AND strAccountType = N'Asset'), @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'15000', N'Beginning Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'16000', N'Inventories', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'17000', N'Ending Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'18000', N'Supplies', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'21000', N'Pending Accounts Payable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'22000', N'Inspection Fee', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'23000', N'Federal Excise Tax ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'24000', N'State Excise Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'25000', N'State Sales Tax ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'26000', N'Prepaid Sales Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'27000', N'Locale Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'40000', N'Sales Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'45000', N'Discount Take', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Discounts' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'46000', N'Sales Ticket Variance', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'48000', N'Finance Charge', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'49000', N'Other Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'50000', N'Purchases Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Purchases' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'51000', N'Purchases Variance', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Purchases' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'55000', N'Purchases Discounts', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Purchases Discounts' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'61000', N'Write Off', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'63000', N'Cash Over/Short', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'64000', N'Freight Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'35000', N'Owner''s Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Owners Equities' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'39000', N'Retained Earnings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Retained Earnings' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'72500', N'Tax Expense ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_AGAccounting , N'99000', N'Wash Account', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
	END

GO	
	PRINT N'END INSERT ACCOUNT TEMPLATE: AG Accounting'
	PRINT N'BEGIN INSERT ACCOUNT TEMPLATE: C-Store'
GO
	
	DECLARE @GL_intAccountStructureId_Primary AS INT
	SET @GL_intAccountStructureId_Primary = (SELECT TOP 1 intAccountStructureId FROM tblGLAccountStructure WHERE strType = N'Primary')
	
	IF NOT EXISTS(SELECT TOP 1 1 FROM tblGLCOATemplate WHERE strAccountTemplateName = N'C-Store' AND strType = N'Primary') AND NOT EXISTS(SELECT TOP 1 1 FROM tblGLAccount)
	BEGIN
		INSERT [dbo].[tblGLCOATemplate] ([strAccountTemplateName], [strType], [intConcurrencyId]) VALUES (N'C-Store', N'Primary', 1)
		
		DECLARE @GL_intAccountTemplateId_CStore AS INT		
		SET @GL_intAccountTemplateId_CStore = (SELECT TOP 1 intAccountTemplateId FROM tblGLCOATemplate WHERE strAccountTemplateName = N'C-Store' AND strType = N'Primary')			
		
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'10000', N'Check book in Bank', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Cash Accounts' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'11000', N'Cash Clearing', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Undeposited Funds' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'12000', N'Accounts Receivable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Receivables' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'12500', N'Credit Card Receivable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Receivables' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'16000', N'Inventories', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'40000', N'Sales Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'46000', N'Sales Ticket Variance', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'50000', N'Purchases Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Purchases' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'60000', N'Miscellaneous Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'61500', N'Fee Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'35000', N'Owner''s Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Owners Equities' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'39000', N'Retained Earnings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Retained Earnings' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'72500', N'Tax Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_CStore , N'99000', N'Wash Account', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
	END

GO	
	PRINT N'END INSERT ACCOUNT TEMPLATE: C-Store'
	PRINT N'BEGIN INSERT ACCOUNT TEMPLATE: Fixed Asset'
GO
	
	DECLARE @GL_intAccountStructureId_Primary AS INT
	SET @GL_intAccountStructureId_Primary = (SELECT TOP 1 intAccountStructureId FROM tblGLAccountStructure WHERE strType = N'Primary')
	
	IF NOT EXISTS(SELECT TOP 1 1 FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Fixed Asset' AND strType = N'Primary') AND NOT EXISTS(SELECT TOP 1 1 FROM tblGLAccount)
	BEGIN
		INSERT [dbo].[tblGLCOATemplate] ([strAccountTemplateName], [strType], [intConcurrencyId]) VALUES (N'Fixed Asset', N'Primary', 1)
		
		DECLARE @GL_intAccountTemplateId_FixedAsset AS INT		
		SET @GL_intAccountTemplateId_FixedAsset = (SELECT TOP 1 intAccountTemplateId FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Fixed Asset' AND strType = N'Primary')
				
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'19000', N'Land', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Fixed Assets' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'19300', N'Land Improvements', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Fixed Assets' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'19500', N'Buildings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Fixed Assets' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'19700', N'Equipment', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Fixed Assets' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'19900', N'Accumulated Depreciation', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Fixed Assets' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'19950', N'Goodwill', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Assets' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'35000', N'Owner''s Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Owners Equities' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'39000', N'Retained Earnings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Retained Earnings' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'62000', N'Depreciation Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'72500', N'Tax Expense ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ([intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_FixedAsset , N'99000', N'Wash Account', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
	END

GO	
	PRINT N'END INSERT ACCOUNT TEMPLATE: Fixed Asset'
	PRINT N'BEGIN INSERT ACCOUNT TEMPLATE: Grain'
GO

	DECLARE @GL_intAccountStructureId_Primary AS INT
	SET @GL_intAccountStructureId_Primary = (SELECT TOP 1 intAccountStructureId FROM tblGLAccountStructure WHERE strType = N'Primary')
	
	IF NOT EXISTS(SELECT TOP 1 1 FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Grain' AND strType = N'Primary') AND NOT EXISTS(SELECT TOP 1 1 FROM tblGLAccount)
	BEGIN
		INSERT [dbo].[tblGLCOATemplate] ([strAccountTemplateName], [strType], [intConcurrencyId]) VALUES (N'Grain', N'Primary', 1)
		
		DECLARE @GL_intAccountTemplateId_Grain AS INT		
		SET @GL_intAccountTemplateId_Grain = (SELECT TOP 1 intAccountTemplateId FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Grain' AND strType = N'Primary')
				
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'10000', N'Check book in Bank', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Cash Accounts' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'11000', N'Cash Clearing', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Undeposited Funds' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'12000', N'Accounts Receivable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Receivables' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'12300', N'Discount Receivable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Receivables' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'12700', N'Storage Receivable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Receivables' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'15000', N'Beginning Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'16000', N'Inventories', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'17000', N'Ending Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)		
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'20000', N'Accounts Payable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'23000', N'Federal Excise Tax ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'24000', N'State Excise Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'25000', N'State Sales Tax ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'26000', N'Prepaid Sales Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'27000', N'Locale Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'29000', N'Freight Payable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'29100', N'DP Liability', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'35000', N'Owner''s Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Owners Equities' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'39000', N'Retained Earnings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Retained Earnings' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)		
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'40000', N'Sales Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'40300', N'DP Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'40500', N'Storage Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'41000', N'Freight Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'41500', N'Fee Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'42000', N'Interest Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'43000', N'Options Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'47000', N'Sales Advance ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'49000', N'Other Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)		
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'50000', N'Purchases Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Purchases' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'57000', N'Purchase Advance', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Purchases' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'60000', N'Miscellaneous Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'61500', N'Fee Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'64000', N'Freight Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'70000', N'Storage Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'71000', N'Broker Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'71500', N'Rail Freight', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'72000', N'Interest Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'73000', N'Options Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'74000', N'Contract Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'75000', N'Contract Pur Gain/Loss', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'76000', N'Contract Sales Gain/Loss', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'77000', N'Currency Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'78000', N'Currency Pur Gain/Loss', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'79000', N'Currency Sales Gain/Loss', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'72500', N'Tax Expense ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Grain , N'99000', N'Wash Account', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
	END	

GO	
	PRINT N'END INSERT ACCOUNT TEMPLATE: Grain'
	PRINT N'BEGIN INSERT ACCOUNT TEMPLATE: Payroll'
GO
	
	DECLARE @GL_intAccountStructureId_Primary AS INT
	SET @GL_intAccountStructureId_Primary = (SELECT TOP 1 intAccountStructureId FROM tblGLAccountStructure WHERE strType = N'Primary')
	
	IF NOT EXISTS(SELECT TOP 1 1 FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Payroll' AND strType = N'Primary') AND NOT EXISTS(SELECT TOP 1 1 FROM tblGLAccount)
	BEGIN
		INSERT [dbo].[tblGLCOATemplate] ([strAccountTemplateName], [strType], [intConcurrencyId]) VALUES (N'Payroll', N'Primary', 1)
		
		DECLARE @GL_intAccountTemplateId_Payroll AS INT		
		SET @GL_intAccountTemplateId_Payroll = (SELECT TOP 1 intAccountTemplateId FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Payroll' AND strType = N'Primary')
				
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'10000', N'Check book in Bank', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Cash Accounts' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'28000', N'Other Payroll Liability', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Tax Liabilities' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'28100', N'Federal Withholding', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Tax Liabilities' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'28200', N'State Withholding', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Tax Liabilities' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'28300', N'Social Security ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Tax Liabilities' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'28400', N'Medicare', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Tax Liabilities' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'35000', N'Owner''s Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Owners Equities' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'39000', N'Retained Earnings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Retained Earnings' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'52000', N'Wages Cogs', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Cogs' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'60100', N'Wages Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Earnings' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'60300', N'Payroll Taxes  Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Tax Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'60500', N'Payroll Other Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Payroll Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'72500', N'Tax Expense ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Payroll, N'99000', N'Wash Account', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
	END

GO	
	PRINT N'END INSERT ACCOUNT TEMPLATE: Payroll'
	PRINT N'BEGIN INSERT ACCOUNT TEMPLATE: Petrolac'
GO
	
	DECLARE @GL_intAccountStructureId_Primary AS INT
	SET @GL_intAccountStructureId_Primary = (SELECT TOP 1 intAccountStructureId FROM tblGLAccountStructure WHERE strType = N'Primary')
	
	IF NOT EXISTS(SELECT TOP 1 1 FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Petrolac' AND strType = N'Primary') AND NOT EXISTS(SELECT TOP 1 1 FROM tblGLAccount)
	BEGIN
		INSERT [dbo].[tblGLCOATemplate] ([strAccountTemplateName], [strType], [intConcurrencyId]) VALUES (N'Petrolac', N'Primary', 1)
		
		DECLARE @GL_intAccountTemplateId_Petrolac AS INT		
		SET @GL_intAccountTemplateId_Petrolac = (SELECT TOP 1 intAccountTemplateId FROM tblGLCOATemplate WHERE strAccountTemplateName = N'Petrolac' AND strType = N'Primary')
										
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'11000', N'Cash Clearing', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Undeposited Funds' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'12000', N'Accounts Receivable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Receivables' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'14000', N'Prepaid Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Prepaids' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'15000', N'Beginning Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'16000', N'Inventories', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'17000', N'Ending Inventory', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'18000', N'Supplies', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Inventories' AND strAccountType = N'Asset') , @GL_intAccountStructureId_Primary, 1)		
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'21000', N'Pending Accounts Payable', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'22000', N'Inspection Fee', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'23000', N'Federal Excise Tax ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'24000', N'State Excise Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'25000', N'State Sales Tax ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'26000', N'Prepaid Sales Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'27000', N'Locale Tax', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Tax Payables' AND strAccountType = N'Liability') , @GL_intAccountStructureId_Primary, 1)		
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'35000', N'Owner''s Equity', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Owners Equities' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'39000', N'Retained Earnings', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Retained Earnings' AND strAccountType = N'Equity') , @GL_intAccountStructureId_Primary, 1)		
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'40000', N'Sales Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'41000', N'Freight Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'45000', N'Discount Take', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Sales Discounts' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'46000', N'Sales Ticket Variance', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'48000', N'Finance Charge', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'49000', N'Other Income', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Income' AND strAccountType = N'Revenue') , @GL_intAccountStructureId_Primary, 1)		
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'50000', N'Purchases Default', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Purchases' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'51000', N'Purchases Variance', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Purchases' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'55000', N'Purchases Discounts', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Purchases Discounts' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'61000', N'Write Off', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'63000', N'Cash Over/Short', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'64000', N'Freight Expense', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'72500', N'Tax Expense ', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		INSERT [dbo].[tblGLCOATemplateDetail] ( [intAccountTemplateId], [strCode], [strDescription], [intAccountGroupId], [intAccountStructureId], [intConcurrencyId]) VALUES ( @GL_intAccountTemplateId_Petrolac , N'99000', N'Wash Account', (SELECT TOP 1 intAccountGroupId FROM tblGLAccountGroup WHERE strAccountGroup = N'Other Expenses' AND strAccountType = N'Expense') , @GL_intAccountStructureId_Primary, 1)
		
	END

GO
	PRINT N'END INSERT ACCOUNT TEMPLATE: Petrolac'
GO