CREATE TABLE [dbo].[tblTMDispatch] (
    [intConcurrencyID]         INT             CONSTRAINT [DEF_tblTMDispatch_intConcurrencyID] DEFAULT ((0)) NULL,
    [intDispatchID]            INT             IDENTITY (1, 1) NOT NULL,
    [intSiteID]                INT             CONSTRAINT [DEF_tblTMDispatch_intSiteID] DEFAULT ((0)) NULL,
    [dblPercentLeft]           NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDispatch_dblPercentLeft] DEFAULT ((0)) NULL,
    [dblQuantity]              NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDispatch_dblQuantity] DEFAULT ((0)) NULL,
    [dblMinimumQuantity]       NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDispatch_dblMinimumQuantity] DEFAULT ((0)) NULL,
    [intProductID]             INT             CONSTRAINT [DEF_tblTMDispatch_intProductID] DEFAULT ((0)) NULL,
    [intSubstituteProductID]   INT             CONSTRAINT [DEF_tblTMDispatch_intSubstituteProductID] DEFAULT ((0)) NULL,
    [dblPrice]                 NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDispatch_dblPrice] DEFAULT ((0)) NULL,
    [dblTotal]                 NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDispatch_dblTotal] DEFAULT ((0)) NULL,
    [dtmRequestedDate]         DATETIME        CONSTRAINT [DEF_tblTMDispatch_dtmRequestedDate] DEFAULT ((0)) NULL,
    [intPriority]              INT             CONSTRAINT [DEF_tblTMDispatch_intPriority] DEFAULT ((0)) NULL,
    [strComments]              NVARCHAR (200)  COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDispatch_strComments] DEFAULT ('') NULL,
    [ysnCallEntryPrinted]      BIT             CONSTRAINT [DEF_tblTMDispatch_ysnCallEntryPrinted] DEFAULT ((0)) NULL,
    [intDriverID]              INT             CONSTRAINT [DEF_tblTMDispatch_intDriverID] DEFAULT ((0)) NULL,
    [intDispatchDriverID]      INT             CONSTRAINT [DEF_tblTMDispatch_intDispatchDriverID] DEFAULT ((0)) NULL,
    [strDispatchLoadNumber]    NVARCHAR (3)    COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDispatch_strDispatchLoadNumber] DEFAULT ('') NULL,
    [dtmCallInDate]            DATETIME        CONSTRAINT [DEF_tblTMDispatch_dtmDispatchDate] DEFAULT ((0)) NULL,
    [ysnSelected]              BIT             CONSTRAINT [DEF_tblTMDispatch_ysnSelected] DEFAULT ((0)) NULL,
    [strRoute]                 NVARCHAR (10)   COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDispatch_strRoute] DEFAULT ('') NULL,
    [strSequence]              NVARCHAR (10)   COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDispatch_strSequence] DEFAULT ('') NULL,
    [intUserID]                INT             CONSTRAINT [DEF_tblTMDispatch_intUserID] DEFAULT ((0)) NULL,
    [dtmLastUpdated]           DATETIME        CONSTRAINT [DEF_tblTMDispatch_dtmLastUpdated] DEFAULT ((0)) NULL,
    [ysnDispatched]            BIT             NULL,
    [strCancelDispatchMessage] NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intDeliveryTermID]        INT             NULL,
    [dtmDispatchingDate]       DATETIME        NULL,
    CONSTRAINT [PK_tblTMDispatch] PRIMARY KEY CLUSTERED ([intDispatchID] ASC),
    CONSTRAINT [FK_tblTMDispatch_tblTMSite1] FOREIGN KEY ([intSiteID]) REFERENCES [dbo].[tblTMSite] ([intSiteID])
);

