CREATE TABLE [dbo].[tblTMDeliveryHistory] (
    [intConcurrencyID]                      INT             CONSTRAINT [DEF_tblTMDeliveryHistory_intConcurrencyID] DEFAULT ((0)) NULL,
    [intDeliveryHistoryID]                  INT             IDENTITY (1, 1) NOT NULL,
    [strInvoiceNumber]                      NVARCHAR (50)   COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDeliveryHistory_strInvoiceNumber] DEFAULT ('') NULL,
    [strBulkPlantNumber]                    NVARCHAR (50)   COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDeliveryHistory_strBulkPlantNumber] DEFAULT ('') NULL,
    [dtmInvoiceDate]                        DATETIME        CONSTRAINT [DEF_tblTMDeliveryHistory_dtmInvoiceDate] DEFAULT ((0)) NULL,
    [strProductDelivered]                   NVARCHAR (50)   COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDeliveryHistory_strProductDelivered] DEFAULT ('') NULL,
    [dblQuantityDelivered]                  NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblQuantityDelivered] DEFAULT ((0)) NULL,
    [intDegreeDayOnDeliveryDate]            INT             CONSTRAINT [DEF_tblTMDeliveryHistory_intDegreeDayOnDeliveryDate] DEFAULT ((0)) NULL,
    [intDegreeDayOnLastDeliveryDate]        INT             CONSTRAINT [DEF_tblTMDeliveryHistory_intDegreeDayOnLastDeliveryDate] DEFAULT ((0)) NULL,
    [dblBurnRateAfterDelivery]              NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblBurnRateAfterDelivery] DEFAULT ((0)) NULL,
    [dblCalculatedBurnRate]                 NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblCalculatedBurnRate] DEFAULT ((0)) NULL,
    [ysnAdjustBurnRate]                     BIT             CONSTRAINT [DEF_tblTMDeliveryHistory_ysnAdjustBurnRate] DEFAULT ((0)) NULL,
    [intElapsedDegreeDaysBetweenDeliveries] INT             CONSTRAINT [DEF_tblTMDeliveryHistory_intElapsedDegreeDaysBetweenDeliveries] DEFAULT ((0)) NULL,
    [intElapsedDaysBetweenDeliveries]       INT             CONSTRAINT [DEF_tblTMDeliveryHistory_intElapsedDaysBetweenDeliveries] DEFAULT ((0)) NULL,
    [strSeason]                             NVARCHAR (15)   COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDeliveryHistory_strSeason] DEFAULT ('') NULL,
    [dblWinterDailyUsageBetweenDeliveries]  NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblWinterDailyUsageBetweenDeliveries] DEFAULT ((0)) NULL,
    [dblSummerDailyUsageBetweenDeliveries]  NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblSummerDailyUsageBetweenDeliveries] DEFAULT ((0)) NULL,
    [dblGallonsInTankbeforeDelivery]        NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblGallonsInTankbeforeDelivery] DEFAULT ((0)) NULL,
    [dblGallonsInTankAfterDelivery]         NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblGallonsInTankAfterDelivery] DEFAULT ((0)) NULL,
    [dblEstimatedPercentBeforeDelivery]     NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblEstimatedPercentBeforeDelivery] DEFAULT ((0)) NULL,
    [dblActualPercentAfterDelivery]         NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblActualPercentAfterDelivery] DEFAULT ((0)) NULL,
    [dblMeterReading]                       NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblMeterReading] DEFAULT ((0)) NULL,
    [dblLastMeterReading]                   NUMERIC (18, 6) CONSTRAINT [DEF_tblTMDeliveryHistory_dblLastMeterReading] DEFAULT ((0)) NULL,
    [intUserID]                             INT             CONSTRAINT [DEF_tblTMDeliveryHistory_intUserID] DEFAULT ((0)) NULL,
    [dtmLastUpdated]                        DATETIME        CONSTRAINT [DEF_tblTMDeliveryHistory_dtmLastUpdated] DEFAULT ((0)) NULL,
    [intSiteID]                             INT             CONSTRAINT [DEF_tblTMDeliveryHistory_intSiteID] DEFAULT ((0)) NULL,
    [strSalesPersonID]                      NVARCHAR (50)   COLLATE Latin1_General_CI_AS CONSTRAINT [DEF_tblTMDeliveryHistory_strSalesPersonID] DEFAULT ((0)) NULL,
    [dbltmpExtendedAmount]                  NUMERIC (18, 6) NULL,
    CONSTRAINT [PK_tblTMDeliveryHistory] PRIMARY KEY CLUSTERED ([intDeliveryHistoryID] ASC),
    CONSTRAINT [FK_tblTMDeliveryHistory_tblTMSite] FOREIGN KEY ([intSiteID]) REFERENCES [dbo].[tblTMSite] ([intSiteID])
);

