:r .\PostDeployment\01_InventoryTransactionTypes.sql 
:r .\PostDeployment\03_DefaultData.sql 
:r .\PostDeployment\04_CostingMethods.sql 
:r .\PostDeployment\05_LotStatus.sql
:r .\PostDeployment\07_Status.sql
:r .\PostDeployment\08_InventoryTransactionPostingIntegration.sql
:r .\PostDeployment\09_InventoryTransactionsWithNoCounterAccountCategory.sql
:r .\PostDeployment\15_InventoryCostAdjustmentTypes.sql
:r .\PostDeployment\18_FOBPointTypes.sql
:r .\PostDeployment\19_M2MComputations.sql
:r .\PostDeployment\20_UpdateContractItemStatuses.sql
:r .\PostDeployment\21_AdjustmentInventoryTerms.sql
:r .\PostDeployment\22_StockTypes.sql
:r .\PostDeployment\PopulateLotContainerNoAndCondition.sql
:r .\PostDeployment\1740_DataFix_FixIntTransactionDetailId.sql
:r .\PostDeployment\22_Update_Qty_Cost_For_ReceiptTaxes.sql
:r .\PostDeployment\23_Update_ActualCostId_On_InventoryTransaction.sql
:r .\PostDeployment\24_ImplementBasketChanges.sql
:r .\PostDeployment\25_MigratePackedTypeToQuantityType.sql
:r .\PostDeployment\26_AddStockUOM.sql
:r .\PostDeployment\27_RemoveAfter18.1_DataFix.sql 
:r .\PostDeployment\28_Company_Preferences.sql
:r .\PostDeployment\29_Inventory_Constraints.sql
:r .\PostDeployment\30_Populate_Shipment_LineTotal.sql
:r .\PostDeployment\31_RemoveAfter18.3_DataFix.sql 
:r .\PostDeployment\31_Add_Default_Edi_Mapping_Template.sql