StartTest (function (t) {
        var commonIC = Ext.create('Inventory.CommonIC');
        new iRely.FunctionalTest().start(t)


      
        //endregion         
            
            
        //Scenario 3: Check Gross/Net UOM and Line Total where Receipt UOM and Gross/Net UOM is the same
        .displayText('===== Scenario 3: Check Gross/Net UOM and Line Total where Receipt UOM and Gross/Net UOM is the same =====')
        .addFunction(function(next){
            commonIC.addDirectIRLotted (t,next, 'ABC Trucking', 1, 'Direct - LTI - 01','Test_Pounds', 100, 10, 'Raw Station', 'RM Storage', 'LOT-01', 'Test_Pounds')
        })
        .waitUntilLoaded().waitUntilLoaded()
        .clickButton('Close')

        //Create Direct IR for Non Lotted Item
        .displayText('===== Scenario 4: Check Gross/Net UOM and Line Total where Receipt UOM and Gross/Net UOM are different =====')

        .displayText('===== Creeating Direct IR for Non Lotted Item  =====')
        //.clickMenuFolder('Inventory','Folder')
        .clickMenuScreen('Inventory Receipts','Screen')
        .waitUntilLoaded()
        .clickButton('New')
        .waitUntilLoaded('icinventoryreceipt')
        .selectComboBoxRowNumber('ReceiptType',4,0)
        .selectComboBoxRowValue('Vendor', 'ABC Trucking' , 'Vendor',1)
        .selectComboBoxRowNumber('Location',1,0)
        .clickButton('Close')
        .clickButton('InsertInventoryReceipt')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strItemNo', 'Direct - LTI - 01','strItemNo')
        .enterUOMGridData('InventoryReceipt', 1, 'colUOMQtyToReceive', 'strUnitMeasure', 100, 'Test_50 lb bag')
        .verifyGridData('InventoryReceipt', 1, 'colItemSubCurrency', 'USD')
        .enterGridData('InventoryReceipt', 1, 'colUnitCost', 10)
        .verifyGridData('InventoryReceipt', 1, 'colCostUOM', 'Test_Pounds')
        .verifyGridData('InventoryReceipt', 1, 'colWeightUOM', 'Test_Pounds')
        .verifyGridData('InventoryReceipt', 1, 'colGross', '5000')
        .verifyGridData('InventoryReceipt', 1, 'colNet', '5000')
        .verifyGridData('InventoryReceipt', 1, 'colLineTotal', '50000')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strSubLocationName','Raw Station','strSubLocationName')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strStorageLocationName','RM Storage','strSubLocationName')

        .enterGridData('LotTracking', 1, 'colLotId', 'LOT-02')
        .selectGridComboBoxRowValue('LotTracking',1,'strUnitMeasure','Test_Pounds' ,'strUnitMeasure')
        .enterGridData('LotTracking', 1, 'colLotQuantity', 5000)
        .verifyGridData('LotTracking', 1, 'colLotGrossWeight', '5000')
        .verifyGridData('LotTracking', 1, 'colLotNetWeight', '5000')
        .verifyGridData('LotTracking', 1, 'colLotTareWeight', '0')
        .verifyGridData('LotTracking', 1, 'colLotWeightUOM','Test_Pounds')
        .verifyGridData('LotTracking', 1, 'colLotStorageLocation', 'RM Storage')


        .clickTab('Post Preview')
        .waitUntilLoaded('')
        .clickTab('Details')
        .waitUntilLoaded('')
        .clickTab('Post Preview')
        .waitUntilLoaded('')
        .verifyGridData('RecapTransaction', 1, 'colAccountId', '16000-0001-000')
        .verifyGridData('RecapTransaction', 1, 'colDebit', '50000')
        .verifyGridData('RecapTransaction', 2, 'colAccountId', '21000-0001-000')
        .verifyGridData('RecapTransaction', 2, 'colCredit', '50000')
        .clickButton('Post')
        .waitUntilLoaded('')
        .addResult('Successfully Posted',2000)
        .waitUntilLoaded('')
        .clickButton('Close')
        .waitUntilLoaded().waitUntilLoaded().waitUntilLoaded()
         .clickButton('Close')
        .displayText('===== Creating Direct IR for Non Lotted Done =====')
        //.clickMenuFolder('Inventory','Folder')


        // .displayText('===== Scenario 5: Receipt UOM 50 KG Bags Net Weight is Less than Gross Weight =====')
        // .displayText('===== Creeating Direct IR for Non Lotted Item  =====')
        // //.clickMenuFolder('Inventory','Folder')
        // .clickMenuScreen('Inventory Receipts','Screen')
        // .waitUntilLoaded()
        // .clickButton('New')
        // .waitUntilLoaded('icinventoryreceipt')
        // .selectComboBoxRowNumber('ReceiptType',4,0)
        // .selectComboBoxRowValue('Vendor', 'ABC Trucking' , 'Vendor',1)
        // .selectComboBoxRowNumber('Location',1,0)
        // .clickButton('Close')
        // .clickButton('InsertInventoryReceipt')
        // .selectGridComboBoxRowValue('InventoryReceipt',1,'strItemNo', 'Direct - LTI - 02','strItemNo')
        // .enterUOMGridData('InventoryReceipt', 1, 'colUOMQtyToReceive', 'strUnitMeasure', 100, 'Test_50 KG bags')
        // .verifyGridData('InventoryReceipt', 1, 'colItemSubCurrency', 'USD')
        // .enterGridData('InventoryReceipt', 1, 'colUnitCost', 10)
        // .verifyGridData('InventoryReceipt', 1, 'colCostUOM', 'Test_KG')
        // .verifyGridData('InventoryReceipt', 1, 'colWeightUOM', 'Test_KG')
        // .verifyGridData('InventoryReceipt', 1, 'colGross', '5000')
        // .enterGridData('InventoryReceipt', 1, 'colNet', '4900')

        // .verifyGridData('InventoryReceipt', 1, 'colLineTotal', '49000')
        // .selectGridComboBoxRowValue('InventoryReceipt',1,'strSubLocationName','Raw Station','strSubLocationName')
        // .selectGridComboBoxRowValue('InventoryReceipt',1,'strStorageLocationName','RM Storage','strSubLocationName')

        // .enterGridData('LotTracking', 1, 'colLotId', 'LOT-02')
        // .selectGridComboBoxRowValue('LotTracking',1,'strUnitMeasure','Test_50 KG bags' ,'strUnitMeasure')
        // .enterGridData('LotTracking', 1, 'colLotQuantity', 100)
        // .verifyGridData('LotTracking', 1, 'colLotGrossWeight', '5000')
        // .enterGridData('LotTracking', 1, 'colLotTareWeight', 100)
        // .verifyGridData('LotTracking', 1, 'colLotWeightUOM','Test_KG')
        // .verifyGridData('LotTracking', 1, 'colLotStorageLocation', 'RM Storage')


        // .clickTab('Post Preview')
        // .waitUntilLoaded('')
        // .clickTab('Details')
        // .waitUntilLoaded('')
        // .clickTab('Post Preview')
        // .waitUntilLoaded('')
        // .verifyGridData('RecapTransaction', 1, 'colAccountId', '16000-0001-000')
        // .verifyGridData('RecapTransaction', 1, 'colDebit', '49000')
        // .verifyGridData('RecapTransaction', 2, 'colAccountId', '21000-0001-000')
        // .verifyGridData('RecapTransaction', 2, 'colCredit', '49000')
        // .clickButton('Post')
        // .waitUntilLoaded('')
        // .addResult('Successfully Posted',2000)
        // .waitUntilLoaded('')
        // .clickButton('Close')
        // .waitUntilLoaded().waitUntilLoaded().waitUntilLoaded()
        // .clickButton('Close')
        // .displayText('===== Creating Direct IR for Non Lotted Done =====')
        //.clickMenuFolder('Inventory','Folder')



        //Create Direct IR for Non Lotted Item
        .displayText('===== Scenario 6: There is duplicate Lot Number and Lot UOM does not match that of existing lot number =====')

        .displayText('===== Creeating Direct IR for Non Lotted Item  =====')
        //.clickMenuFolder('Inventory','Folder')
        .clickMenuScreen('Inventory Receipts','Screen')
        .waitUntilLoaded()
        .clickButton('New')
        .waitUntilLoaded('icinventoryreceipt')
        .selectComboBoxRowNumber('ReceiptType',4,0)
        .selectComboBoxRowValue('Vendor', 'ABC Trucking' , 'Vendor',1)
        .selectComboBoxRowNumber('Location',1,0)
         .clickButton('Close')
        .clickButton('InsertInventoryReceipt')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strItemNo', 'Direct - LTI - 02','strItemNo')
        .enterUOMGridData('InventoryReceipt', 1, 'colUOMQtyToReceive', 'strUnitMeasure', 1000, 'Test_KG')
        .verifyGridData('InventoryReceipt', 1, 'colItemSubCurrency', 'USD')
        .enterGridData('InventoryReceipt', 1, 'colUnitCost', 10)
        .verifyGridData('InventoryReceipt', 1, 'colCostUOM', 'Test_KG')
        .verifyGridData('InventoryReceipt', 1, 'colWeightUOM', 'Test_KG')
        .verifyGridData('InventoryReceipt', 1, 'colGross', '1000')
        .verifyGridData('InventoryReceipt', 1, 'colNet', '1000')
        .verifyGridData('InventoryReceipt', 1, 'colLineTotal', '10000')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strSubLocationName','Raw Station','strSubLocationName')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strStorageLocationName','RM Storage','strSubLocationName')

//        .enterGridData('LotTracking', 1, 'colLotId', 'LOT-02')
        //.selectGridComboBoxRowValue('LotTracking',1,'strLotNumber','LOT-02[ENTER]','strLotNumber')
        .enterGridData('LotTracking', 1, 'colLotId', 'LOT-02')
        //.selectGridComboBoxRowValue('LotTracking',1,'strParentLotNumber','LOT-02[ENTER]','strParentLotNumber')
        //.enterGridData('LotTracking', 1, 'colLotParentLotId', '[ENTER]')
        .selectGridComboBoxRowValue('LotTracking',1,'strUnitMeasure','Test_25 KG Bag' ,'strUnitMeasure')
        .enterGridData('LotTracking', 1, 'colLotQuantity', 40)
        .verifyGridData('LotTracking', 1, 'colLotGrossWeight', '1000')
        .verifyGridData('LotTracking', 1, 'colLotNetWeight', '1000')
        .verifyGridData('LotTracking', 1, 'colLotTareWeight', '0')
        .verifyGridData('LotTracking', 1, 'colLotWeightUOM','Test_KG')
        .verifyGridData('LotTracking', 1, 'colLotStorageLocation', 'RM Storage')

        .clickButton('Post')
        .waitUntilLoaded('')
        .clickMessageBoxButton('ok')
        .waitUntilLoaded('')
        .addResult('Done Checking Message',2000)
        .waitUntilLoaded('')
        .clickButton('Close')
        .waitUntilLoaded().waitUntilLoaded().waitUntilLoaded()
        .clickButton('Close')
        .displayText('===== Creating Direct IR for Non Lotted Done =====')
        //.clickMenuFolder('Inventory','Folder')

        .done();

})