StartTest (function (t) {
    var commonIC = Ext.create('Inventory.CommonIC');
    new iRely.FunctionalTest().start(t)


        .displayText('===== Scenario 10: Create Direct Inventory Receipt Type. (Lotted Item)Change the location from Fortwayne to Indianapolis =====')
        .displayText('===== Creeating Direct IR for Non Lotted Item  =====')
        .clickMenuFolder('Inventory','Folder')
        .clickMenuScreen('Inventory Receipts','Screen')
        .waitUntilLoaded()
        .clickButton('New')
        .waitUntilLoaded('icinventoryreceipt')
        .selectComboBoxRowNumber('ReceiptType',4,0)
        .selectComboBoxRowValue('Vendor', 'ABC Trucking' , 'Vendor',1)
        .selectComboBoxRowValue('Location', '0001 - Fort Wayne' , 'Vendor',1)
        .selectComboBoxRowNumber('FreightTerms',1,0)
        .waitUntilLoaded()
        .addResult('Selected Freight Terms',2000)
        .waitUntilLoaded()
        .clickTab('EDI')
        .waitUntilLoaded('')
        .clickTab('Details')
        .waitUntilLoaded('')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strItemNo', 'Direct - LTI - 01','strItemNo')
        .enterUOMGridData('InventoryReceipt', 1, 'colUOMQtyToReceive', 'strUnitMeasure', 1000, 'LB')
        .verifyGridData('InventoryReceipt', 1, 'colItemSubCurrency', 'USD')
        .enterGridData('InventoryReceipt', 1, 'colUnitCost', 10)
        .verifyGridData('InventoryReceipt', 1, 'colCostUOM', 'LB')
        .verifyGridData('InventoryReceipt', 1, 'colWeightUOM', 'LB')
        .verifyGridData('InventoryReceipt', 1, 'colGross', '1000')
        .verifyGridData('InventoryReceipt', 1, 'colNet', '1000')
        .verifyGridData('InventoryReceipt', 1, 'colLineTotal', '10000')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strSubLocationName','Raw Station','strSubLocationName')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strStorageLocationName','RM Storage','strSubLocationName')

        .selectGridComboBoxRowValue('LotTracking',1,'strLotNumber','LOT-01','strLotNumber')
        .selectGridComboBoxRowValue('LotTracking',1,'strUnitMeasure','LB' ,'strUnitMeasure')
        .enterGridData('LotTracking', 1, 'colLotQuantity', 1000)
        .verifyGridData('LotTracking', 1, 'colLotStorageLocation', 'RM Storage')
        .selectComboBoxRowValue('Location', '0002 - Indianapolis' , 'Vendor',1)
        .waitUntilLoaded('')
        .verifyMessageBox('iRely i21','Changing Location will clear ALL Sub Locations and Storage Locations. Do you want to continue?','yesno','warning')
        .clickMessageBoxButton('yes')
        .waitUntilLoaded('')
        .clickButton('Post')
        .waitUntilLoaded('')
        .verifyGridData('InventoryReceipt', 1, 'colSubLocation', '')
        .verifyGridData('InventoryReceipt', 1, 'colStorageLocation', '')
        .clickButton('Close')
        .waitUntilLoaded('')
        .clickMessageBoxButton('no')
        .waitUntilLoaded('')
        .clickMenuFolder('Inventory','Folder')
        .displayText('===== Scenario 10: Create Direct Inventory Receipt Type. (Lotted Item)Change the location from Fortwayne to Indianapolis Done =====')


        .displayText('===== Scenario 11: Create Direct Inventory Receipt Type. (Lotted Item) Different net quantities =====')
        .displayText('===== Creeating Direct IR for Non Lotted Item  =====')
        .clickMenuFolder('Inventory','Folder')
        .clickMenuScreen('Inventory Receipts','Screen')
        .waitUntilLoaded()
        .clickButton('New')
        .waitUntilLoaded('icinventoryreceipt')
        .selectComboBoxRowNumber('ReceiptType',4,0)
        .selectComboBoxRowValue('Vendor', 'ABC Trucking' , 'Vendor',1)
        .selectComboBoxRowNumber('Location',1,0)
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strItemNo', 'Direct - LTI - 01','strItemNo')
        .enterUOMGridData('InventoryReceipt', 1, 'colUOMQtyToReceive', 'strUnitMeasure', 1000, 'LB')
        .verifyGridData('InventoryReceipt', 1, 'colItemSubCurrency', 'USD')
        .enterGridData('InventoryReceipt', 1, 'colUnitCost', 10)
        .verifyGridData('InventoryReceipt', 1, 'colCostUOM', 'LB')
        .verifyGridData('InventoryReceipt', 1, 'colWeightUOM', 'LB')
        .verifyGridData('InventoryReceipt', 1, 'colGross', '1000')
        .verifyGridData('InventoryReceipt', 1, 'colNet', '1000')
        .verifyGridData('InventoryReceipt', 1, 'colLineTotal', '10000')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strSubLocationName','Raw Station','strSubLocationName')
        .selectGridComboBoxRowValue('InventoryReceipt',1,'strStorageLocationName','RM Storage','strSubLocationName')

        .selectGridComboBoxRowValue('LotTracking',1,'strLotNumber','LOT-01','strLotNumber')
        .selectGridComboBoxRowValue('LotTracking',1,'strUnitMeasure','LB' ,'strUnitMeasure')
        .enterGridData('LotTracking', 1, 'colLotQuantity', 1000)
        .enterGridData('LotTracking', 1, 'colLotTareWeight', 100)
        .verifyGridData('LotTracking', 1, 'colLotGrossWeight', '1000')
        .verifyGridData('LotTracking', 1, 'colLotNetWeight', '900')
        .verifyGridData('LotTracking', 1, 'colLotTareWeight', '100')
        .verifyGridData('LotTracking', 1, 'colLotWeightUOM','LB')
        .verifyGridData('LotTracking', 1, 'colLotStorageLocation', 'RM Storage')

        .clickButton('Post')
        .waitUntilLoaded('')
        .waitUntilLoaded('')
        .clickMessageBoxButton('ok')
        .clickButton('Close')
        .waitUntilLoaded('')
        .clickMenuFolder('Inventory','Folder')
        .waitUntilLoaded('')
        .displayText('===== Scenario 11: Create Direct Inventory Receipt Type. (Lotted Item) Different net quantities Done =====')

        .done();

})