StartTest (function (t) {
    new iRely.FunctionalTest().start(t)

        //region Scenario 1: Add Lotted Yes Serial Item
        .clickMenu('Inventory','Folder')
        .clickScreenMenu('Items','Screen')
        .clickButton('New')
        .enterData('textbox','ItemNo','001 - CLTI')
        .enterData('textbox','Description','001 - CRUD Lotted Item')
        .selectComboBoxRowValue('Category', 'Grains', 200, 'Category',0)
        .selectComboBoxRowValue('Commodity', 'Corn', 200, 'Commodity',0)
        .selectComboBoxRowNumber('LotTracking',2)
        .verifyData('combobox','Tracking','Lot Level')
        .selectGridComboBoxRowValue('#grdUnitOfMeasure',0,'strUnitMeasure','LB', 200,'strUnitMeasure')
        .clickButton('InsertUom')
        .selectGridComboBoxRowValue('#grdUnitOfMeasure',1,'strUnitMeasure','50 lb bag', 200,'strUnitMeasure')
        .selectGridComboBoxRowValue('#grdUnitOfMeasure',2,'strUnitMeasure','Bushels', 200,'strUnitMeasure')
        .selectGridComboBoxRowValue('#grdUnitOfMeasure',3,'strUnitMeasure','25 kg bag', 200,'strUnitMeasure')
        .clickGridCheckBox('#grdUnitOfMeasure', 'strUnitMeasure', 'LB', 'ysnStockUnit', true)
        .waitTillLoaded()
        .verifyGridData('#grdUnitOfMeasure', 0, 'colDetailUnitQty', '1')
        .verifyGridData('#grdUnitOfMeasure', 1, 'colDetailUnitQty', '50')
        .verifyGridData('#grdUnitOfMeasure', 2, 'colDetailUnitQty', '56')
        .verifyGridData('#grdUnitOfMeasure', 3, 'colDetailUnitQty', '55.1156')

        .clickTab('Setup')
        .clickButton('AddRequiredAccounts').wait(100)
        .verifyGridData('#grdGlAccounts', 0, 'colGLAccountCategory', 'AP Clearing')
        .verifyGridData('#grdGlAccounts', 1, 'colGLAccountCategory', 'Inventory')
        .verifyGridData('#grdGlAccounts', 2, 'colGLAccountCategory', 'Cost of Goods')
        .verifyGridData('#grdGlAccounts', 3, 'colGLAccountCategory', 'Sales Account')
        .verifyGridData('#grdGlAccounts', 4, 'colGLAccountCategory', 'Inventory In-Transit')
        .verifyGridData('#grdGlAccounts', 5, 'colGLAccountCategory', 'Inventory Adjustment')
        .verifyGridData('#grdGlAccounts', 6, 'colGLAccountCategory', 'Auto-Variance')

        .selectGridComboBoxRowValue('#grdGlAccounts', 0, 'strAccountId', '21000-0000-000', 200, 'strAccountId')
        .selectGridComboBoxRowValue('#grdGlAccounts', 1, 'strAccountId', '16000-0000-000', 200, 'strAccountId')
        .selectGridComboBoxRowValue('#grdGlAccounts', 2, 'strAccountId', '50000-0000-000', 200, 'strAccountId')
        .selectGridComboBoxRowValue('#grdGlAccounts', 3, 'strAccountId', '40010-0001-006', 200, 'strAccountId')
        .selectGridComboBoxRowValue('#grdGlAccounts', 4, 'strAccountId', '16050-0000-000', 200, 'strAccountId')
        .selectGridComboBoxRowValue('#grdGlAccounts', 5, 'strAccountId', '16040-0000-000', 200, 'strAccountId')
        .selectGridComboBoxRowValue('#grdGlAccounts', 6, 'strAccountId', '16010-0000-000', 200, 'strAccountId')

        .clickTab('Location')
        .clickButton('AddLocation')
        .selectComboBoxRowValue('SubLocation', 'Raw Station', 200, 'SubLocation',0)
        .selectComboBoxRowValue('StorageLocation', 'RM Storage', 200, 'StorageLocation',0)
        .selectComboBoxRowValue('IssueUom', 'LB', 200, 'IssueUom',0)
        .selectComboBoxRowValue('ReceiveUom', 'LB', 200, 'ReceiveUom',0)
        .clickButton('Save')
        .clickButton('Close')


       /* .selectMenu('Items')
        .selectComboRowByFilter('Category', 'Grains', 200, 'Category',0)
        .selectComboRowByFilter('Commodity', 'Corn', 200, 'Commodity',0)
        .selectComboRowByIndex('LotTracking',2)
        .VerifyData('combobox','Tracking','Lot Level')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',0,'strUnitMeasure','LB', 200,'strUnitMeasure')
        .clickButton('InsertUom')
        .clickGridCheckBox('#grdUnitOfMeasure', 'strUnitMeasure', 'LB', 'ysnStockUnit', true)
        .selectGridComboRowByFilter('#grdUnitOfMeasure',1,'strUnitMeasure','50 lb bag', 200,'strUnitMeasure')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',2,'strUnitMeasure','Bushels', 200,'strUnitMeasure')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',3,'strUnitMeasure','25 kg bag', 200,'strUnitMeasure')

        .checkGridData('#grdUnitOfMeasure', 0, 'colDetailUnitQty', '1')
        .checkGridData('#grdUnitOfMeasure', 1, 'colDetailUnitQty', '50')
        .checkGridData('#grdUnitOfMeasure', 2, 'colDetailUnitQty', '56')
        .checkGridData('#grdUnitOfMeasure', 3, 'colDetailUnitQty', '55.1156')

        .clickTab('Setup')
        .clickButton('AddRequiredAccounts').wait(100)
        .checkGridData('#grdGlAccounts', 0, 'colGLAccountCategory', 'AP Clearing')
        .checkGridData('#grdGlAccounts', 1, 'colGLAccountCategory', 'Inventory')
        .checkGridData('#grdGlAccounts', 2, 'colGLAccountCategory', 'Cost of Goods')
        .checkGridData('#grdGlAccounts', 3, 'colGLAccountCategory', 'Sales Account')
        .checkGridData('#grdGlAccounts', 4, 'colGLAccountCategory', 'Inventory In-Transit')
        .checkGridData('#grdGlAccounts', 5, 'colGLAccountCategory', 'Inventory Adjustment')
        .checkGridData('#grdGlAccounts', 6, 'colGLAccountCategory', 'Auto-Variance')

        .selectGridComboRowByFilter('#grdGlAccounts', 0, 'strAccountId', '21000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 1, 'strAccountId', '16000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 2, 'strAccountId', '50000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 3, 'strAccountId', '40010-0001-006', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 4, 'strAccountId', '16050-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 5, 'strAccountId', '16040-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 6, 'strAccountId', '16010-0000-000', 200, 'strAccountId')

        .clickTab('Location')
        .clickButton('AddLocation')
        .VerifyData('combobox','Location','0001 - Fort Wayne')
        .selectComboRowByFilter('SubLocation', 'Raw Station', 200, 'SubLocation',0)
        .selectComboRowByFilter('StorageLocation', 'RM Storage', 200, 'StorageLocation',0)
        .selectComboRowByFilter('IssueUom', 'LB', 200, 'IssueUom',0)
        .selectComboRowByFilter('ReceiveUom', 'LB', 200, 'ReceiveUom',0)
        .clickButton('Save')
        .clickButton('Close')

        .clickTab('Pricing')
        .checkGridData('#grdPricing', 0, 'strLocationName', '0001 - Fort Wayne')
        .enterGridData('#grdPricing', 0, 'dblLastCost', '10')
        .enterGridData('#grdPricing', 0, 'dblStandardCost', '10')
        .selectGridComboRowByIndex('#grdPricing', 0, 'strPricingMethod',2, 'strPricingMethod')
        .enterGridData('#grdPricing', 0, 'dblAmountPercent', '40')
        .checkGridData('#grdPricing', 0, 'dblSalePrice', '14')
        .clickButton('Save')
        .clickButton('Close')
        .checkGridRecordCount('#grdSearch', 201)
        //endregion


        //region Scenario 2: Add Lotted Yes Manual Item
        .selectMenu('Items')
        .clickButton('New')
        .enterData('textbox','ItemNo','002 - CLTI')
        .enterData('textbox','Description','002 - CRUD Lotted Item')
        .selectComboRowByFilter('Category', 'Grains', 200, 'Category',0)
        .selectComboRowByFilter('Commodity', 'Corn', 200, 'Commodity',0)
        .selectComboRowByIndex('LotTracking',1)
        .VerifyData('combobox','Tracking','Lot Level')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',0,'strUnitMeasure','LB', 200,'strUnitMeasure')
        .clickButton('InsertUom')
        .clickGridCheckBox('#grdUnitOfMeasure', 'strUnitMeasure', 'LB', 'ysnStockUnit', true)
        .selectGridComboRowByFilter('#grdUnitOfMeasure',1,'strUnitMeasure','50 lb bag', 200,'strUnitMeasure')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',2,'strUnitMeasure','Bushels', 200,'strUnitMeasure')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',3,'strUnitMeasure','25 kg bag', 200,'strUnitMeasure')

        .checkGridData('#grdUnitOfMeasure', 0, 'colDetailUnitQty', '1')
        .checkGridData('#grdUnitOfMeasure', 1, 'colDetailUnitQty', '50')
        .checkGridData('#grdUnitOfMeasure', 2, 'colDetailUnitQty', '56')
        .checkGridData('#grdUnitOfMeasure', 3, 'colDetailUnitQty', '55.1156')

        .clickTab('Setup')
        .clickButton('AddRequiredAccounts').wait(100)
        .checkGridData('#grdGlAccounts', 0, 'colGLAccountCategory', 'AP Clearing')
        .checkGridData('#grdGlAccounts', 1, 'colGLAccountCategory', 'Inventory')
        .checkGridData('#grdGlAccounts', 2, 'colGLAccountCategory', 'Cost of Goods')
        .checkGridData('#grdGlAccounts', 3, 'colGLAccountCategory', 'Sales Account')
        .checkGridData('#grdGlAccounts', 4, 'colGLAccountCategory', 'Inventory In-Transit')
        .checkGridData('#grdGlAccounts', 5, 'colGLAccountCategory', 'Inventory Adjustment')
        .checkGridData('#grdGlAccounts', 6, 'colGLAccountCategory', 'Auto-Variance')

        .selectGridComboRowByFilter('#grdGlAccounts', 0, 'strAccountId', '21000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 1, 'strAccountId', '16000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 2, 'strAccountId', '50000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 3, 'strAccountId', '40010-0001-006', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 4, 'strAccountId', '16050-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 5, 'strAccountId', '16040-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 6, 'strAccountId', '16010-0000-000', 200, 'strAccountId')

        .clickTab('Location')
        .clickButton('AddLocation')
        .VerifyData('combobox','Location','0001 - Fort Wayne')
        .selectComboRowByFilter('SubLocation', 'Raw Station', 200, 'SubLocation',0)
        .selectComboRowByFilter('StorageLocation', 'RM Storage', 200, 'StorageLocation',0)
        .selectComboRowByFilter('IssueUom', 'LB', 200, 'IssueUom',0)
        .selectComboRowByFilter('ReceiveUom', 'LB', 200, 'ReceiveUom',0)
        .clickButton('Save')
        .clickButton('Close')

        .clickTab('Pricing')
        .checkGridData('#grdPricing', 0, 'strLocationName', '0001 - Fort Wayne')
        .enterGridData('#grdPricing', 0, 'dblLastCost', '10')
        .enterGridData('#grdPricing', 0, 'dblStandardCost', '10')
        .selectGridComboRowByIndex('#grdPricing', 0, 'strPricingMethod',2, 'strPricingMethod')
        .enterGridData('#grdPricing', 0, 'dblAmountPercent', '40')
        .checkGridData('#grdPricing', 0, 'dblSalePrice', '14')
        .clickButton('Save')
        .clickButton('Close')
        .checkGridRecordCount('#grdSearch', 202)
        //endregion


        //region Scenario 3: Add Lotted Yes Manual Item
        .selectMenu('Items')
        .clickButton('New')
        .enterData('textbox','ItemNo','003 - CNLTI')
        .enterData('textbox','Description','002 - CRUD Non Lotted Item')
        .selectComboRowByFilter('Category', 'Grains', 200, 'Category',0)
        .selectComboRowByFilter('Commodity', 'Corn', 200, 'Commodity',0)
        .selectComboRowByIndex('LotTracking',3)
        .VerifyData('combobox','Tracking','Item Level')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',0,'strUnitMeasure','LB', 200,'strUnitMeasure')
        .clickButton('InsertUom')
        .clickGridCheckBox('#grdUnitOfMeasure', 'strUnitMeasure', 'LB', 'ysnStockUnit', true)
        .selectGridComboRowByFilter('#grdUnitOfMeasure',1,'strUnitMeasure','50 lb bag', 200,'strUnitMeasure')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',2,'strUnitMeasure','Bushels', 200,'strUnitMeasure')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',3,'strUnitMeasure','25 kg bag', 200,'strUnitMeasure')

        .checkGridData('#grdUnitOfMeasure', 0, 'colDetailUnitQty', '1')
        .checkGridData('#grdUnitOfMeasure', 1, 'colDetailUnitQty', '50')
        .checkGridData('#grdUnitOfMeasure', 2, 'colDetailUnitQty', '56')
        .checkGridData('#grdUnitOfMeasure', 3, 'colDetailUnitQty', '55.1156')

        .clickTab('Setup')
        .clickButton('AddRequiredAccounts').wait(100)
        .checkGridData('#grdGlAccounts', 0, 'colGLAccountCategory', 'AP Clearing')
        .checkGridData('#grdGlAccounts', 1, 'colGLAccountCategory', 'Inventory')
        .checkGridData('#grdGlAccounts', 2, 'colGLAccountCategory', 'Cost of Goods')
        .checkGridData('#grdGlAccounts', 3, 'colGLAccountCategory', 'Sales Account')
        .checkGridData('#grdGlAccounts', 4, 'colGLAccountCategory', 'Inventory In-Transit')
        .checkGridData('#grdGlAccounts', 5, 'colGLAccountCategory', 'Inventory Adjustment')
        .checkGridData('#grdGlAccounts', 6, 'colGLAccountCategory', 'Auto-Variance')

        .selectGridComboRowByFilter('#grdGlAccounts', 0, 'strAccountId', '21000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 1, 'strAccountId', '16000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 2, 'strAccountId', '50000-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 3, 'strAccountId', '40010-0001-006', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 4, 'strAccountId', '16050-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 5, 'strAccountId', '16040-0000-000', 200, 'strAccountId')
        .selectGridComboRowByFilter('#grdGlAccounts', 6, 'strAccountId', '16010-0000-000', 200, 'strAccountId')

        .clickTab('Location')
        .clickButton('AddLocation')
        .VerifyData('combobox','Location','0001 - Fort Wayne')
        .selectComboRowByFilter('SubLocation', 'Raw Station', 200, 'SubLocation',0)
        .selectComboRowByFilter('StorageLocation', 'RM Storage', 200, 'StorageLocation',0)
        .selectComboRowByFilter('IssueUom', 'LB', 200, 'IssueUom',0)
        .selectComboRowByFilter('ReceiveUom', 'LB', 200, 'ReceiveUom',0)
        .clickButton('Save')
        .clickButton('Close')

        .clickTab('Pricing')
        .checkGridData('#grdPricing', 0, 'strLocationName', '0001 - Fort Wayne')
        .enterGridData('#grdPricing', 0, 'dblLastCost', '10')
        .enterGridData('#grdPricing', 0, 'dblStandardCost', '10')
        .selectGridComboRowByIndex('#grdPricing', 0, 'strPricingMethod',2, 'strPricingMethod')
        .enterGridData('#grdPricing', 0, 'dblAmountPercent', '40')
        .checkGridData('#grdPricing', 0, 'dblSalePrice', '14')
        .clickButton('Save')
        .clickButton('Close')
        .checkGridRecordCount('#grdSearch', 203)
        //endregion


        //region Scenario 4: Check Required Fields
        .selectMenu('Items')
        .clickButton('New')
        .clickButton('Save')
        .clickButton('Close')
        .checkMessageBox('iRely i21','Do you want to save the changes you made?','yesnocancel','question')
        .clickMessageBoxButton('no')
        //endregion


        //region Scenario 5: Update an Item
        .selectMenu('Items')
        .selectRowNumber(1)
        .clickButton('OpenSelected')
        .waitTillLoaded()
        .enterData('textbox','Description','001 - CRUD Lotted Item - Updated')
        .clickButton('InsertUom')
        .selectGridComboRowByFilter('#grdUnitOfMeasure',4,'strUnitMeasure','40 lb bag', 200,'strUnitMeasure')
        .checkGridData('#grdUnitOfMeasure', 4, 'colDetailUnitQty', '40')
        .clickButton('Close')
        .checkMessageBox('iRely i21','Do you want to save the changes you made?','yesnocancel','question')
        .clickMessageBoxButton('yes')

        .selectMenu('Items')
        .selectRowNumber(1)
        .clickButton('OpenSelected')
        .waitTillLoaded()
        .VerifyData('textbox','Description','001 - CRUD Lotted Item - Updated')
        .checkGridData('#grdUnitOfMeasure', 0, 'colDetailUnitMeasure', '40 lb bag')
        .checkGridData('#grdUnitOfMeasure', 0, 'colDetailUnitQty', '40')
        .clickButton('Close')
        //endregion

        //region Scenario 6: Duplicate an Item
        .selectMenu('Items')
        .selectRowNumber(1)
        .clickButton('OpenSelected')
        .waitTillLoaded()
        .clickButton('Duplicate')
        .VerifyData('textbox','ItemNo','001 - CLTI-copy')
        .VerifyData('textbox','Description','001 - CRUD Lotted Item - Updated')
        .VerifyData('combobox','LotTracking','Yes - Serial Number')
        .VerifyData('combobox','Category','Grains')
        .VerifyData('combobox','Commodity','Corn')
        .checkGridData('#grdUnitOfMeasure', 0, 'colDetailUnitQty', '40')
        .checkGridData('#grdUnitOfMeasure', 3, 'colDetailUnitQty', '1')
        .checkGridData('#grdUnitOfMeasure', 2, 'colDetailUnitQty', '50')
        .checkGridData('#grdUnitOfMeasure', 4, 'colDetailUnitQty', '56')
        .checkGridData('#grdUnitOfMeasure', 1, 'colDetailUnitQty', '55.1156')
        .clickButton('Close')
        .checkGridRecordCount('#grdSearch', 204)
        //endregion*/




        .done();

})