CREATE UNIQUE NONCLUSTERED INDEX [IX_tblGLAccountReallocation_strName] ON [dbo].[tblGLAccountReallocation]
(
	[strName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,   IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO