StartTest(function (t) {

    var engine = new iRely.TestEngine();
    var commonSM = Ext.create('SystemManager.CommonSM');
    var commonIC = Ext.create('i21.test.Inventory.CommonIC');

    engine.start(t)


        // LOG IN
        .displayText('Log In').wait(500)
        .addFunction(function (next) {
            commonSM.commonLogin(t, next); }).wait(100)
        .waitTillMainMenuLoaded('Login Successful').wait(500)

        .expandMenu('Inventory').wait(500)
        .markSuccess('Inventory successfully expanded').wait(300)
        .openScreen('Storage Locations').wait(200)
        .waitTillLoaded('Open Storage Locations Search Screen Successful').wait(200)



        //#1 Allow bin of the same name to be used in a different Sub Location.
        .displayText('====== Scenario 1. Allow bin of the same name to be used in a different Sub Location ======').wait(300)
        .clickButton('#btnNew').wait(200)
        .waitTillVisible('icstorageunit','Open Inventory UOM  Successful').wait(200)
        .checkScreenShown('icstorageunit').wait(200)
        .enterData('#txtName','Test SL - SH - 001').wait(100)
        .enterData('#txtDescription','Test SL - SH - 001').wait(100)
        .selectComboRowByFilter('#cboUnitType','Bin',300, 'strStorageUnitType').wait(100)
        .selectComboRowByFilter('#cboLocation','0001 - Fort Wayne',300, 'intLocationId').wait(100)
        .selectComboRowByFilter('#cboSubLocation','Stellhorn',300, 'intSubLocationId').wait(100)
        .selectComboRowByFilter('#cboParentUnit','RM Storage',300, 'intParentStorageLocationId').wait(100)
        .enterData('#txtAisle','Test Aisle').wait(100)
        .clickCheckBox('#chkAllowConsume',true).wait(100)
        .clickCheckBox('#chkAllowMultipleItems',true).wait(100)
        .clickCheckBox('#chkAllowMultipleLots',true).wait(100)
        .clickCheckBox('#chkMergeOnMove',true).wait(100)
        .clickCheckBox('#chkCycleCounted',true).wait(100)
        .clickCheckBox('#chkDefaultWarehouseStagingUnit',true).wait(100)
        .checkStatusMessage('Edited').wait(100)
        .clickButton('#btnSave').wait(100)
        .checkStatusMessage('Saved').wait(100)
        .clickButton('#btnClose').wait(100)
        .checkIfScreenClosed('icstorageunit').wait(100)
        .markSuccess('====== Allow bin of the same name to be used in a different Sub Location Successful ======').wait(200)

        // #2  Allow bin of the same name to be used in a different Sub Location
        .displayText('====== Scenario 2. Allow bin of the same name to be used in a different Sub Location ======').wait(300)
        .clickButton('#btnNew').wait(200)
        .waitTillVisible('icstorageunit','Open Inventory UOM  Successful').wait(200)
        .checkScreenShown('icstorageunit').wait(200)
        .enterData('#txtName','Test SL - SH - 001').wait(100)
        .enterData('#txtDescription','Test SL - SH - 001').wait(100)
        .selectComboRowByFilter('#cboUnitType','Bin',300, 'strStorageUnitType').wait(100)
        .selectComboRowByFilter('#cboLocation','0001 - Fort Wayne',300, 'intLocationId').wait(100)
        .selectComboRowByFilter('#cboSubLocation','FG Station',300, 'intSubLocationId').wait(100)
        .selectComboRowByFilter('#cboParentUnit','RM Storage',300, 'intParentStorageLocationId').wait(100)
        .enterData('#txtAisle','Test Aisle').wait(100)
        .clickCheckBox('#chkAllowConsume',true).wait(100)
        .clickCheckBox('#chkAllowMultipleItems',true).wait(100)
        .clickCheckBox('#chkAllowMultipleLots',true).wait(100)
        .clickCheckBox('#chkMergeOnMove',true).wait(100)
        .clickCheckBox('#chkCycleCounted',true).wait(100)
        .clickCheckBox('#chkDefaultWarehouseStagingUnit',true).wait(100)
        .checkStatusMessage('Edited').wait(100)
        .clickButton('#btnSave').wait(100)
        .checkStatusMessage('Saved').wait(100)
        .clickButton('#btnClose').wait(100)
        .checkIfScreenClosed('icstorageunit')
        .markSuccess('====== Allow bin of the same name to be used in a different Sub Location Successful ======').wait(200)


        //#3 Allow bin of the same name to be used in a different Sub Location
        .displayText('====== Scenario 3. Allow bin of the same name to be used in a different Sub Location ======').wait(300)
        .clickButton('#btnNew').wait(100)
        .waitTillVisible('icstorageunit','Open Inventory UOM  Successful').wait(200)
        .checkScreenShown('icstorageunit').wait(200)
        .enterData('#txtName','Test SL - SH - 002').wait(100)
        .enterData('#txtDescription','Test SL - SH - 002').wait(100)
        .selectComboRowByFilter('#cboUnitType','Bin',300, 'strStorageUnitType').wait(100)
        .selectComboRowByFilter('#cboLocation','0001 - Fort Wayne',300, 'intLocationId').wait(100)
        .selectComboRowByFilter('#cboSubLocation','Stellhorn',300, 'intSubLocationId').wait(100)
        .selectComboRowByFilter('#cboParentUnit','RM Storage',300, 'intParentStorageLocationId').wait(100)
        .enterData('#txtAisle','Test Aisle').wait(100)
        .clickCheckBox('#chkAllowConsume',true).wait(100)
        .clickCheckBox('#chkAllowMultipleItems',true).wait(100)
        .clickCheckBox('#chkAllowMultipleLots',true).wait(100)
        .clickCheckBox('#chkMergeOnMove',true).wait(100)
        .clickCheckBox('#chkCycleCounted',true).wait(100)
        .clickCheckBox('#chkDefaultWarehouseStagingUnit',true).wait(100)
        .checkStatusMessage('Edited').wait(100)
        .clickButton('#btnSave').wait(100)
        .checkStatusMessage('Saved').wait(100)
        .clickButton('#btnClose').wait(100)
        .checkIfScreenClosed('icstorageunit')
        .markSuccess('====== Allow bin of the same name to be used in a different Sub Location Successful ======').wait(200)


        //#4 Allow bin of the same name to be used in a different Location
        .displayText('====== Scenario 3.Allow bin of the same name to be used in a different Location ======').wait(300)
        .clickButton('#btnNew').wait(200)
        .waitTillVisible('icstorageunit','Open Inventory UOM  Successful').wait(200)
        .checkScreenShown('icstorageunit').wait(200)
        .enterData('#txtName','Test SL - SH - 002').wait(100)
        .enterData('#txtDescription','Test SL - SH - 002').wait(100)
        .selectComboRowByFilter('#cboUnitType','Bin',300, 'strStorageUnitType').wait(100)
        .selectComboRowByFilter('#cboLocation','0002 - Indianapolis',300, 'intLocationId').wait(100)
        .selectComboRowByFilter('#cboSubLocation','Indy',300, 'intSubLocationId').wait(100)
        .selectComboRowByFilter('#cboParentUnit','RM Storage',300, 'intParentStorageLocationId').wait(100)
        .enterData('#txtAisle','Test Aisle').wait(100)
        .clickCheckBox('#chkAllowConsume',true).wait(100)
        .clickCheckBox('#chkAllowMultipleItems',true).wait(100)
        .clickCheckBox('#chkAllowMultipleLots',true).wait(100)
        .clickCheckBox('#chkMergeOnMove',true).wait(100)
        .clickCheckBox('#chkCycleCounted',true).wait(100)
        .clickCheckBox('#chkDefaultWarehouseStagingUnit',true).wait(100)
        .checkStatusMessage('Edited').wait(100)
        .clickButton('#btnSave').wait(100)
        .checkStatusMessage('Saved').wait(100)
        .clickButton('#btnClose').wait(100)
        .checkIfScreenClosed('icstorageunit').wait(200)
        .markSuccess('====== Allow bin of the same name to be used in a different Location  Successful ======').wait(200)


        //#5 Allow bin of the same name to be used in a different Location
        .displayText('====== Scenario 5. Add Duplicate Storage Location ======').wait(300)
        .clickButton('#btnNew').wait(100)
        .waitTillVisible('icstorageunit','Open Inventory UOM  Successful').wait(200)
        .checkScreenShown('icstorageunit').wait(200)
        .enterData('#txtName','Test SL - SH - 001').wait(100)
        .enterData('#txtDescription','Test SL - SH - 001').wait(100)
        .selectComboRowByFilter('#cboUnitType','Bin',300, 'strStorageUnitType').wait(100)
        .selectComboRowByFilter('#cboLocation','0001 - Fort Wayne',300, 'intLocationId').wait(100)
        .selectComboRowByFilter('#cboSubLocation','Stellhorn',300, 'intSubLocationId').wait(100)
        .selectComboRowByFilter('#cboParentUnit','RM Storage',300, 'intParentStorageLocationId').wait(100)
        .enterData('#txtAisle','Test Aisle').wait(100)
        .clickCheckBox('#chkAllowConsume',true).wait(100)
        .clickCheckBox('#chkAllowMultipleItems',true).wait(100)
        .clickCheckBox('#chkAllowMultipleLots',true).wait(100)
        .clickCheckBox('#chkMergeOnMove',true).wait(100)
        .clickCheckBox('#chkCycleCounted',true).wait(100)
        .clickCheckBox('#chkDefaultWarehouseStagingUnit',true).wait(100)
        .checkStatusMessage('Edited').wait(100)
        .clickButton('#btnSave').wait(100)
        .checkMessageBox('iRely i21', 'Storage Location must be unique per Location and Sub Location.', 'ok', 'error').wait(100)
        .clickMessageBoxButton('ok').wait(100)
        .clickButton('#btnClose').wait(100)
        .checkIfScreenClosed('icstorageunit').wait(200)
        .markSuccess('====== Add Duplicate Storage Location Was Not Successful ======').wait(200)


        .done()
});

