CREATE TABLE [dbo].[tblSTstgRebatesRJReynolds]
(
	[intRJRId] int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[strOutletName] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	[intOutletNumber] int NULL,
	[strOutletAddressOne] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	[strOutletAddressTwo] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	[strOutletCity] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	[strOutletState] nvarchar(2) COLLATE Latin1_General_CI_AS NULL,
	[strOutletZipCode] nvarchar(5) COLLATE Latin1_General_CI_AS NULL,
	[strTransactionDateTime] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	[strMarketBasketTransactionId] nvarchar(300) COLLATE Latin1_General_CI_AS NULL,
	[strScanTransactionId] nvarchar(300) COLLATE Latin1_General_CI_AS NULL,
	[strRegisterId] nvarchar(300) COLLATE Latin1_General_CI_AS NULL,
	[intQuantity] int NULL,
	[dblPrice] decimal(18, 6) NULL,
	[strUpcCode] nvarchar(14) COLLATE Latin1_General_CI_AS NULL,
	[strUpcDescription] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	[strUnitOfMeasure] nvarchar(10) COLLATE Latin1_General_CI_AS NULL,
	[strPromotionFlag] nvarchar(1) COLLATE Latin1_General_CI_AS NULL,
	[strOutletMultipackFlag] nvarchar(1) COLLATE Latin1_General_CI_AS NULL,
	[intOutletMultipackQuantity] int NULL,
	[dblOutletMultipackDiscountAmount] decimal(18, 6) NULL,
	[strAccountPromotionName] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	[dblAccountDiscountAmount] decimal(18, 6) NULL,
	[dblManufacturerDiscountAmount] decimal(18, 6) NULL,
	[strCouponPid] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,
	[dblCouponAmount] decimal(18, 6) NULL,

	[strManufacturerMultipackFlag] nvarchar(1) COLLATE Latin1_General_CI_AS NULL,
	[intManufacturerMultipackQuantity] int NULL,
	[dblManufacturerMultipackDiscountAmount] decimal(18, 6) NULL,
	[strManufacturerPromotionDescription] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	[strManufacturerBuydownDescription] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	[dblManufacturerBuydownAmount] decimal(18, 6) NULL,
	[strManufacturerMultiPackDescription] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	[strAccountLoyaltyIDNumber] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	[strCouponDescription] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
)