PRINT N'EM COMPANY PREFERENCE DEFAULT DATA - START'

IF NOT EXISTS(SELECT TOP 1 1 FROM tblEMCompanyPreference)
BEGIN
	INSERT INTO tblEMCompanyPreference(ysnShowInternationalInformation)
	VALUES(0)
END

PRINT N'EM COMPANY PREFERENCE DEFAULT DATA - END'


