CREATE PROCEDURE [testi21Database].[Fake posted Bill]
(
	@posted BIT = 0
	,@addDetail BIT = 1
	,@enableConstraints BIT = 0
)
AS

EXEC tSQLt.FakeTable 'dbo.tblAPBill', @Identity=1, @Defaults = @enableConstraints;

IF(@addDetail = 1)
BEGIN
	EXEC tSQLt.FakeTable 'dbo.tblAPBillDetail', @Identity=1, @Defaults = @enableConstraints;
END

INSERT INTO tblAPBill(
	[intBillBatchId]				,
    [strVendorOrderNumber]			,
    [intTermsId]           			,
    [intTransactionReversed]		,
    [dtmDate]              			,
    [dtmDueDate]           			,
    [intAccountId]         			,
    [strReference]					,
	[strApprovalNotes]     			,
	[strComment]					,
    [dblTotal]             			,
	[dblSubtotal]          			,
    [ysnPosted]            			,
    [ysnPaid]              			,
    [strBillId]            			,
    [dblAmountDue]         			,
    [dtmDatePaid]          			,
	[dtmApprovalDate]      			,
    [dtmDiscountDate]      			,
    [intUserId]            			,
    [intConcurrencyId]  			,
    [dtmBillDate] 					,
    [intEntityId] 					,
    [intEntityVendorId] 			,
    [dblWithheld] 					,
    [dblDiscount] 					,
	[dblBillTax] 					,
	[dblPayment] 					,
	[dblInterest] 					,
    [intTransactionType] 			,
    [intPurchaseOrderId] 			,
	[strPONumber] 					,
	[strShipToAttention] 			,
	[strShipToAddress] 				,
	[strShipToCity] 				,
	[strShipToState] 				,
	[strShipToZipCode] 				,
	[strShipToCountry] 				,
	[strShipToPhone] 				,
	[strShipFromAttention] 			,
	[strShipFromAddress] 			,
	[strShipFromCity] 				,
	[strShipFromState] 				,
	[strShipFromZipCode] 			,
	[strShipFromCountry] 			,
	[strShipFromPhone] 				,
    [intShipFromId] 				,
	[intShipToId] 					,
	[intShipViaId]					,
    [intStoreLocationId] 			,
    [intContactId] 					,
    [intOrderById] 					,
    [intCurrencyId]					,
	[ysnApproved] 					,
	[ysnForApproval] 				,
    [ysnOrigin] 					,
	[ysnDeleted]					,
	[dtmDateDeleted] 				,
    [dtmDateCreated] 
)
SELECT
	[intBillBatchId]				=	NULL,
    [strVendorOrderNumber]			=	'Vendor Order Number',
    [intTermsId]           			=	1,
    [intTransactionReversed]			1,
    [dtmDate]              			,
    [dtmDueDate]           			,
    [intAccountId]         			,
    [strReference]					,
	[strApprovalNotes]     			,
	[strComment]					,
    [dblTotal]             			,
	[dblSubtotal]          			,
    [ysnPosted]            			,
    [ysnPaid]              			,
    [strBillId]            			,
    [dblAmountDue]         			,
    [dtmDatePaid]          			,
	[dtmApprovalDate]      			,
    [dtmDiscountDate]      			,
    [intUserId]            			,
    [intConcurrencyId]  			,
    [dtmBillDate] 					,
    [intEntityId] 					,
    [intEntityVendorId] 			,
    [dblWithheld] 					,
    [dblDiscount] 					,
	[dblBillTax] 					,
	[dblPayment] 					,
	[dblInterest] 					,
    [intTransactionType] 			,
    [intPurchaseOrderId] 			,
	[strPONumber] 					,
	[strShipToAttention] 			,
	[strShipToAddress] 				,
	[strShipToCity] 				,
	[strShipToState] 				,
	[strShipToZipCode] 				,
	[strShipToCountry] 				,
	[strShipToPhone] 				,
	[strShipFromAttention] 			,
	[strShipFromAddress] 			,
	[strShipFromCity] 				,
	[strShipFromState] 				,
	[strShipFromZipCode] 			,
	[strShipFromCountry] 			,
	[strShipFromPhone] 				,
    [intShipFromId] 				,
	[intShipToId] 					,
	[intShipViaId]					,
    [intStoreLocationId] 			,
    [intContactId] 					,
    [intOrderById] 					,
    [intCurrencyId]					,
	[ysnApproved] 					,
	[ysnForApproval] 				,
    [ysnOrigin] 					,
	[ysnDeleted]					,
	[dtmDateDeleted] 				,
    [dtmDateCreated] 
VALUES
(NULL, N'uhaa', 4, 0, CAST(N'2015-07-17 00:00:00.000' AS DateTime), CAST(N'2015-05-02 00:00:00.000' AS DateTime), 9597, N'', N'', NULL, CAST(100.000000 AS Decimal(18, 6)), CAST(100.000000 AS Decimal(18, 6)), 1, 0, N'BL-13170', CAST(100.000000 AS Decimal(18, 6)), NULL, NULL, NULL, 0, 1, CAST(N'2015-04-17 00:00:00.000' AS DateTime), 1059, 653, CAST(0.000000 AS Decimal(18, 6)), CAST(1.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), 1, NULL, N'', N'', N'4242 Flagstaff Cove', N'Fort Wayne', N'IN', N'46815', N'United States', N'8004335724', N'', N'Association
318 Susan Dr', N'Normal              ', N'IL', N'61761     ', N'United States', N'', 327, 1, NULL, 1, 654, 1059, 3, 0, 0, 0, 0, NULL, CAST(N'2015-07-16 17:28:53.567' AS DateTime), NULL)

INSERT INTO tblAPBillDetail
(
	[intBillId]						,
	[strMiscDescription]			,
	[strComment]					,
	[intAccountId]					,
	[intItemId]						,
	[intInventoryReceiptItemId]		,
	[intPurchaseDetailId]			,
	[intContractHeaderId]			,
	[intContractDetailId]			,
	[intPrepayTypeId]				,
	[dblTotal]						,
	[intConcurrencyId]				,
	[dblQtyOrdered]					,
	[dblQtyReceived]				,
	[dblDiscount]					,
	[dblCost]						,
	[dblLandedCost]					,
	[dblPrepayPercentage]			,
	[dblWeight]						,
	[dblVolume]						,
	[dtmExpectedDate]				,
	[int1099Code]					,
	[int1099Category]				,
	[intTaxId]						,
	[intLineNo]						
)
VALUES
(26678, 35768, N'Test', N'', 11488, NULL, NULL, NULL, NULL, NULL, NULL, CAST(100.000000 AS Decimal(18, 6)), 1, CAST(1.000000 AS Decimal(18, 6)), CAST(1.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), CAST(100.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), CAST(0.000000 AS Decimal(18, 6)), CAST(N'2015-07-17 01:21:49.000' AS DateTime), NULL, NULL, 0, 1)