CREATE TABLE [dbo].[tblPATTransferDetail]
(
	[intTransferDetailId] INT NOT NULL IDENTITY, 
    [intTransferId] INT NULL, 
    [intTransferorId] INT NULL,
	[strEquityType] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[intFiscalYearId] INT NULL,
	[intRefundTypeId] INT NULL,
	[dblParValue] NUMERIC(18,6) NULL,
	[intCustomerStockId] INT NULL,
	[intPatronageCategoryId] INT NULL,
	[intCustomerVolumeId] INT NULL,
	[intCustomerEquityId] INT NULL,
	[dblQuantityAvailable] NUMERIC(18,6) NULL,
    [intTransfereeId] INT NULL, 
	[intToCustomerVolumeId] INT NULL,
	[intToCustomerEquityId] INT NULL,
    [intToFiscalYearId] INT NULL,
	[intToRefundTypeId] INT NULL,
	[dblTransferPercentage] NUMERIC(18,6) NULL,
	[intToStockId] INT NULL,
	[strToCertificateNo] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[strToStockStatus] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[dtmToIssueDate] DATETIME NULL,
	[dblToParValue] NUMERIC(18,6) NULL,
    [dblQuantityTransferred] DECIMAL(18, 6) NULL, 
    [intConcurrencyId] INT NULL DEFAULT 0, 
    CONSTRAINT [PK_tblPATTransferDetail] PRIMARY KEY ([intTransferDetailId]),
	CONSTRAINT [FK_tblPATTransferDetail_tblPATTransfer] FOREIGN KEY ([intTransferId]) REFERENCES [tblPATTransfer]([intTransferId]) ON DELETE CASCADE
)