CREATE TABLE [dbo].[glragmst] (
    [glrag_grid_id]     CHAR (20)      NOT NULL,
    [glrag_desc]        CHAR (30)      NOT NULL,
    [glrag_acct1_8_1]   INT            NULL,
    [glrag_acct1_8_2]   INT            NULL,
    [glrag_acct1_8_3]   INT            NULL,
    [glrag_acct1_8_4]   INT            NULL,
    [glrag_acct1_8_5]   INT            NULL,
    [glrag_acct1_8_6]   INT            NULL,
    [glrag_acct1_8_7]   INT            NULL,
    [glrag_acct1_8_8]   INT            NULL,
    [glrag_acct1_8_9]   INT            NULL,
    [glrag_acct1_8_10]  INT            NULL,
    [glrag_acct1_8_11]  INT            NULL,
    [glrag_acct1_8_12]  INT            NULL,
    [glrag_acct1_8_13]  INT            NULL,
    [glrag_acct1_8_14]  INT            NULL,
    [glrag_acct1_8_15]  INT            NULL,
    [glrag_acct1_8_16]  INT            NULL,
    [glrag_acct1_8_17]  INT            NULL,
    [glrag_acct1_8_18]  INT            NULL,
    [glrag_acct1_8_19]  INT            NULL,
    [glrag_acct1_8_20]  INT            NULL,
    [glrag_acct1_8_21]  INT            NULL,
    [glrag_acct1_8_22]  INT            NULL,
    [glrag_acct1_8_23]  INT            NULL,
    [glrag_acct1_8_24]  INT            NULL,
    [glrag_acct1_8_25]  INT            NULL,
    [glrag_acct1_8_26]  INT            NULL,
    [glrag_acct1_8_27]  INT            NULL,
    [glrag_acct1_8_28]  INT            NULL,
    [glrag_acct1_8_29]  INT            NULL,
    [glrag_acct1_8_30]  INT            NULL,
    [glrag_acct1_8_31]  INT            NULL,
    [glrag_acct1_8_32]  INT            NULL,
    [glrag_acct1_8_33]  INT            NULL,
    [glrag_acct1_8_34]  INT            NULL,
    [glrag_acct1_8_35]  INT            NULL,
    [glrag_acct1_8_36]  INT            NULL,
    [glrag_acct1_8_37]  INT            NULL,
    [glrag_acct1_8_38]  INT            NULL,
    [glrag_acct1_8_39]  INT            NULL,
    [glrag_acct1_8_40]  INT            NULL,
    [glrag_acct1_8_41]  INT            NULL,
    [glrag_acct1_8_42]  INT            NULL,
    [glrag_acct1_8_43]  INT            NULL,
    [glrag_acct1_8_44]  INT            NULL,
    [glrag_acct1_8_45]  INT            NULL,
    [glrag_acct1_8_46]  INT            NULL,
    [glrag_acct1_8_47]  INT            NULL,
    [glrag_acct1_8_48]  INT            NULL,
    [glrag_acct1_8_49]  INT            NULL,
    [glrag_acct1_8_50]  INT            NULL,
    [glrag_acct9_16_1]  INT            NULL,
    [glrag_acct9_16_2]  INT            NULL,
    [glrag_acct9_16_3]  INT            NULL,
    [glrag_acct9_16_4]  INT            NULL,
    [glrag_acct9_16_5]  INT            NULL,
    [glrag_acct9_16_6]  INT            NULL,
    [glrag_acct9_16_7]  INT            NULL,
    [glrag_acct9_16_8]  INT            NULL,
    [glrag_acct9_16_9]  INT            NULL,
    [glrag_acct9_16_10] INT            NULL,
    [glrag_acct9_16_11] INT            NULL,
    [glrag_acct9_16_12] INT            NULL,
    [glrag_acct9_16_13] INT            NULL,
    [glrag_acct9_16_14] INT            NULL,
    [glrag_acct9_16_15] INT            NULL,
    [glrag_acct9_16_16] INT            NULL,
    [glrag_acct9_16_17] INT            NULL,
    [glrag_acct9_16_18] INT            NULL,
    [glrag_acct9_16_19] INT            NULL,
    [glrag_acct9_16_20] INT            NULL,
    [glrag_acct9_16_21] INT            NULL,
    [glrag_acct9_16_22] INT            NULL,
    [glrag_acct9_16_23] INT            NULL,
    [glrag_acct9_16_24] INT            NULL,
    [glrag_acct9_16_25] INT            NULL,
    [glrag_acct9_16_26] INT            NULL,
    [glrag_acct9_16_27] INT            NULL,
    [glrag_acct9_16_28] INT            NULL,
    [glrag_acct9_16_29] INT            NULL,
    [glrag_acct9_16_30] INT            NULL,
    [glrag_acct9_16_31] INT            NULL,
    [glrag_acct9_16_32] INT            NULL,
    [glrag_acct9_16_33] INT            NULL,
    [glrag_acct9_16_34] INT            NULL,
    [glrag_acct9_16_35] INT            NULL,
    [glrag_acct9_16_36] INT            NULL,
    [glrag_acct9_16_37] INT            NULL,
    [glrag_acct9_16_38] INT            NULL,
    [glrag_acct9_16_39] INT            NULL,
    [glrag_acct9_16_40] INT            NULL,
    [glrag_acct9_16_41] INT            NULL,
    [glrag_acct9_16_42] INT            NULL,
    [glrag_acct9_16_43] INT            NULL,
    [glrag_acct9_16_44] INT            NULL,
    [glrag_acct9_16_45] INT            NULL,
    [glrag_acct9_16_46] INT            NULL,
    [glrag_acct9_16_47] INT            NULL,
    [glrag_acct9_16_48] INT            NULL,
    [glrag_acct9_16_49] INT            NULL,
    [glrag_acct9_16_50] INT            NULL,
    [glrag_pct_1]       DECIMAL (9, 6) NULL,
    [glrag_pct_2]       DECIMAL (9, 6) NULL,
    [glrag_pct_3]       DECIMAL (9, 6) NULL,
    [glrag_pct_4]       DECIMAL (9, 6) NULL,
    [glrag_pct_5]       DECIMAL (9, 6) NULL,
    [glrag_pct_6]       DECIMAL (9, 6) NULL,
    [glrag_pct_7]       DECIMAL (9, 6) NULL,
    [glrag_pct_8]       DECIMAL (9, 6) NULL,
    [glrag_pct_9]       DECIMAL (9, 6) NULL,
    [glrag_pct_10]      DECIMAL (9, 6) NULL,
    [glrag_pct_11]      DECIMAL (9, 6) NULL,
    [glrag_pct_12]      DECIMAL (9, 6) NULL,
    [glrag_pct_13]      DECIMAL (9, 6) NULL,
    [glrag_pct_14]      DECIMAL (9, 6) NULL,
    [glrag_pct_15]      DECIMAL (9, 6) NULL,
    [glrag_pct_16]      DECIMAL (9, 6) NULL,
    [glrag_pct_17]      DECIMAL (9, 6) NULL,
    [glrag_pct_18]      DECIMAL (9, 6) NULL,
    [glrag_pct_19]      DECIMAL (9, 6) NULL,
    [glrag_pct_20]      DECIMAL (9, 6) NULL,
    [glrag_pct_21]      DECIMAL (9, 6) NULL,
    [glrag_pct_22]      DECIMAL (9, 6) NULL,
    [glrag_pct_23]      DECIMAL (9, 6) NULL,
    [glrag_pct_24]      DECIMAL (9, 6) NULL,
    [glrag_pct_25]      DECIMAL (9, 6) NULL,
    [glrag_pct_26]      DECIMAL (9, 6) NULL,
    [glrag_pct_27]      DECIMAL (9, 6) NULL,
    [glrag_pct_28]      DECIMAL (9, 6) NULL,
    [glrag_pct_29]      DECIMAL (9, 6) NULL,
    [glrag_pct_30]      DECIMAL (9, 6) NULL,
    [glrag_pct_31]      DECIMAL (9, 6) NULL,
    [glrag_pct_32]      DECIMAL (9, 6) NULL,
    [glrag_pct_33]      DECIMAL (9, 6) NULL,
    [glrag_pct_34]      DECIMAL (9, 6) NULL,
    [glrag_pct_35]      DECIMAL (9, 6) NULL,
    [glrag_pct_36]      DECIMAL (9, 6) NULL,
    [glrag_pct_37]      DECIMAL (9, 6) NULL,
    [glrag_pct_38]      DECIMAL (9, 6) NULL,
    [glrag_pct_39]      DECIMAL (9, 6) NULL,
    [glrag_pct_40]      DECIMAL (9, 6) NULL,
    [glrag_pct_41]      DECIMAL (9, 6) NULL,
    [glrag_pct_42]      DECIMAL (9, 6) NULL,
    [glrag_pct_43]      DECIMAL (9, 6) NULL,
    [glrag_pct_44]      DECIMAL (9, 6) NULL,
    [glrag_pct_45]      DECIMAL (9, 6) NULL,
    [glrag_pct_46]      DECIMAL (9, 6) NULL,
    [glrag_pct_47]      DECIMAL (9, 6) NULL,
    [glrag_pct_48]      DECIMAL (9, 6) NULL,
    [glrag_pct_49]      DECIMAL (9, 6) NULL,
    [glrag_pct_50]      DECIMAL (9, 6) NULL,
    [glrag_percent_amt] SMALLINT       NULL,
    [glrag_user_id]     CHAR (16)      NULL,
    [glrag_user_rev_dt] INT            NULL,
    [A4GLIdentity]      NUMERIC (9)    IDENTITY (1, 1) NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [Iglragmst0]
    ON [dbo].[glragmst]([glrag_grid_id] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [Iglragmst1]
    ON [dbo].[glragmst]([glrag_desc] ASC, [glrag_grid_id] ASC);

