CREATE TABLE [dbo].[tblAPImportVoucherSupplierInvoice]
(
	[intSaleYear] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strSubBook] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strSaleNo] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[strCatalogueType] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strVendorId] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[strChannel] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strInvoiceNumber] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[strBook] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[dtmDate] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[dtmExpectedDate] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strBrokerageRate] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strSalesTaxCode] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strTaxPercentage] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strStampDuty] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strSurchargePercentage] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strIsBrokerageApplicable] NVARCHAR (10) COLLATE Latin1_General_CI_AS NULL,
	[strIsSalesTaxApplicable] NVARCHAR (10) COLLATE Latin1_General_CI_AS NULL,
	[dtmSaleDate] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strLotNumber] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[dblCost] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[dblQtyReceived] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strPackageBreakups] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strPreInvoiceGarden] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[strPreInvoiceGrade] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[strPreInvoiceGardenNumber] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[strPurchaseType] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[strDocumentNumber] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[dblWeightBreakup1] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[dblWeightBreakup1Bags] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
	[dblWeightBreakup2] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[dblWeightBreakup2Bags] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[dblWeightBreakup3] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[dblWeightBreakup3Bags] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[dblWeightBreakup4] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[dblWeightBreakup4Bags] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[dblWeightBreakup5] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[dblWeightBreakup5Bags] NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL, 
	[strStorageLocation] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL
)

