CREATE TABLE tblApiSchemaEmployee(
    guiApiUniqueId UNIQUEIDENTIFIER NOT NULL,
    intRowNumber INT NULL,
    intKey INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    strEmployeeId NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strName NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strContactNumber NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strSuffix NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPhone NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strClass NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strLocationName NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPrintedName NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPhone NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strEmail NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strAdress NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strCity NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strState NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strZipCode NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strCountry NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strTimezone NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDocumentDelivery1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDocumentDelivery2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDocumentDelivery3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strExternalERPId NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dtmOriginationDate [datetime] NULL,
    strLineOfBusiness1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strLineOfBusiness2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strLineOfBusiness3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strLineOfBusiness4 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strLineOfBusiness5 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strFirstName NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strMiddleName NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
	strLastName NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
	strNameSuffix NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,	
    strTitle NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strType NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPayPeriod NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strRank NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dtmReviewDate [datetime] NULL,
    dtmNextReview [datetime] NULL,
    strTimeEntryPassword NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strEmergencyContact NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strEmergencyRelation NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strEmergencyPhone NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strEmergencyPhone2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dtmBirthDate [datetime] NULL,
    ysnActive NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dtmOriginalDateHired [datetime] NULL,
    strGender NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dtmDateHired [datetime] NULL,
    strSpouse NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strMaritalStatus NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strWorkPhone NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    intWorkersCompensationId,
    strEthnicity NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strEEOCCode NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strSocialSecurity NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dtmTerminated [datetime] NULL,
    strTerminatedReason NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    ysn1099Employee NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strSupervisorId1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL, 
    strSupervisorName1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL, 
    strSupervisorId2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL, 
    strSupervisorName2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL, 
    strSupervisorId3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL, 
    strSupervisorName3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL, 
    strDepartment1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDepartmentDesc1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDepartment2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDepartmentDesc2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDepartment3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDepartmentDesc3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strGlLocationDistributionLocation1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dblGlLocationDistributionPercent1 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strGlLocationDistributionLocation2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dblGlLocationDistributionPercent2 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strGlLocationDistributionLocation3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    dblGlLocationDistributionPercent3 NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    ysnStatutoryEmployee NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    ysnThirdPartySickPay NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    ysnRetirementPlan NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL

)