CREATE TABLE [dbo].[tblARSalesTrendStagingTable]
(
	[intYear]				    INT NULL,
    [intMonth]				    INT NULL,
    [dtmTransactionDate]		DATETIME NULL,
    [dtmTransactionDateEnding]	DATETIME NULL,
    [intEntityCustomerId]       INT NULL,
    [intCompanyLocationId]		INT NULL,
    [strName]			        NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strCustomerName]			NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strCustomerNumber]			NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [intSourceId]		        INT NULL, 
    [strInvoiceOriginId]	    NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [intItemId]			        INT NULL,
    [strItemNo]			        NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strDescription]			NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [intCategoryId]			    INT NULL,
    [strCategoryCode]		    NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strCategoryDescription]	NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strSalesPersonEntityNo]	NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strSalesPersonName]		NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [intSalesPersonId]			INT NULL,
    [dblSalesAmount]			NUMERIC(18, 6) NULL,
    [dblQuantity]				NUMERIC(18, 6) NULL,
    [dblBeginSalesAmount]		NUMERIC(18, 6) NULL,
    [dblBeginQuantity]			NUMERIC(18, 6) NULL,
    [dblEndSalesAmount]			NUMERIC(18, 6) NULL,
    [dblEndQuantity]			NUMERIC(18, 6) NULL,
    [dtmBeginDate]				DATETIME NULL,
    [dtmEndingDate]				DATETIME NULL,
    [dblCost]				    NUMERIC(18, 6) NULL,
    [strAccountStatusCode]		NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strSource]		            NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strLocationName]		    NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strCompanyName]		    NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strCompanyAddress]		    NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [dblJanuary]				NUMERIC(18, 6) NULL,
    [dblFebruary]				NUMERIC(18, 6) NULL,
    [dblMarch]				    NUMERIC(18, 6) NULL,
    [dblApril]				    NUMERIC(18, 6) NULL,
    [dblMay]				    NUMERIC(18, 6) NULL,
    [dblJune]				    NUMERIC(18, 6) NULL,
    [dblJuly]				    NUMERIC(18, 6) NULL,
    [dblAugust]				    NUMERIC(18, 6) NULL,
    [dblSeptember]				NUMERIC(18, 6) NULL,
    [dblOctober]				NUMERIC(18, 6) NULL,
    [dblNovember]				NUMERIC(18, 6) NULL,
    [dblDecember]				NUMERIC(18, 6) NULL,
    [dblSalesJanuary]			NUMERIC(18, 6) NULL,
    [dblSalesFebruary]			NUMERIC(18, 6) NULL,
    [dblSalesMarch]				NUMERIC(18, 6) NULL,
    [dblSalesApril]				NUMERIC(18, 6) NULL,
    [dblSalesMay]				NUMERIC(18, 6) NULL,
    [dblSalesJune]				NUMERIC(18, 6) NULL,
    [dblSalesJuly]				NUMERIC(18, 6) NULL,
    [dblSalesAugust]			NUMERIC(18, 6) NULL,
    [dblSalesSeptember]			NUMERIC(18, 6) NULL,
    [dblSalesOctober]			NUMERIC(18, 6) NULL,
    [dblSalesNovember]			NUMERIC(18, 6) NULL,
    [dblSalesDecember]			NUMERIC(18, 6) NULL,
    [strMonth]		            NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[strLogoType]				NVARCHAR (10) COLLATE Latin1_General_CI_AS NULL,
    [blbLogo]			        VARBINARY(MAX) NULL
)