CREATE TABLE [dbo].[tblAPProvisional] (
    [intBillId]            INT             IDENTITY (1, 1) NOT NULL,
    [intBillBatchId]       INT             NULL ,
    [strVendorOrderNumber] NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [intTermsId]           INT             NOT NULL DEFAULT 0,
    [intTransactionReversed]				INT             NULL ,
	[intCommodityId]				INT             NULL ,
	[intInvoiceRefId]				INT             NULL ,
	[intCompanyId]				INT             NULL ,
	[intBankInfoId]				INT             NULL ,
	[intBookId]	INT NULL,
	[intSubBookId] INT NULL,
	[ysnPrepayHasPayment]				BIT             NOT NULL DEFAULT 0,
    [dtmDate]              DATETIME        NOT NULL DEFAULT GETDATE(),
    [dtmDueDate]           DATETIME        NOT NULL DEFAULT GETDATE(),
    [intAccountId]         INT             NULL ,
    [strReference]			NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
	[strTempPaymentInfo]			NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
	[strApprovalNotes]     NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
	[strRemarks]     NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
	[strComment]			NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [dblTotal]             DECIMAL (18, 6) NOT NULL DEFAULT 0,
	[dblTotalController]   DECIMAL (18, 6) NOT NULL DEFAULT 0,
	[dbl1099]             DECIMAL (18, 6) NOT NULL DEFAULT 0,
	[dblSubtotal]          DECIMAL (18, 6) NOT NULL DEFAULT 0,
    [ysnPosted]            BIT             NOT NULL DEFAULT 0,
    [ysnPaid]              BIT             NOT NULL DEFAULT 0,
	[ysnProcessedClaim]    BIT			   NOT NULL DEFAULT 0,
    [strBillId]            NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblAmountDue]         DECIMAL (18, 6) NOT NULL DEFAULT 0,
    [dtmDatePaid]          DATETIME        NULL ,
	[dtmApprovalDate]       DATETIME        NULL ,
    [dtmDiscountDate]      DATETIME        NULL,
	[dtmInterestDate]      DATETIME        NULL,
	[dtmDeferredInterestDate]      DATETIME        NULL,
	[dtmInterestAccruedThru]      DATETIME        NULL,
    [intUserId]            INT             NULL,
    [intConcurrencyId] INT NOT NULL DEFAULT 0, 
    [dtmBillDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [intEntityId] INT NOT NULL , 
    [intEntityVendorId] INT NOT NULL  , 
	[intShipFromEntityId] INT NOT NULL  , 
    [dblWithheld] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
	[dblTempWithheld] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
    [dblDiscount] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
	[dblTempDiscount] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
	[dblTax] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
	[dblPayment] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
	[dblTempPayment] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
	[dblInterest] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
	[dblTempInterest] DECIMAL(18, 6) NOT NULL DEFAULT 0,
    [intTransactionType] INT NOT NULL DEFAULT 0, 
    [intPurchaseOrderId] INT NULL,
	[strCreatedWith] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, -- Possible values: "IDP" which indicates that the bill was created through IDP, or null if created the usual way
	[strPONumber] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipToAttention] NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL, 
	[strShipToAddress] NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL, 
	[strShipToCity] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipToState] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipToZipCode] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipToCountry] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipToPhone] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipFromAttention] NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL, 
	[strShipFromAddress] NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL, 
	[strShipFromCity] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipFromState] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipFromZipCode] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipFromCountry] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
	[strShipFromPhone] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL, 
    [intShipFromId] INT NULL , 
	[intDeferredVoucherId] INT NULL , 
	[intPayToAddressId] INT NULL,
	[intVoucherDifference] INT NULL,
	[intShipToId] INT NULL , 
	[intShipViaId] INT NULL , 
    [intStoreLocationId] INT NULL , 
    [intContactId] INT NULL , 
    [intOrderById] INT NULL , 
    [intCurrencyId] INT NOT NULL,
	[intSubCurrencyCents] INT NOT NULL DEFAULT 1,
	[ysnApproved] BIT NOT NULL DEFAULT 0,
	[ysnForApproval] BIT NOT NULL DEFAULT 0,
    [ysnOrigin] BIT NOT NULL DEFAULT 0,
	[ysnDeleted] BIT NULL DEFAULT 0 ,
	[ysnIsPaymentScheduled] BIT NOT NULL DEFAULT 0 ,
	[ysnDiscountOverride] BIT NOT NULL DEFAULT 0,
	[ysnReadyForPayment] BIT NULL DEFAULT 0 ,
	[ysnRecurring] BIT NULL DEFAULT 0 ,
	[ysnExported] BIT NULL,
	[ysnForApprovalSubmitted] BIT NOT NULL DEFAULT 0 ,
	[ysnOldPrepayment] BIT NOT NULL DEFAULT 0 ,
	[dtmDateDeleted] DATETIME NULL,
	[dtmExportedDate] DATETIME NULL,
    [dtmDateCreated] DATETIME NULL DEFAULT GETDATE(), 
	[dblPaymentTemp] DECIMAL(18, 6) NOT NULL DEFAULT 0,
	[ysnInPayment] BIT NULL DEFAULT 0,
	[ysnOverrideCashFlow] BIT NULL DEFAULT 0,
	[dtmCashFlowDate] DATETIME NULL,
	--Payment Info
	[intDefaultPayFromBankAccountId] INT NULL,
	[strFinancingSourcedFrom] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[strFinancingTransactionNumber] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[ysnOverridePayFromBankAccount] BIT NULL DEFAULT 0,
	[intPayFromBankAccountId] INT NULL,
	[intPayToBankAccountId] INT NULL,
	--Trade Finance Info
	[strFinanceTradeNo] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[intBankId] INT NULL,
	[intBankAccountId] INT NULL,
	[intBorrowingFacilityId] INT NULL,
	[strBankReferenceNo] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[intBorrowingFacilityLimitId] INT NULL,
	[intBorrowingFacilityLimitDetailId] INT NULL,
	[strReferenceNo] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[intBankValuationRuleId] INT NULL,
	[intFreightTermId] INT NULL, 
	[strComments] NVARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
	[dblRoundingTotal] DECIMAL (18, 6) NOT NULL DEFAULT 0,
	[dblAverageExchangeRate] DECIMAL (18, 6) NULL
    CONSTRAINT [PK_dbo.tblAPProvisional] PRIMARY KEY CLUSTERED ([intBillId] ASC),
    -- CONSTRAINT [FK_dbo.tblAPBill_dbo.tblAPBillBatch_intBillBatchId] FOREIGN KEY ([intBillBatchId]) REFERENCES [dbo].[tblAPBillBatch] ([intBillBatchId]) ON DELETE CASCADE,
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblSMTerm_intTermId] FOREIGN KEY ([intTermsId]) REFERENCES [dbo].[tblSMTerm] ([intTermID]),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblEMEntity_intEntityId] FOREIGN KEY (intEntityId) REFERENCES tblEMEntity(intEntityId),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo_tblEMEntity_intContactId] FOREIGN KEY (intContactId) REFERENCES tblEMEntity(intEntityId),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblAPVendor_intVendorId] FOREIGN KEY ([intEntityVendorId]) REFERENCES tblAPVendor([intEntityId]),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblAPVendor_intShipFromEntityId] FOREIGN KEY ([intShipFromEntityId]) REFERENCES tblAPVendor([intEntityId]),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblGLAccount_intAccountId] FOREIGN KEY (intAccountId) REFERENCES tblGLAccount(intAccountId),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblSMCompanyLocation_intShipToId] FOREIGN KEY (intShipToId) REFERENCES tblSMCompanyLocation(intCompanyLocationId),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblEMEntityLocation_intShipFromId] FOREIGN KEY (intShipFromId) REFERENCES [tblEMEntityLocation](intEntityLocationId),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblSMShipVia_intShipViaId] FOREIGN KEY (intShipViaId) REFERENCES tblSMShipVia([intEntityId]),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblSMCurrency_intCurrencyID] FOREIGN KEY (intCurrencyId) REFERENCES tblSMCurrency(intCurrencyID),
	CONSTRAINT [FK_dbo.tblAPProvisional_dbo.tblEMEntityContact_intContactId] FOREIGN KEY (intContactId) REFERENCES tblEMEntity(intEntityId),
	CONSTRAINT [UK_dbo.tblAPProvisional_strBillId] UNIQUE (strBillId),

	CONSTRAINT [FK_tblAPProvisional_intBankInfoId] FOREIGN KEY ([intBankInfoId]) REFERENCES tblCMBankAccount([intBankAccountId]),
	CONSTRAINT [FK_tblAPProvisional_intPurchaseOrderId] FOREIGN KEY ([intPurchaseOrderId]) REFERENCES tblPOPurchase([intPurchaseId]),
	CONSTRAINT [FK_tblAPProvisional_intPayToAddressId] FOREIGN KEY ([intPayToAddressId]) REFERENCES tblEMEntityLocation([intEntityLocationId]),
	CONSTRAINT [FK_tblAPProvisional_intStoreLocationId] FOREIGN KEY ([intStoreLocationId]) REFERENCES tblSMCompanyLocation([intCompanyLocationId]),
	CONSTRAINT [FK_tblAPProvisional_intDeferredVoucherId] FOREIGN KEY ([intDeferredVoucherId]) REFERENCES tblAPBill([intBillId]),
	CONSTRAINT [FK_tblAPProvisional_intBookId] FOREIGN KEY ([intBookId]) REFERENCES tblCTBook([intBookId]),
	CONSTRAINT [FK_tblAPProvisional_intSubBookId] FOREIGN KEY ([intSubBookId]) REFERENCES tblCTSubBook([intSubBookId])
);
GO
CREATE NONCLUSTERED INDEX [IX_intProvisionalBatchId]
    ON [dbo].[tblAPProvisional]([intBillBatchId] ASC);
GO
CREATE NONCLUSTERED INDEX [IX_strProvisionalId]
    ON [dbo].[tblAPProvisional]([strBillId] ASC)
	INCLUDE (intBillId, intEntityVendorId, dtmBillDate, ysnPosted, [strVendorOrderNumber], [intAccountId]);
GO
CREATE NONCLUSTERED INDEX [IX_intProvisionalId]
    ON [dbo].[tblAPProvisional]([intBillId] ASC)
	INCLUDE (strBillId, intEntityVendorId, dtmBillDate, ysnPosted, [strVendorOrderNumber], [intAccountId]);
GO
CREATE NONCLUSTERED INDEX [IX_intProvisionalVendorId]
    ON [dbo].[tblAPProvisional]([intEntityVendorId] ASC)
	INCLUDE ([intBillId], dtmBillDate, ysnPosted, [strVendorOrderNumber], [intAccountId]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO
