CREATE TABLE [dbo].[tblApiSchemaCustomer]
(
	guiApiUniqueId              UNIQUEIDENTIFIER NOT NULL,
    intRowNumber                INT NULL,
    intKey                      INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    strEntityNumber             NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strCustomerName             NVARCHAR(100),
    strPhone                    NVARCHAR(100),
    strContactName              NVARCHAR(100),
    strSuffix                   NVARCHAR(100),
    strEmail                    NVARCHAR(100),
    strMobileNo                 NVARCHAR(100),
    strLocationName             NVARCHAR(100),
    strFreightTerm              NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strPrintedName              NVARCHAR(100),
    strAddress                  NVARCHAR(100),
    strCity                     NVARCHAR(100),
    strState                    NVARCHAR(100),
    strZip                      NVARCHAR(100),
    strCountry                  NVARCHAR(100),
    strTimezone                 NVARCHAR(100),
    strLanguage                 NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strDocumentDelivery         NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strExternalERP              NVARCHAR(100),
    strOriginationDate          NVARCHAR(100),
    strInternalNotes            NVARCHAR(100),
    strCustomerNumber           NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strType                     NVARCHAR(100),
    strAccountNo                NVARCHAR(100),
    strCurrency                 NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strPaymentMethod            NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strTerms                    NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strShipVia                  NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strSalesperson              NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strStatus                   NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strFLO                      NVARCHAR(100),
    strPricing                  NVARCHAR(100),
    strTaxNumber                NVARCHAR(100),
    strExemptAllTax             NVARCHAR(100),
    strTaxCounty                NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strVatNumber                NVARCHAR(100),
    strEmployeeCount            NVARCHAR(100),
    strRevenue                  NVARCHAR(100),
    strCurrentSystem            NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strCreditLimit              NVARCHAR(100),
    strCreditStopDays           NVARCHAR(100),
    strCreditCode               NVARCHAR(100),
    strActive                   NVARCHAR(100),
    strPORequired               NVARCHAR(100),
    strCreditHold               NVARCHAR(100),
    strBudgetBeginDate          NVARCHAR(100),
    strBudgetMonthly            NVARCHAR(100),
    strBudgetNoPeriod           NVARCHAR(100),
    strBudgetTieCustomerAging   NVARCHAR(100),
    strStatementDetail          NVARCHAR(100),
    strStatementCreditLimit     NVARCHAR(100),
    strStatementFormat          NVARCHAR(100),
    strServiceCharge            NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strLastServiceChargeDate    NVARCHAR(100),
    strApplyPrepaidTax          NVARCHAR(100),
    strApplySalesTax            NVARCHAR(100),
    strCalculateAutoFreight     NVARCHAR(100),
    strUpdateQuote              NVARCHAR(100),
    strDiscountSchedule         NVARCHAR(100),
    strPrintInvoice             NVARCHAR(100),
    strLinkCustomerNumber       NVARCHAR(100),
    strReferencebyCustomer      NVARCHAR(100),
    strSpecialPriceGroup        NVARCHAR(100),
    strReceivedSignedLicense    NVARCHAR(100),
    strIncludeNameInAddress     NVARCHAR(100),
    strExcludeDunningLetter     NVARCHAR(100),
    strPrintPriceOnPickTicket   NVARCHAR(100),
    strFederalTax               NVARCHAR(100),
    strStateTax                 NVARCHAR(100)
)