CREATE TABLE [dbo].[tblARCustomAgingStagingTable]
(
    [intEntityCustomerId]		INT NULL, 
	[intEntityUserId]			INT NULL,
    [dtmAsOfDate]				DATETIME NULL, 
    [strCustomerName]			NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL, 
    [strCustomerNumber]			NVARCHAR(100)  COLLATE Latin1_General_CI_AS NULL, 
	[strCustomerInfo]			NVARCHAR(500) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyName]            NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strCompanyAddress]         NVARCHAR(500) COLLATE Latin1_General_CI_AS NULL,
    [dblCreditLimit]			NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblTotalAR]				NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblTotalCustomerAR]		NUMERIC(18, 6) NULL DEFAULT 0,
    [dblFuture]					NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblBucket1]				NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblBucket2]				NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblBucket3]				NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblBucket4]				NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblBucket5]				NUMERIC(18, 6) NULL DEFAULT 0,
	[dblBucket6]				NUMERIC(18, 6) NULL DEFAULT 0,
    [strBucket1]				NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
    [strBucket2]				NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
    [strBucket3]				NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
    [strBucket4]				NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
    [strBucket5]				NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	[strBucket6]				NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	[ysnShowBucket1]			BIT NULL DEFAULT 1, 
    [ysnShowBucket2]			BIT NULL DEFAULT 1, 
    [ysnShowBucket3]			BIT NULL DEFAULT 1, 
    [ysnShowBucket4]			BIT NULL DEFAULT 1, 
    [ysnShowBucket5]			BIT NULL DEFAULT 1,
	[ysnShowBucket6]			BIT NULL DEFAULT 1,
    [dblCredits]				NUMERIC(18, 6) NULL DEFAULT 0, 
    [dblPrepayments]			NUMERIC(18, 6) NULL DEFAULT 0,
    [strReportLogId]			NVARCHAR(MAX),
    [blbLogo]                   VARBINARY(MAX) NULL
);
