CREATE TABLE [dbo].[tblApiSchemaEntityEFTInformation] 
(
    guiApiUniqueId				UNIQUEIDENTIFIER NOT NULL,
    intRowNumber				INT NULL,
    intKey						INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
 
    strEntityName				NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strDefault					NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    strBankName					NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strCurrency					NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strBankAccountNumber		NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strIBAN						NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strSwift					NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strBICCode					NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strBranchCode				NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strIntermediaryBank			NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strIntermediaryBankAddress	NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strIntermediarySwiftCode	NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strIntermediaryBICCode		NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strIntermediaryIBAN			NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strNationalBankIdentifier	NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strComment					NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strDetailsOfCharges			NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strFiftySevenFormat			NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strFiftySixFormat			NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPrintNotifications		NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strAccountType				NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strAccountClassification	NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strEffectiveDate			NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strActive					NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPullARBy					NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPullTaxSeparately		NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strRefundBudgetCredits		NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL,
    strPrenoteSent				NVARCHAR(100) COLLATE Latin1_General_CI_AS  NULL
)