CREATE TABLE [dbo].[tblCTContractHeader](
	[intContractHeaderId] [int] IDENTITY(1,1) NOT NULL,
	[intConcurrencyId] [int] NOT NULL,
	[intPurchaseSale] [int] NOT NULL,
	[intEntityId] [int] NOT NULL,
	[intCommodityId] [int] NOT NULL,
	[dblQuantity] [numeric](24, 4) NOT NULL,
	[intCommodityUnitMeasureId] [int] NOT NULL,
	[intContractNumber] [int] NOT NULL,
	[dtmContractDate] [datetime] NOT NULL,
	[strCustomerContract] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[dtmDeferPayDate] [datetime] NULL,
	[dblDeferPayRate] [numeric](5, 2) NULL,
	[intContractTextId] [int] NULL,
	[strInternalComments] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[ysnSigned] [bit] NOT NULL CONSTRAINT [DF_tblCTContractHeader_ysnSigned]  DEFAULT ((0)),
	[ysnPrinted] [bit] NOT NULL CONSTRAINT [DF_tblCTContractHeader_ysnPrinted]  DEFAULT ((0)),
	[intSalespersonId] [int] NOT NULL,
	[intGradeId] [int] NOT NULL,
	[intWeightId] [int] NOT NULL,
	[intCropYearId] [int] NULL,
	[strContractComments] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[intAssociationId] INT NULL, 
    [intTermId] INT NOT NULL, 
    [intPricingType] INT NOT NULL DEFAULT 4, 

	[intApprovalBasisId] [INT] NULL,
	[intContractBasisId] [INT] NULL,
	[intPositionId] [INT] NULL,
	[intInsuranceById] [INT] NULL,
	[intInvoiceTypeId] [INT] NULL,
	[dblTolerancePct] NUMERIC(18, 4) NULL,
	[dblProvisionalInvoicePct] NUMERIC(18, 2) NULL,
    CONSTRAINT [PK_tblCTContractHeader_intContractHeaderId] PRIMARY KEY CLUSTERED ([intContractHeaderId] ASC), 	
	CONSTRAINT [UQ_tblCTContractHeader_intPurchaseSale_intContractNumber] UNIQUE ([intPurchaseSale], [intContractNumber]), 
	CONSTRAINT [FK_tblCTContractHeader_tblCTAssociation_intAssociationId] FOREIGN KEY ([intAssociationId]) REFERENCES [tblCTAssociation]([intAssociationId]),
	CONSTRAINT [FK_tblCTContractHeader_tblSMTerm_intTermId] FOREIGN KEY ([intTermId]) REFERENCES [tblSMTerm]([intTermID]),
	CONSTRAINT [FK_tblCTContractHeader_tblEntity_intEntityId] FOREIGN KEY ([intEntityId]) REFERENCES [tblEntity] ([intEntityId]),
	CONSTRAINT [FK_tblCTContractHeader_tblARSalesperson_intSalespersonId] FOREIGN KEY([intSalespersonId])REFERENCES [tblARSalesperson] ([intEntitySalespersonId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTContractText_intContractTextId] FOREIGN KEY([intContractTextId])REFERENCES [tblCTContractText] ([intContractTextId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTCropYear_intCropYearId] FOREIGN KEY([intCropYearId])REFERENCES [tblCTCropYear] ([intCropYearId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTWeightGrade_intWeightGradeId_intGradeId] FOREIGN KEY([intGradeId])REFERENCES [tblCTWeightGrade] ([intWeightGradeId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTWeightGrade_intWeightGradeId_intWeightId] FOREIGN KEY([intWeightId])REFERENCES [tblCTWeightGrade] ([intWeightGradeId]),
	CONSTRAINT [FK_tblCTContractHeader_tblICCommodity_intCommodityId] FOREIGN KEY([intCommodityId])REFERENCES [tblICCommodity] ([intCommodityId]),
	CONSTRAINT [FK_tblCTContractHeader_tblICCommodityUnitMeasure_intCommodityUnitMeasureId] FOREIGN KEY([intCommodityUnitMeasureId])REFERENCES [tblICUnitMeasure] ([intUnitMeasureId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTPricingType_intPricingType] FOREIGN KEY ([intPricingType]) REFERENCES [tblCTPricingType]([Value]),

	CONSTRAINT [FK_tblCTContractHeader_tblCTApprovalBasis_intApprovalBasisId] FOREIGN KEY ([intApprovalBasisId]) REFERENCES [tblCTApprovalBasis]([intApprovalBasisId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTContractBasis_intContractBasisId] FOREIGN KEY ([intContractBasisId]) REFERENCES [tblCTContractBasis]([intContractBasisId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTPosition_intPositionId] FOREIGN KEY ([intPositionId]) REFERENCES [tblCTPosition]([intPositionId]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTInsuranceBy_] FOREIGN KEY ([intInsuranceById]) REFERENCES [tblCTInsuranceBy]([intInsuranceById]),
	CONSTRAINT [FK_tblCTContractHeader_tblCTInvoiceType_] FOREIGN KEY ([intInvoiceTypeId]) REFERENCES [tblCTInvoiceType]([intInvoiceTypeId])
	
)



