CREATE TABLE [dbo].[tblCTContractDetail]
(
	[intContractDetailId] [int] IDENTITY(1,1) NOT NULL,
	[intConcurrencyId] [int] NOT NULL,
	[intContractHeaderId] [int] NOT NULL,
	[intContractStatusId] [int] NULL,
	[intContractSeq] [int] NOT NULL,
	[intCompanyLocationId] [int] NOT NULL,
	[dtmStartDate] [datetime] NOT NULL,
	[dtmEndDate] [datetime] NOT NULL,
	[intFreightTermId] [int] NULL,
	[intShipViaId] [int] NULL,
	
	[intItemId] [int] NULL,
	[intCategoryId] INT NULL,
	[dblQuantity] [numeric](12, 4) NOT NULL,
	[dblOriginalQty] NUMERIC(12, 4) NULL, 
    [dblBalance] NUMERIC(12, 4) NULL, 
    [dblIntransitQty] NUMERIC(12, 4) NULL, 
    [dblScheduleQty] NUMERIC(12, 4) NULL, 
	[dblNetWeight] NUMERIC(12, 4) NULL, 
	[intUnitMeasureId] [int] NULL,
	[intItemUOMId] [int] NULL,	
	[intCategoryUOMId] INT NULL, 
	
	[intNoOfLoad] INT NULL, 
	[intBalanceNoOfLoad] INT NULL, 
	[dblQuantityPerLoad] NUMERIC(18, 4) NULL, 
    [intLoadItemUOMId] INT NULL, 
    [intLoadCategoryUOMId] INT NULL, 
    
	[intIndexId] INT NULL, 
	[dblAdjustment] NUMERIC(8, 6) NULL, 
	[intAdjItemUOMId] [int] NULL,
    
	[intPricingTypeId] [int] NULL,
	[intFutureMarketId] [int] NULL,
	[intFutureMonthId] INT NULL,
	[dblFutures] [numeric](8, 4) NULL,
	[dblBasis] [numeric](8, 4) NULL,	
	[dblCashPrice] [numeric](9, 4) NULL,
	[intCurrencyId] [int] NULL,
	[intPriceItemUOMId]  INT NULL, 
	[intNoOfLots] INT NULL,
		
	[intMarketZoneId] [int] NULL,
	[intDiscountTypeId] [int] NULL ,
	[intDiscountId] [int] NULL,
	[intContractOptHeaderId] [int] NULL,
	[strBuyerSeller] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[intBillTo] [int] NULL,
	[intFreightRateId] [int] NULL,
	[strFobBasis] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[intRailGradeId] [int] NULL,
	[strRailRemark] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	

	
    [intLoadingPortId] INT NULL, 
    [intDestinationPortId] INT NULL, 
    [strShippingTerm] NVARCHAR(64) COLLATE Latin1_General_CI_AS NULL, 
    [intShippingLineId] INT NULL, 
	[strVessel] NVARCHAR(64) COLLATE Latin1_General_CI_AS NULL, 
    [intDestinationCityId] INT NULL, 
    [intShipperId] INT NULL, 
	[strRemark] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 

	[strGarden] NVARCHAR(128) COLLATE Latin1_General_CI_AS NULL,
	[strVendorLotID] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	[strInvoiceNo] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	[strReference] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,

	[intUnitsPerLayer] INT NULL,
	[intLayersPerPallet] INT NULL,
	[dtmEventStartDate] [datetime] NULL,
	[dtmPlannedAvailabilityDate] [datetime] NULL,
	[dtmUpdatedAvailabilityDate]  [datetime] NULL,
	[intBookId] INT NULL,
	[intSubBookId] INT NULL,

	[intContainerTypeId] INT NULL,
	[intNumberOfContainers] INT NULL,
	[intInvoiceCurrencyId] [int] NULL,
	[dtmFXValidFrom]  [datetime] NULL,
	[dtmFXValidTo]  [datetime] NULL,
	[dblRate] [numeric](8, 4) NULL,
	[strFXRemarks] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[dblAssumedFX] [numeric](8, 4) NULL,
	[strFixationBy] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	
	
    
	
    CONSTRAINT [PK_tblCTContractDetail_intContractDetailId] PRIMARY KEY CLUSTERED ([intContractDetailId] ASC),
	CONSTRAINT [UQ_tblCTContractDetail_intContractHeaderId_intContractSeq] UNIQUE ([intContractHeaderId],[intContractSeq]), 

	CONSTRAINT [FK_tblCTContractDetail_tblARMarketZone_intMarketZoneId] FOREIGN KEY ([intMarketZoneId]) REFERENCES [tblARMarketZone]([intMarketZoneId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTContractHeader_intContractHeaderId] FOREIGN KEY ([intContractHeaderId]) REFERENCES [tblCTContractHeader]([intContractHeaderId]) ON DELETE CASCADE,
	CONSTRAINT [FK_tblCTContractDetail_tblCTContractStatus_intContractStatusId] FOREIGN KEY ([intContractStatusId]) REFERENCES [tblCTContractStatus]([intContractStatusId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTContractOptHeader_intContractOptHeaderId] FOREIGN KEY ([intContractOptHeaderId]) REFERENCES [tblCTContractOptHeader]([intContractOptHeaderId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTFreightRate_intFreightRateId] FOREIGN KEY ([intFreightRateId]) REFERENCES [tblCTFreightRate]([intFreightRateId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTPricingType_intPricingTypeId] FOREIGN KEY ([intPricingTypeId]) REFERENCES [tblCTPricingType]([intPricingTypeId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTRailGrade_intRailGradeId] FOREIGN KEY ([intRailGradeId]) REFERENCES [tblCTRailGrade]([intRailGradeId]),
	CONSTRAINT [FK_tblCTContractDetail_tblICItem_intItemId] FOREIGN KEY ([intItemId]) REFERENCES [tblICItem]([intItemId]),
	CONSTRAINT [FK_tblCTContractDetail_tblICUnitMeasure_intUnitMeasureId] FOREIGN KEY ([intUnitMeasureId]) REFERENCES [tblICUnitMeasure]([intUnitMeasureId]),
	CONSTRAINT [FK_tblCTContractDetail_tblSMCompanyLocation_intCompanyLocationId] FOREIGN KEY ([intCompanyLocationId]) REFERENCES [tblSMCompanyLocation]([intCompanyLocationId]),
	CONSTRAINT [FK_tblCTContractDetail_tblSMCurrency_intCurrencyId] FOREIGN KEY ([intCurrencyId]) REFERENCES [tblSMCurrency]([intCurrencyID]),
	CONSTRAINT [FK_tblCTContractDetail_tblSMFreightTerms_intFreightTermId] FOREIGN KEY ([intFreightTermId]) REFERENCES [tblSMFreightTerms]([intFreightTermId]),
	CONSTRAINT [FK_tblCTContractDetail_tblSMShipVia_intShipViaId] FOREIGN KEY ([intShipViaId]) REFERENCES [tblSMShipVia]([intEntityShipViaId]),
	CONSTRAINT [FK_tblCTContractDetail_tblRKFutureMarket_intFutureMarketId] FOREIGN KEY ([intFutureMarketId]) REFERENCES [tblRKFutureMarket]([intFutureMarketId]),
	CONSTRAINT [FK_tblCTContractDetail_tblAPVendor_intVendorId] FOREIGN KEY ([intBillTo]) REFERENCES [tblAPVendor]([intEntityVendorId]),
	CONSTRAINT [FK_tblCTContractDetail_tblGRDiscountId_intDiscountId] FOREIGN KEY ([intDiscountId]) REFERENCES [tblGRDiscountId]([intDiscountId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTDiscount_intDiscountTypeId] FOREIGN KEY ([intDiscountTypeId]) REFERENCES [tblCTDiscountType]([intDiscountTypeId]),
	
	CONSTRAINT [FK_tblCTContractDetail_tblSMCity_intLoadingPortId_intCityId] FOREIGN KEY ([intLoadingPortId]) REFERENCES [tblSMCity]([intCityId]),
	CONSTRAINT [FK_tblCTContractDetail_tblSMCity_intDestinationPortId_intCityId] FOREIGN KEY ([intDestinationPortId]) REFERENCES [tblSMCity]([intCityId]),
	CONSTRAINT [FK_tblCTContractDetail_tblSMCity_intDestinationCityId_intCityId] FOREIGN KEY ([intDestinationCityId]) REFERENCES [tblSMCity]([intCityId]),
	CONSTRAINT [FK_tblCTContractDetail_tblEntity_intShippingLineId_intEntityId] FOREIGN KEY ([intShippingLineId]) REFERENCES [tblEntity]([intEntityId]),
	CONSTRAINT [FK_tblCTContractDetail_tblEntity_intShipperId_intEntityId] FOREIGN KEY ([intShipperId]) REFERENCES [tblEntity]([intEntityId]),
	CONSTRAINT [FK_tblCTContractDetail_tblRKFuturesMonth_intFutureMonthId] FOREIGN KEY ([intFutureMonthId]) REFERENCES [tblRKFuturesMonth]([intFutureMonthId]),

	CONSTRAINT [FK_tblCTContractDetail_tblCTBook_intBookId] FOREIGN KEY ([intBookId]) REFERENCES [tblCTBook]([intBookId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTSubBook_intSubBookId] FOREIGN KEY ([intSubBookId]) REFERENCES [tblCTSubBook]([intSubBookId]),

	CONSTRAINT [FK_tblCTContractDetail_tblICItemUOM_intItemUOMId] FOREIGN KEY ([intItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),
	CONSTRAINT [FK_tblCTContractDetail_tblICItemUOM_intPriceItemUOMId_intItemUOMId] FOREIGN KEY ([intPriceItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),
	CONSTRAINT [FK_tblCTContractDetail_tblICItemUOM_intAdjItemUOMId_intItemUOMId] FOREIGN KEY ([intAdjItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),
	CONSTRAINT [FK_tblCTContractDetail_tblICItemUOM_intLoadItemUOMId_intItemUOMId] FOREIGN KEY ([intLoadItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),


	CONSTRAINT [FK_tblCTContractDetail_tblICCategoryUOM_intCategoryUOMId] FOREIGN KEY([intCategoryUOMId])REFERENCES [tblICCategoryUOM] ([intCategoryUOMId]),
	CONSTRAINT [FK_tblCTContractDetail_tblICCategoryUOM_intLoadCategoryUOMId_intCategoryUOMId] FOREIGN KEY ([intLoadCategoryUOMId]) REFERENCES [tblICCategoryUOM]([intCategoryUOMId]),

	CONSTRAINT [FK_tblCTContractDetail_tblSMCurrency_intInvoiceCurrencyId_intCurrencyId] FOREIGN KEY ([intInvoiceCurrencyId]) REFERENCES [tblSMCurrency]([intCurrencyID]),
	CONSTRAINT [FK_tblCTContractDetail_tblLGContainerType_intContainerTypeId] FOREIGN KEY ([intContainerTypeId]) REFERENCES [tblLGContainerType]([intContainerTypeId]),
	CONSTRAINT [FK_tblCTContractDetail_tblICCategory_intCategoryId] FOREIGN KEY([intCategoryId])REFERENCES [tblICCategory] ([intCategoryId]),
	CONSTRAINT [FK_tblCTContractDetail_tblCTIndex_intIndexId] FOREIGN KEY ([intIndexId]) REFERENCES [tblCTIndex]([intIndexId])
) 