CREATE TABLE [dbo].[tblCFInvoiceReportTempTable] (
    [intCustomerGroupId]              INT             NULL,
    [intTransactionId]                INT             NULL,
    [intOdometer]                     INT             NULL,
    [intOdometerAging]                INT             NULL,
    [intInvoiceId]                    INT             NULL,
    [intProductId]                    INT             NULL,
    [intCardId]                       INT             NULL,
    [intAccountId]                    INT             NULL,
    [intInvoiceCycle]                 INT             NULL,
    [intSubAccountId]                 INT             NULL,
    [intCustomerId]                   INT             NULL,
    [strGroupName]                    NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strCustomerNumber]               NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strShipTo]                       NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strBillTo]                       NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strCompanyName]                  NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strCompanyAddress]               NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strType]                         NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strCustomerName]                 NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strLocationName]                 NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strInvoiceNumber]                NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strTransactionId]                NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strTransactionType]              NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strInvoiceReportNumber]          NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strTempInvoiceReportNumber]      NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strMiscellaneous]                NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strName]                         NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strCardNumber]                   NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strCardDescription]              NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strNetwork]                      NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strInvoiceCycle]                 NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strPrimarySortOptions]           NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strSecondarySortOptions]         NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintRemittancePage]          NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintPricePerGallon]          NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintSiteAddress]             NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteNumber]                   NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteName]                     NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strProductNumber]                NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strItemNo]                       NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strDescription]                  NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strVehicleNumber]                NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strVehicleDescription]           NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strTaxState]                     NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strDepartment]                   NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strDepartmentDescription]        NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteType]                     NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strState]                        NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteAddress]                  NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteCity]                     NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintTimeStamp]               NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strEmailDistributionOption]      NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strEmail]                        NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [dtmTransactionDate]              DATETIME        NULL,
    [dtmDate]                         DATETIME        NULL,
    [dtmPostedDate]                   DATETIME        NULL,
    [dtmBillingDate]                  DATETIME        NULL,
    [dblTotalMiles]                   NUMERIC (18, 6) NULL,
    [dblQuantity]                     NUMERIC (18, 6) NULL,
    [dblCalculatedTotalAmount]        NUMERIC (18, 6) NULL,
    [dblOriginalTotalAmount]          NUMERIC (18, 6) NULL,
    [dblCalculatedGrossAmount]        NUMERIC (18, 6) NULL,
    [dblOriginalGrossAmount]          NUMERIC (18, 6) NULL,
    [dblCalculatedNetAmount]          NUMERIC (18, 6) NULL,
    [dblOriginalNetAmount]            NUMERIC (18, 6) NULL,
    [dblMargin]                       NUMERIC (18, 6) NULL,
    [dblTotalTax]                     NUMERIC (18, 6) NULL,
    [dblTotalSST]                     NUMERIC (18, 6) NULL,
    [dblTaxExceptSST]                 NUMERIC (18, 6) NULL,
    [dblInvoiceTotal]                 NUMERIC (18, 6) NULL,
    [ysnPrintMiscellaneous]           BIT             NULL,
    [ysnShowSST]           BIT             NULL,
    [ysnSummaryByCard]                BIT             NULL,
    [ysnSummaryByDepartmentProduct]   BIT             NULL,
    [ysnSummaryByDepartment]          BIT             NULL,
    [ysnSummaryByMiscellaneous]       BIT             NULL,
    [ysnSummaryByProduct]             BIT             NULL,
    [ysnSummaryByVehicle]             BIT             NULL,
    [ysnSummaryByDeptCardProd]        BIT             NULL,
    [ysnSummaryByCardProd]            BIT             NULL,
    [ysnPrintTimeOnInvoices]          BIT             NULL,
    [ysnPrintTimeOnReports]           BIT             NULL,
    [ysnInvalid]                      BIT             NULL,
    [ysnExpensed]                     BIT             NULL,
    [ysnPosted]                       BIT             NULL,
    [ysnPostedCSV]                    BIT             NULL,
    [ysnPostForeignSales]             BIT             NULL,
    [ysnDepartmentGrouping]           BIT             NULL,
    [ysnSummaryByDeptVehicleProd]     BIT             NULL,
    [strGuid]                         NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strUserId]                       NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [intVehicleId]                    INT             NULL,
    [strStatementType]                NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strDriverPinNumber]              NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [strDriverDescription]            NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [intDriverPinId]                  INT             NULL,
    [ysnSummaryByDriverPin]           BIT             NULL,
    [strDetailDisplay]                NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [ysnMPGCalculation]               BIT             NULL,
    [ysnShowVehicleDescriptionOnly]   BIT             NULL,
    [ysnShowDriverPinDescriptionOnly] BIT             NULL,
	[ysnPageBreakByPrimarySortOrder]  BIT			  NULL,
	[ysnSummaryByDeptDriverPinProd]   BIT			  NULL,
	[strDepartmentGrouping]           NVARCHAR(100)	 COLLATE Latin1_General_CI_AS  NULL,
    
);



















