CREATE TABLE [dbo].[tblCTImportAOP]
(
	intImportAOPId			INT IDENTITY(1,1) NOT NULL,
	strYear					NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	dtmFromDate				DATETIME NULL,
	dtmToDate				DATETIME NULL,
	strBook					NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	strSubBook				NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	strCommodity			NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	strCompanyLocation		NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	strItem					NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	dblVolume				NUMERIC(18, 6) NULL,
	strVolumeUOM			NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	strCurrency				NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	strWeightUOM			NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	strPriceUOM				NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	dblComponent1			NUMERIC(18, 6) NULL,
	dblComponent2			NUMERIC(18, 6) NULL,
	dblComponent3			NUMERIC(18, 6) NULL,
	dblComponent4			NUMERIC(18, 6) NULL,
	dblComponent5			NUMERIC(18, 6) NULL,
	dblComponent6			NUMERIC(18, 6) NULL,
	dblComponent7			NUMERIC(18, 6) NULL,
	dblComponent8			NUMERIC(18, 6) NULL,
	dblComponent9			NUMERIC(18, 6) NULL,
	dblComponent10			NUMERIC(18, 6) NULL,
	intAOPId				INT NULL,
	intAOPDetailId			INT NULL,
	ysnImported				BIT NULL,
	intImportedById			INT NULL,
	dtmImported				DATETIME NULL,
	strErrorMsg				NVARCHAR(max) NULL,
	intSession				BIGINT NULL,

	CONSTRAINT [PK_tblCTImportAOP_intImportAOPId] PRIMARY KEY CLUSTERED (intImportAOPId ASC), 
)
