CREATE TABLE [dbo].[tblCMEmailEventLog](
	[intEmailEventLogId] [int] IDENTITY(1,1) NOT NULL,
	[dtmDate] [datetime] NULL,
	[intEntityId] [int] NULL,
	[intConcurrencyId] INT NULL,
 CONSTRAINT [PK_tblCMEmailEventLog] PRIMARY KEY CLUSTERED 
(
	[intEmailEventLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


