CREATE TABLE [dbo].[tblCTContractImportTemp]
(
	[strContractType] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strEntityName] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strEntityNo] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strCommodity] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strContractNumber] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[dtmContractDate] [datetime] NULL,
	[strSalesperson] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strCropYear] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strPosition] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strContractStatus] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[intContractSeq] [int] NULL,
	[strLocationName] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[dtmStartDate] [datetime] NULL,
	[dtmEndDate] [datetime] NULL,
	[strItem] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[dblQuantity] [numeric](18, 6),
	[strQuantityUOM] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strPricingType] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strFutMarketName] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[intMonth] [int] NULL,
	[intYear] [int] NULL,
	[dblFutures] [numeric](18, 6) NULL,
	[dblBasis] [numeric](18, 6) NULL,
	[dblCashPrice] [numeric](18, 6) NULL,
	[strCurrency] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strPriceUOM] [nvarchar](255)  COLLATE Latin1_General_CI_AS NULL,
	[strRemark] [nvarchar](max)  COLLATE Latin1_General_CI_AS NULL,
	[dtmM2MDate] [datetime] NULL,
	[strShipperId] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strShipper] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strBook] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strVendorRef] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strFreightTerm] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strLoadingPort] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strDestinationPort] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strTerms] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[intDaysFOrFinance] int null,
	[strGrade] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strSampleType] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strWeights] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strAssociation] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strArbitration] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strProducer] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strRequiredDocuments] nvarchar(max)  COLLATE Latin1_General_CI_AS NULL,
	[strPackingDescription] nvarchar(50)  COLLATE Latin1_General_CI_AS NULL,
	[strContainerType] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[intNoOfContainers] int null,
	[strCertification] nvarchar(max)  COLLATE Latin1_General_CI_AS NULL,
	[strCounterCurrency] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[dblFXRate] numeric(18,6) null,
	[strCashFlowOverride] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[dtmCashFlowDate] datetime null,
	[strMarketZone] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[dblBudgetPrice] numeric(18,6) NULL,
	[strBundleItem] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strCostTerm] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strMTMPoint] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[dtmHistoricDate] datetime null,
	[strRevolutionCurrencyPair] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[dblHistoricRate] numeric(18,6) null,
	[strHistoricType] nvarchar(255)  COLLATE Latin1_General_CI_AS NULL,
	[strWarehouse] nvarchar(100)  COLLATE Latin1_General_CI_AS NULL
)
