CREATE TABLE [dbo].[tblCTContractAdjustment]
(
	intAdjustmentId INT IDENTITY,
	intContractDetailId INT NOT NULL,
	strAdjustmentNo NVARCHAR(50) NOT NULL,
	dtmAdjustmentDate DATETIME NOT NULL,
	strComment NVARCHAR(MAX),
	ysnAdjustment BIT,
	dblOldQuantity NUMERIC(12, 4),
	dblOldBalance NUMERIC(12, 4),
	[dblAdjAmount] NUMERIC(12, 4) NOT NULL,
	dblNewBalance NUMERIC(12, 4),
	dblNewQuantity NUMERIC(12, 4),
	dblContractPrice NUMERIC(8, 4),
	dblCancellationPrice NUMERIC(8, 4),
	dblGainLossPerUnit NUMERIC(8, 4) NULL,
	dblCancelFeePerUnit NUMERIC(8, 4),
	dblCancelFeeFlatAmount NUMERIC(8, 4),
	dblTotalGainLoss NUMERIC(8, 4),
	intUserId INT NOT NULL,
	dtmCreatedDate DATETIME,
	intTicketId INT,
	intRailId INT,
	intProvisionalInvoiceId INT,
	dblProvisionalPrice NUMERIC(8, 4),
	CONSTRAINT [PK_tblCTContractAdjustment_intAdjustmentId] PRIMARY KEY CLUSTERED ([intAdjustmentId] ASC), 
	CONSTRAINT [FK_tblCTContractAdjustment_tblCTContractDetail_intContractDetailId] FOREIGN KEY ([intContractDetailId]) REFERENCES [tblCTContractDetail]([intContractDetailId]),
	CONSTRAINT [FK_tblCTContractAdjustment_tblSCTicket_intTicketId] FOREIGN KEY ([intTicketId]) REFERENCES [tblSCTicket]([intTicketId])
)
