CREATE TABLE [dbo].[tblCFTransactionPricingType] (
    [intItemId]            INT             NULL,
    [intProductId]         INT             NULL,
    [strProductNumber]     NVARCHAR (MAX)  NULL,
    [strItemId]            NVARCHAR (MAX)  NULL,
    [intCustomerId]        INT             NULL,
    [intLocationId]        INT             NULL,
    [dblQuantity]          NUMERIC (18, 6) NULL,
    [intItemUOMId]         INT             NULL,
    [dtmTransactionDate]   DATETIME        NULL,
    [strTransactionType]   NVARCHAR (MAX)  NULL,
    [intNetworkId]         INT             NULL,
    [intSiteId]            INT             NULL,
    [dblTransferCost]      NUMERIC (18, 6) NULL,
    [dblInventoryCost]     NUMERIC (18, 6) NULL,
    [dblOriginalPrice]     NUMERIC (18, 6) NULL,
    [dblPrice]             NUMERIC (18, 6) NULL,
    [strPriceMethod]       NVARCHAR (MAX)  NULL,
    [dblAvailableQuantity] NUMERIC (18, 6) NULL,
    [intContractHeaderId]  INT             NULL,
    [intContractDetailId]  INT             NULL,
    [strContractNumber]    NVARCHAR (MAX)  NULL,
    [intContractSeq]       INT             NULL,
    [strPriceBasis]        NVARCHAR (MAX)  NULL,
    [intPriceProfileId]    INT             NULL,
    [intPriceIndexId]      INT             NULL,
    [intSiteGroupId]       INT             NULL,
    [strPriceProfileId]    NVARCHAR (MAX)  NULL,
    [strPriceIndexId]      NVARCHAR (MAX)  NULL,
    [strSiteGroup]         NVARCHAR (MAX)  NULL,
    [dblPriceProfileRate]  NUMERIC (18, 6) NULL,
    [dblPriceIndexRate]    NUMERIC (18, 6) NULL,
    [dtmPriceIndexDate]    DATETIME        NULL,
    [dblMargin]            NUMERIC (18, 6) NULL,
    [dblAdjustmentRate]    NUMERIC (18, 6) NULL,
    [ysnDuplicate]         BIT             NULL,
    [ysnInvalid]           BIT             NULL,
    [dblGrossTransferCost] NUMERIC (18, 6) NULL,
    [dblNetTransferCost]   NUMERIC (18, 6) NULL,
    [intFreightTermId]     INT             NULL
);

