CREATE TABLE [dbo].[tblCFInvoiceReportTempTable] (
    [intCustomerGroupId]         INT             NULL,
    [intTransactionId]           INT             NULL,
    [intOdometer]                INT             NULL,
    [intOdometerAging]           INT             NULL,
    [intInvoiceId]               INT             NULL,
    [intProductId]               INT             NULL,
    [intCardId]                  INT             NULL,
    [intAccountId]               INT             NULL,
    [intInvoiceCycle]            INT             NULL,
    [intSubAccountId]            INT             NULL,
    [intCustomerId]              INT             NULL,
    [strGroupName]               NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strCustomerNumber]          NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strShipTo]                  NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strBillTo]                  NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strCompanyName]             NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strCompanyAddress]          NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strType]                    NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strCustomerName]            NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strLocationName]            NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strInvoiceNumber]           NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strTransactionId]           NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strTransactionType]         NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strInvoiceReportNumber]     NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strTempInvoiceReportNumber] NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strMiscellaneous]           NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strName]                    NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strCardNumber]              NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strCardDescription]         NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strNetwork]                 NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strInvoiceCycle]            NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strPrimarySortOptions]      NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strSecondarySortOptions]    NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintRemittancePage]     NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintPricePerGallon]     NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintSiteAddress]        NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteNumber]              NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteName]                NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strProductNumber]           NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strItemNo]                  NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDescription]             NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strVehicleNumber]           NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strVehicleDescription]      NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strTaxState]                NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDepartment]              NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteType]                NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strState]                   NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteAddress]             NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteCity]                NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strPrintTimeStamp]          NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strEmailDistributionOption] NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strEmail]                   NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [dtmTransactionDate]         DATETIME        NULL,
    [dtmDate]                    DATETIME        NULL,
    [dtmPostedDate]              DATETIME        NULL,
    [dblTotalMiles]              NUMERIC (18, 6) NULL,
    [dblQuantity]                NUMERIC (18, 6) NULL,
    [dblCalculatedTotalAmount]   NUMERIC (18, 6) NULL,
    [dblOriginalTotalAmount]     NUMERIC (18, 6) NULL,
    [dblCalculatedGrossAmount]   NUMERIC (18, 6) NULL,
    [dblOriginalGrossAmount]     NUMERIC (18, 6) NULL,
    [dblCalculatedNetAmount]     NUMERIC (18, 6) NULL,
    [dblOriginalNetAmount]       NUMERIC (18, 6) NULL,
    [dblMargin]                  NUMERIC (18, 6) NULL,
    [dblTotalTax]                NUMERIC (18, 6) NULL,
    [dblTotalSST]                NUMERIC (18, 6) NULL,
    [dblTaxExceptSST]            NUMERIC (18, 6) NULL,
    [dblInvoiceTotal]            NUMERIC (18, 6) NULL,
    [ysnPrintMiscellaneous]      BIT             NULL,
    [ysnSummaryByCard]           BIT             NULL,
    [ysnSummaryByDepartment]     BIT             NULL,
    [ysnSummaryByMiscellaneous]  BIT             NULL,
    [ysnSummaryByProduct]        BIT             NULL,
    [ysnSummaryByVehicle]        BIT             NULL,
    [ysnSummaryByDeptCardProd]   BIT             NULL,
    [ysnSummaryByCardProd]       BIT             NULL,
    [ysnPrintTimeOnInvoices]     BIT             NULL,
    [ysnPrintTimeOnReports]      BIT             NULL,
    [ysnInvalid]                 BIT             NULL,
    [ysnPosted]                  BIT             NULL
);



