CREATE TABLE [dbo].[tblCTContractDetailImport]
(
	intContractDetailImportId INT IDENTITY NOT NULL,
	intContractDetailImportHeaderId INT NULL,
	strContractNumber NVARCHAR(50) NOT NULL,
	intSequence INT NOT NULL,
	strStatus NVARCHAR(50) NULL,
	dtmStartDate DATETIME NOT NULL,
	dtmEndDate DATETIME NOT NULL,
	dtmM2MDate DATETIME NULL,
	dtmPlannedAvailability DATETIME NULL,
	dtmEventStartDate DATETIME NULL,
	dtmUpdatedAvailability DATETIME NULL,
	strLocation NVARCHAR(100) NOT NULL,
	strBook NVARCHAR(50) NULL,
	strSubBook NVARCHAR(50) NULL,
	strContractItem NVARCHAR(100) NULL,
	strItem NVARCHAR(100) NOT NULL,
	strItemSpecification NVARCHAR(250) NULL,
	strPurchasingGroup NVARCHAR(50) NULL,
	strFarmNo NVARCHAR(50) NULL,
	strGrade NVARCHAR(200) NULL,
	strGarden NVARCHAR(50) NULL,
	strVendorLotId NVARCHAR(50) NULL,
	dblQuantity NUMERIC(18, 6) NOT NULL DEFAULT((0)),
	strQuantityUOM NVARCHAR(50) NOT NULL,
	dblNetWeight NUMERIC(18, 6) NOT NULL DEFAULT((0)),
	strWeightUOM NVARCHAR(50) NOT NULL,
	strPackingDescription NVARCHAR(100) NULL,
	dblEstYieldPercent NUMERIC(18, 6) NULL DEFAULT((0)),
	dblUnitPerLayer NUMERIC(18, 6) NULL DEFAULT((0)),
	dblLayerPerPallet NUMERIC(18, 6) NULL DEFAULT((0)),
	intNoOfLots INT NULL,
	strContainerType NVARCHAR(50) NULL,
	intNoOfContainers INT NULL,
	strMarketZone NVARCHAR(50) NULL,
	strDiscount NVARCHAR(50) NULL,
	strDiscountTable NVARCHAR(50) NULL,
	strScheduleCode NVARCHAR(50) NULL,
	strOption NVARCHAR(50) NULL,
	strSplit NVARCHAR(50) NULL,
	strFixationBy NVARCHAR(50) NULL,
	strPricingType NVARCHAR(50) NULL,
	strFuturesMarket NVARCHAR(50) NULL,
	strFutureMonth NVARCHAR(50) NULL,
	dblFutures NUMERIC(18, 6) NULL DEFAULT((0)),
	strBasisUOM NVARCHAR(50) NULL,
	strBasisCurrency NVARCHAR(50) NULL,
	dblBasis NUMERIC(18, 6) NULL DEFAULT((0)),
	dblCashPrice NUMERIC(18, 6) NULL DEFAULT((0)),
	strPriceUOM NVARCHAR(50) NULL,
	strPriceCurrency NVARCHAR(50) NULL,
	dblTotalCost NUMERIC(18, 6) NULL DEFAULT((0)),
	strERPPONo NVARCHAR(50) NULL,
	strERPItemNo NVARCHAR(50) NULL,
	strERPBatchNo NVARCHAR(50) NULL,
	strInvoiceCurrency NVARCHAR(50) NULL,
	dtmFXValidFrom DATETIME NULL,
	dtmFXValidTo DATETIME NULL,
	strCurrencyPair NVARCHAR(50) NULL,
	dblForexRate NUMERIC(18, 6) NULL DEFAULT((0)),
	dblFXPrice NUMERIC(18, 6) NULL DEFAULT((0)),
	ysnPrice BIT NULL DEFAULT((0)),
	strRateType NVARCHAR(50) NULL,
	strFXPriceUOM NVARCHAR(50) NULL,
	strRemarks NVARCHAR(50) NULL,
	strFreightTerms NVARCHAR(50) NULL,
	strShipVia NVARCHAR(50) NULL,
	strFarmInvoiceNo NVARCHAR(50) NULL,
	strProducer NVARCHAR(50) NULL,
	ysnClaimsToProducer BIT NULL DEFAULT((0)),
	ysnFronting BIT NULL DEFAULT((0)),
	ysnInvoice BIT NULL DEFAULT((0)),
	ysnProvisionalInvoice BIT NULL DEFAULT((0)),
	ysnQuantityFinal BIT NULL DEFAULT((0)),
	ysnBackToBack BIT NULL DEFAULT((0)),
	ysnFinalPnL BIT NULL DEFAULT((0)),
	ysnProvisionalPnL BIT NULL DEFAULT((0)),
	strBuyerSellerName NVARCHAR(100) NULL,
	strBillTo NVARCHAR(100) NULL,
	strOriginDestination NVARCHAR(50) NULL,
	strFOBBasis NVARCHAR(50) NULL,
	strRailGrade NVARCHAR(50) NULL,
	strRailRemarks NVARCHAR(50) NULL,
	strLoadingPointType NVARCHAR(50) NULL,
	strLoadingPoint NVARCHAR(50) NULL,
	strDestinationPointType NVARCHAR(50) NULL,
	strDestinationPoint NVARCHAR(50) NULL,
	strDestinationCity NVARCHAR(50) NULL,
	strShippingTerms NVARCHAR(50) NULL,
	strShippineLine NVARCHAR(50) NULL,
	strVessel NVARCHAR(50) NULL,
	strShipper NVARCHAR(50) NULL,
	strStorageLocation NVARCHAR(50) NULL,
	strStorageUnit NVARCHAR(50) NULL,
	strPrintRemarks NVARCHAR(50) NULL,
	guiUniqueId UNIQUEIDENTIFIER NULL,
	ysnImported BIT NULL DEFAULT((0)),
	strMessage NVARCHAR(250) NULL,
	[intConcurrencyId] INT NULL DEFAULT ((1)), 
	[strReference] [nvarchar](100) NULL,
	[dtmEtaPod] [date] NULL,
	[dtmEtaPol] [date] NULL,
    CONSTRAINT [PK_tblCTContractDetailImport_intContractDetailImportId] PRIMARY KEY CLUSTERED (intContractDetailImportId ASC), 
    CONSTRAINT [FK_tblCTContractDetailImport_tblCTContractDetailImportHeader] FOREIGN KEY ([intContractDetailImportHeaderId]) REFERENCES [tblCTContractDetailImportHeader]([intContractDetailImportHeaderId]) ON DELETE CASCADE

)
