
CREATE TABLE [dbo].[tblCMTradeFinanceLimitType](
	intLimitTypeId      INT IDENTITY(1,1) NOT NULL,
    strLimitType        NVARCHAR(40) COLLATE Latin1_General_CI_AS NOT NULL,
    intConcurrencyId    INT NOT NULL
CONSTRAINT [PK_tblCMTradeFinanceLimitType] PRIMARY KEY CLUSTERED 
(
	intLimitTypeId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


