CREATE TABLE [dbo].[tblCTPriceFixationMultiplePrice]
(
	[intPriceFixationMultiplePriceId] INT IDENTITY(1,1) NOT NULL,
	[intPriceFixationId] INT NOT NULL,
	[intPriceContractId] INT,
	[intConcurrencyId] INT NOT NULL,
	[intContractHeaderId] INT NOT NULL, 
	[intContractDetailId] INT NULL,
	[intOriginalFutureMarketId] INT NOT NULL,
	[intOriginalFutureMonthId] INT NOT NULL,
	[dblOriginalBasis] NUMERIC(18,6) NOT NULL,
	[dblTotalLots] NUMERIC(18,6),
	[dblLotsFixed] NUMERIC(18,6),
	[intLotsHedged] INT,
	[dblPolResult] NUMERIC(18,6),
	[dblPremiumPoints] NUMERIC(18,6),
	[ysnAAPrice] BIT,
	[ysnSettlementPrice] BIT,
	[ysnToBeAgreed] BIT,
	[dblSettlementPrice] NUMERIC(18,6),
	[dblAgreedAmount] NUMERIC(18,6),
	[intAgreedItemUOMId] INT,
	[dblPolPct] NUMERIC(18,6),
	[dblPriceWORollArb]  NUMERIC(18,6),
	[dblRollArb]  NUMERIC(18,6),
	[dblPolSummary]  NUMERIC(18,6),
	[dblAdditionalCost]  NUMERIC(18,6),
	[dblFinalPrice]  NUMERIC(18,6),
	[intFinalPriceUOMId] INT NOT NULL,
	[ysnSplit] BIT,
	[intPriceFixationRefId] INT,

    CONSTRAINT [PK_tblCTPriceFixationMultiplePrice_intPriceFixationMultiplePriceId] PRIMARY KEY CLUSTERED ([intPriceFixationMultiplePriceId] ASC),
	CONSTRAINT [FK_tblCTPriceFixationMultiplePrice_tblCTPriceFixation_intPriceFixationId] FOREIGN KEY ([intPriceFixationId]) REFERENCES [tblCTPriceFixation]([intPriceFixationId]) on delete cascade
)