CREATE TABLE [dbo].[tblCMBankImportLog]
(
	[intImportLogId]	INT IDENTITY(1,1) NOT NULL,
	[dtmDate]			DATETIME NULL,
	[strVersion]		NVARCHAR(20) COLLATE Latin1_General_CI_AS NULL,
	[intEntityId]		INT NULL,
	CONSTRAINT [PK_tblCMBankImportLog] PRIMARY KEY CLUSTERED ([intImportLogId] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
