
--2 ENTRY PER ADJUSTMENT (1 FOR PRINCIPAL AND FOR RELATED)

CREATE TABLE [dbo].[tblCMBankTransactionAdjustment](
	[intAdjustmentId] [int] IDENTITY(1,1) NOT NULL,
	[intBankFeeId] [int] NULL,
	[intTransactionId] [int] NULL,
    [strType] NVARCHAR(10) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_tblCMBankTransactionAdjustment] PRIMARY KEY CLUSTERED 
(
	[intAdjustmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

