CREATE TABLE [dbo].[tblDBPanel] (
    [intPanelId]            INT             IDENTITY (1, 1) NOT NULL,
    [intRowsReturned]       INT             NOT NULL,
    [intRowsVisible]        SMALLINT        NOT NULL,
    [intChartZoom]          SMALLINT        NOT NULL,
    [intChartHeight]        SMALLINT        NOT NULL,
    [intUserId]             INT             NOT NULL,
    [intDefaultColumn]      SMALLINT        NULL,
    [intDefaultRow]         SMALLINT        NULL,
    [intDefaultWidth]       SMALLINT        NULL,
    [intSourcePanelId]      INT             NOT NULL,
    [intConnectionId]       INT             NOT NULL,
    [intDrillDownPanel]     INT             NOT NULL,
    [strClass]              NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS DEFAULT ('') NOT NULL,
    [strPanelName]          NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS DEFAULT ('') NOT NULL,
    [strStyle]              NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strAccessType]         NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strCaption]            NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NOT NULL,
    [strChart]              NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strChartPosition]      NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strChartColor]         NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strConnectionName]     NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDateCondition]      NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDateCondition2]     NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDateFieldName]      NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDateFieldName2]     NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDataSource]         NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDataSource2]        NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDateVariable]       NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDateVariable2]      NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDefaultTab]         NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strDescription]        NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strPanelNameDuplicate] NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strPanelType]          NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strQBCriteriaOptions]  NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strFilterCondition]    NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strFilterVariable]     NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strFilterFieldName]    NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strFilterVariable2]    NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strFilterFieldName2]   NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strGroupFields]        NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strFilters]            NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [strConfigurator]       NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [ysnChartLegend]        BIT             DEFAULT ((0)) NOT NULL,
    [ysnShowInGroups]       BIT             DEFAULT ((0)) NOT NULL,
    [imgLayoutGrid]         VARBINARY (MAX) NULL,
    [imgLayoutPivotGrid]    VARBINARY (MAX) NULL,
    [strPanelVersion]       NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS DEFAULT ((14.1)) NOT NULL,
    [intFilterId]           INT             NULL,
    [intConcurrencyId ]     INT             DEFAULT ((1)) NOT NULL,
    [intCannedPanelId] INT NOT NULL DEFAULT ((0)), 
    CONSTRAINT [PK_dbo.tblDBPanel] PRIMARY KEY CLUSTERED ([intPanelId] ASC),
    CONSTRAINT [FK_dbo.tblDBPanelFilter_dbo.tblDBPanel_intFilterId] FOREIGN KEY ([intFilterId]) REFERENCES [dbo].[tblDBPanelFilter] ([intFilterId])
);

