CREATE TABLE tblFADepreciateLog
(
    intLogId INT IDENTITY(1,1) NOT NULL,
    strBatchId NVARCHAR(40) COLLATE Latin1_General_CI_AS  NULL, 
    dtmDate DATETIME NULL,
    intEntityId INT NULL,
    CONSTRAINT [PK_tblFADepreciateLog] PRIMARY KEY CLUSTERED 
    (
	    [intLogId] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
     IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY]