CREATE  TABLE tblGLAccountImportStaging
(
	intAccountId INT null,
	intImportStagingId INT IDENTITY(1,1) NOT NULL,
	strBatchId	 NVARCHAR(40)  COLLATE Latin1_General_CI_AS NOT NULL ,
	strAccountId NVARCHAR(40)  COLLATE Latin1_General_CI_AS NOT NULL ,
	strStatus NVARCHAR(40)   COLLATE Latin1_General_CI_AS NULL ,
	intLineNo INT NOT NULL,
	ysnMissingSegment BIT null,
	ysnExist BIT NULL,
	dtmDate DATETIME NOT NULL,
	ysnAccountBuilt BIT NULL,
 CONSTRAINT [PK_tblGLAccountImportStaging] PRIMARY KEY CLUSTERED 
(
	[intImportStagingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[intImportStagingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]