CREATE TABLE [dbo].[tblGLDataFix](
	[intDataFixId] [int] IDENTITY(1,1) NOT NULL,
	[strDescription] [nvarchar](100) NULL,
 CONSTRAINT [PK_tblGLDataFix] PRIMARY KEY CLUSTERED 
(
	[intDataFixId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO