CREATE TABLE [dbo].[tblICImportStagingItem] (
	[intImportStagingItemId] [int] IDENTITY(1,1) NOT NULL,
	[strImportIdentifier] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[strItemNo] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strType] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strShortName] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strDescription] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strManufacturer] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strCommodity] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strBrand] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strModelNo] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strCategory] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[ysnStockedItem] BIT NULL,
	[ysnDyedFuel] BIT NULL,
	[ysnMSDSRequired] BIT NULL,
	[strEPANumber] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[ysnInboundTax] BIT NULL,
	[ysnOutboundTax] BIT NULL,
	[ysnRestrictedChemical] BIT NULL,
	[ysnFuelItem] BIT NULL,
	[ysnListBundleItemsSeparately] BIT NULL,
	[dblDenaturantPercentage] NUMERIC(38, 20) NULL,
	[ysnTonnageTax] BIT NULL,
	[ysnLoadTracking] BIT NULL,
	[dblMixOrder] NUMERIC(38, 20) NULL,
	[ysnHandAddIngredients] BIT NULL,
	[ysnExtendPickTicket] BIT NULL,
	[ysnExportEDI] BIT NULL,
	[ysnHazardMaterial] BIT NULL,
	[ysnMaterialFee] BIT NULL,
	[ysnAutoBlend] BIT NULL,
	[dblUserGroupFeePercentage] NUMERIC(38, 20) NULL,
	[dblWgtTolerancePercentage] NUMERIC(38, 20) NULL,
	[dblOverReceiveTolerancePercentage] NUMERIC(38, 20) NULL,
	[ysnLandedCost] BIT NULL,
	[strLeadTime] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[ysnTaxable] BIT NULL,
	[strKeywords] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[dblCaseQty] NUMERIC(38, 20) NULL,
	[dtmDateShip] DATETIME NULL,
	[dblTaxExempt] NUMERIC(38, 20) NULL,
	[ysnDropShip] BIT NULL,
	[ysnCommissionable] BIT NULL,
	[ysnSpecialCommission] BIT NULL,
	[ysnTankRequired] BIT NULL,
	[ysnAvailableforTM] BIT NULL,
	[dblDefaultPercentageFull] NUMERIC(38, 20) NULL,
	[dblRate] NUMERIC(38, 20) NULL,
	[strNACSCategory] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[ysnReceiptCommentReq] BIT NULL,
	[strDirectSale] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strPatronageCategory] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strPhysicalItem] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strVolumeRebateGroup] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strIngredientTag] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strMedicationTag] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strFuelCategory] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[ysnLotWeightsRequired] BIT NULL,
	[ysnUseWeighScales] BIT NULL,
	[strCountCode] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strRinRequired] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strStatus] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strLotTracking] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strBarcodePrint] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strFuelInspectFee] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[ysnSeparateStockForUOMs] BIT NULL DEFAULT ((1)),
	[dtmDateCreated] [datetime] NULL,
	[dtmDateModified] [datetime] NULL,
	[intCreatedByUserId] [int] NULL,
	[intModifiedByUserId] [int] NULL,
	[intConcurrencyId] [int] NULL,
    CONSTRAINT [PK_tblICImportStagingItem] PRIMARY KEY ([intImportStagingItemId] ASC)
)