CREATE TABLE [dbo].[tblICImportStagingCategoryLocation]
(
	[intImportStagingCategoryLocationId] INT NOT NULL IDENTITY,
	[strImportIdentifier] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[strCategory] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[strLocation] [nvarchar](200) COLLATE Latin1_General_CI_AS NOT NULL,
	[intCashRegisterDepartment] INT NULL,
	[ysnUpdatePrices] BIT NULL DEFAULT ((0)),
	[ysnUseTaxFlag1] BIT NULL DEFAULT ((0)),
	[ysnUseTaxFlag2] BIT NULL DEFAULT ((0)),
	[ysnUseTaxFlag3] BIT NULL DEFAULT ((0)),
	[ysnUseTaxFlag4] BIT NULL DEFAULT ((0)),
	[ysnBlueLaw1] BIT NULL DEFAULT ((0)),
	[ysnBlueLaw2] BIT NULL DEFAULT ((0)),
	[intNucleusGroupId] INT NULL,
	[dblTargetGrossProfit] NUMERIC(18, 6) NULL DEFAULT ((0)),
	[dblTargetInventoryCost] NUMERIC(18, 6) NULL DEFAULT ((0)),
	[dblCostInventoryBOM] NUMERIC(38, 20) NULL DEFAULT ((0)),
	[dblLowGrossMarginAlert] NUMERIC(18, 6) NULL DEFAULT ((0)),
	[dblHighGrossMarginAlert] NUMERIC(18, 6) NULL DEFAULT ((0)),
	[dtmLastInventoryLevelEntry] DATETIME NULL,
	[ysnNonRetailUseDepartment] BIT NULL DEFAULT ((0)),
	[ysnReportNetGross] BIT NULL DEFAULT ((0)),
	[ysnDepartmentForPumps] BIT NULL DEFAULT ((0)),
	[strConvertToPaidout] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[ysnDeleteFromRegister] BIT NULL DEFAULT ((0)),
	[ysnDeptKeyTaxed] BIT NULL DEFAULT ((0)),
	[strProductCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strFamily] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strClass] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[ysnFoodStampable] BIT NULL DEFAULT ((0)),
	[ysnReturnable] BIT NULL DEFAULT ((0)),
	[ysnSaleable] BIT NULL DEFAULT ((0)),
	[ysnPrePriced] BIT NULL DEFAULT ((0)),
	[ysnIdRequiredLiquor] BIT NULL DEFAULT ((0)),
	[ysnIdRequiredCigarette] BIT NULL DEFAULT ((0)),
	[intMinimumAge] INT NULL DEFAULT ((0)),
	[strGeneralItemNo] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[intConcurrencyId] INT NULL DEFAULT ((0)),
	[dtmDateCreated] DATETIME NULL,
	[dtmDateModified] DATETIME NULL,
	[intCreatedByUserId] INT NULL,
	[intModifiedByUserId] INT NULL,
	CONSTRAINT [PK_tblICImportStagingCategoryLocation] PRIMARY KEY ([intImportStagingCategoryLocationId])
)