CREATE TABLE [dbo].[tblICImportStagingReceiptItemLot]
(
    [intImportStagingReceiptItemLotId] INT IDENTITY(1, 1) NOT NULL,
    [strImportIdentifier] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	[intInventoryReceiptItemId] INT NOT NULL,
    [strLotNo] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strParentLotNo] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strUnitMeasure] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [dblQuantity] NUMERIC(38, 20) NULL,
    [dblGross] NUMERIC(38, 20) NULL,
    [dblTare] NUMERIC(38, 20) NULL,
    [strStorageUnit] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [dtmExpiryDate] DATETIME NULL,
    [strLotAlias] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strCertificate] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strProducer] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strCertificateId] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strTrackingNumber] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [dblStatedGrossPerUnit] NUMERIC(38, 20) NULL,
    [dblStatedTarePerUnit] NUMERIC(38, 20) NULL,
    [strContainerNo] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strGarden] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strOrigin] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [intUnitPallet] INT NULL,
    [intSeasonCropYear] INT NULL,
    [strVendorLotId] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [dtmManufacturedDate] DATETIME NULL,
    [strRemarks] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strMarkings] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strCondition] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [dtmCertified] DATETIME NULL,
    [dtmDateCreated] DATETIME NULL,
	[dtmDateModified] DATETIME NULL,
	[intCreatedByUserId] INT NULL,
	[intModifiedByUserId] INT NULL,
	[intConcurrencyId] INT NULL,
    CONSTRAINT [PK_tblICImportStagingReceiptItemLot] PRIMARY KEY ([intImportStagingReceiptItemLotId] ASC)
)