CREATE TABLE [dbo].[tblICLocationBinsReport]
	(
		[intKey] INT NOT NULL IDENTITY, 
		[intItemId] INT NULL, 
		[strType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[strItemNo] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
		[strDescription] NVARCHAR(500) COLLATE Latin1_General_CI_AS NULL, 
		[strLotTracking] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[strInventoryTracking] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[strStatus] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[intLocationId] INT NULL DEFAULT ((0)),
		[intItemLocationId] INT NULL DEFAULT ((0)),
		[intSubLocationId] INT NULL DEFAULT ((0)),
		[intCategoryId] INT NULL DEFAULT ((0)),
		[strCategoryCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[intCommodityId] INT NULL DEFAULT ((0)),
		[strCommodityCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[intStorageLocationId] INT NULL DEFAULT ((0)),
		[strLocationName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[strLocationType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[intStockUOMId] INT NULL DEFAULT ((0)),
		[strStockUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[strStockUOMType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[dblStockUnitQty] NUMERIC(38, 20) NULL DEFAULT(1),
		[intAllowNegativeInventory] INT NULL DEFAULT ((0)),
		[strAllowNegativeInventory] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[intCostingMethod] INT NULL DEFAULT ((0)),
		[strCostingMethod] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[dblAmountPercent] NUMERIC(38, 20) NULL DEFAULT(1),
		[dblSalePrice] NUMERIC(38, 20) NULL DEFAULT(1),
		[dblMSRPPrice] NUMERIC(38, 20) NULL DEFAULT(1),
		[strPricingMethod] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[dblLastCost] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblStandardCost] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblAverageCost] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblEndMonthCost] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblOnOrder] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblInTransitInbound] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblUnitOnHand] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblInTransitOutbound] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblBackOrder] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblOrderCommitted] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblUnitStorage] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblConsignedPurchase] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblConsignedSale] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblUnitReserved] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblAvailable] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblExtended] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblExtendedRetail] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblMinOrder] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblLeadTime] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblSuggestedQty] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblReorderPoint] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblNearingReorderBy] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblCapacity] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblSpaceAvailable] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblPercentFull] NUMERIC(38, 20) NULL DEFAULT(0),
		[dtmLastPurchaseDate] DATETIME NULL,
		[dtmLastSaleDate] DATETIME NULL,
		[strEntityVendor] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
		[dblAverageUsagePerPeriod] NUMERIC(38, 20) NULL DEFAULT(0),
		[dblInTransitDirect] NUMERIC(38, 20) NULL DEFAULT(0),
		[dtmDateCreated] DATETIME NULL,
        [dtmDateModified] DATETIME NULL,
        [intCreatedByUserId] INT NULL,
        [intModifiedByUserId] INT NULL, 
		CONSTRAINT [PK_tblICLocationBinsReport] PRIMARY KEY ([intKey])
	)