CREATE TABLE [dbo].[tblICImportStagingItemLocation]
(
    [intImportStagingItemLocationId] INT IDENTITY(1, 1) NOT NULL,
    [strImportIdentifier] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	[intLineNo] INT NULL,
    [strItemNo] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strLocation] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strPOSDescription] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strVendorId] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strCostingMethod] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strStorageLocation] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strStorageUnit] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strSaleUOM] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strGrossNetUOM] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strPurchaseUOM] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strFamily] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strClass] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strProductCode] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strPassportFuelID1] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strPassportFuelID2] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strPassportFuelID3] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [ysnTaxFlag1] BIT NULL DEFAULT(0),
    [ysnTaxFlag2] BIT NULL DEFAULT(0),
    [ysnTaxFlag3] BIT NULL DEFAULT(0),
    [ysnTaxFlag4] BIT NULL DEFAULT(0),
    [ysnActive] BIT NULL,
    [ysnPromotionalItem] BIT NULL DEFAULT(0),
    [ysnDepositRequired] BIT NULL DEFAULT(0),
    [strDepositPLU] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [intBottleDepositNo] INT NULL,
    [ysnSaleable] BIT NULL DEFAULT(0),
    [ysnQuantityRequired] BIT NULL DEFAULT(0),
    [ysnScaleItem] BIT NULL DEFAULT(0),
    [ysnFoodStampable] BIT NULL DEFAULT(0),
    [ysnReturnable] BIT NULL DEFAULT(0),
    [ysnPrePriced] BIT NULL DEFAULT(0),
    [ysnOpenPricedPLU] BIT NULL DEFAULT(0),
    [ysnLinkedItem] BIT NULL DEFAULT(0),
    [strVendorCategory] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [ysnIDRequiredLiquor] BIT NULL DEFAULT(0),
    [ysnIDRequiredCigarrettes] BIT NULL DEFAULT(0),
    [intMinimumAge] INT NULL,
    [ysnApplyBlueLaw1] BIT NULL DEFAULT(0),
    [ysnApplyBlueLaw2] BIT NULL DEFAULT(0),
    [ysnCarWash] BIT NULL DEFAULT(0),
    [intItemTypeCode] INT NULL,
    [intItemTypeSubcode] INT NULL,
    [ysnAllowNegativeInventory] BIT NULL DEFAULT(0),
    [dblReorderPoint] NUMERIC(38, 20) NULL,
    [dblMinOrder] NUMERIC(38, 20) NULL,
    [dblSuggestedQty] NUMERIC(38, 20) NULL,
    [dblLeadTime] NUMERIC(38, 20) NULL,
    [strInventoryCountGroup] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strCounted] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [ysnCountedDaily] BIT NULL DEFAULT(0),
    [ysnCountbySerialNumber] BIT NULL DEFAULT(0),
    [strSerialNumberBegin] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strSerialNumberEnd] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strStorageUnitNo] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [ysnAutoCalculateFreight] BIT NULL DEFAULT(0),
    [dblFreightRate] NUMERIC(38, 20) NULL,
    [strFreightTerm] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strShipVia] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [ysnStorageUnitRequired] BIT NULL DEFAULT(0),
    [dtmDateCreated] [datetime] NULL,
	[dtmDateModified] [datetime] NULL,
	[intCreatedByUserId] [int] NULL,
	[intModifiedByUserId] [int] NULL,
	[intConcurrencyId] [int] NULL,
    CONSTRAINT [PK_tblICImportStagingItemLocation] PRIMARY KEY ([intImportStagingItemLocationId] ASC)
)