CREATE TABLE [dbo].[tblICImportStagingOpeningBalance] (
	[intImportStagingOpeningBalanceId] [int] IDENTITY(1,1) NOT NULL,
	[strImportIdentifier] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[strLocationNo] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[dtmDate] DATETIME NULL,
	[strItemNo] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[dblQuantity] NUMERIC(38, 20) NULL,
	[dblUnitCost] NUMERIC(38, 20) NULL,
	[strOwnershipType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strDescription] NVARCHAR(1000) COLLATE Latin1_General_CI_AS NULL,
	[strWeightUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[dblNetWeight] NUMERIC(38, 20) NULL,
	[strLotNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strStorageLocation] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strStorageUnit] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intConcurrencyId] INT NULL,
	[intCompanyId] INT NULL, 
	[dtmCreated] DATETIME NULL DEFAULT (GETDATE()),
	[dtmDateCreated] DATETIME NULL,
	[dtmDateModified] DATETIME NULL,
	[intCreatedByUserId] INT NULL,
	[intModifiedByUserId] INT NULL,
	CONSTRAINT [PK_tblICImportStagingOpeningBalance] PRIMARY KEY ([intImportStagingOpeningBalanceId] ASC)
)