CREATE TABLE [dbo].[tblICInventoryShipment]
(
	[intInventoryShipmentId] INT NOT NULL IDENTITY, 
    [strBOLNumber] NVARCHAR(50) NOT NULL, 
    [dtmShipDate] DATETIME NOT NULL DEFAULT (getdate()), 
    [intOrderType] INT NOT NULL, 
    [strReferenceNumber] NVARCHAR(50) NULL, 
    [dtmRequestedArrivalDate] DATETIME NULL, 
    [intShipFromLocationId] INT NOT NULL, 
    [intCustomerId] INT NULL, 
    [strShipToAddress] NVARCHAR(MAX) NOT NULL, 
    [intFreightTermId] INT NOT NULL, 
    [ysnDirectShipment] BIT NULL DEFAULT ((0)), 
    [intCarrierId] INT NULL, 
    [strVessel] NVARCHAR(50) NULL, 
    [strProNumber] NVARCHAR(50) NULL, 
    [strDriverId] NVARCHAR(50) NULL, 
    [strSealNumber] NVARCHAR(50) NULL, 
    [dtmAppointmentTime] DATETIME NULL, 
    [dtmDepartureTime] DATETIME NULL, 
    [dtmArrivalTime] DATETIME NULL, 
    [dtmDeliveredDate] DATETIME NULL, 
    [dtmFreeTime] DATETIME NULL, 
    [strReceivedBy] NVARCHAR(50) NULL, 
    [intConcurrencyId] INT NULL DEFAULT ((0)), 
    CONSTRAINT [PK_tblICInventoryShipment] PRIMARY KEY ([intInventoryShipmentId]), 
    CONSTRAINT [AK_tblICInventoryShipment_strBOLNumber] UNIQUE ([strBOLNumber]), 
    CONSTRAINT [FK_tblICInventoryShipment_tblSMCompanyLocation] FOREIGN KEY ([intShipFromLocationId]) REFERENCES [tblSMCompanyLocation]([intCompanyLocationId]), 
    CONSTRAINT [FK_tblICInventoryShipment_tblSMFreightTerm] FOREIGN KEY ([intFreightTermId]) REFERENCES [tblSMFreightTerms]([intFreightTermId]), 
    CONSTRAINT [FK_tblICInventoryShipment_tblSMShipVia] FOREIGN KEY ([intCarrierId]) REFERENCES [tblSMShipVia]([intShipViaID]), 
)
