CREATE TABLE [dbo].[tblMFPickListDetail]
(
	[intPickListDetailId] INT NOT NULL IDENTITY,
	[intPickListId] INT NOT NULL, 
    [intLotId] INT NOT NULL,
	[intParentLotId] INT NULL,  
	[intItemId] INT NOT NULL,
	[intStorageLocationId] INT,
	[dblQuantity] NUMERIC(38, 20) NOT NULL, 
    [intItemUOMId] INT NOT NULL, 
    [dblIssuedQuantity] NUMERIC(38, 20) NULL, 
    [intItemIssuedUOMId] INT NULL,
	[dblPickQuantity] NUMERIC(38, 20) NOT NULL,
    [intPickUOMId] INT NOT NULL,
	[intStageLotId] INT,
	[dtmCreated] DATETIME NULL, 
    [intCreatedUserId] INT NULL,
	[dtmLastModified] DATETIME NULL, 
    [intLastModifiedUserId] INT NULL,
	[intConcurrencyId] INT NULL CONSTRAINT [DF_tblMFKitPickListDetail_intConcurrencyId] DEFAULT 0,
	CONSTRAINT [PK_tblMFPickListDetail_intPickListDetailId] PRIMARY KEY (intPickListDetailId),
	CONSTRAINT [FK_tblMFPickListDetail_intPickListId] FOREIGN KEY ([intPickListId]) REFERENCES [tblMFPickList]([intPickListId]),
	CONSTRAINT [FK_tblMFPickListDetail_tblICLot_inLotId] FOREIGN KEY ([intLotId]) REFERENCES [tblICLot]([intLotId]),
	CONSTRAINT [FK_tblMFPickListDetail_tblICParentLot_inParentLotId] FOREIGN KEY ([intParentLotId]) REFERENCES [tblICParentLot]([intParentLotId]), 
	CONSTRAINT [FK_tblMFPickListDetail_tblICItem_inItemId] FOREIGN KEY ([intItemId]) REFERENCES [tblICItem]([intItemId]),
	CONSTRAINT [FK_tblMFPickListDetail_tblICStorageLocation_intStorageLocationId] FOREIGN KEY ([intStorageLocationId]) REFERENCES [tblICStorageLocation]([intStorageLocationId]), 
	CONSTRAINT [FK_tblMFPickListDetail_tblICLot_intStageLotId] FOREIGN KEY ([intStageLotId]) REFERENCES [tblICLot]([intLotId]),
)
