CREATE TABLE [dbo].[tblMFWorkOrder]
(
	[intWorkOrderId] INT NOT NULL IDENTITY(1,1), 
    [strWorkOrderNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL , 
    [intItemId] INT NOT NULL, 
    [dblQuantity] NUMERIC(18, 6) NOT NULL, 
    [intItemUOMId] INT NOT NULL, 
    [intStatusId] INT NOT NULL, 
	[intManufacturingCellId] INT NOT NULL, 
    [intStorageLocationId] INT NULL,
	[intLocationId] INT NOT NULL,
	[dtmCreated] DATETIME NULL, 
    [intCreatedUserId] INT NULL,
	[dtmLastModified] DATETIME NULL, 
    [intLastModifiedUserId] INT NULL,
    [dtmExpectedDate] DATETIME NULL, 
    [intExecutionOrder] INT NULL, 
	[dtmReleasedDate] DATETIME NULL, 
    [dtmStartedDate] DATETIME NULL, 
    [dtmCompletedDate] DATETIME NULL, 
    [dtmOnHoldDate] DATETIME NULL, 
    [intProductionTypeId] INT NOT NULL,
	[dblProducedQuantity] NUMERIC(18, 6) NULL, 
    [dtmActualProductionStartDate] DATETIME NULL, 
    [dtmActualProductionEndDate] DATETIME NULL,	
	[ysnUseTemplate] BIT NOT NULL CONSTRAINT [DF_tblMFWorkOrder_ysnUseTemplate] DEFAULT 0, 
    [dblBinSize] NUMERIC(18, 6) NULL, 
    [dblPlannedQuantity] NUMERIC(18, 6) NULL, 
	[dblStagedQty] NUMERIC(18, 6) NULL, 
    [intMachineId] INT NULL, 
    [intStagingLocationId] INT NULL,
	[intParentWorkOrderId] INT NULL, 
    [intBlendRequirementId] INT NULL, 
    [intPickId] INT NULL, 
    [ysnKittingEnabled] BIT NOT NULL CONSTRAINT [DF_tblMFWorkOrder_ysnKittingEnabled] DEFAULT 0,
    [intProductOwnerId] INT NULL,  
    [intCustomerId] INT NULL, 
    [strSalesOrderNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strCustomerOrderNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strERPOrderNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intSalesOrderLineItemId] INT NULL, 
    [strLotId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strVendorLotNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intOrderHeaderId] INT NULL, 
    [strBOLNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [dtmEarliestDate] DATETIME NULL, 
    [dtmLatestDate] DATETIME NULL, 
    [dtmEarliestStartDate] DATETIME NULL, 
    [intSalesRepresentativeId] INT NULL, 
    [dtmPlannedDate] DATETIME NULL, 
    [intPlannedShiftId] INT NULL, 
    [intActualShiftId] INT NULL, 
	[strSpecialInstruction] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strComment] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[intBatchID] INT NULL,
	[intConcurrencyId] INT NULL CONSTRAINT [DF_tblMFWorkOrder_intConcurrencyId] DEFAULT 0,
	CONSTRAINT [PK_tblMFWorkOrder_intWorkOrderId] PRIMARY KEY (intWorkOrderId),
	CONSTRAINT [UQ_tblMFWorkOrder_strWorkOrderNo] UNIQUE ([strWorkOrderNo]),
	CONSTRAINT [FK_tblMFWorkOrder_tblICItem_intItemId] FOREIGN KEY ([intItemId]) REFERENCES [tblICItem]([intItemId]),
    CONSTRAINT [FK_tblMFWorkOrder_tblICItemUOM_intItemUOMId] FOREIGN KEY ([intItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),
	CONSTRAINT [FK_tblMFWorkOrder_tblMFWorkOrderStatus_intStatusId] FOREIGN KEY ([intStatusId]) REFERENCES [tblMFWorkOrderStatus]([intStatusId]), 
	CONSTRAINT [FK_tblMFWorkOrder_tblMFProductionType_intProductionTypeId] FOREIGN KEY ([intProductionTypeId]) REFERENCES [tblMFWorkOrderProductionType]([intProductionTypeId]), 
	CONSTRAINT [FK_tblMFWorkOrder_tblMFBlendRequirement_intBlendRequirementId] FOREIGN KEY ([intBlendRequirementId]) REFERENCES [tblMFBlendRequirement]([intBlendRequirementId]), 
	CONSTRAINT [FK_tblMFWorkOrder_tblICStorageLocation_intStorageLocationId] FOREIGN KEY ([intStorageLocationId]) REFERENCES [tblICStorageLocation]([intStorageLocationId]), 
	CONSTRAINT [FK_tblMFWorkOrder_tblSMCompanyLocation_intLocationId] FOREIGN KEY ([intLocationId]) REFERENCES [tblSMCompanyLocation]([intCompanyLocationId])
)