CREATE TABLE [dbo].[tblMBILOrder](
	[intOrderId] INT IDENTITY(1,1) NOT NULL,
	[intDispatchId] INT NULL,
	[strOrderNumber] NVARCHAR (30) COLLATE Latin1_General_CI_AS NULL,
	[strOrderStatus] NVARCHAR (40) COLLATE Latin1_General_CI_AS NULL,
	[dtmRequestedDate] DATETIME NULL,
	[intEntityId] INT NULL,
	[intSiteId] INT NULL,
	[intItemId] INT NULL,
	[dblQuantity] NUMERIC (18, 6) NULL,
	[dblPrice] NUMERIC (18, 6) NULL,
	[intContractDetailId] INT NULL,
	[intTermId] INT NULL,
	[strComments] NVARCHAR (400) COLLATE Latin1_General_CI_AS NULL,
	[intDriverId] INT				NULL,
	[intRouteId] INT NULL,
	[intStopNumber] INT	NULL,
	[intConcurrencyId] INT DEFAULT 1 NOT NULL,
	CONSTRAINT [PK_tblMBILOrder] PRIMARY KEY CLUSTERED ([intOrderId] ASC)
)