CREATE TABLE [dbo].[tblMFWorkOrderProducedLot]
(
	[intWorkOrderProducedLotId] INT NOT NULL IDENTITY(1,1), 
    [intWorkOrderId] INT NOT NULL, 
    [intLotId] INT NOT NULL, 
    [dblQuantity] NUMERIC(18, 6) NOT NULL, 
    [intItemUOMId] INT NOT NULL, 
    [dblWeightPerUnit] NUMERIC(18, 6) NULL, 
	[dblPhysicalCount] NUMERIC(18, 6) NULL, 
    [intPhysicalItemUOMId] INT NULL,
	[strDateCode] NVARCHAR(255) COLLATE Latin1_General_CI_AS NULL,
	[strMarking] NVARCHAR(255) COLLATE Latin1_General_CI_AS NULL,
	[intReleasedUserId] INT NULL,
	[dtmReleasedDate] DATETIME NULL,
    [intReleasedShiftId] INT NULL,
	[intShiftActivityId] INT NULL,
	[ysnReleased] BIT NULL DEFAULT 0,
	[strVesselNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strComment] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[intBatchId] INT NULL,
	[dtmCreated] DATETIME NULL, 
    [intCreatedUserId] INT NULL,
	[dtmLastModified] DATETIME NULL, 
    [intLastModifiedUserId] INT NULL,
	[intConcurrencyId] INT NULL CONSTRAINT [DF_tblMFWorkOrderProducedLot_intConcurrencyId] DEFAULT 0,
	CONSTRAINT [PK_tblMFWorkOrderProducedLot_intWorkOrderProducedLotId] PRIMARY KEY ([intWorkOrderProducedLotId]),
	CONSTRAINT [FK_tblMFWorkOrderProducedLot_tblMFWorkOrder_intWorkOrderId] FOREIGN KEY ([intWorkOrderId]) REFERENCES [tblMFWorkOrder]([intWorkOrderId]) ON DELETE CASCADE,
	CONSTRAINT [FK_tblMFWorkOrderProducedLot_tblICLot_inLotId] FOREIGN KEY ([intLotId]) REFERENCES [tblICLot]([intLotId]),
	CONSTRAINT [FK_tblMFWorkOrderProducedLot_tblICItemUOM_intItemUOMId] FOREIGN KEY ([intItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),
	CONSTRAINT [FK_tblMFWorkOrderProducedLot_tblICItemUOM_intItemUOMId_intPhysicalItemUOMId] FOREIGN KEY ([intPhysicalItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),
)
