CREATE TABLE [dbo].[tblMBILLoadSchedule](
	[intLoadScheduleId] [int] IDENTITY(1,1) NOT NULL,
	[intLoadId] [int] NOT NULL,
	[intLoadDetailId] [int] NOT NULL,
	[intDriverEntityId] [int] NOT NULL,
	[strLoadNumber] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[strType] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[intItemId] [int] NOT NULL,
	[strItemNo] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strItemDescription] [nvarchar](175) COLLATE Latin1_General_CI_AS NULL,
	[dblQuantity] [decimal](18, 6) NULL,
	[strItemUOM] [nvarchar](75) COLLATE Latin1_General_CI_AS NULL,
	[dblGross] [decimal](18, 6) NULL,
	[dblTare] [decimal](18, 6) NULL,
	[dblNet] [decimal](18, 6) NULL,
	[strWeightItemUOM] [nvarchar](75) COLLATE Latin1_General_CI_AS NULL,
	[intEntityId] [int] NOT NULL,
	[strName] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[intEntityLocationId] [int] NULL,
	[strShipName] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[strAddress] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[strCity] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strCountry] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strZipCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strEmail] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strPhone] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strMobile] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[dblLongitude] [numeric](18, 6) NULL,
	[dblLatitude] [numeric](18, 6) NULL,
	[strCompanyName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[intCompanyLocationId] [int] NULL,
	[strCompanyLocationName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyLocationAddress] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyLocationCity] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyLocationCountry] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyLocationState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyLocationZipCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyLocationMail] [nvarchar](150) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyLocationPhone] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[dblCompanyLocationLongitude] [numeric](18, 6) NULL,
	[dblCompanyLocationLatitude] [numeric](18, 6) NULL,
	[dtmSchedulePullDate] [datetime] NULL,
	[dtmScheduleDeliveryDate] [datetime] NULL,
	[strBOL] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strPONumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[strTruckNo] [nvarchar](150) COLLATE Latin1_General_CI_AS NULL,
	[strTrailerNo] [nvarchar](150) COLLATE Latin1_General_CI_AS NULL ,
	[intTruckId] [int] NULL,
 CONSTRAINT [PK_tblMBILLoadSchedule] PRIMARY KEY CLUSTERED ([intLoadScheduleId] ASC)
)
GO


