CREATE TABLE [dbo].[tblPRTypeTax](
	[intTypeTaxId] [int] IDENTITY(1,1) NOT NULL,
	[strTax] [nvarchar](50) NOT NULL,
	[strDescription] [nvarchar](50) NULL,
	[strCheckLiteral] [nvarchar](50) NOT NULL,
	[strCalculationType] [nvarchar](20) NULL,
	[strType] [nvarchar](40) NULL,
	[dblAmount] [numeric](18, 6) NULL DEFAULT ((0)),
	[dblLimit] [numeric](18, 6) NULL DEFAULT ((0)),
	[intTypeTaxStateId] INT NULL,
	[intTypeTaxLocalId] INT NULL,
	[intTaxAgencyId] INT NULL,
	[intAccountId] INT NULL,
	[intExpenseAccountId] INT NULL,
	[strPaidBy] [nvarchar](10) NULL DEFAULT ('Employee'),
	[ysnCreatePayable] [bit]  NOT NULL DEFAULT ((0)),
	[intVendorId] INT NULL,
	[intSort] INT NULL,
	[intConcurrencyId] INT NULL DEFAULT ((1)), 
    CONSTRAINT [PK_tblPRTypeTax] PRIMARY KEY ([intTypeTaxId]), 
    CONSTRAINT [AK_tblPRTypeTax_strTax] UNIQUE ([strTax]),
) ON [PRIMARY]
GO