CREATE TABLE [dbo].[tblPATCompanyPreference]
(
	[intCompanyPreferenceId] INT NOT NULL IDENTITY, 
    [intYearEnd] INT NULL, 
    [intGrainDiscountId] INT NULL, 
    [intGrainStorageId] INT NULL, 
    [intServiceChargeId] INT NULL, 
	[strDebitMemos] CHAR(1) NULL,
	[strDiscountGiven] CHAR(1) NULL,
    [strRefund] CHAR(1) NULL, 
    [dblMinimumRefund] NUMERIC(18, 6) NULL, 
    [dblServiceFee] NUMERIC(18, 6) NULL, 
    [dblCutoffAmount] NUMERIC(18, 6) NULL, 
    [strCutoffTo] NVARCHAR(20) NULL, 
    [strPayOnGrain] NVARCHAR(20) NULL, 
    [dblFederalBackup] NUMERIC(18, 6) NULL, 
    [intCheckbookAccountId] INT NULL, 
    [strPrintCheck] NVARCHAR(2) NULL, 
    [dblMinimumDividends] NUMERIC(18, 6) NULL, 
    [ysnProRatedDividends] BIT NULL, 
    [dtmCutoffDate] DATETIME NULL, 
    [intVotingStockId] INT NULL, 
    [intNonVotingStockId] INT NULL, 
    [intFractionalShareId] INT NULL, 
    [intServiceFeeIncomeId] INT NULL, 
    [intFWTLiabilityAccountId] INT NULL, 
    [intDividendsGLAccount] INT NULL, 
    [intTreasuryGLAccount] INT NULL, 
    [intConcurrencyId] INT NULL, 
    CONSTRAINT [PK_tblPATCompanyPreference] PRIMARY KEY ([intCompanyPreferenceId]) 
)
