CREATE TABLE [dbo].[tblPATCustomerStock]
(
	[intCustomerStockId] INT NOT NULL IDENTITY, 
    [intCustomerPatronId] INT NOT NULL, 
    [intStockId] INT NOT NULL, 
    [strIssueNo] NVARCHAR(25) COLLATE Latin1_General_CI_AS NULL,
    [strCertificateNo] NVARCHAR(25) COLLATE Latin1_General_CI_AS NOT NULL, 
    [strStockStatus] NVARCHAR(25) COLLATE Latin1_General_CI_AS NOT NULL, 
    [dblSharesNo] NUMERIC(18, 6) NOT NULL, 
    [dtmIssueDate] DATETIME NOT NULL, 
    [strActivityStatus] NVARCHAR(25) COLLATE Latin1_General_CI_AS NOT NULL, 
	[dtmRetireDate] DATETIME NULL,
    [intTransferredFrom] INT NULL, 
    [dtmTransferredDate] DATETIME NULL, 
	[dblParValue] NUMERIC(18,6) NULL,
	[dblFaceValue] NUMERIC(18,6) NULL,
	[ysnPosted] BIT NULL DEFAULT 0,
	[ysnRetiredPosted] BIT NULL DEFAULT 0,
	[intBillId] INT NULL,
	[intInvoiceId] INT NULL,
    [intConcurrencyId] INT NULL DEFAULT 0, 
    CONSTRAINT [PK_tblPATCustomerStock] PRIMARY KEY ([intCustomerStockId]), 
    CONSTRAINT [FK_tblPATCustomerStock_tblPATStockClassification] FOREIGN KEY ([intStockId]) REFERENCES [tblPATStockClassification]([intStockId]),
	CONSTRAINT [AK_tblPATCustomerStock_strCertificateNo] UNIQUE ([strCertificateNo]),
	CONSTRAINT [FK_tblPATCustomerStock_tblAPBill] FOREIGN KEY (intBillId) REFERENCES [tblAPBill]([intBillId]) ON DELETE SET NULL,
	CONSTRAINT [FK_tblPATCustomerStock_tblARInvoice] FOREIGN KEY (intInvoiceId) REFERENCES [tblARInvoice]([intInvoiceId]) ON DELETE SET NULL
)