CREATE TABLE [dbo].[tblQMAuction]
(
	[intAuctionId] INT IDENTITY(1,1) NOT NULL,
	[intConcurrencyId] INT NULL DEFAULT 0, 
	[intSampleId] INT NOT NULL, 
	[intSaleYearId] INT, 
	[strSaleYear] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strSaleNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[dtmSaleDate] DATETIME NULL, 
	[intCatalogueTypeId] INT NULL, 
	[strCatalogueType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[dtmPromptDate] DATETIME NULL, 
	[strChopNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intBrokerId] INT NULL, 
	[strBroker] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intGradeId] INT NULL, 
	[strGrade] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intLeafCategoryId] INT NULL, 
	[strLeafCategory] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intManufacturingLeafTypeId] INT NULL,
	[strManufacturingLeafType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intSeasonId] INT NULL, 
	[strSeason] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intGardenMarkId] INT NULL,
	[strGardenMark] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[dtmManufacturingDate] DATETIME NULL, 
	[intTotalNumberOfPackageBreakups] BIGINT NULL,
	[dblNetWtPerPackages] NUMERIC(18, 6) NULL,
	[intNoOfPackages] BIGINT NULL,
	[dblNetWtSecondPackageBreak] NUMERIC(18, 6) NULL,
	[intNoOfPackagesSecondPackageBreak] BIGINT NULL,
	[dblNetWtThirdPackageBreak] NUMERIC(18, 6) NULL,
	[intNoOfPackagesThirdPackageBreak] BIGINT NULL,
	[intProductLineId] INT NULL,
	[strProductLine] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[ysnOrganic] BIT DEFAULT 0,
	[dblSupplierValuationPrice] NUMERIC(18, 6) NULL,
	[intProducerId] INT NULL,
	[strProducer] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intPurchaseGroupId] INT NULL,
	[strPurchaseGroup] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strERPRefNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[dblGrossWeight] NUMERIC(18, 6) NULL,
	[dblTareWeight] NUMERIC(18, 6) NULL,
	[dblNetWeight] NUMERIC(18, 6) NULL,
	[strBatchNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[str3PLStatus] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strAdditionalSupplierReference] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intAWBSampleReceived] BIGINT NULL,
	[strAWBSampleReference] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[dblBasePrice] NUMERIC(18, 6) NULL,
	[ysnBoughtAsReserve] BIT DEFAULT 0,
	[intCurrencyId] INT NULL,
	[strCurrency] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[ysnEuropeanCompliantFlag] BIT DEFAULT 0,
	[intEvaluatorsCodeAtTBOId] INT NULL,
	[strEvaluatorsCodeAtTBO] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intFromLocationCodeId] INT NULL,
	[strFromLocationCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strSampleBoxNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intBrandId] INT NULL,
	[strBrand] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intValuationGroupId] INT NULL,
	[strValuationGroupName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strMusterLot] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strMissingLot] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intMarketZoneId] INT NULL,
	[strMarketZoneCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intDestinationStorageLocationId] INT NULL,
	[strDestinationStorageLocationName] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strComments2] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS,
	[strComments3] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS,

	CONSTRAINT [PK_tblQMAuction] PRIMARY KEY ([intAuctionId]), 
	CONSTRAINT [FK_tblQMAuction_tblQMSample_intSampleId] FOREIGN KEY ([intSampleId]) REFERENCES [dbo].[tblQMSample]([intSampleId]),
	CONSTRAINT [FK_tblQMAuction_tblQMSaleYear_intSaleYearId] FOREIGN KEY ([intSaleYearId]) REFERENCES [dbo].[tblQMSaleYear]([intSaleYearId]),
	CONSTRAINT [FK_tblQMAuction_tblQMCatalogueType_intCatalogueTypeId] FOREIGN KEY ([intCatalogueTypeId]) REFERENCES [dbo].[tblQMCatalogueType]([intCatalogueTypeId]),
	CONSTRAINT [FK_tblQMAuction_tblEMEntity_intBrokerId] FOREIGN KEY ([intBrokerId]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityAttribute2_intLeafCategoryId] FOREIGN KEY ([intLeafCategoryId]) REFERENCES [dbo].[tblICCommodityAttribute2]([intCommodityAttributeId2]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityAttribute_intManufacturingLeafTypeId] FOREIGN KEY ([intManufacturingLeafTypeId]) REFERENCES [dbo].[tblICCommodityAttribute]([intCommodityAttributeId]),
	CONSTRAINT [FK_tblQMAuction_tblQMGardenMark_intGardenMarkId] FOREIGN KEY ([intGardenMarkId]) REFERENCES [dbo].[tblQMGardenMark]([intGardenMarkId]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityProductLine_intProductLineId] FOREIGN KEY ([intProductLineId]) REFERENCES [dbo].[tblICCommodityProductLine]([intCommodityProductLineId]),
	CONSTRAINT [FK_tblQMAuction_tblEMEntity_intProducerId_intProducerId] FOREIGN KEY ([intProducerId]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),  
	CONSTRAINT [FK_tblQMAuction_tblSMPurchasingGroup_intPurchaseGroupId] FOREIGN KEY ([intPurchaseGroupId]) REFERENCES [dbo].[tblSMPurchasingGroup]([intPurchasingGroupId]),  
	CONSTRAINT [FK_tblQMAuction_tblSMCurrency_intCurrencyId] FOREIGN KEY (intCurrencyId) REFERENCES [dbo].[tblSMCurrency]([intCurrencyID]),
	CONSTRAINT [FK_tblQMAuction_tblEMEntity_intEvaluatorsCodeAtTBOId] FOREIGN KEY ([intEvaluatorsCodeAtTBOId]) REFERENCES [dbo].[tblEMEntity]([intEntityId]), -- User
	CONSTRAINT [FK_tblQMAuction_tblSMCity_intFromLocationCodeId] FOREIGN KEY ([intFromLocationCodeId]) REFERENCES [dbo].[tblSMCity]([intCityId]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityAttribute_intSeasonId] FOREIGN KEY ([intSeasonId]) REFERENCES [dbo].[tblICCommodityAttribute]([intCommodityAttributeId]), -- Color
	CONSTRAINT [FK_tblQMAuction_tblICCommodityAttribute_intGradeId] FOREIGN KEY ([intGradeId]) REFERENCES [dbo].[tblICCommodityAttribute]([intCommodityAttributeId]), -- Grade
	CONSTRAINT [FK_tblQMAuction_tblICBrand_intBrandId] FOREIGN KEY ([intBrandId]) REFERENCES [dbo].[tblICBrand]([intBrandId]), -- Size
	CONSTRAINT [FK_tblQMAuction_tblCTValuationGroup_intValuationGroupId] FOREIGN KEY ([intValuationGroupId]) REFERENCES [dbo].[tblCTValuationGroup]([intValuationGroupId]), -- Leaf Style
	CONSTRAINT [FK_tblQMAuction_tblARMarketZone_intMarketZoneId] FOREIGN KEY ([intMarketZoneId]) REFERENCES [dbo].[tblARMarketZone]([intMarketZoneId]),
	CONSTRAINT [FK_tblQMAuction_tblICStorageLocation_intDestinationStorageLocationId] FOREIGN KEY ([intDestinationStorageLocationId]) REFERENCES [dbo].[tblICStorageLocation]([intStorageLocationId]),
)