CREATE TABLE [dbo].[tblQMSampleOtherBuyers]
(
	[intOtherBuyerId] INT IDENTITY(1,1) NOT NULL, 
    [intSampleId] INT NOT NULL, 
    [intBuyer1Id] INT NULL, 
    [strBuyer1] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB1QtyBought] NUMERIC(18, 6) NULL, 
    [intB1QtyUOMId] INT NULL, 
    [dblB1Price] NUMERIC(18, 6) NULL, 
    [intB1PriceUOMId] INT NULL,
    [intBuyer2Id] INT NULL, 
    [strBuyer2] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB2QtyBought] NUMERIC(18, 6) NULL, 
    [intB2QtyUOMId] INT NULL, 
    [dblB2Price] NUMERIC(18, 6) NULL, 
    [intB2PriceUOMId] INT NULL,
    [intBuyer3Id] INT NULL, 
    [strBuyer3] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB3QtyBought] NUMERIC(18, 6) NULL, 
    [intB3QtyUOMId] INT NULL, 
    [dblB3Price] NUMERIC(18, 6) NULL, 
    [intB3PriceUOMId] INT NULL,
    [intBuyer4Id] INT NULL, 
    [strBuyer4] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB4QtyBought] NUMERIC(18, 6) NULL, 
    [intB4QtyUOMId] INT NULL, 
    [dblB4Price] NUMERIC(18, 6) NULL, 
    [intB4PriceUOMId] INT NULL,
    [intBuyer5Id] INT NULL, 
    [strBuyer5] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB5QtyBought] NUMERIC(18, 6) NULL, 
    [intB5QtyUOMId] INT NULL, 
    [dblB5Price] NUMERIC(18, 6) NULL, 
    [intB5PriceUOMId] INT NULL,
    [intConcurrencyId] INT NULL DEFAULT 0, 
    CONSTRAINT [PK_tblQMSampleOtherBuyers] PRIMARY KEY ([intOtherBuyerId])

)
