CREATE TABLE [dbo].[tblQMAuction]
(
	[intAuctionId] INT IDENTITY(1,1) NOT NULL,
	[intConcurrencyId] INT NULL DEFAULT 0, 
	[intSampleId] INT NOT NULL, 
	[intSaleYearId] INT, 
	[strSaleYear] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[dblSaleNumber] NUMERIC(18, 0) NULL,
	[dtmSaleDate] DATETIME NULL, 
	[intCatalogueTypeId] INT NULL, 
	[strCatalogueType] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[dtmPromptDate] DATETIME NULL, 
	[strChopNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intBrokerId] INT NOT NULL, 
	[strBroker] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strGrade] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intLeafCategoryId] INT NULL, 
	[strLeafCategory] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intManufacturingLeafTypeId] INT NULL,
	[strManufacturingLeafType] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strSeason] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intGardenMarkId] INT NULL,
	[strGardenMark] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[dtmManufacturingDate] DATETIME NULL, 
	[dblTotalNumberOfPackageBreakups] NUMERIC(18, 0) NULL,
	[dblNetWtPerPackages] NUMERIC(18, 6) NULL,
	[dblNoOfPackages] NUMERIC(18, 0) NULL,
	[dblNetWtSecondPackageBreak] NUMERIC(18, 6) NULL,
	[dblNoOfPackagesSecondPackageBreak] NUMERIC(18, 0) NULL,
	[dblNetWtThirdPackageBreak] NUMERIC(18, 6) NULL,
	[dblNoOfPackagesThirdPackageBreak] NUMERIC(18, 0) NULL,
	[intProductLineId] INT NULL,
	[strProductLine] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[ysnOrganic] BIT DEFAULT 0,
	[dblSupplierValuationPrice] NUMERIC(18, 6) NULL,
	[intProducerId] INT NULL,
	[strProducer] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intPurchaseGroupId] INT NULL,
	[strPurchaseGroup] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strERPRefNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[dblGrossWeight] NUMERIC(18, 6) NULL,
	[dblTareWeight] NUMERIC(18, 6) NULL,
	[dblNetWeight] NUMERIC(18, 6) NULL,
	[strLotNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[str3PLStatus] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strAdditionalSupplierReference] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[dblAWBSampleReceived] NUMERIC(18, 0) NULL,
	[strAWBSampleReference] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[dblBasePrice] NUMERIC(18, 6) NULL,
	[ysnBoughtAsReserve] BIT DEFAULT 0,
	[intCurrencyId] INT NULL,
	[strCurrency] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[ysnEuropeanCompliantFlag] BIT DEFAULT 0,
	[intEvaluatorsCodeAtTBOId] INT NULL,
	[strEvaluatorsCodeAtTBO] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intFromLocationCodeId] INT NULL,
	[strFromLocationCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strSampleBoxNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intColourId] INT NULL,
	[strColour] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strSize] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strMusterLot] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strMissingLot] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intMarketZoneId] INT NULL,
	[strMarketZoneCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[intStorageLocationId] INT NULL,
	[strStorageLocationName] NVARCHAR(50) COLLATE Latin1_General_CI_AS,
	[strComments2] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS,
	[strComments3] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS,

	CONSTRAINT [PK_tblQMAuction] PRIMARY KEY ([intAuctionId]), 
	CONSTRAINT [FK_tblQMAuction_tblQMSample] FOREIGN KEY ([intSampleId]) REFERENCES [dbo].[tblQMSample]([intSampleId]),
	CONSTRAINT [FK_tblQMAuction_tblQMSaleYear] FOREIGN KEY ([intSaleYearId]) REFERENCES [dbo].[tblQMSaleYear]([intSaleYearId]),
	CONSTRAINT [FK_tblQMAuction_tblQMCatalogueType] FOREIGN KEY ([intCatalogueTypeId]) REFERENCES [dbo].[tblQMCatalogueType]([intCatalogueTypeId]),
	CONSTRAINT [FK_tblQMAuction_tblEMEntity_intBrokerId] FOREIGN KEY ([intBrokerId]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityAttribute2] FOREIGN KEY ([intLeafCategoryId]) REFERENCES [dbo].[tblICCommodityAttribute2]([intCommodityAttributeId2]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityAttribute1] FOREIGN KEY ([intManufacturingLeafTypeId]) REFERENCES [dbo].[tblICCommodityAttribute1]([intCommodityAttributeId1]),
	CONSTRAINT [FK_tblQMAuction_tblQMGardenMark] FOREIGN KEY ([intGardenMarkId]) REFERENCES [dbo].[tblQMGardenMark]([intGardenMarkId]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityProductLine] FOREIGN KEY ([intProductLineId]) REFERENCES [dbo].[tblICCommodityProductLine]([intCommodityProductLineId]),
	CONSTRAINT [FK_tblQMAuction_tblEMEntity_intProducerId] FOREIGN KEY ([intProducerId]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),  
	CONSTRAINT [FK_tblQMAuction_tblEMEntity_intPurchaseGroupId] FOREIGN KEY ([intPurchaseGroupId]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),  
	CONSTRAINT [FK_tblQMAuction_tblSMCurrency] FOREIGN KEY (intCurrencyId) REFERENCES [dbo].[tblSMCurrency]([intCurrencyID]),
	CONSTRAINT [FK_tblQMAuction_tblEMEntity_intEvaluatorsCodeAtTBOId] FOREIGN KEY ([intEvaluatorsCodeAtTBOId]) REFERENCES [dbo].[tblEMEntity]([intEntityId]), -- User
	CONSTRAINT [FK_tblQMAuction_tblSMCity_intFromLocationCodeId] FOREIGN KEY ([intFromLocationCodeId]) REFERENCES [dbo].[tblSMCity]([intCityId]),
	CONSTRAINT [FK_tblQMAuction_tblICCommodityAttribute] FOREIGN KEY ([intColourId]) REFERENCES [dbo].[tblICCommodityAttribute]([intCommodityAttributeId]), -- Season
	CONSTRAINT [FK_tblQMAuction_tblARMarketZone_intMarketZoneId] FOREIGN KEY ([intMarketZoneId]) REFERENCES [dbo].[tblARMarketZone]([intMarketZoneId]),
	CONSTRAINT [FK_tblQMAuction_tblICStorageLocation_intStorageLocationId] FOREIGN KEY ([intStorageLocationId]) REFERENCES [dbo].[tblICStorageLocation]([intStorageLocationId]),
)