CREATE TABLE [dbo].[tblQMSampleOtherBuyers]
(
	[intOtherBuyerId] INT IDENTITY(1,1) NOT NULL, 
    [intSampleId] INT NOT NULL, 
    [intBuyer1Id] INT NULL, 
    [strBuyer1] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB1QtyBought] NUMERIC(18, 6) NULL, 
    [intB1QtyUOMId] INT NULL, 
	[strB1QtyUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB1Price] NUMERIC(18, 6) NULL, 
    [intB1PriceUOMId] INT NULL,
	[strB1PriceUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [intBuyer2Id] INT NULL, 
    [strBuyer2] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB2QtyBought] NUMERIC(18, 6) NULL, 
    [intB2QtyUOMId] INT NULL, 
	[strB2QtyUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB2Price] NUMERIC(18, 6) NULL, 
    [intB2PriceUOMId] INT NULL,
	[strB2PriceUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [intBuyer3Id] INT NULL, 
    [strBuyer3] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB3QtyBought] NUMERIC(18, 6) NULL, 
    [intB3QtyUOMId] INT NULL, 
	[strB3QtyUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB3Price] NUMERIC(18, 6) NULL, 
    [intB3PriceUOMId] INT NULL,
	[strB3PriceUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [intBuyer4Id] INT NULL, 
    [strBuyer4] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB4QtyBought] NUMERIC(18, 6) NULL, 
    [intB4QtyUOMId] INT NULL, 
	[strB4QtyUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB4Price] NUMERIC(18, 6) NULL, 
    [intB4PriceUOMId] INT NULL,
	[strB4PriceUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [intBuyer5Id] INT NULL, 
    [strBuyer5] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB5QtyBought] NUMERIC(18, 6) NULL, 
    [intB5QtyUOMId] INT NULL, 
	[strB5QtyUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [dblB5Price] NUMERIC(18, 6) NULL, 
    [intB5PriceUOMId] INT NULL,
	[strB5PriceUOM] NVARCHAR(50) COLLATE Latin1_General_CI_AS, 
    [intConcurrencyId] INT NULL DEFAULT 0, 
    CONSTRAINT [PK_tblQMSampleOtherBuyers] PRIMARY KEY ([intOtherBuyerId]),
    CONSTRAINT [FK_tblQMSampleOtherBuyers_tblEMEntity_intBuyer1Id] FOREIGN KEY ([intBuyer1Id]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),
	CONSTRAINT [FK_tblQMSampleOtherBuyers_tblEMEntity_intBuyer2Id] FOREIGN KEY ([intBuyer2Id]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),
	CONSTRAINT [FK_tblQMSampleOtherBuyers_tblEMEntity_intBuyer3Id] FOREIGN KEY ([intBuyer3Id]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),
	CONSTRAINT [FK_tblQMSampleOtherBuyers_tblEMEntity_intBuyer4Id] FOREIGN KEY ([intBuyer4Id]) REFERENCES [dbo].[tblEMEntity]([intEntityId]),
	CONSTRAINT [FK_tblQMSampleOtherBuyers_tblEMEntity_intBuyer5Id] FOREIGN KEY ([intBuyer5Id]) REFERENCES [dbo].[tblEMEntity]([intEntityId])

)