CREATE TABLE [dbo].[tblRKCreditInsurance] 
(
    [intCreditInsuranceId] INT IDENTITY(1,1) NOT NULL,
	[strTransaction] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL,
    [intEntityId] INT NOT NULL,
	[strEntityName] NVARCHAR(50) COLLATE Latin1_General_CI_AS  NOT NULL,
    [strPolicyNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS  NOT NULL,
    [dblInsuranceCoverage] NUMERIC(18, 6) NULL,
    [dblReimbursementDays] NUMERIC(18, 6) NULL,
	[dblDaysToClaim] NUMERIC(18, 6) NULL,
	[intCommodityAttributeId] INT NOT NULL,
	[strDescription] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NOT NULL,
	[dblPremiumPercent] NUMERIC(18, 6) NULL,
	[dtmValidFrom] DATETIME NULL, 
	[dtmValidTo] DATETIME NULL, 
	[intCommodityId] INT NOT NULL,
	[strCommodityCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL,
	[intInsuranceTypeId] INT NOT NULL,
	[strInsuranceType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL,
	[dblAggregatedPolicyAmount] NUMERIC(18, 6) NOT NULL, 
	[strRemarks] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	[intCurrencyID] INT NOT NULL,
	[strCurrency] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NOT NULL,
	[intConcurrencyId] INT NOT NULL DEFAULT 1,
	CONSTRAINT [PK_tblRKCreditInsurance_intCreditInsuranceId] PRIMARY KEY ([intCreditInsuranceId]),
	CONSTRAINT [FK_tblRKCreditInsurance_tblICCommodity_intCommodityId] FOREIGN KEY ([intCommodityId]) REFERENCES [tblICCommodity]([intCommodityId]),
	CONSTRAINT [FK_tblRKCreditInsurance_tblEMEntity_intEntityId] FOREIGN KEY (intEntityId) REFERENCES tblEMEntity([intEntityId]),
	CONSTRAINT [FK_tblRKCreditInsurance_tblICCommodityAttribute_intCommodityAttributeId] FOREIGN KEY (intCommodityAttributeId) REFERENCES tblICCommodityAttribute([intCommodityAttributeId]),
	CONSTRAINT [FK_tblRKCreditInsurance_tblSMCurrency_intCurrencyID] FOREIGN KEY (intCurrencyID) REFERENCES tblSMCurrency([intCurrencyID]),
	CONSTRAINT [UQ_tblRKCreditInsurance_strPolicyNumber] UNIQUE NONCLUSTERED ([strPolicyNumber] ASC)
)
