CREATE TABLE [dbo].[tblRKCurExpStock]
(
	[intCurExpStockId] INT IDENTITY(1,1) NOT NULL,	
	[intConcurrencyId] INT NOT NULL, 
	[intCurrencyExposureId] INT NOT NULL, 
	[intContractDetailId] INT NOT NULL, 
	[strLotNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL,
	[intStorageLocationId] int NULL,
	[intItemId] int NULL,
	[intFutureMarketId] int NULL,
	[strSpotMonth] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL,
	[dblClosingPrice]  NUMERIC(24, 6) NULL,	
	[dblMarketPremium]  NUMERIC(24, 6) NULL,	
	[intMarketPremiumCurrencyId] int NULL,
	[intMarketPremiumUOMId] int NULL,
	[dblMarketPrice]  NUMERIC(24, 6) NULL,	
	[intMarketPriceCurrencyId] int NULL,
	[intMarketPriceUOMId] int NULL,
	[dblQuantity]  NUMERIC(24, 6) NOT NULL,	
	[dblValue]  NUMERIC(24, 6) NOT NULL,	
	[intCompanyId] int NULL,   

	CONSTRAINT [PK_tblRKCurExpStock_intCurExpStockId] PRIMARY KEY (intCurExpStockId),   
	CONSTRAINT [FK_tblRKCurExpStock_tblRKCurrencyExposure_intCurrencyExposureId] FOREIGN KEY([intCurrencyExposureId])REFERENCES [dbo].[tblRKCurrencyExposure] (intCurrencyExposureId) ON DELETE CASCADE,  
	CONSTRAINT [FK_tblRKCurExpStock_tblCTContractDetail_intContractDetailId] FOREIGN KEY(intContractDetailId)REFERENCES [dbo].[tblCTContractDetail] (intContractDetailId),
	CONSTRAINT [FK_tblRKCurExpStock_tblICStorageLocation_intStorageLocationId] FOREIGN KEY(intStorageLocationId)REFERENCES [dbo].[tblICStorageLocation] (intStorageLocationId),
	CONSTRAINT [FK_tblRKCurExpStock_tblICItem_intItemId] FOREIGN KEY(intItemId)REFERENCES [dbo].[tblICItem] (intItemId),
	CONSTRAINT [FK_tblRKCurExpStock_tblRKFutureMarket_intFutureMarketId] FOREIGN KEY(intFutureMarketId)REFERENCES [dbo].[tblRKFutureMarket] (intFutureMarketId),
	CONSTRAINT [FK_tblRKCurExpStock_tblSMCurrency_intMarketPremiumCurrencyId] FOREIGN KEY(intMarketPremiumCurrencyId)REFERENCES [dbo].[tblSMCurrency] (intCurrencyID),
	CONSTRAINT [FK_tblRKCurExpStock_tblICUnitMeasure_intMarketPremiumUOMId] FOREIGN KEY(intMarketPremiumUOMId)REFERENCES [dbo].[tblICUnitMeasure] (intUnitMeasureId),
	CONSTRAINT [FK_tblRKCurExpStock_tblSMCurrency_intMarketPriceCurrencyId] FOREIGN KEY(intMarketPriceCurrencyId)REFERENCES [dbo].[tblSMCurrency] (intCurrencyID),
	CONSTRAINT [FK_tblRKCurExpStock_tblICUnitMeasure_intMarketPriceUOMId] FOREIGN KEY(intMarketPriceUOMId)REFERENCES [dbo].[tblICUnitMeasure] (intUnitMeasureId),
)