CREATE TABLE [dbo].[tblRKAllocatedContractsGainOrLossHeader]
(
	[intAllocatedContractsGainOrLossHeaderId] INT NOT NULL IDENTITY, 
    [strRecordName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
    [intCommodityId] INT NULL, 
    [intBasisEntryId] INT NULL, 
    [intFutureSettlementPriceId] INT NULL, 
    [intPriceUOMId] INT NULL, 
    [intQtyUOMId] INT NULL, 
    [intCurrencyId] INT NULL, 
    [dtmTransactionUpTo] DATETIME NULL, 
    [intLocationId] INT NULL, 
    [intMarketZoneId] INT NULL, 
    [dtmPostDate] DATETIME NULL, 
    [dtmReverseDate] DATETIME NULL, 
    [dtmLastReversalDate] DATETIME NULL, 
    [ysnPosted] BIT NULL DEFAULT ((0)), 
    [dtmCreatedDate] DATETIME NULL DEFAULT (GETDATE()), 
    [dtmUnpostDate] DATETIME NULL, 
    [strBatchId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intCompanyId] INT NULL , 
    [intConcurrencyId] INT NULL DEFAULT ((1)), 
    [strRateType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    CONSTRAINT [PK_tblRKAllocatedContractsGainOrLossHeader] PRIMARY KEY ([intAllocatedContractsGainOrLossHeaderId]), 
    CONSTRAINT [AK_tblRKAllocatedContractsGainOrLossHeader_strRecordName] UNIQUE ([strRecordName]), 
    CONSTRAINT [FK_tblRKAllocatedContractsGainOrLossHeader_tblICCommodity] FOREIGN KEY ([intCommodityId]) REFERENCES [tblICCommodity]([intCommodityId]), 
    CONSTRAINT [FK_tblRKAllocatedContractsGainOrLossHeader_tblRKM2MBasis] FOREIGN KEY ([intBasisEntryId]) REFERENCES [tblRKM2MBasis]([intM2MBasisId]), 
    CONSTRAINT [FK_tblRKAllocatedContractsGainOrLossHeader_tblRKFuturesSettlementPrice] FOREIGN KEY ([intFutureSettlementPriceId]) REFERENCES [tblRKFuturesSettlementPrice]([intFutureSettlementPriceId]), 
    CONSTRAINT [FK_tblRKAllocatedContractsGainOrLossHeader_tblSMCurrency] FOREIGN KEY ([intCurrencyId]) REFERENCES [tblSMCurrency]([intCurrencyID]), 
    CONSTRAINT [FK_tblRKAllocatedContractsGainOrLossHeader_tblSMCompanyLocation] FOREIGN KEY ([intLocationId]) REFERENCES [tblSMCompanyLocation]([intCompanyLocationId]), 
    CONSTRAINT [FK_tblRKAllocatedContractsGainOrLossHeader_tblARMarketZone] FOREIGN KEY ([intMarketZoneId]) REFERENCES [tblARMarketZone]([intMarketZoneId]) 
)