CREATE TABLE [dbo].[tblRKCompanyPreference]
(
	[intCompanyPreferenceId] INT NOT NULL IDENTITY, 
    [intConcurrencyId] INT NOT NULL,
    [intUnitMeasureId] INT NULL, 
    [dblDecimals] NUMERIC(18, 6) NULL, 
    [dblRefreshRate] NUMERIC(18, 6) NULL, 
    [ysnIncludeInTransitInCompanyTitled] BIT NULL, 
    [ysnIncludeOffsiteInventoryInCompanyTitled] BIT NULL, 
    [ysnIncludeDPPurchasesInCompanyTitled] BIT NULL, 
    [ysnIncludeOptionsInRiskInquiryOrCoverage] BIT NULL, 
    [ysnIncludeInventoryHedge] BIT NULL, 
    [ysnIncludeExpiredMonths] BIT NULL, 
    [strRiskView] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strReportLevel] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strTimingField] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strReportTerms] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [ysnIncludeInventoryBasis] BIT NULL, 
    [strM2MReportLevel] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [ysnIncludeInventoryM2M] BIT NULL, 
    [ysnIncludeBasisDifferentialsInResults] BIT NULL, 
    [ysnEnterSeparateMarketBasisDifferentialsForBuyVsSell] BIT NULL, 
    [ysnEnterForwardCurveForMarketBasisDifferential] BIT NULL, 
    [ysnAllowPartialPricingOfAContractSequence] BIT NULL, 
    [strPricingQty] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [ysnEnablePolarizationAdjustments] BIT NULL,
    [strPeriodType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[ysnValueBasisAndDPDeliveries] BIT NULL, 
    [strEvaluationBy] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strEvaluationByZone] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[intCurrencyId] INT NULL, 
	[strDateTimeFormat] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[intInterfaceSystemId] INT NULL, 
    [ysnAutoExpire] BIT NULL,
    [ysnIsAutoAssign] BIT NULL, 
    CONSTRAINT [PK_tblRKCompanyPreference_intCompanyPreferenceId] PRIMARY KEY ([intCompanyPreferenceId]), 
    CONSTRAINT [FK_tblRKCompanyPreference_tblICUnitMeasure_intUnitMeasureId] FOREIGN KEY([intUnitMeasureId]) REFERENCES [dbo].[tblICUnitMeasure] ([intUnitMeasureId]),
	CONSTRAINT [FK_tblRKCompanyPreference_tblSMCurrency_intCurrencyId] FOREIGN KEY([intCurrencyId])REFERENCES [dbo].[tblSMCurrency] ([intCurrencyID]),
	CONSTRAINT [FK_tblRKCompanyPreference_tblRKInterfaceSystem_intCurrencyId] FOREIGN KEY([intInterfaceSystemId])REFERENCES [dbo].[tblRKInterfaceSystem] ([intInterfaceSystemId])	
)