CREATE TABLE [dbo].[tblRKFutOptTransaction]
(
	[intFutOptTransactionId] INT IDENTITY(1,1) NOT NULL,
	[intFutOptTransactionHeaderId] INT NOT NULL,
    [intConcurrencyId] INT NOT NULL, 
	[dtmTransactionDate] DATETIME NOT NULL, 
    [intBrokerId] INT NOT NULL, 
    [intBrokerageAccountId] INT NOT NULL, 
    [intFutureMarketId] INT NOT NULL, 
    [intInstrumentTypeId] INT NOT NULL, 
    [intCommodityId] INT NOT NULL, 
    [intLocationId] INT NOT NULL, 
    [intTraderId] INT NOT NULL, 
    [intCurrencyId] INT NOT NULL, 
    [strInternalTradeNo] NVARCHAR(10) NOT NULL, 
    [strBrokerTradeNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
    [strBuySell] NVARCHAR(10) COLLATE Latin1_General_CI_AS NOT NULL, 
    [intNoOfContract] INT NOT NULL, 
    [intFutureMonthId] int NULL, 
	[intOptionMonthId] int NULL, 
    [strOptionType] NVARCHAR(10) COLLATE Latin1_General_CI_AS NULL, 
    [dblStrike] NUMERIC(18, 6) NULL, 
    [dblPrice] NUMERIC(18, 6) NOT NULL, 
    [strReference] NVARCHAR(250) COLLATE Latin1_General_CI_AS NULL, 
    [strStatus] NVARCHAR(250) COLLATE Latin1_General_CI_AS NOT NULL, 
    [dtmFilledDate] DATETIME NULL, 
    [strReserveForFix] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intBookId] INT NULL, 
    [intSubBookId] INT NULL, 
    [ysnOffset] BIT NULL, 
    CONSTRAINT [PK_tblRKFutOptTransaction_intFutOptTransactionId] PRIMARY KEY (intFutOptTransactionId),	
	CONSTRAINT [FK_tblRKFutOptTransaction_tblRKFutOptTransactionHeader_intFutOptTransactionHeaderId] FOREIGN KEY ([intFutOptTransactionHeaderId]) REFERENCES [tblRKFutOptTransactionHeader]([intFutOptTransactionHeaderId]) ON DELETE CASCADE,
	CONSTRAINT [FK_tblRKFutOptTransaction_tblRKFutureMarket_intFutureMarketId] FOREIGN KEY ([intFutureMarketId]) REFERENCES [tblRKFutureMarket]([intFutureMarketId]),
	CONSTRAINT [FK_tblRKFutOptTransaction_tblSMCompanyLocation_intCompanyLocationId] FOREIGN KEY ([intLocationId]) REFERENCES [tblSMCompanyLocation]([intCompanyLocationId]),
	CONSTRAINT [FK_tblRKFutOptTransaction_tblRKBrokerageAccount_intBrokerageAccountId] FOREIGN KEY ([intBrokerageAccountId]) REFERENCES [tblRKBrokerageAccount]([intBrokerageAccountId]),
	CONSTRAINT [FK_tblRKFutOptTransaction_tblRKFuturesMonth_intFutureMonthId] FOREIGN KEY ([intFutureMonthId]) REFERENCES [tblRKFuturesMonth]([intFutureMonthId]),
	CONSTRAINT [FK_tblRKFutOptTransaction_tblRKOptionsMonth_intOptionMonthId] FOREIGN KEY ([intOptionMonthId]) REFERENCES [tblRKOptionsMonth]([intOptionMonthId]),
	CONSTRAINT [FK_tblRKFutOptTransaction_tblCTBook_intBookId] FOREIGN KEY ([intBookId]) REFERENCES [tblCTBook]([intBookId]),
	CONSTRAINT [FK_tblRKFutOptTransaction_tblCTSubBook_intBookId] FOREIGN KEY ([intSubBookId]) REFERENCES [tblCTSubBook]([intSubBookId]), 
	CONSTRAINT [FK_tblRKFutOptTransaction_tblICCommodity_intCommodityId] FOREIGN KEY ([intCommodityId]) REFERENCES [tblICCommodity]([intCommodityId]),
	CONSTRAINT [FK_tblRKFutOptTransaction_tblSMCurrency_intCurrencyId] FOREIGN KEY([intCurrencyId])REFERENCES [dbo].[tblSMCurrency] ([intCurrencyID]),
    CONSTRAINT [UK_tblRKFutOptTransaction_strBrokerTradeNo] UNIQUE ([strBrokerTradeNo])
)