CREATE TABLE [dbo].[tblSTTranslogRebates] (
    [intTranslogId]                          INT             IDENTITY (1, 1) NOT NULL,
    [intScanTransactionId]                   INT             NULL,
    [strTrlUPCwithoutCheckDigit]             NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTransSetPeriodID]                    INT             NULL,
    [strTransSetPeriodame]                   NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [dtmTransSetLongId]                      DATETIME        NULL,
    [dtmTransSetShortId]                     DATETIME        NULL,
    [intTransSetSite]                        INT             NULL,
    [dtmOpenedTime]                          DATETIME        NULL,
    [dtmClosedTime]                          DATETIME        NULL,
    [dblInsideSales]                         DECIMAL (18, 6) NULL,
    [dblInsideGrand]                         DECIMAL (18, 6) NULL,
    [dblOutsideSales]                        DECIMAL (18, 6) NULL,
    [dblOutsideGrand]                        DECIMAL (18, 6) NULL,
    [dblOverallSales]                        DECIMAL (18, 6) NULL,
    [dblOverallGrand]                        DECIMAL (18, 6) NULL,
    [strTransType]                           NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTransRecalled]                       NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [strTransRollback]                       NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [strTransFuelPrepayCompletion]           NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [strTransFuelPrepay]					 NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [intTermMsgSN]                           BIGINT          NULL,
    [strTermMsgSNtype]                       NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [intTermMsgSNterm]                       INT             NULL,
    [intTrTickNumPosNum]                     INT             NULL,
    [intTrTickNumTrSeq]                      BIGINT          NULL,
    [intTrUniqueSN]                          BIGINT          NULL,
    [strPeriodNameHOUR]                      NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [intPeriodNameHOURSeq]                   INT             NULL,
    [intPeriodNameHOURLevel]                 INT             NULL,
    [strPeriodNameSHIFT]                     NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [intPeriodNameSHIFTSeq]                  INT             NULL,
    [intPeriodNameSHIFTLevel]                INT             NULL,
    [strPeriodNameDAILY]                     NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [intPeriodNameDAILYSeq]                  INT             NULL,
    [intPeriodNameDAILYLevel]                INT             NULL,
    [dtmDate]                                DATETIME        NULL,
    [intDuration]                            BIGINT          NULL,
    [intTill]                                INT             NULL,
    [strCashier]                             NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [intCashierSysId]                        INT             NULL,
    [strCashierEmpNum]                       NVARCHAR (Max)  COLLATE Latin1_General_CI_AS NULL,
    [intCashierPosNum]                       INT             NULL,
    [intCashierPeriod]                       INT             NULL,
    [intCashierDrawer]                       INT             NULL,
    [strOriginalCashier]                     NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [intOriginalCashierSysid]                INT             NULL,
    [strOriginalCashierEmpNum]               NVARCHAR (Max)  COLLATE Latin1_General_CI_AS NULL,
    [intOriginalCashierPosNum]               INT             NULL,
    [intOriginalCashierPeriod]               INT             NULL,
    [intOriginalCashierDrawer]               INT             NULL,
    [intStoreNumber]                         INT             NULL,
    [strTrFuelOnlyCst]                       NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [strPopDiscTran]                         NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [dblCoinDispensed]                       DECIMAL (18, 2) NULL,
    [dblTrValueTrTotNoTax]                   DECIMAL (18, 2) NULL,
    [dblTrValueTrTotWTax]                    DECIMAL (18, 2) NULL,
    [dblTrValueTrTotTax]                     DECIMAL (18, 2) NULL,
    [dblTaxAmtsTaxAmt]                       DECIMAL (18, 2) NULL,
    [intTaxAmtsTaxAmtSysid]                  INT             NULL,
    [strTaxAmtsTaxAmtCat]                    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTaxAmtsTaxRate]                      DECIMAL (18, 2) NULL,
    [intTaxAmtsTaxRateSysid]                 INT             NULL,
    [strTaxAmtsTaxRateCat]                   NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTaxAmtsTaxNet]                       DECIMAL (18, 2) NULL,
    [intTaxAmtsTaxNetSysid]                  INT             NULL,
    [strTaxAmtsTaxNetCat]                    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTaxAmtsTaxAttribute]                 DECIMAL (18, 2) NULL,
    [intTaxAmtsTaxAttributeSysid]            INT             NULL,
    [strTaxAmtsTaxAttributeCat]              NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrCurrTot]                           DECIMAL (18, 2) NULL,
    [strTrCurrTotLocale]                     NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrSTotalizer]                        DECIMAL (18, 2) NULL,
    [dblTrGTotalizer]                        DECIMAL (18, 2) NULL,
    [dblTrFstmpTrFstmpTot]                   DECIMAL (18, 2) NULL,
    [dblTrFstmpTrFstmpTax]                   DECIMAL (18, 2) NULL,
    [dblTrFstmpTrFstmpChg]                   DECIMAL (18, 2) NULL,
    [dblTrFstmpTrFstmpTnd]                   DECIMAL (18, 2) NULL,
    [dblTrCshBkAmt]                          DECIMAL (18, 2) NULL,
    [dblTrCshBkAmtMop]                       INT             NULL,
    [dblTrCshBkAmtCat]                       INT             NULL,
    [strCustDOB]                             NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [dblRecallAmt]                           DECIMAL (18, 2) NULL,
    [intTrExNetProdTrENPPcode]               INT             NULL,
    [dblTrExNetProdTrENPAmount]              DECIMAL (18, 2) NULL,
    [dblTrExNetProdTrENPItemCnt]             DECIMAL (18, 2) NULL,
    [strTrLoyaltyProgramProgramID]           NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrLoyaltyProgramTrloSubTotal]        DECIMAL (18, 2) NULL,
    [dblTrLoyaltyProgramTrloAutoDisc]        DECIMAL (18, 2) NULL,
    [dblTrLoyaltyProgramTrloCustDisc]        DECIMAL (18, 2) NULL,
    [strTrLoyaltyProgramTrloAccount]         NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrLoyaltyProgramTrloEntryMeth]       NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrLoyaltyProgramTrloAuthReply]       NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [ysnTrLineDuplicate]                     BIT             NULL,
    [strTrLineType]                          NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrLineUnsettled]                     NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrlTaxesTrlTax]                      DECIMAL (18, 2) NULL,
    [intTrlTaxesTrlTaxSysid]                 INT             NULL,
    [strTrlTaxesTrlTaxCat]                   NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrlTaxesTrlTaxReverse]               INT             NULL,
    [dblTrlTaxesTrlRate]                     DECIMAL (18, 2) NULL,
    [intTrlTaxesTrlRateSysid]                INT             NULL,
    [strTrlTaxesTrlRateCat]                  NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlBdayVerif]                NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlFstmp]                    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlPLU]                      NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlUpdPluCust]               NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlUpdDepCust]               NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlCatCust]                  NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlFuelSale]                 NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFlagsTrlMatch]                    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlDept]                             NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrlDeptNumber]                       INT             NULL,
    [strTrlDeptType]                         NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlCat]                              NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrlCatNumber]                        INT             NULL,
    [strTrlNetwCode]                         NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrlQty]                              DECIMAL (18, 2) NULL,
    [dblTrlSign]                             DECIMAL (18, 2) NULL,
    [dblTrlSellUnitPrice]                    DECIMAL (18, 3) NULL,
    [dblTrlUnitPrice]                        DECIMAL (18, 3) NULL,
    [dblTrlLineTot]                          DECIMAL (18, 3) NULL,
    [dblTrlPrcOvrd]                          DECIMAL (18, 3) NULL,
    [strTrlDesc]                             NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlUPC]                              NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlModifier]                         NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlUPCEntryType]                     NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrloLnItemDiscProgramId]             NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrloLnItemDiscDiscAmt]               DECIMAL (18, 3) NULL,
    [dblTrloLnItemDiscQty]                   DECIMAL (18, 3) NULL,
    [intTrloLnItemDiscTaxCred]               INT             NULL,

    [strTrlFuelType]                         NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlFuelSeq]                          INT             NULL,
    [strTrlFuelPosition]                     INT             NULL,
    [strTrlFuelDepst]                        DECIMAL (18, 3) NULL,
    [strTrlFuelProd]                         NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [strTrlFuelProdSysid]                    INT             NULL,
    [strTrlFuelProdNAXMLFuelGradeID]         NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [strTrlFuelSvcMode]                      NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [strTrlFuelSvcModeSysid]                 INT             NULL,
    [strTrlFuelMOP]                          NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [strTrlFuelMOPSysid]                     INT             NULL,
    [strTrlFuelVolume]                       DECIMAL (18, 3) NULL,
    [strTrlFuelBasePrice]                    DECIMAL (18, 3) NULL,
    [strTrPaylineType]                       NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrPaylineSysid]                      INT             NULL,
    [strTrPaylineLocale]                     NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpPaycode]                          NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrpPaycodeMop]                       INT             NULL,
    [intTrpPaycodeCat]                       INT             NULL,
    [strTrPaylineNacstendercode]             NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [strTrPaylineNacstendersubcode]          NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrpAmt]                              DECIMAL (18, 3) NULL,
    [strTrpCardInfoTrpcAccount]              NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoTrpcCCName]               NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrpCardInfoTrpcCCNameProdSysid]      INT             NULL,
    [strTrpCardInfoTrpcHostID]               NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoTrpcAuthCode]             NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoTrpcAuthSrc]              NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoTrpcTicket]               NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoTrpcEntryMeth]            NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrpCardInfoTrpcBatchNr]              INT             NULL,
    [intTrpCardInfoTrpcSeqNr]                INT             NULL,
    [dtmTrpCardInfoTrpcAuthDateTime]         DATETIME        NULL,
    [strTrpCardInfoTrpcRefNum]               NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoMerchInfoTrpcmMerchID]    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoMerchInfoTrpcmTermID]     NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrpCardInfoTrpcAcquirerBatchNr]      INT             NULL,
    [strTrlMatchLineTrlMatchName]            NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [dblTrlMatchLineTrlMatchQuantity]        DECIMAL (18, 3) NULL,
    [dblTrlMatchLineTrlMatchPrice]           DECIMAL (18, 3) NULL,
    [intTrlMatchLineTrlMatchMixes]           INT             NULL,
    [dblTrlMatchLineTrlPromoAmount]          DECIMAL (18, 3) NULL,
    [strTrlMatchLineTrlPromotionID]          NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [strTrlMatchLineTrlPromotionIDPromoType] NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [intTrlMatchLineTrlMatchNumber]          INT             NULL,

	[intRegisterClassId]					 INT             NULL,		-- Will be used to determine the Register Class
    [intStoreId]                             INT             NOT NULL,
    [intCheckoutId]                          INT             NULL,			-- In the future the intCheckoutId is not necessary
    [ysnSubmitted]                           BIT             NOT NULL,
    [ysnPMMSubmitted]                        BIT             DEFAULT ((0)) NOT NULL,
    [ysnRJRSubmitted]                        BIT             DEFAULT ((0)) NOT NULL,
    [intConcurrencyId]                       INT             NOT NULL,
    CONSTRAINT [PK_tblSTTranslogRebates] PRIMARY KEY CLUSTERED ([intTranslogId] ASC),
    CONSTRAINT [FK_tblSTTranslogRebates_tblSTCheckoutHeader] FOREIGN KEY ([intCheckoutId]) REFERENCES [dbo].[tblSTCheckoutHeader] ([intCheckoutId]) ON DELETE CASCADE,
	CONSTRAINT [FK_tblSTTranslogRebates_tblSTRegisterSetup] FOREIGN KEY ([intRegisterClassId]) REFERENCES [dbo].[tblSTRegisterSetup] ([intRegisterSetupId]) ON DELETE CASCADE
);


Go

--ALTER TABLE tblSTTranslogRebates
--DROP INDEX [IDX_tblSTTranslogRebates] ON  tblSTTranslogRebates

CREATE NONCLUSTERED INDEX [IDX_tblSTTranslogRebates]
		ON [dbo].[tblSTTranslogRebates]([dtmDate] ASC, [intTermMsgSN] ASC, [intTermMsgSNterm] ASC, [intStoreId] ASC, [intCheckoutId] ASC);



--CREATE TABLE [dbo].[tblSTTranslogRebates]
--(
--	--[intTranslogId] int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
--	[intTranslogId] INT NOT NULL IDENTITY,

--	[dtmOpenedTime] datetime NULL,
--	[dtmClosedTime] datetime NULL,
--	[dblInsideSales] decimal(18, 6) NULL,
--	[dblInsideGrand] decimal(18, 6) NULL,
--	[dblOutsideSales] decimal(18, 6) NULL,
--	[dblOutsideGrand] decimal(18, 6) NULL,
--	[dblOverallSales] decimal(18, 6) NULL,
--	[dblOverallGrand] decimal(18, 6) NULL,

--	[strTransType] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTransRecalled] nvarchar(10) COLLATE Latin1_General_CI_AS NULL,
--	[strTransRollback] nvarchar(10) COLLATE Latin1_General_CI_AS NULL,
--	[strTransFuelPrepayCompletion] nvarchar(10) COLLATE Latin1_General_CI_AS NULL,

--    [intScanTransactionId] int NULL,

--    [intTermMsgSN] bigint NULL,
--	[strTermMsgSNtype] nvarchar(10) COLLATE Latin1_General_CI_AS NULL,
--	[intTermMsgSNterm] int NULL,
--    [intTrTickNumPosNum] int NULL,
--	[intTrTickNumTrSeq] bigint NULL,
--    [intTrUniqueSN] bigint NULL,                                                    -- NEW 
--    [strPeriodNameHOUR] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,             -- Modified 
--    [intPeriodNameHOURSeq] int NULL,                                                -- Modified 
--    [intPeriodNameHOURLevel] int NULL,	                                            -- Modified 
--	[strPeriodNameSHIFT] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,            -- Modified 
--    [intPeriodNameSHIFTSeq] int NULL,                                               -- Modified 
--    [intPeriodNameSHIFTLevel] int NULL,                                             -- Modified 
--	[strPeriodNameDAILY] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,            -- Modified 
--    [intPeriodNameDAILYSeq] int NULL,                                               -- Modified 
--    [intPeriodNameDAILYLevel] int NULL,                                             -- Modified 
--    [dtmDate] datetime NULL,
--	[intDuration] double precision NULL,
--    [intTill] int NULL,
--    [strCashier] nvarchar(200) COLLATE Latin1_General_CI_AS NULL,
--    [intCashierPeriod] int NULL,
--    [intCashierPosNum] int NULL,
--    [intCashierEmpNum] int NULL,
--    [intCashierSysId] int NULL,
--    [intCashierDrawer] int NULL, 
--    [strOriginalCashier] nvarchar(200) COLLATE Latin1_General_CI_AS NULL,
--    [intOriginalCashierPeriod] int NULL,
--    [intOriginalCashierPosNum] int NULL,
--    [intOriginalCashierEmpNum] int NULL,
--    [intOriginalCashierSysid] int NULL,
--    [intOriginalCashierDrawer] int NULL,
--	[intStoreNumber] int NULL,
--    [strTrFuelOnlyCst] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
--    [strPopDiscTran] nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
--    [dblCoinDispensed] decimal(18, 2) NULL,
--	[dblTrValueTrTotNoTax] decimal(18, 2) NULL,
--	[dblTrValueTrTotWTax] decimal(18, 2) NULL,
--	[dblTrValueTrTotTax] decimal(18, 2) NULL,
--	[dblTaxAmtsTaxAmt] decimal(18, 2) NULL,
--	[intTaxAmtsTaxAmtSysid] int NULL,
--	[strTaxAmtsTaxAmtCat] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[dblTaxAmtsTaxRate] decimal(18, 2) NULL,
--	[intTaxAmtsTaxRateSysid] int NULL,
--	[strTaxAmtsTaxRateCat] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[dblTaxAmtsTaxNet] decimal(18, 2) NULL,
--	[intTaxAmtsTaxNetSysid] int NULL,
--	[strTaxAmtsTaxNetCat] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[dblTaxAmtsTaxAttribute] decimal(18, 2) NULL,
--	[intTaxAmtsTaxAttributeSysid] int NULL,
--	[strTaxAmtsTaxAttributeCat] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[dblTrCurrTot] decimal(18, 2) NULL,
--	[strTrCurrTotLocale] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,	
--	[dblTrSTotalizer] decimal(18, 2) NULL,
--	[dblTrGTotalizer] decimal(18, 2) NULL,
--	[dblTrFstmpTrFstmpTot] decimal(18, 2) NULL,
--	[dblTrFstmpTrFstmpTax] decimal(18, 2) NULL,
--	[dblTrFstmpTrFstmpChg] decimal(18, 2) NULL,
--	[dblTrFstmpTrFstmpTnd] decimal(18, 2) NULL,
--    [strTrLoyaltyProgramProgramID] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,
--	[dblTrLoyaltyProgramTrloSubTotal] decimal(18, 2) NULL,
--	[dblTrLoyaltyProgramTrloAutoDisc] decimal(18, 2) NULL,
--	[dblTrLoyaltyProgramTrloCustDisc] decimal(18, 2) NULL,
--	[strTrLoyaltyProgramTrloAccount] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrLoyaltyProgramTrloEntryMeth] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrLoyaltyProgramTrloAuthReply] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [dblTrCshBkAmt] decimal(18, 2) NULL,
--	[dblTrCshBkAmtMop] int NULL,
--	[dblTrCshBkAmtCat] int NULL,
--    [strCustDOB] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,
--    [dblRecallAmt] decimal(18, 2) NULL,
--	[intTrExNetProdTrENPPcode] int NULL,
--	[dblTrExNetProdTrENPAmount] decimal(18, 2) NULL,
--	[dblTrExNetProdTrENPItemCnt] decimal(18, 2) NULL,                               -- NEW
--	[strTrLineType] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [ysnTrLineDuplicate] bit NULL,                                                  -- NEW
--	[strTrLineUnsettled] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[dblTrlTaxesTrlTax] decimal(18, 2) NULL,
--	[intTrlTaxesTrlTaxSysid] int NULL,
--	[strTrlTaxesTrlTaxCat] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[intTrlTaxesTrlTaxReverse] int NULL,
--	[dblTrlTaxesTrlRate] decimal(18, 2) NULL,
--	[intTrlTaxesTrlRateSysid] int NULL,
--	[strTrlTaxesTrlRateCat] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlFlagsTrlBdayVerif] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [strTrlFlagsTrlFstmp] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,            -- NEW
--	[strTrlFlagsTrlPLU] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlFlagsTrlUpdPluCust] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlFlagsTrlUpdDepCust] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlFlagsTrlCatCust] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlFlagsTrlFuelSale] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlFlagsTrlMatch] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlDept] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [strTrlDeptType] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,
--	[intTrlDeptNumber] int NULL,
--    [strTrlCat] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,                     -- trLine type="preFuel"
--	[strTrlCatNumber] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,               -- trLine type="preFuel"
--	[strTrlNetwCode] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[dblTrlQty] decimal(18, 2) NULL,
--	[dblTrlSign] decimal(18, 2) NULL,
--	[dblTrlSellUnitPrice] decimal(18, 3) NULL,
--	[dblTrlUnitPrice] decimal(18, 3) NULL,
--	[dblTrlLineTot] decimal(18, 3) NULL,
--	[strTrlDesc] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlUPC] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlUPCwithoutCheckDigit] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,

--	[strTrlModifier] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrlUPCEntryType] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [strTrPaylineType] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[intTrPaylineSysid] int NULL,
--	[strTrPaylineLocale] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpPaycode] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [intTrpPaycodeCat] int NULL,
--    [intTrpPaycodeMop] int NULL,
--    [strTrPaylineNacstendersubcode] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,
--	[strTrPaylineNacstendercode] nvarchar(20) COLLATE Latin1_General_CI_AS NULL,
--	[dblTrpAmt] decimal(18, 3) NULL,
--	[strTrpCardInfoTrpcAccount] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [strTrpCardInfoTrpcCCName] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[intTrpCardInfoTrpcCCNameProdSysid] int NULL,
--	[strTrpCardInfoTrpcHostID] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoTrpcAuthCode] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoTrpcAuthSrc] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoTrpcTicket] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoTrpcEntryMeth] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoTrpcBatchNr] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoTrpcSeqNr] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[dtmTrpCardInfoTrpcAuthDateTime] datetime NULL,
--	[strTrpCardInfoTrpcRefNum] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoMerchInfoTrpcmMerchID] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[strTrpCardInfoMerchInfoTrpcmTermID] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,	
--	[strTrlMatchLineTrlMatchName] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [dblTrlMatchLineTrlMatchQuantity] decimal(18, 3) NULL,
--    [dblTrlMatchLineTrlMatchPrice] decimal(18, 3) NULL,
--    [intTrlMatchLineTrlMatchMixes] int NULL,
--    [dblTrlMatchLineTrlPromoAmount] decimal(18, 3) NULL,
--    [strTrlMatchLineTrlPromotionID] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--    [strTrlMatchLineTrlPromotionIDPromoType] nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
--	[intTrlMatchLineTrlMatchNumber] int NULL,

--	[intStoreId] int NOT NULL,
--	[intCheckoutId] int NOT NULL,
--	[ysnSubmitted] bit NOT NULL,
--	[ysnPMMSubmitted] BIT NOT NULL DEFAULT ((0)),
--	[ysnRJRSubmitted] BIT NOT NULL DEFAULT ((0)),
--	[intConcurrencyId] int NOT NULL,
--	CONSTRAINT [PK_tblSTTranslogRebates] PRIMARY KEY ([intTranslogId]),
--	CONSTRAINT [FK_tblSTTranslogRebates_tblSTCheckoutHeader] FOREIGN KEY ([intCheckoutId]) REFERENCES [tblSTCheckoutHeader]([intCheckoutId]) ON DELETE CASCADE,
--	--CONSTRAINT [PK_tblSTTranslogRebates] PRIMARY KEY NONCLUSTERED ([intTranslogId])
--)
--Go

--CREATE NONCLUSTERED INDEX [IDX_tblSTTranslogRebates]
--		ON [dbo].[tblSTTranslogRebates]([dtmDate] ASC, [intTermMsgSN] ASC, [intTermMsgSNterm] ASC, [intStoreId] ASC, [intCheckoutId] ASC);


GO
CREATE NONCLUSTERED INDEX [tblSTTranslogRebates_strTrlUPCwithoutCheckDigit_idx]
    ON [dbo].[tblSTTranslogRebates]([strTrlUPCwithoutCheckDigit] ASC);


GO
CREATE NONCLUSTERED INDEX [tblSTTranslogRebates_dtmDate_idx]
    ON [dbo].[tblSTTranslogRebates]([dtmDate] ASC);
	
GO
CREATE NONCLUSTERED INDEX [IX_intStoreNumber]
    ON [dbo].[tblSTTranslogRebates]([intStoreNumber] ASC, [dtmDate] ASC);


