CREATE TABLE [dbo].[tblSMCompanyLocation]
(
	[intCompanyLocationId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [strLocationName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
    [strLocationType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
    [strAddress] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strZipPostalCode] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strCity] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strStateProvince] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [strCountry] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [strPhone] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strFax] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strEmail] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strWebsite] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strInternalNotes] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
    [strUseLocationAddress] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strSkipSalesmanDefault] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL , 
	[ysnSkipTermsDefault] BIT NULL DEFAULT (1),
	[strOrderTypeDefault] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strPrintCashReceipts] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL , 
	[ysnPrintCashTendered] BIT NULL DEFAULT (1),
	[strSalesTaxByLocation] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL , 
	[strDeliverPickupDefault] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strTaxState] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strTaxAuthorityId1] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strTaxAuthorityId2] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[ysnOverridePatronage] BIT NULL DEFAULT (1),
	[strOutOfStockWarning] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL , 
	[strLotOverdrawnWarning] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL , 
	[strDefaultCarrier] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[ysnOrderSection2Required] BIT NULL DEFAULT (1),
	[strPrintonPO] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[dblMixerSize] NUMERIC(18, 6) NULL DEFAULT (0), 
	[ysnOverrideMixerSize] BIT NULL DEFAULT (1),
	[ysnEvenBatches] BIT NULL DEFAULT (1),
	[ysnDefaultCustomBlend] BIT NULL DEFAULT (1),
	[ysnAgroguideInterface] BIT NULL DEFAULT (1),
	[ysnLocationActive] BIT NULL DEFAULT (1),
	[intProfitCenter] INT NULL,
	[intCashAccount] INT NULL,
	[intDepositAccount] INT NULL,
	[intARAccount] INT NULL,
	[intAPAccount] INT NULL,
	[intSalesAdvAcct] INT NULL,
	[intPurchaseAdvAccount] INT NULL,
	[intFreightAPAccount] INT NULL,
	[intFreightExpenses] INT NULL,
	[intFreightIncome] INT NULL,
	[intServiceCharges] INT NULL,
	[intSalesDiscounts] INT NULL,
	[intCashOverShort] INT NULL,
	[intWriteOff] INT NULL,
	[intCreditCardFee] INT NULL,
	[intSalesAccount] INT NULL,
	[intCostofGoodsSold] INT NULL,
	[intInventory] INT NULL,
	[strInvoiceType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strDefaultInvoicePrinter] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strPickTicketType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strDefaultTicketPrinter] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strLastOrderNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strLastInvoiceNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strPrintonInvoice] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[ysnPrintContractBalance] BIT NULL DEFAULT (1),
	[strJohnDeereMerchant] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strInvoiceComments] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[ysnUseOrderNumberforInvoiceNumber] BIT NULL DEFAULT (1),
	[ysnOverrideOrderInvoiceNumber] BIT NULL DEFAULT (1),
	[ysnPrintInvoiceMedTags] BIT NULL DEFAULT (1),
	[ysnPrintPickTicketMedTags] BIT NULL DEFAULT (1),
	[ysnSendtoEnergyTrac] BIT NULL DEFAULT (1),
	[strDiscountScheduleType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strLocationDiscount] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strLocationStorage] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strMarketZone] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strLastTicket] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[ysnDirectShipLocation] BIT NULL DEFAULT (1),
	[ysnScaleInstalled] BIT NULL DEFAULT (1),
	[strDefaultScaleId] NVARCHAR(50) NULL,
	[ysnActive] BIT NULL DEFAULT (1),
	[ysnUsingCashDrawer] BIT NULL DEFAULT (1),
	[strCashDrawerDeviceId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[ysnPrintRegisterTape] BIT NULL DEFAULT (1),
	[ysnUseUPConOrders] BIT NULL DEFAULT (1),
	[ysnUseUPConPhysical] BIT NULL DEFAULT (1),
	[ysnUseUPConPurchaseOrders] BIT NULL DEFAULT (1),
	[strUPCSearchSequence] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strBarCodePrinterName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strPriceLevel1] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strPriceLevel2] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strPriceLevel3] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strPriceLevel4] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strPriceLevel5] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[ysnOverShortEntries] BIT NULL DEFAULT (1),
	[strOverShortCustomer] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strOverShortAccount] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[ysnAutomaticCashDepositEntries] BIT NULL DEFAULT (1), 
    [intConcurrencyId] INT NOT NULL DEFAULT (1)
)
