CREATE TABLE [dbo].[tblSTPromotionSalesList]
(
	[intPromoSalesListId] INT NOT NULL IDENTITY, 
    [strPromoType] NVARCHAR COLLATE Latin1_General_CI_AS NOT NULL, 
    [intStoreId] INT NOT NULL, 
    [intPromoSalesId] INT NOT NULL, 
    [intCategoryId] INT NOT NULL, 
    [strPromoSalesDescription] NVARCHAR(40) COLLATE Latin1_General_CI_AS NULL, 
    [strPromoReason] NVARCHAR(40) COLLATE Latin1_General_CI_AS NOT NULL, 
    [intPromoUnits] INT NULL, 
    [dblPromoPrice] NUMERIC(5, 2) NULL, 
    [intPromoFeeType] INT NOT NULL, 
    [intRegProdId] INT NULL, 
    [dtmPromoBegPeriod] DATETIME NULL, 
    [dtmPromoBegTime] DATETIME NULL, 
    [dtmPromoEndPeriod] DATETIME NULL, 
    [dtmPromoEndTime] DATETIME NULL, 
    [intPurchaseLimit] INT NULL, 
    [intSalesRestrictCode] INT NULL, 
    [ysnPurchaseAtleastMin] BIT NULL, 
    [ysnPurchaseExactMultiples] BIT NULL, 
    [ysnRecieptItemSize] BIT NULL, 
    [ysnReturnable] BIT NULL, 
    [ysnFoodStampable] BIT NULL, 
    [ysnId1Required] BIT NULL, 
    [ysnId2Required] BIT NULL, 
    [ysnDiscountAllowed] BIT NULL, 
    [ysnBlueLaw1] BIT NULL, 
    [ysnBlueLaw2] BIT NULL, 
    [ysnUserTaxFlag1] BIT NULL, 
    [ysnUserTaxFlag2] BIT NULL, 
    [ysnUserTaxFlag3] BIT NULL, 
    [ysnUserTaxFlag4] BIT NULL, 
    [ysnDeleteFromRegister] BIT NULL, 
    [ysnSentToRuby] BIT NULL, 
    [dtmLastUpdateDate] DATETIME NULL, 
    [intConcurrencyId] INT NOT NULL, 
    CONSTRAINT [PK_tblSTPromotionSalesList] PRIMARY KEY CLUSTERED ([intPromoSalesListId] ASC), 
    CONSTRAINT [AK_tblSTPromotionSalesList_intStoreId_strPromoType_intPromoSalesId] UNIQUE NONCLUSTERED([intStoreId],[strPromoType],[intPromoSalesId] ASC), 
    CONSTRAINT [FK_tblSTPromotionSalesList_tblSTStore] FOREIGN KEY ([intStoreId]) REFERENCES [tblSTStore]([intStoreId]), 
    CONSTRAINT [FK_tblSTPromotionSalesList_tblSTSubcategoryRegProd] FOREIGN KEY ([intRegProdId]) REFERENCES [tblSTSubcategoryRegProd]([intRegProdId]), 
    CONSTRAINT [FK_tblSTPromotionSalesList_tblICCategory] FOREIGN KEY ([intCategoryId]) REFERENCES [tblICCategory]([intCategoryId]) 
);
