CREATE TABLE [dbo].[tblSTCheckoutShiftPhysicalDetail]
(
    [intCheckoutShiftPhysicalDetailId] INT NOT NULL IDENTITY,
    [intCheckoutId] INT NOT NULL,
    [intItemId] INT NULL,
    [intItemLocationId] INT NULL,
    [intCompanyLocationSubLocationId] INT NULL,
    [intStorageLocationId] INT NULL,
    [intCountGroupId] INT NULL,
    [intLotId] INT NULL,
    [strLotNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [strLotAlias] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [intParentLotId] INT NULL,
    [strParentLotNo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [strParentLotAlias] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [intStockUOMId] INT NULL,
    [dblSystemCount] NUMERIC(38, 20) NOT NULL DEFAULT ((0)),
    [dblLastCost] NUMERIC(38, 20) NOT NULL DEFAULT ((0)),
    [strAutoCreatedLotNumber] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [strCountLine] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [dblPallets] NUMERIC(38, 20) NULL DEFAULT ((0)),
    [dblQtyPerPallet] NUMERIC(38, 20) NULL DEFAULT ((0)),
    [dblPhysicalCount] NUMERIC(38, 20) NOT NULL DEFAULT ((0)),
    [intItemUOMId] INT NULL,  
    [intWeightUOMId] INT NULL,
    [dblWeightQty] NUMERIC(38, 20) NULL DEFAULT((0)),
    [dblNetQty] NUMERIC(38, 20) NULL DEFAULT((0)),
    [ysnRecount] BIT NOT NULL DEFAULT ((0)),
    [dblQtyReceived] NUMERIC(38, 20) NULL DEFAULT((0)),
    [dblQtySold] NUMERIC(38, 20) NULL DEFAULT((0)),
    [intEntityUserSecurityId] INT NOT NULL,
    [intSort] INT NULL,
    [intConcurrencyId] INT NULL DEFAULT ((0)),
    CONSTRAINT [PK_tblCheckoutShiftPhysicalDetail] PRIMARY KEY ([intCheckoutShiftPhysicalDetailId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblSTCheckoutHeader] FOREIGN KEY ([intCheckoutId]) REFERENCES [tblSTCheckoutHeader]([intCheckoutId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblICItem] FOREIGN KEY ([intItemId]) REFERENCES [tblICItem]([intItemId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblICItemLocation] FOREIGN KEY ([intItemLocationId]) REFERENCES [tblICItemLocation]([intItemLocationId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblSMCompanyLocationSubLocation] FOREIGN KEY ([intCompanyLocationSubLocationId]) REFERENCES [tblSMCompanyLocationSubLocation]([intCompanyLocationSubLocationId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblICStorageLocation] FOREIGN KEY ([intStorageLocationId]) REFERENCES [tblICStorageLocation]([intStorageLocationId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblICLot] FOREIGN KEY ([intLotId]) REFERENCES [tblICLot]([intLotId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblICItemUOM] FOREIGN KEY ([intItemUOMId]) REFERENCES [tblICItemUOM]([intItemUOMId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblICCountGroup] FOREIGN KEY ([intCountGroupId]) REFERENCES [tblICCountGroup]([intCountGroupId]),
    CONSTRAINT [FK_tblCheckoutShiftPhysicalDetail_tblSMUserSecurity] FOREIGN KEY ([intEntityUserSecurityId]) REFERENCES [tblSMUserSecurity]([intEntityId])
)
