CREATE TABLE [dbo].[tblSTStore]
(
	[intStoreId] INT NOT NULL IDENTITY,
    [intStoreNo] INT NOT NULL, 
    [strStoreName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
    [strDescription] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
    [strRegion] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strDestrict] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strAddress1] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strAddress2] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strCity] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strSate] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strZip] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strPhone] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strFax] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strEmail] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strWebsite] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intProfitCenter] INT NULL, 
    [ysnStoreOnHost] BIT NULL, 
    [ysnPricebookAutomated] BIT NULL, 
    [strHandheldCostBasis] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strVendorName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strLocation] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strGlCoId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strArCoId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intNextOrderNo] INT NULL, 
    [ysnUsePricebook] BIT NULL, 
    [intMaxPlu] INT NULL, 
    [ysnUseLargePlu] BIT NULL, 
    [ysnUseCfn] BIT NULL, 
    [strCfnSiteId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [ysnInterfaceChecksToCheckbook] BIT NULL, 
    [strCheckbook] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strQuickbookInterfaceClass] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strBarcodePrinterName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [dblServiceChargeRate] NUMERIC(7, 3) NULL, 
    [ysnUseArStatements] BIT NULL, 
    [dtmLastShiftOpenDate] DATETIME NULL, 
    [intLastShiftNo] INT NULL, 
    [dtmLastPhysicalImportDate] DATETIME NULL, 
    [dtmLastStatementRollDate] DATETIME NULL, 
    [ysnShiftPhysicalQuantityRecieved] BIT NULL, 
    [ysnShiftPhysicalQuantitySold] BIT NULL, 
    [strHandheldDeviceModel] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strDepositLookupType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strDefaultPaidoutId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intCustomerChargeMOP] INT NULL, 
    [intCashTransctionMOP] INT NULL, 
    [ysnAllowMassPriceChanges] BIT NULL, 
    [ysnUsingTankMonitors] BIT NULL, 
    [strPosRegisterId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intMaxRegisterPlu] INT NULL, 
    [strReportDepartmentAtGrossOrNet] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intLoyaltyDiscountMop] INT NULL, 
    [intLoyaltyDiscountDepartment] INT NULL, 
    [ysnBreakoutPropCardTotal] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intRemovePropCardMop] INT NULL, 
    [intAddPropCardMOP] INT NULL, 
    [strPropNetworkCardName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strAllowRegisterMarkUpDown] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strRegisterCheckoutDataEntry] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strReconcileFuels] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [ysnRecieveProductByDepartment] BIT NULL, 
    [ysnKeepArATStore] BIT NULL, 
    [ysnUsingCheckWriter] BIT NULL, 
    [ysnLoadFuelCost] BIT NULL, 
    [ysnUseSafeFunds] BIT NULL, 
    [ysnClearPricebookFieldsOnAdd] BIT NULL, 
    [intNumberOfShifts] INT NULL, 
    [ysnUpdatePriceFromReciept] BIT NULL, 
    [strGlSalesIndicator] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [ysnUpdateCaseCost] BIT NULL, 
    [dtmInvoiceCloseDate] DATETIME NULL, 
    [strTaxIdPassword] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intConcurrencyId] INT NOT NULL, 
    CONSTRAINT [PK_tblSTStore] PRIMARY KEY CLUSTERED ([intStoreId] ASC),
    CONSTRAINT [AK_tblSTStore_intStoreNo] UNIQUE NONCLUSTERED ([intStoreNo] ASC),
	CONSTRAINT [AK_tblSTStore_strStoreName] UNIQUE NONCLUSTERED ([strStoreName] ASC)
);