CREATE TABLE [dbo].[tblSMUserSecurity] (
    [intUserSecurityID] INT            IDENTITY (1, 1) NOT NULL,
    [intUserRoleID]     INT            NOT NULL,
	[intCompanyLocationId]     INT     NULL,
    [strUserName]       NVARCHAR (50)  COLLATE Latin1_General_CI_AS DEFAULT ('') NOT NULL,
    [strFullName]       NVARCHAR (50)  COLLATE Latin1_General_CI_AS DEFAULT ('') NOT NULL,
    [strPassword]       NVARCHAR (50)  COLLATE Latin1_General_CI_AS DEFAULT ('') NOT NULL,
	[strOverridePassword] NVARCHAR (50)  COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
	[strDashboardRole]  NVARCHAR (50)  COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strFirstName]      NVARCHAR (50)  COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strMiddleName]     NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL DEFAULT (''),
    [strLastName]       NVARCHAR (50)  COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strPhone]          NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL DEFAULT (''),
    [strDepartment]     NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL DEFAULT (''),
    [strLocation]       NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL DEFAULT (''),
    [strEmail]          NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL,
    [strMenuPermission] NVARCHAR (MAX) COLLATE Latin1_General_CI_AS NULL DEFAULT (''),
    [strMenu]           NVARCHAR (MAX) COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strForm]           NVARCHAR (MAX) COLLATE Latin1_General_CI_AS NULL DEFAULT (''),
    [strFavorite]       NVARCHAR (MAX) COLLATE Latin1_General_CI_AS DEFAULT ('') NOT NULL,
    [ysnDisabled]       BIT            DEFAULT ((0)) NOT NULL,
    [ysnAdmin]          BIT            DEFAULT ((0)) NOT NULL,
    [intConcurrencyId]  INT            DEFAULT (1) NOT NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([intUserSecurityID] ASC),
    CONSTRAINT [FK_UserSecurity_UserRole] FOREIGN KEY ([intUserRoleID]) REFERENCES [dbo].[tblSMUserRole] ([intUserRoleID]),
	CONSTRAINT [FK_UserSecurity_CompanyLocation] FOREIGN KEY ([intCompanyLocationId]) REFERENCES [dbo].[tblSMCompanyLocation] ([intCompanyLocationId])
);

