CREATE TABLE [dbo].[tblSMCompanyPreference]
(
	[intCompanyPreferenceId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [intDefaultCurrencyId] INT NULL, 
    [intDefaultReportingCurrencyId] INT NULL, 
    [intDefaultCountryId] INT NULL, 
    [strEnvironmentType] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL DEFAULT (''), 
    [ysnLegacyIntegration] BIT NOT NULL, 
    [strSourceSystem] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL DEFAULT (''), 
	[strAccountingMethod] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strSMTPHost] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intSMTPPort] INT NOT NULL, 
    [strSMTPUserName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strSMTPPassword] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strSMTPFromEmail] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strSMTPFromName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [ysnSMTPAuthentication] BIT NOT NULL, 
    [strSMTPSsl] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intInterfaceSystemId] INT NOT NULL, 
    [strQuotingSystemBatchUserID] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strQuotingSystemBatchUserPassword] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strInterfaceWebServicesURL] NVARCHAR(150) COLLATE Latin1_General_CI_AS NULL, 
    [ysnAllowForContractPricing] BIT NOT NULL, 
	[ysnInterfaceToTargetOrders] BIT NOT NULL,
    [ysnAllowUseForClosingPrices] BIT NOT NULL, 
    [ysnAllowUseForEndOfMonth] BIT NOT NULL, 
    [ysnInterfaceToScales] BIT NOT NULL, 
    [intSaveHistoryEveryId] INT NOT NULL, 
    [strIntervalStartTime] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strIntervalEndTime] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strIntervalUpdatesMinutes] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strQuotesDecimalsShown] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strHelperUrlDomain] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strNotificationEmailUrl] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
	[ysnEnableCreditCardProcessing] BIT NOT NULL DEFAULT 0, 
	[strMerchantId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strMerchantPassword] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strPaymentServer] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strDateFormat] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
    [strNumberFormat] NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,	
	[intCurrencyDecimal] INT NOT NULL DEFAULT 2,
	[intLockedRecordExpiration] INT NOT NULL DEFAULT 60,
	[ysnValidatePassword] BIT NOT NULL DEFAULT 0, 
	[intDefaultTermId] INT NULL, 
    [intCompanySetupId] INT NOT NULL,
	[intMultiCurrencyId] INT NULL,
    [intConcurrencyId] INT NOT NULL DEFAULT 1
)
