CREATE TABLE [dbo].[tblTMSyncFailed] (
    [intSyncFailedID]               INT             IDENTITY (1, 1) NOT NULL,
    [strCustomerNumber]             NVARCHAR (10)   COLLATE Latin1_General_CI_AS NOT NULL,
    [strCustomerName]               NVARCHAR (150)  COLLATE Latin1_General_CI_AS NULL,
    [strSiteNumber]                 NVARCHAR (4)    COLLATE Latin1_General_CI_AS NOT NULL,
    [strSiteAddress]                NCHAR (500)     COLLATE Latin1_General_CI_AS NULL,
    [dblMeterReading]               DECIMAL (18, 6) NULL,
    [strInvoiceNumber]              NVARCHAR (10)   COLLATE Latin1_General_CI_AS NOT NULL,
    [strBulkPlantNumber]            NVARCHAR (3)    COLLATE Latin1_General_CI_AS DEFAULT ('') NOT NULL,
    [dtmInvoiceDate]                DATETIME        DEFAULT 0 NULL,
    [strItemNumber]                 NVARCHAR (13)   COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strItemAvailableForTM]         NVARCHAR (1)    COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strReversePreviousDelivery]    NVARCHAR (1)    COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strPerformerID]                NVARCHAR (3)    COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [intInvoiceLineNumber]          INT             DEFAULT 0 NOT NULL,
    [dblExtendedAmount]             DECIMAL (18, 6) DEFAULT 0 NULL,
    [dblQuantityDelivered]          DECIMAL (18, 6) DEFAULT 0 NULL,
    [dblActualPercentAfterDelivery] DECIMAL (18, 6) DEFAULT 0 NULL,
    [strInvoiceType]                NVARCHAR (1)    COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strSalesPersonID]              NVARCHAR (3)    COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strReason]                     NVARCHAR (250)  COLLATE Latin1_General_CI_AS NULL,
    [ysnTemp]                       BIT             NULL,
    [intConcurrencyId]              INT             DEFAULT 1 NOT NULL,
    CONSTRAINT [PK_tblTMSyncFailed] PRIMARY KEY CLUSTERED ([intSyncFailedID] ASC)
);

