CREATE TABLE [dbo].[tblTFTransactions](
	[intTransactionId] [int] IDENTITY(1,1) NOT NULL,
	[intReportingComponentDetailId] [int] NULL,
	[pxrpt_trans_rev_dt] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_ord_no] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_itm_no] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_itm_loc_no] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_itm_desc] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_cus_no] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_cus_name] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_cus_addr] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_cus_state] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_vnd_no] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_vnd_name] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_vnd_addr1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_vnd_state] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_pur_carrier] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_pur_gross_un] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_pur_net_un] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_pur_bal_un] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxrpt_sls_trans_gals] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[pxpxrpt_sls_sst_exempt_pct] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[intTaxAuthorityId] [int] NULL,
	[strTaxAuthority] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strFormCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strFormName] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strScheduleCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strScheduleName] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[intProductCodeId] [int] NULL,
	[strProductCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strType] [nvarchar](MAX) COLLATE Latin1_General_CI_AS NULL,
	[strTaxCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[strTaxClass] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[dtmDate] [datetime] NULL,
	[dtmLastRun] [datetime] NULL,
	[dtmReportingPeriodBegin] [datetime] NULL,
	[dtmReportingPeriodEnd] [datetime] NULL,
	[intConcurrencyId] [int] CONSTRAINT [DF_tblTFTransactions_intConcurrencyId] DEFAULT ((1)) NULL,
 CONSTRAINT [PK_tblDummyTransaction] PRIMARY KEY CLUSTERED 
(
	[intTransactionId] ASC
)
)