CREATE TABLE [dbo].[tblTMDeliveryHistory] (
    [intConcurrencyId]                      INT             DEFAULT 1 NOT NULL,
    [intDeliveryHistoryID]                  INT             IDENTITY (1, 1) NOT NULL,
    [strInvoiceNumber]                      NVARCHAR (50)   COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [strBulkPlantNumber]                    NVARCHAR (50)   COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [dtmInvoiceDate]                        DATETIME        DEFAULT 0 NULL,
    [strProductDelivered]                   NVARCHAR (50)   COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [dblQuantityDelivered]                  NUMERIC (18, 6) DEFAULT 0 NULL,
    [intDegreeDayOnDeliveryDate]            INT             DEFAULT 0 NULL,
    [intDegreeDayOnLastDeliveryDate]        INT             DEFAULT 0 NULL,
    [dblBurnRateAfterDelivery]              NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblCalculatedBurnRate]                 NUMERIC (18, 6) DEFAULT 0 NULL,
    [ysnAdjustBurnRate]                     BIT             DEFAULT 0 NULL,
    [intElapsedDegreeDaysBetweenDeliveries] INT             DEFAULT 0 NULL,
    [intElapsedDaysBetweenDeliveries]       INT             DEFAULT 0 NULL,
    [strSeason]                             NVARCHAR (15)   COLLATE Latin1_General_CI_AS DEFAULT ('') NULL,
    [dblWinterDailyUsageBetweenDeliveries]  NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblSummerDailyUsageBetweenDeliveries]  NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblGallonsInTankbeforeDelivery]        NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblGallonsInTankAfterDelivery]         NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblEstimatedPercentBeforeDelivery]     NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblActualPercentAfterDelivery]         NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblMeterReading]                       NUMERIC (18, 6) DEFAULT 0 NULL,
    [dblLastMeterReading]                   NUMERIC (18, 6) DEFAULT 0 NULL,
    [intUserID]                             INT             DEFAULT 0 NULL,
    [dtmLastUpdated]                        DATETIME        DEFAULT 0 NULL,
    [intSiteID]                             INT             DEFAULT 0 NULL,
    [strSalesPersonID]                      NVARCHAR (50)   COLLATE Latin1_General_CI_AS DEFAULT 0 NULL,
    [dblExtendedAmount]                  NUMERIC (18, 6) NOT NULL DEFAULT 0,
    [ysnForReview] BIT NOT NULL DEFAULT 0, 
    [dtmMarkForReviewDate] DATETIME NULL, 
    CONSTRAINT [PK_tblTMDeliveryHistory] PRIMARY KEY CLUSTERED ([intDeliveryHistoryID] ASC),
    CONSTRAINT [FK_tblTMDeliveryHistory_tblTMSite] FOREIGN KEY ([intSiteID]) REFERENCES [dbo].[tblTMSite] ([intSiteID])
);

