CREATE TABLE [dbo].[tblWMSKU]
(
	[intSKUId]	INT NOT NULL,
	[intConcurrencyId] INT NOT NULL,
	[strSKUNo]	NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
	[intSKUStatusId]	INT NOT NULL,
	[strLotCode]	NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
	[dlbQty]	NUMERIC(18,6) NOT NULL,
	[dtmReceiveDate]	DATETIME,
	[dtmProductionDate]	DATETIME,
	[intItemId]	INT NOT NULL,
	[intContainerId]	INT NOT NULL,
	[intOwnerId]	INT NOT NULL,
	[intLotId]	INT NOT NULL,
	[intUOMId]	INT NOT NULL,
	[strReasonCode]	NVARCHAR(100) COLLATE Latin1_General_CI_AS NOT NULL, 
	[strComment]	NVARCHAR(100) COLLATE Latin1_General_CI_AS NOT NULL, 
	[intParentSKUId]	INT,
	[strParentSKUNo]	NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
	[dblWeightPerUnit]	NUMERIC(18,6) NOT NULL,
	[intWeightPerUnitUOMKey]	NUMERIC NOT NULL,
	[intUnitsPerLayer]	INT NOT NULL,
	[intLayersPerPallet]	INT NOT NULL,
	[ysnIsSanitized]	BIT,
	[strBatchNo]	NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 

    CONSTRAINT [PK_tblWMSKU_intSKUId]  PRIMARY KEY ([intSKUId]),	
	CONSTRAINT [FK_tblWMSKU_tblWMContainer_intContainerId] FOREIGN KEY ([intContainerId]) REFERENCES [tblWMContainer]([intContainerId]), 
	CONSTRAINT [FK_tblWMSKU_tblICLot_intLotId] FOREIGN KEY ([intLotId]) REFERENCES [tblICLot]([intLotId]), 
	CONSTRAINT [FK_tblWMSKU_tblICItem_intItemId] FOREIGN KEY ([intItemId]) REFERENCES [tblICItem]([intItemId]), 
	CONSTRAINT [FK_tblWMSKU_tblWMSKUStatus_intSKUStatusId] FOREIGN KEY ([intSKUStatusId]) REFERENCES [tblWMSKUStatus]([intSKUStatusId]), 

)
