CREATE PROCEDURE [dbo].[uspFRDTrialBalanceDetailWithCurrencies]        
 @intRowId AS INT      
AS        
        
 SET QUOTED_IDENTIFIER OFF        
 SET ANSI_NULLS ON        
 SET NOCOUNT ON        
 SET XACT_ABORT ON        
      
BEGIN       
 DECLARE @intStartRow int        
 DECLARE @intEndRow int        
 DECLARE @strFormula NVARCHAR(MAX)             
      
 CREATE TABLE [dbo].[#tblFRRowDesign] (      
  [intRowId]     INT             NOT NULL,      
  [intRefNo]     INT             NOT NULL,      
  [strDescription]   NVARCHAR (250)  COLLATE Latin1_General_CI_AS NULL,      
  [strRowType]    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,      
  [strBalanceSide]   NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,      
  [strSource]     NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,      
  [strCalculationOverride] NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,       
  [strRelatedRows]   NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,      
  [strAccountsUsed]   NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,      
  [strPercentage]    NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,      
  [strAccountsType]   NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,      
  [strDateOverride]   NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,       
  [ysnShowCredit]    BIT             DEFAULT 1 NULL,      
  [ysnShowDebit]    BIT             DEFAULT 1 NULL,      
  [ysnShowOthers]    BIT             DEFAULT 1 NULL,      
  [ysnLinktoGL]    BIT             NULL,      
  [ysnPrintEach]    BIT             NULL,      
  [ysnHidden]     BIT             NULL,      
  [dblHeight]     NUMERIC (18, 6) NULL,      
  [strFontName]    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,      
  [strFontStyle]    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,      
  [strFontColor]    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,      
  [intFontSize]    INT             NULL,      
  [strOverrideFormatMask]  NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,      
  [ysnForceReversedExpense] BIT             DEFAULT 0 NULL,      
  [ysnOverrideFormula]  BIT             DEFAULT 0 NULL,      
  [ysnOverrideColumnFormula] BIT             DEFAULT 0 NULL,      
  [intSort]     INT             NULL,      
  [intConcurrencyId]   INT             DEFAULT 1 NOT NULL,      
  [ysnShowCurrencies]         BIT             DEFAULT 0 NULL,      
  [intCurrencyID]    INT             DEFAULT 0 NULL,      
  [strCurrency]          NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,         
  [ysnUnnaturalAccount]     BIT             DEFAULT 0 NULL,      
 );      
      
-- COLUMNS      
      
 INSERT INTO [#tblFRRowDesign] (      
  [intRowId],      
  [intRefNo],      
  [strDescription],      
  [strRowType],      
  [strBalanceSide],      
  [strSource],        
  [strRelatedRows],      
  [strAccountsUsed],      
  [strPercentage],      
  [strAccountsType],      
  [ysnShowCredit],      
  [ysnShowDebit],      
  [ysnShowOthers],      
  [ysnLinktoGL],      
  [ysnPrintEach],      
  [ysnHidden],      
  [dblHeight],      
  [strFontName],      
  [strFontStyle],      
  [strFontColor],      
  [intFontSize],      
  [strOverrideFormatMask],      
  [ysnForceReversedExpense],      
  [ysnOverrideFormula],      
  [ysnOverrideColumnFormula],      
  [intSort],      
  [ysnShowCurrencies],      
  [intConcurrencyId],      
  [intCurrencyID],      
  [strCurrency],      
  [ysnUnnaturalAccount])       
 SELECT       
  @intRowId intRowId,      
  1,      
  '' strDescription,      
  'Column Name - Page Header' strRowType,      
  '' strBalanceSide,      
  '' strSource,      
  '' strRelatedRows,      
  '' strAccountsUsed,      
  NULL strPercentage,      
  '' strAccountsType,      
  0 ysnShowCredit,      
  0 ysnShowDebit,      
  1 ysnShowOthers,      
  0 ysnLinktoGL,      
  NULL ysnPrintEach,      
  0 ysnHidden,      
  '3.000000' dblHeight,      
  'Arial' strFontName,      
  'Normal' strFontStyle,      
  'Black' strFontColor,      
  8 intFontSize,      
  '' strOverrideFormatMask,      
  0 ysnForceReversedExpense,      
  0 ysnOverrideFormula,      
  0 ysnOverrideColumnFormula,      
  1,      
  0 ysnShowCurrencies,      
  1 intConcurrencyId,      
  0 intCurrencyID,      
  NULL strCurrency,      
  0 ysnUnnaturalAccount      
      
-- GET ACCOUNTS AND PUT TO TEMPTABLE      
      
 SELECT ROW_NUMBER() OVER (ORDER BY strAccountId)intRefNo,strAccountId ,1  intRowId,T0.intAccountId, strAccountId + ' - ' +  strDescription strDescription, 'Filter Accounts' strRowType,'Debit' strBalanceSide,'Column' strSource,'' strRelatedRows,      
 '[ID] ='''+ strAccountId +''' ' strAccountsUsed,NULL strPercentage,      
 CASE       
  WHEN ISNULL(intRetainAccount,0) <> 0 THEN 'RE'      
  ELSE      
   CASE       
    WHEN strAccountType = 'Asset' OR strAccountType = 'Liability'  THEN 'BS'      
    WHEN strAccountType = 'Revenue' OR strAccountType = 'Expense'  THEN 'IS'      
    ELSE  'BS'      
   END       
  END      
 strAccountsType,0 ysnShowCredit ,0 ysnShowDebit ,0 ysnShowOthers , 0 ysnLinktoGL , 0 ysnPrintEach  , 0 ysnHidden ,'3.000000' dblHeight , 'Arial' strFontName, 'Normal' strFontStyle, 'Black' strFontColor,      
 8 intFontSize,'' strOverrideFormatMask, 0 ysnForceReversedExpense, 0 ysnOverrideFormula,0 ysnOverrideColumnFormula,GETDATE() dtmEntered, 1 ysnShowCurrencies,1 intConcurrencyId,0 intCurrencyID, NULL strCurrency,0 ysnUnnaturalAccount      
 INTO #TMPTABLE       
 FROM tblGLAccount T0      
 INNER JOIN tblGLAccountGroup T1      
 ON T0.intAccountGroupId = T1.intAccountGroupId      
 LEFT JOIN (SELECT DISTINCT intRetainAccount FROM tblGLFiscalYear) T2       
 ON T0.intAccountId = T2.intRetainAccount       
 ORDER BY strAccountId      
      
-- UBNDERSCORE      
 INSERT INTO [#tblFRRowDesign] (      
  [intRowId],      
  [intRefNo],      
  [strDescription],      
  [strRowType],      
  [strBalanceSide],      
  [strSource],        
  [strRelatedRows],      
  [strAccountsUsed],      
  [strPercentage],      
  [strAccountsType],      
  [ysnShowCredit],      
  [ysnShowDebit],      
  [ysnShowOthers],      
  [ysnLinktoGL],      
  [ysnPrintEach],      
  [ysnHidden],      
  [dblHeight],      
  [strFontName],      
  [strFontStyle],      
  [strFontColor],      
  [intFontSize],      
  [strOverrideFormatMask],      
  [ysnForceReversedExpense],      
  [ysnOverrideFormula],      
  [ysnOverrideColumnFormula],      
  [intSort],      
  [ysnShowCurrencies],      
  [intConcurrencyId],      
  [intCurrencyID],      
  [strCurrency],      
  [ysnUnnaturalAccount])       
 SELECT       
  @intRowId intRowId,      
  9997,      
  '' strDescription,      
  'Underscore' strRowType,      
  '' strBalanceSide,      
  '' strSource,      
  '' strRelatedRows,      
  '' strAccountsUsed,      
  NULL strPercentage,      
  '' strAccountsType,      
  1 ysnShowCredit,      
  1 ysnShowDebit,      
  1 ysnShowOthers,      
  0 ysnLinktoGL,      
  NULL ysnPrintEach,      
  0 ysnHidden,      
  '3.000000' dblHeight,      
  'Arial' strFontName,      
  'Normal' strFontStyle,      
  'Black' strFontColor,      
  8 intFontSize,      
  '' strOverrideFormatMask,      
  0 ysnForceReversedExpense,      
  0 ysnOverrideFormula,      
  0 ysnOverrideColumnFormula,      
  1,      
  0 ysnShowCurrencies,      
  1 intConcurrencyId,      
  0 intCurrencyID,      
  NULL strCurrency,      
  0 ysnUnnaturalAccount      
      
-- TOTAL      
      
 SET @intStartRow = (SELECT TOP 1 intRefNo FROM #TMPTABLE ) + 1      
 SET @intEndRow = (SELECT MAX(intRefNo) FROM #TMPTABLE) + 1      
 SET @strFormula = 'SUM(R'+CAST(@intStartRow AS nvarchar(5))+':R'+CAST(@intEndRow AS nvarchar(5))+')'      
      
 INSERT INTO [#tblFRRowDesign] (      
  [intRowId],      
  [intRefNo],      
  [strDescription],      
  [strRowType],      
  [strBalanceSide],      
  [strSource],        
  [strRelatedRows],      
  [strAccountsUsed],      
  [strPercentage],      
  [strAccountsType],      
  [ysnShowCredit],      
  [ysnShowDebit],      
  [ysnShowOthers],      
  [ysnLinktoGL],      
  [ysnPrintEach],      
  [ysnHidden],      
  [dblHeight],      
  [strFontName],      
  [strFontStyle],      
  [strFontColor],      
  [intFontSize],      
  [strOverrideFormatMask],      
  [ysnForceReversedExpense],      
  [ysnOverrideFormula],      
  [ysnOverrideColumnFormula],      
  [intSort],      
  [ysnShowCurrencies],      
  [intConcurrencyId],      
  [intCurrencyID],      
  [strCurrency],      
  [ysnUnnaturalAccount])       
 SELECT       
  @intRowId intRowId,      
  9998,      
  '          Total :' strDescription,      
  'Row Calculation' strRowType,      
  '' strBalanceSide,      
  '' strSource,      
  @strFormula strRelatedRows,      
  '' strAccountsUsed,      
  NULL strPercentage,      
  '' strAccountsType,      
  1 ysnShowCredit,      
  1 ysnShowDebit,      
  1 ysnShowOthers,      
  0 ysnLinktoGL,      
  NULL ysnPrintEach,      
  0 ysnHidden,      
  '3.000000' dblHeight,      
  'Arial' strFontName,      
  'Bold' strFontStyle,      
  'Black' strFontColor,      
  8 intFontSize,      
  '' strOverrideFormatMask,      
  0 ysnForceReversedExpense,      
  1 ysnOverrideFormula,      
  0 ysnOverrideColumnFormula,      
  1,      
  0 ysnShowCurrencies,      
  1 intConcurrencyId,      
  0 intCurrencyID,      
  NULL strCurrency,      
  0 ysnUnnaturalAccount      
      
-- DOUBLE UNDERSCORE      
      
 INSERT INTO [#tblFRRowDesign] (      
  [intRowId],      
  [intRefNo],      
  [strDescription],      
  [strRowType],      
  [strBalanceSide],      
  [strSource],        
  [strRelatedRows],      
  [strAccountsUsed],      
  [strPercentage],      
  [strAccountsType],      
  [ysnShowCredit],      
  [ysnShowDebit],      
  [ysnShowOthers],      
  [ysnLinktoGL],      
  [ysnPrintEach],      
  [ysnHidden],      
  [dblHeight],      
  [strFontName],      
  [strFontStyle],      
  [strFontColor],      
  [intFontSize],      
  [strOverrideFormatMask],      
  [ysnForceReversedExpense],      
  [ysnOverrideFormula],      
  [ysnOverrideColumnFormula],      
  [intSort],      
  [ysnShowCurrencies],      
  [intConcurrencyId],      
  [intCurrencyID],      
  [strCurrency],      
  [ysnUnnaturalAccount])       
 SELECT       
  @intRowId intRowId,      
  9999,      
  '' strDescription,      
  'Double Underscore' strRowType,      
  '' strBalanceSide,      
  '' strSource,      
  '' strRelatedRows,      
  '' strAccountsUsed,      
  NULL strPercentage,      
  '' strAccountsType,      
  1 ysnShowCredit,      
  1 ysnShowDebit,      
  1 ysnShowOthers,      
  0 ysnLinktoGL,      
  NULL ysnPrintEach,      
  0 ysnHidden,      
  '3.000000' dblHeight,      
  'Arial' strFontName,      
  'Normal' strFontStyle,      
  'Black' strFontColor,      
  8 intFontSize,      
  '' strOverrideFormatMask,      
  0 ysnForceReversedExpense,      
  0 ysnOverrideFormula,      
  0 ysnOverrideColumnFormula,      
  1,      
  0 ysnShowCurrencies,      
  1 intConcurrencyId,      
  0 intCurrencyID,      
  NULL strCurrency,      
  0 ysnUnnaturalAccount      
      
-- INSERT TEMPTALE ROW TO #TBLFRROWDESIGN      
 INSERT INTO [#tblFRRowDesign] (      
  [intRowId],      
  [intRefNo],      
  [strDescription],      
  [strRowType],      
  [strBalanceSide],      
  [strSource],        
  [strRelatedRows],      
  [strAccountsUsed],      
  [strPercentage],      
  [strAccountsType],      
  [ysnShowCredit],      
  [ysnShowDebit],      
  [ysnShowOthers],      
  [ysnLinktoGL],      
  [ysnPrintEach],      
  [ysnHidden],      
  [dblHeight],      
  [strFontName],      
  [strFontStyle],      
  [strFontColor],      
  [intFontSize],      
  [strOverrideFormatMask],      
  [ysnForceReversedExpense],      
  [ysnOverrideFormula],      
  [ysnOverrideColumnFormula],      
  [intSort],      
  [intConcurrencyId],      
  [ysnShowCurrencies],      
  [intCurrencyID],      
  [strCurrency],      
  [ysnUnnaturalAccount])       
 SELECT       
  @intRowId,      
  intRefNo,      
  strDescription,      
  strRowType,      
  strBalanceSide,      
  strSource,      
  strRelatedRows,      
  strAccountsUsed,      
  strPercentage,      
  strAccountsType,      
  ysnShowCredit,      
  ysnShowDebit,      
  ysnShowOthers,      
  ysnLinktoGL,      
  ysnPrintEach,      
  ysnHidden,      
  dblHeight,      
  strFontName,      
  strFontStyle,      
  strFontColor,      
  intFontSize,      
  strOverrideFormatMask,      
  ysnForceReversedExpense,      
  ysnOverrideFormula,      
  ysnOverrideColumnFormula,      
  intRefNo,      
  intConcurrencyId,      
  ysnShowCurrencies,      
  intCurrencyID,      
  strCurrency,      
  ysnUnnaturalAccount       
  FROM #TMPTABLE      
       
-- INSERT INTO TBLROWDESIGN      
       
 INSERT INTO tblFRRowDesign (      
  [intRowId],      
  [intRefNo],      
  [strDescription],      
  [strRowType],      
  [strBalanceSide],      
  [strSource],        
  [strRelatedRows],      
  [strAccountsUsed],      
  [strPercentage],      
  [strAccountsType],      
  [ysnShowCredit],      
  [ysnShowDebit],      
  [ysnShowOthers],      
  [ysnLinktoGL],      
  [ysnPrintEach],      
  [ysnHidden],     
  [dblHeight],      
  [strFontName],      
  [strFontStyle],      
  [strFontColor],      
  [intFontSize],      
  [strOverrideFormatMask],      
  [ysnForceReversedExpense],      
  [ysnOverrideFormula],      
  [ysnOverrideColumnFormula],      
  [intSort],      
  [intConcurrencyId],      
  [ysnShowCurrencies],      
  [intCurrencyID],      
  [strCurrency],      
  [ysnUnnaturalAccount])       
 SELECT       
  @intRowId,      
  ROW_NUMBER() OVER (ORDER BY intRefNo , strDescription),      
  strDescription,      
  strRowType,      
  strBalanceSide,      
  strSource,      
  strRelatedRows,      
  strAccountsUsed,      
  strPercentage,      
  strAccountsType,      
  ysnShowCredit,      
  ysnShowDebit,      
  ysnShowOthers,      
  ysnLinktoGL,      
  ysnPrintEach,      
  ysnHidden,      
  dblHeight,      
  strFontName,      
  strFontStyle,      
  strFontColor,      
  intFontSize,      
  strOverrideFormatMask,      
  ysnForceReversedExpense,      
  ysnOverrideFormula,      
  ysnOverrideColumnFormula,      
  ROW_NUMBER() OVER (ORDER BY intRefNo , strDescription),      
  intConcurrencyId,      
  ysnShowCurrencies,      
  intCurrencyID,      
  strCurrency,      
  ysnUnnaturalAccount       
  FROM #tblFRRowDesign      
        
-- INSERT INTO TBLROWDESIGNFILTERACCOUNT      
      
  INSERT INTO tblFRRowDesignFilterAccount      
  SELECT T0.intRowDetailId,T0.intRowId,T0.intRefNo,'ID','=',T1.strAccountId,'','Or','1' FROM tblFRRowDesign  T0      
  INNER JOIN #TMPTABLE T1 ON T0.strAccountsUsed = T1.strAccountsUsed      
       
 DROP TABLE #TMPTABLE      
END