CREATE PROCEDURE [dbo].[uspHDUpdateJiraIcon]
AS
BEGIN

SET QUOTED_IDENTIFIER OFF  
SET ANSI_NULLS ON  
SET NOCOUNT ON  
SET XACT_ABORT ON  
SET ANSI_WARNINGS ON  

	UPDATE JiraDetailToUpdate
	SET JiraDetailToUpdate.strJiraType = CASE WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Bug%'
														THEN 'Bug' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Bug-Ongoing UAP%'
														THEN 'Bug-Ongoing UAP' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Bug-QC%'
														THEN 'Bug-QC' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Bug-UAP%'
														THEN 'Bug-UAP' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Data Fix%'
														THEN 'Data Fix' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Epic%'
														THEN 'Epic' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Feature%'
														THEN 'Feature' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Gap%'
														THEN 'Gap' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Integration%'
														THEN 'Integration' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Paid%'
														THEN 'Paid' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Story%'
														THEN 'Story' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Sub-task%'
														THEN 'Sub-task' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Sub-test%'
														THEN 'Sub-test' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Suggestion%'
														THEN 'Suggestion' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Task%'
														THEN 'Task' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%Technical Debt%'
														THEN 'Technical Debt' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%UAP Automation%'
														THEN 'UAP Automation' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%UAP Test Case%'
														THEN 'UAP Test Case'
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%UAP Verification%'
														THEN 'UAP Verification' 
													 WHEN JiraDetailToUpdate.strTypeIconUrl LIKE '%zOld%'
														THEN 'zOld' 
													 ELSE ''
												END
	,JiraDetailToUpdate.strJiraPriority = CASE WHEN JiraDetailToUpdate.strPriorityIconUrl LIKE '%Blocker%'
														THEN 'Blocker' 
													 WHEN JiraDetailToUpdate.strPriorityIconUrl LIKE '%Critical%'
														THEN 'Critical' 
													 WHEN JiraDetailToUpdate.strPriorityIconUrl LIKE '%Major%'
														THEN 'Major' 
													 WHEN JiraDetailToUpdate.strPriorityIconUrl LIKE '%Minor%'
														THEN 'Minor' 
													 ELSE '' 
												END
    ,JiraDetailToUpdate.strJiraStatus	= CASE   WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Open%'
															  THEN 'Open' 
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Closed%'
															  THEN 'Closed'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Unapproved%'
															  THEN 'Unapproved'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Coding%'
															  THEN 'Coding'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Investigating%'
															  THEN 'Investigating'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Wait for Estimate%'
															  THEN 'Wait for Estimate'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Wait for Funding%'
															  THEN 'Wait for Funding'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Spec Incomplete%'
															  THEN 'Spec Incomplete'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Reopened%'
															  THEN 'Reopened'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Resolved%'
															  THEN 'Resolved'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Testing%'
															  THEN 'Testing'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Ready to Test%'
															  THEN 'Ready to Test'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%To Do%'
															  THEN 'To Do'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Passed%'
															  THEN 'Passed'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Backlog%'
															  THEN 'Backlog'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Selected for Development%'
															  THEN 'Selected for Development'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Failed%'
															  THEN 'Failed'
														 WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Done%'
															  THEN 'Done'
														WHEN JiraDetailToUpdate.strStatusIconUrl LIKE '%Locked%'
															  THEN 'Locked'
														 ELSE ''
													END 
													 + REPLACE(JiraDetailToUpdate.strStatusIconUrl, SUBSTRING(JiraDetailToUpdate.strStatusIconUrl, 0, CHARINDEX('&nbsp', JiraDetailToUpdate.strStatusIconUrl)), '')
	FROM tblHDTicketJIRAIssue TicketJIRAIssue
		INNER JOIN tblHDTicketJIRAIssue JiraDetailToUpdate
	ON JiraDetailToUpdate.intTicketJIRAIssueId = TicketJIRAIssue.intTicketJIRAIssueId
END
GO