CREATE PROCEDURE [dbo].[uspICRepostSettleStorageCostAdjustment]
	@strSettleStorageId AS NVARCHAR(50)
	,@strBatchId AS NVARCHAR(20)
	,@intEntityUserSecurityId AS INT
AS

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON
SET NOCOUNT ON
SET XACT_ABORT ON
SET ANSI_WARNINGS OFF

_Exit:
