CREATE PROCEDURE uspMFCopyBatch (
	@strBatchId NVARCHAR(50)
	,@intDestinationLocationId INT
	)
AS
BEGIN
	INSERT INTO dbo.tblMFBatch (
		strBatchId
		,intSales
		,intSalesYear
		,dtmSalesDate
		,strTeaType
		,intBrokerId
		,strVendorLotNumber
		,intBuyingCenterLocationId
		,intParentBatchId
		,intStorageLocationId
		,intStorageUnitId
		,intInventoryReceiptId
		,intBrokerWarehouseId
		,intSampleId
		,intItemUOMId
		,intWeightUOMId
		,intContractDetailId
		,str3PLStatus
		,strSupplierReference
		,strAirwayBillCode
		,strAWBSampleReceived
		,strAWBSampleReference
		,dblBasePrice
		,ysnBoughtAsReserved
		,dblBoughtPrice
		,dblBulkDensity
		,strBuyingOrderNumber
		,intSubBookId
		,strContainerNumber
		,intCurrencyId
		,dtmProductionBatch
		,dtmTeaAvailableFrom
		,strDustContent
		,ysnEUCompliant
		,strTBOEvaluatorCode
		,strEvaluatorRemarks
		,dtmExpiration
		,intFromPortId
		,dblGrossWeight
		,dtmInitialBuy
		,dblWeightPerUnit
		,dblLandedPrice
		,strLeafCategory
		,strLeafManufacturingType
		,strLeafSize
		,strLeafStyle
		,intMixingUnitLocationId
		,dblPackagesBought
		,strTeaOrigin
		,intOriginalItemId
		,dblPackagesPerPallet
		,strPlant
		,dblTotalQuantity
		,strSampleBoxNumber
		,dblSellingPrice
		,dtmStock
		,strSubChannel
		,ysnStrategic
		,strTeaLingoSubCluster
		,dtmSupplierPreInvoiceDate
		,strSustainability
		,strTasterComments
		,dblTeaAppearance
		,strTeaBuyingOffice
		,strTeaColour
		,strTeaGardenChopInvoiceNumber
		,intGardenMarkId
		,strTeaGroup
		,dblTeaHue
		,dblTeaIntensity
		,strLeafGrade
		,dblTeaMoisture
		,dblTeaMouthFeel
		,ysnTeaOrganic
		,dblTeaTaste
		,dblTeaVolume
		,intTealingoItemId
		,dtmWarehouseArrival
		,intYearManufacture
		,strPackageSize
		,intPackageUOMId
		,dblTareWeight
		,strTaster
		,strFeedStock
		,strFlourideLimit
		,strLocalAuctionNumber
		,strPOStatus
		,strProductionSite
		,strReserveMU
		,strQualityComments
		,strRareEarth
		,strERPPONumber
		,strFreightAgent
		,strSealNumber
		,strContainerType
		,strVoyage
		,strVessel
		,intReasonCodeId
		,dtmSplit
		,strNotes
		,intConcurrencyId
		)
	SELECT strBatchId
		,intSales
		,intSalesYear
		,dtmSalesDate
		,strTeaType
		,intBrokerId
		,strVendorLotNumber
		,intBuyingCenterLocationId
		,intParentBatchId
		,intStorageLocationId
		,intStorageUnitId
		,intInventoryReceiptId
		,intBrokerWarehouseId
		,intSampleId
		,intItemUOMId
		,intWeightUOMId
		,intContractDetailId
		,str3PLStatus
		,strSupplierReference
		,strAirwayBillCode
		,strAWBSampleReceived
		,strAWBSampleReference
		,dblBasePrice
		,ysnBoughtAsReserved
		,dblBoughtPrice
		,dblBulkDensity
		,strBuyingOrderNumber
		,intSubBookId
		,strContainerNumber
		,intCurrencyId
		,dtmProductionBatch
		,dtmTeaAvailableFrom
		,strDustContent
		,ysnEUCompliant
		,strTBOEvaluatorCode
		,strEvaluatorRemarks
		,dtmExpiration
		,intFromPortId
		,dblGrossWeight
		,dtmInitialBuy
		,dblWeightPerUnit
		,dblLandedPrice
		,strLeafCategory
		,strLeafManufacturingType
		,strLeafSize
		,strLeafStyle
		,@intDestinationLocationId
		,dblPackagesBought
		,strTeaOrigin
		,intOriginalItemId
		,dblPackagesPerPallet
		,strPlant
		,dblTotalQuantity
		,strSampleBoxNumber
		,dblSellingPrice
		,dtmStock
		,strSubChannel
		,ysnStrategic
		,strTeaLingoSubCluster
		,dtmSupplierPreInvoiceDate
		,strSustainability
		,strTasterComments
		,dblTeaAppearance
		,strTeaBuyingOffice
		,strTeaColour
		,strTeaGardenChopInvoiceNumber
		,intGardenMarkId
		,strTeaGroup
		,dblTeaHue
		,dblTeaIntensity
		,strLeafGrade
		,dblTeaMoisture
		,dblTeaMouthFeel
		,ysnTeaOrganic
		,dblTeaTaste
		,dblTeaVolume
		,intTealingoItemId
		,dtmWarehouseArrival
		,intYearManufacture
		,strPackageSize
		,intPackageUOMId
		,dblTareWeight
		,strTaster
		,strFeedStock
		,strFlourideLimit
		,strLocalAuctionNumber
		,strPOStatus
		,strProductionSite
		,strReserveMU
		,strQualityComments
		,strRareEarth
		,strERPPONumber
		,strFreightAgent
		,strSealNumber
		,strContainerType
		,strVoyage
		,strVessel
		,intReasonCodeId
		,dtmSplit
		,strNotes
		,intConcurrencyId
	FROM dbo.tblMFBatch
	WHERE strBatchId = @strBatchId
END
