CREATE PROCEDURE [dbo].[uspSCTicketAutoScaleLog]
	@TICKET_ID INT
	,@UNIT NUMERIC(18, 6)
	,@CONTRACT_ID INT	
AS
BEGIN
	PRINT 'TICKET LOG'
	INSERT INTO tblSCTicketAutoScaleLog(intTicketId, dblUnit, intContractDetailId) 
	SELECT @TICKET_ID, @UNIT, @CONTRACT_ID
END
