CREATE TABLE [dbo].[gaaudmst] (
    [gaaud_pur_sls_ind]            CHAR (1)        NOT NULL,
    [gaaud_trans_type]             CHAR (2)        NOT NULL,
    [gaaud_key_filler1]            CHAR (26)       NOT NULL,
    [gaaud_in_type]                CHAR (2)        NOT NULL,
    [gaaud_key_filler2]            CHAR (18)       NOT NULL,
    [gaaud_tie_breaker]            INT             NOT NULL,
    [gaaudcnt_cnt_rev_dt]          INT             NULL,
    [gaaudcnt_cnt_time]            SMALLINT        NULL,
    [gaaudcnt_beg_ship_rev_dt]     INT             NULL,
    [gaaudcnt_due_rev_dt]          INT             NULL,
    [gaaudcnt_defer_pmt_rev_dt]    INT             NULL,
    [gaaudcnt_trk_rail_ind]        CHAR (1)        NULL,
    [gaaudcnt_pbhcu_ind]           CHAR (1)        NULL,
    [gaaudcnt_no_un]               DECIMAL (11, 3) NULL,
    [gaaudcnt_un_bal]              DECIMAL (11, 3) NULL,
    [gaaudcnt_un_bal_unprc]        DECIMAL (11, 3) NULL,
    [gaaudcnt_un_bal_transit]      DECIMAL (11, 3) NULL,
    [gaaudcnt_sched_un]            DECIMAL (11, 3) NULL,
    [gaaudcnt_dp_cnt_max_un]       DECIMAL (11, 3) NULL,
    [gaaudcnt_un_bot_prc]          DECIMAL (9, 5)  NULL,
    [gaaudcnt_bot]                 CHAR (1)        NULL,
    [gaaudcnt_bot_option]          CHAR (5)        NULL,
    [gaaudcnt_un_bot_basis]        DECIMAL (9, 5)  NULL,
    [gaaudcnt_un_frt_basis]        DECIMAL (9, 5)  NULL,
    [gaaudcnt_as_is_disc]          DECIMAL (9, 5)  NULL,
    [gaaudcnt_cnt_fee_un]          DECIMAL (9, 5)  NULL,
    [gaaudcnt_roll_fee_un]         DECIMAL (9, 5)  NULL,
    [gaaudcnt_un_cash_prc]         DECIMAL (9, 5)  NULL,
    [gaaudcnt_cnt_fill_no]         CHAR (5)        NULL,
    [gaaudcnt_mkt_zone]            CHAR (3)        NULL,
    [gaaudcnt_option]              TINYINT         NULL,
    [gaaudcnt_variety_cd]          CHAR (2)        NULL,
    [gaaudcnt_last_cnt_seq_no]     SMALLINT        NULL,
    [gaaudcnt_last_cnt_sub_no]     SMALLINT        NULL,
    [gaaudcnt_last_hst_seq_no]     INT             NULL,
    [gaaudcnt_int_rt]              DECIMAL (7, 4)  NULL,
    [gaaudcnt_carry_per_day]       DECIMAL (9, 6)  NULL,
    [gaaudcnt_disc_dca_ind]        CHAR (1)        NULL,
    [gaaudcnt_disc_schd_no]        TINYINT         NULL,
    [gaaudcnt_stor_schd_no]        TINYINT         NULL,
    [gaaudcnt_text_no]             CHAR (2)        NULL,
    [gaaudcnt_signed_yn]           CHAR (1)        NULL,
    [gaaudcnt_printed_yn]          CHAR (1)        NULL,
    [gaaudcnt_printed_lbl_yn]      CHAR (1)        NULL,
    [gaaudcnt_buyer]               CHAR (15)       NULL,
    [gaaudcnt_seller]              CHAR (15)       NULL,
    [gaaudcnt_comments]            CHAR (15)       NULL,
    [gaaudcnt_cus_cnt_no]          CHAR (10)       NULL,
    [gaaudcnt_remarks_1]           CHAR (40)       NULL,
    [gaaudcnt_remarks_2]           CHAR (40)       NULL,
    [gaaudcnt_remarks_3]           CHAR (40)       NULL,
    [gaaudcnt_remarks_4]           CHAR (40)       NULL,
    [gaaudcnt_remarks_5]           CHAR (40)       NULL,
    [gaaudcnt_remarks_6]           CHAR (40)       NULL,
    [gaaudcnt_remarks_7]           CHAR (40)       NULL,
    [gaaudcnt_remarks_8]           CHAR (40)       NULL,
    [gaaudcnt_remarks_9]           CHAR (40)       NULL,
    [gaaudcnt_loads_cnt_yn]        CHAR (1)        NULL,
    [gaaudcnt_un_per_load]         DECIMAL (11, 3) NULL,
    [gaaudcnt_orig_no_loads]       INT             NULL,
    [gaaudcnt_applied_no_loads]    INT             NULL,
    [gaaudcnt_frt_trk_rt]          DECIMAL (9, 5)  NULL,
    [gaaudcnt_avg_car_grade]       CHAR (1)        NULL,
    [gaaudcnt_bill_to_cus]         CHAR (10)       NULL,
    [gaaudcnt_broker_no]           CHAR (10)       NULL,
    [gaaudcnt_brk_posted_yn]       CHAR (1)        NULL,
    [gaaudcnt_broker_un_rt]        DECIMAL (9, 5)  NULL,
    [gaaudcnt_broker_gl_acct]      DECIMAL (16, 8) NULL,
    [gaaudcnt_origin]              CHAR (20)       NULL,
    [gaaudcnt_destination]         CHAR (20)       NULL,
    [gaaudcnt_grade_cd]            CHAR (1)        NULL,
    [gaaudcnt_weight_cd]           CHAR (1)        NULL,
    [gaaudcnt_fob_prc_basis]       CHAR (13)       NULL,
    [gaaudcnt_frt_cus_1]           CHAR (10)       NULL,
    [gaaudcnt_frt_cus_2]           CHAR (10)       NULL,
    [gaaudcnt_frt_cus_3]           CHAR (10)       NULL,
    [gaaudcnt_frt_type_1]          CHAR (1)        NULL,
    [gaaudcnt_frt_type_2]          CHAR (1)        NULL,
    [gaaudcnt_frt_type_3]          CHAR (1)        NULL,
    [gaaudcnt_frt_rail_rt_1]       DECIMAL (11, 6) NULL,
    [gaaudcnt_frt_rail_rt_2]       DECIMAL (11, 6) NULL,
    [gaaudcnt_frt_rail_rt_3]       DECIMAL (11, 6) NULL,
    [gaaudcnt_frt_gl_acct_1]       DECIMAL (16, 8) NULL,
    [gaaudcnt_frt_gl_acct_2]       DECIMAL (16, 8) NULL,
    [gaaudcnt_frt_gl_acct_3]       DECIMAL (16, 8) NULL,
    [gaaudcnt_frt_currency]        CHAR (3)        NULL,
    [gaaudcnt_frt_currency_rt]     DECIMAL (15, 8) NULL,
    [gaaudcnt_frt_currency_cnt]    CHAR (8)        NULL,
    [gaaudcnt_currency]            CHAR (3)        NULL,
    [gaaudcnt_currency_rt]         DECIMAL (15, 8) NULL,
    [gaaudcnt_currency_cnt]        CHAR (8)        NULL,
    [gaaudcnt_wmp_whole]           DECIMAL (9, 5)  NULL,
    [gaaudcnt_wmp_broken]          DECIMAL (9, 5)  NULL,
    [gaaudcnt_loan_whole]          DECIMAL (9, 5)  NULL,
    [gaaudcnt_loan_broken]         DECIMAL (9, 5)  NULL,
    [gaaudcnt_orig_no_un]          DECIMAL (11, 3) NULL,
    [gaaudcnt_orig_un_basis]       DECIMAL (9, 5)  NULL,
    [gaaudcnt_orig_bot_un_prc]     DECIMAL (9, 5)  NULL,
    [gaaudcnt_orig_bot_option]     CHAR (5)        NULL,
    [gaaudcnt_eom_no_un]           DECIMAL (11, 3) NULL,
    [gaaudcnt_eom_un_basis]        DECIMAL (9, 5)  NULL,
    [gaaudcnt_eom_bot_un_prc]      DECIMAL (9, 5)  NULL,
    [gaaudcnt_eom_bot_option]      CHAR (5)        NULL,
    [gaaudcnt_prv_no_un]           DECIMAL (11, 3) NULL,
    [gaaudcnt_prv_un_basis]        DECIMAL (9, 5)  NULL,
    [gaaudcnt_prv_bot_un_prc]      DECIMAL (9, 5)  NULL,
    [gaaudcnt_prv_bot_option]      CHAR (5)        NULL,
    [gaaudcnt_un_basis_prc]        DECIMAL (11, 3) NULL,
    [gaaudcnt_basis_prc_yn]        CHAR (1)        NULL,
    [gaaudcnt_user_id]             CHAR (16)       NULL,
    [gaaudcnt_user_rev_dt]         INT             NULL,
    [gaaudcol_cnt_no]              CHAR (8)        NULL,
    [gaaudcol_open_rev_dt]         INT             NULL,
    [gaaudcol_orig_un]             DECIMAL (11, 3) NULL,
    [gaaudcol_un_bal]              DECIMAL (11, 3) NULL,
    [gaaudcol_close_rev_dt]        INT             NULL,
    [gaaudcol_comment]             CHAR (30)       NULL,
    [gaaudcol_user_id]             CHAR (16)       NULL,
    [gaaudcol_user_rev_dt]         CHAR (8)        NULL,
    [gaaudexf_comment]             CHAR (30)       NULL,
    [gaaudexf_rev_dt]              INT             NULL,
    [gaaudexf_no_un]               DECIMAL (11, 3) NULL,
    [gaaudexf_frt_no]              CHAR (10)       NULL,
    [gaaudexf_frt_no_un]           DECIMAL (11, 3) NULL,
    [gaaudexf_frt_un_rt]           DECIMAL (9, 5)  NULL,
    [gaaudexf_frt_gl_acct]         DECIMAL (16, 8) NULL,
    [gaaudexf_un_prc]              DECIMAL (9, 5)  NULL,
    [gaaudexf_cost]                DECIMAL (11, 2) NULL,
    [gaaudexf_tic_comment]         CHAR (30)       NULL,
    [gaaudexf_tot_shrk_pct_wgt]    DECIMAL (7, 4)  NULL,
    [gaaudexf_disc_schd_no]        TINYINT         NULL,
    [gaaudexf_disc_cd_1]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_2]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_3]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_4]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_5]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_6]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_7]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_8]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_9]           CHAR (2)        NULL,
    [gaaudexf_disc_cd_10]          CHAR (2)        NULL,
    [gaaudexf_disc_cd_11]          CHAR (2)        NULL,
    [gaaudexf_disc_cd_12]          CHAR (2)        NULL,
    [gaaudexf_reading_1]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_2]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_3]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_4]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_5]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_6]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_7]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_8]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_9]           DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_10]          DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_11]          DECIMAL (7, 3)  NULL,
    [gaaudexf_reading_12]          DECIMAL (7, 3)  NULL,
    [gaaudexf_un_disc_amt_1]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_2]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_3]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_4]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_5]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_6]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_7]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_8]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_9]       DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_10]      DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_11]      DECIMAL (9, 6)  NULL,
    [gaaudexf_un_disc_amt_12]      DECIMAL (9, 6)  NULL,
    [gaaudexf_shrk_what_1]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_2]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_3]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_4]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_5]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_6]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_7]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_8]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_9]         CHAR (1)        NULL,
    [gaaudexf_shrk_what_10]        CHAR (1)        NULL,
    [gaaudexf_shrk_what_11]        CHAR (1)        NULL,
    [gaaudexf_shrk_what_12]        CHAR (1)        NULL,
    [gaaudexf_shrk_pct_1]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_2]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_3]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_4]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_5]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_6]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_7]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_8]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_9]          DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_10]         DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_11]         DECIMAL (7, 4)  NULL,
    [gaaudexf_shrk_pct_12]         DECIMAL (7, 4)  NULL,
    [gaaudexf_from_bin_no]         CHAR (5)        NULL,
    [gaaudexf_to_bin_no]           CHAR (5)        NULL,
    [gaaudexf_audit_no]            CHAR (4)        NULL,
    [gaaudexf_user_id]             CHAR (16)       NULL,
    [gaaudexf_user_rev_dt]         INT             NULL,
    [gaaudhdg_exposure_yyyymm]     INT             NULL,
    [gaaudhdg_bot_prc]             DECIMAL (9, 5)  NULL,
    [gaaudhdg_bot_basis]           DECIMAL (9, 5)  NULL,
    [gaaudhdg_bot]                 CHAR (1)        NULL,
    [gaaudhdg_bot_option]          CHAR (5)        NULL,
    [gaaudhdg_comment]             CHAR (30)       NULL,
    [gaaudhdg_long_short_ind]      CHAR (1)        NULL,
    [gaaudhdg_un_hdg]              DECIMAL (11, 3) NULL,
    [gaaudhdg_un_hdg_bal]          DECIMAL (11, 3) NULL,
    [gaaudhdg_offset_yn]           CHAR (1)        NULL,
    [gaaudhdg_offset_rev_dt]       INT             NULL,
    [gaaudhdg_offset_ref]          CHAR (6)        NULL,
    [gaaudhdg_offset_seq]          SMALLINT        NULL,
    [gaaudhdg_orig_prc]            DECIMAL (9, 5)  NULL,
    [gaaudhdg_orig_basis]          DECIMAL (9, 5)  NULL,
    [gaaudhdg_avg_basis]           DECIMAL (9, 5)  NULL,
    [gaaudhdg_user_id]             CHAR (16)       NULL,
    [gaaudhdg_user_rev_dt]         INT             NULL,
    [gaaudins_hst_type]            CHAR (1)        NULL,
    [gaaudins_loc_no]              CHAR (3)        NULL,
    [gaaudins_spl_cus_no]          CHAR (10)       NULL,
    [gaaudins_spl_no]              CHAR (4)        NULL,
    [gaaudins_stl_amt]             DECIMAL (11, 2) NULL,
    [gaaudins_wthhld_amt]          DECIMAL (11, 2) NULL,
    [gaaudins_stl_rev_dt]          INT             NULL,
    [gaaudins_defer_pmt_rev_dt]    INT             NULL,
    [gaaudins_defer_pmt_cnt_no]    CHAR (8)        NULL,
    [gaaudins_pd_yn]               CHAR (1)        NULL,
    [gaaudins_man_auto_ind]        CHAR (1)        NULL,
    [gaaudins_chk_no]              INT             NULL,
    [gaaudins_pmt_rev_dt]          INT             NULL,
    [gaaudins_pmt_audit_no]        CHAR (4)        NULL,
    [gaaudins_ivc_printed_yn]      CHAR (1)        NULL,
    [gaaudins_ivc_no]              CHAR (8)        NULL,
    [gaaudins_ivc_rev_dt]          INT             NULL,
    [gaaudins_audit_no]            CHAR (4)        NULL,
    [gaaudins_cus_ref_no]          CHAR (15)       NULL,
    [gaaudins_orig_type]           CHAR (1)        NULL,
    [gaaudins_rail_ref_no]         INT             NULL,
    [gaaudins_no_un]               DECIMAL (11, 3) NULL,
    [gaaudins_un_prc]              DECIMAL (9, 5)  NULL,
    [gaaudins_un_disc_adj]         DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_pd]          DECIMAL (9, 6)  NULL,
    [gaaudins_un_stor_pd]          DECIMAL (9, 6)  NULL,
    [gaaudins_ckoff_amt]           DECIMAL (7, 2)  NULL,
    [gaaudins_origin_state]        CHAR (2)        NULL,
    [gaaudins_ins_amt]             DECIMAL (7, 2)  NULL,
    [gaaudins_ins_state]           CHAR (2)        NULL,
    [gaaudins_tax3_amt]            DECIMAL (7, 2)  NULL,
    [gaaudins_tax3_state]          CHAR (2)        NULL,
    [gaaudins_fees_pd]             DECIMAL (7, 2)  NULL,
    [gaaudins_un_frt_rt]           DECIMAL (9, 5)  NULL,
    [gaaudins_un_cnt_fee]          DECIMAL (9, 5)  NULL,
    [gaaudins_un_roll_fee]         DECIMAL (9, 5)  NULL,
    [gaaudins_un_bot_basis]        DECIMAL (9, 5)  NULL,
    [gaaudins_bot]                 CHAR (1)        NULL,
    [gaaudins_bot_option]          CHAR (5)        NULL,
    [gaaudins_tot_shrk_pct_wgt]    DECIMAL (7, 4)  NULL,
    [gaaudins_disc_schd_no]        TINYINT         NULL,
    [gaaudins_disc_cd_1]           CHAR (2)        NULL,
    [gaaudins_disc_cd_2]           CHAR (2)        NULL,
    [gaaudins_disc_cd_3]           CHAR (2)        NULL,
    [gaaudins_disc_cd_4]           CHAR (2)        NULL,
    [gaaudins_disc_cd_5]           CHAR (2)        NULL,
    [gaaudins_disc_cd_6]           CHAR (2)        NULL,
    [gaaudins_disc_cd_7]           CHAR (2)        NULL,
    [gaaudins_disc_cd_8]           CHAR (2)        NULL,
    [gaaudins_disc_cd_9]           CHAR (2)        NULL,
    [gaaudins_disc_cd_10]          CHAR (2)        NULL,
    [gaaudins_disc_cd_11]          CHAR (2)        NULL,
    [gaaudins_disc_cd_12]          CHAR (2)        NULL,
    [gaaudins_reading_1]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_2]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_3]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_4]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_5]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_6]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_7]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_8]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_9]           DECIMAL (7, 3)  NULL,
    [gaaudins_reading_10]          DECIMAL (7, 3)  NULL,
    [gaaudins_reading_11]          DECIMAL (7, 3)  NULL,
    [gaaudins_reading_12]          DECIMAL (7, 3)  NULL,
    [gaaudins_disc_calc_1]         CHAR (1)        NULL,
    [gaaudins_disc_calc_2]         CHAR (1)        NULL,
    [gaaudins_disc_calc_3]         CHAR (1)        NULL,
    [gaaudins_disc_calc_4]         CHAR (1)        NULL,
    [gaaudins_disc_calc_5]         CHAR (1)        NULL,
    [gaaudins_disc_calc_6]         CHAR (1)        NULL,
    [gaaudins_disc_calc_7]         CHAR (1)        NULL,
    [gaaudins_disc_calc_8]         CHAR (1)        NULL,
    [gaaudins_disc_calc_9]         CHAR (1)        NULL,
    [gaaudins_disc_calc_10]        CHAR (1)        NULL,
    [gaaudins_disc_calc_11]        CHAR (1)        NULL,
    [gaaudins_disc_calc_12]        CHAR (1)        NULL,
    [gaaudins_un_disc_amt_1]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_2]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_3]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_4]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_5]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_6]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_7]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_8]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_9]       DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_10]      DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_11]      DECIMAL (9, 6)  NULL,
    [gaaudins_un_disc_amt_12]      DECIMAL (9, 6)  NULL,
    [gaaudins_shrk_what_1]         CHAR (1)        NULL,
    [gaaudins_shrk_what_2]         CHAR (1)        NULL,
    [gaaudins_shrk_what_3]         CHAR (1)        NULL,
    [gaaudins_shrk_what_4]         CHAR (1)        NULL,
    [gaaudins_shrk_what_5]         CHAR (1)        NULL,
    [gaaudins_shrk_what_6]         CHAR (1)        NULL,
    [gaaudins_shrk_what_7]         CHAR (1)        NULL,
    [gaaudins_shrk_what_8]         CHAR (1)        NULL,
    [gaaudins_shrk_what_9]         CHAR (1)        NULL,
    [gaaudins_shrk_what_10]        CHAR (1)        NULL,
    [gaaudins_shrk_what_11]        CHAR (1)        NULL,
    [gaaudins_shrk_what_12]        CHAR (1)        NULL,
    [gaaudins_shrk_pct_1]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_2]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_3]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_4]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_5]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_6]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_7]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_8]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_9]          DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_10]         DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_11]         DECIMAL (7, 4)  NULL,
    [gaaudins_shrk_pct_12]         DECIMAL (7, 4)  NULL,
    [gaaudins_tic_comment]         CHAR (30)       NULL,
    [gaaudins_dlvry_rev_dt]        INT             NULL,
    [gaaudins_stor_schd_no]        TINYINT         NULL,
    [gaaudins_stor_tie_breaker]    SMALLINT        NULL,
    [gaaudins_cnt_no]              CHAR (8)        NULL,
    [gaaudins_cnt_seq_no]          SMALLINT        NULL,
    [gaaudins_cnt_sub_no]          SMALLINT        NULL,
    [gaaudins_cnt_loc_wrtn]        CHAR (3)        NULL,
    [gaaudins_advanced_yn]         CHAR (1)        NULL,
    [gaaudins_as_is_disc]          DECIMAL (9, 5)  NULL,
    [gaaudins_gl_acct_no]          DECIMAL (16, 8) NULL,
    [gaaudins_frt_un]              DECIMAL (11, 3) NULL,
    [gaaudins_frt_rt]              DECIMAL (9, 5)  NULL,
    [gaaudins_adv_man_auto_ind]    CHAR (1)        NULL,
    [gaaudins_adv_chk_no]          INT             NULL,
    [gaaudins_adv_reg_bas_ind]     CHAR (1)        NULL,
    [gaaudins_adj_ckoff_amt]       DECIMAL (7, 2)  NULL,
    [gaaudins_adj_ins_amt]         DECIMAL (7, 2)  NULL,
    [gaaudins_adj_tax3_amt]        DECIMAL (7, 2)  NULL,
    [gaaudins_adv_cnt_no]          CHAR (8)        NULL,
    [gaaudins_adv_to_cus_no]       CHAR (10)       NULL,
    [gaaudins_adv_cnt_loc]         CHAR (3)        NULL,
    [gaaudins_adj_csh_rcpt_yn]     CHAR (1)        NULL,
    [gaaudins_adv_audit_no]        CHAR (4)        NULL,
    [gaaudins_adv_tic_tie]         CHAR (3)        NULL,
    [gaaudins_adj_pay_pat_yn]      CHAR (1)        NULL,
    [gaaudins_rice_factor]         CHAR (1)        NULL,
    [gaaudins_wmp_whole]           DECIMAL (9, 5)  NULL,
    [gaaudins_wmp_broken]          DECIMAL (9, 5)  NULL,
    [gaaudins_loan_whole]          DECIMAL (9, 5)  NULL,
    [gaaudins_loan_broken]         DECIMAL (9, 5)  NULL,
    [gaaudins_currency]            CHAR (3)        NULL,
    [gaaudins_currency_rt]         DECIMAL (15, 8) NULL,
    [gaaudins_currency_cnt]        CHAR (8)        NULL,
    [gaaudins_cash_curr_rt]        DECIMAL (15, 8) NULL,
    [gaaudins_user_id]             CHAR (16)       NULL,
    [gaaudins_user_rev_dt]         CHAR (8)        NULL,
    [gaaudins_ckoff_exempt_yn]     CHAR (1)        NULL,
    [gaaudins_reversal_yn]         CHAR (1)        NULL,
    [gaaudins_cnt_cus_no]          CHAR (10)       NULL,
    [gaaudins_un_stor_adj]         DECIMAL (9, 6)  NULL,
    [gaaudins_xfer_yn]             CHAR (1)        NULL,
    [gaaudins_pgm_name]            CHAR (8)        NULL,
    [gaaudstr_spl_cus_no]          CHAR (10)       NULL,
    [gaaudstr_spl_no]              CHAR (4)        NULL,
    [gaaudstr_dlvry_rev_dt]        INT             NULL,
    [gaaudstr_stl_rev_dt]          INT             NULL,
    [gaaudstr_un_bal]              DECIMAL (11, 3) NULL,
    [gaaudstr_orig_un]             DECIMAL (11, 3) NULL,
    [gaaudstr_bin_no]              CHAR (5)        NULL,
    [gaaudstr_stor_schd_no]        TINYINT         NULL,
    [gaaudstr_un_disc_due]         DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_pd]          DECIMAL (9, 6)  NULL,
    [gaaudstr_un_stor_due]         DECIMAL (9, 6)  NULL,
    [gaaudstr_un_stor_pd]          DECIMAL (9, 6)  NULL,
    [gaaudstr_un_ins_rt]           DECIMAL (7, 4)  NULL,
    [gaaudstr_ins_state]           CHAR (2)        NULL,
    [gaaudstr_origin_state]        CHAR (2)        NULL,
    [gaaudstr_fees_due]            DECIMAL (7, 2)  NULL,
    [gaaudstr_fees_pd]             DECIMAL (7, 2)  NULL,
    [gaaudstr_un_frt_rt]           DECIMAL (9, 5)  NULL,
    [gaaudstr_cus_ref_no]          CHAR (15)       NULL,
    [gaaudstr_tic_comment]         CHAR (30)       NULL,
    [gaaudstr_disc_schd_no]        TINYINT         NULL,
    [gaaudstr_disc_cd_1]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_2]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_3]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_4]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_5]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_6]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_7]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_8]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_9]           CHAR (2)        NULL,
    [gaaudstr_disc_cd_10]          CHAR (2)        NULL,
    [gaaudstr_disc_cd_11]          CHAR (2)        NULL,
    [gaaudstr_disc_cd_12]          CHAR (2)        NULL,
    [gaaudstr_reading_1]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_2]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_3]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_4]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_5]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_6]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_7]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_8]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_9]           DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_10]          DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_11]          DECIMAL (7, 3)  NULL,
    [gaaudstr_reading_12]          DECIMAL (7, 3)  NULL,
    [gaaudstr_disc_calc_1]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_2]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_3]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_4]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_5]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_6]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_7]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_8]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_9]         CHAR (1)        NULL,
    [gaaudstr_disc_calc_10]        CHAR (1)        NULL,
    [gaaudstr_disc_calc_11]        CHAR (1)        NULL,
    [gaaudstr_disc_calc_12]        CHAR (1)        NULL,
    [gaaudstr_un_disc_amt_1]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_2]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_3]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_4]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_5]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_6]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_7]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_8]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_9]       DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_10]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_11]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_amt_12]      DECIMAL (9, 6)  NULL,
    [gaaudstr_shrk_what_1]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_2]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_3]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_4]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_5]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_6]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_7]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_8]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_9]         CHAR (1)        NULL,
    [gaaudstr_shrk_what_10]        CHAR (1)        NULL,
    [gaaudstr_shrk_what_11]        CHAR (1)        NULL,
    [gaaudstr_shrk_what_12]        CHAR (1)        NULL,
    [gaaudstr_shrk_pct_1]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_2]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_3]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_4]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_5]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_6]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_7]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_8]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_9]          DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_10]         DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_11]         DECIMAL (7, 4)  NULL,
    [gaaudstr_shrk_pct_12]         DECIMAL (7, 4)  NULL,
    [gaaudstr_un_disc_bill_1]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_2]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_3]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_4]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_5]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_6]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_7]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_8]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_9]      DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_10]     DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_11]     DECIMAL (9, 6)  NULL,
    [gaaudstr_un_disc_bill_12]     DECIMAL (9, 6)  NULL,
    [gaaudstr_tot_shrk_prc]        DECIMAL (5, 2)  NULL,
    [gaaudstr_tot_shrk_wgt]        DECIMAL (7, 4)  NULL,
    [gaaudstr_dpa_or_rcpt_no]      INT             NULL,
    [gaaudstr_takeout_yn]          CHAR (1)        NULL,
    [gaaudstr_currency]            CHAR (3)        NULL,
    [gaaudstr_currency_rt]         DECIMAL (15, 8) NULL,
    [gaaudstr_currency_cnt]        CHAR (8)        NULL,
    [gaaudstr_user_id]             CHAR (16)       NULL,
    [gaaudstr_user_rev_dt]         INT             NULL,
    [gaaudstr_reversal_yn]         CHAR (1)        NULL,
    [gaaudstr_src_pgm]             CHAR (8)        NULL,
    [gaauditr_gross_wgt]           DECIMAL (13, 3) NULL,
    [gaauditr_tare_wgt]            DECIMAL (13, 3) NULL,
    [gaauditr_comment]             CHAR (30)       NULL,
    [gaauditr_how_ship_ind]        CHAR (1)        NULL,
    [gaauditr_trkr_no]             CHAR (10)       NULL,
    [gaauditr_trkr_un_rt]          DECIMAL (9, 5)  NULL,
    [gaauditr_cnt_no]              CHAR (8)        NULL,
    [gaauditr_cnt_seq_no]          SMALLINT        NULL,
    [gaauditr_cnt_sub_seq_no]      SMALLINT        NULL,
    [gaauditr_cnt_loc_no]          CHAR (3)        NULL,
    [gaauditr_un_out]              DECIMAL (13, 3) NULL,
    [gaauditr_process_tic_no]      CHAR (15)       NULL,
    [gaauditr_wgt_accepted]        DECIMAL (13, 3) NULL,
    [gaauditr_un_accepted]         DECIMAL (11, 3) NULL,
    [gaauditr_use_dest_wgts_yn]    CHAR (1)        NULL,
    [gaauditr_direct_ship_yn]      CHAR (1)        NULL,
    [gaauditr_un_shrk]             DECIMAL (11, 3) NULL,
    [gaauditr_ship_rev_dt_info]    INT             NULL,
    [gaauditr_direct_rail_yn]      CHAR (1)        NULL,
    [gaauditr_pbhcu_ind]           CHAR (1)        NULL,
    [gaauditr_rail_ref_no_info]    CHAR (8)        NULL,
    [gaauditr_load_seq_info]       SMALLINT        NULL,
    [gaaudopt_bot]                 CHAR (1)        NULL,
    [gaaudopt_bot_opt]             CHAR (5)        NULL,
    [gaaudopt_option]              TINYINT         NULL,
    [gaaudopt_loc_no]              CHAR (3)        NULL,
    [gaaudopt_mkt_zone]            CHAR (3)        NULL,
    [gaaudopt_no_un]               DECIMAL (11, 3) NULL,
    [gaaudopt_trans_rev_dt]        INT             NULL,
    [gaaudopt_comments]            CHAR (15)       NULL,
    [gaaudopt_buy_sell]            CHAR (1)        NULL,
    [gaaudopt_put_call]            CHAR (1)        NULL,
    [gaaudopt_un_strk_prc]         DECIMAL (9, 5)  NULL,
    [gaaudopt_un_prem]             DECIMAL (9, 5)  NULL,
    [gaaudopt_un_srvc_fee]         DECIMAL (9, 5)  NULL,
    [gaaudopt_un_target_prc]       DECIMAL (9, 5)  NULL,
    [gaaudopt_exp_rev_dt]          INT             NULL,
    [gaaudopt_status_ind]          CHAR (1)        NULL,
    [gaaudopt_prem_srvc_ind]       CHAR (1)        NULL,
    [gaaudopt_bot_un_prc]          DECIMAL (9, 5)  NULL,
    [gaaudopt_prcd_rev_dt]         INT             NULL,
    [gaaudopt_prcd_un_prc]         DECIMAL (9, 5)  NULL,
    [gaaudopt_prcd_no_un]          DECIMAL (11, 3) NULL,
    [gaaudopt_prcd_amt]            DECIMAL (11, 2) NULL,
    [gaaudopt_currency]            CHAR (3)        NULL,
    [gaaudopt_currency_rt]         DECIMAL (15, 8) NULL,
    [gaaudopt_currency_cnt]        CHAR (8)        NULL,
    [gaaudopt_user_id]             CHAR (16)       NULL,
    [gaaudopt_user_rev_dt]         INT             NULL,
    [gaaudpay_hst_type]            CHAR (1)        NULL,
    [gaaudpay_loc_no]              CHAR (3)        NULL,
    [gaaudpay_spl_cus_no]          CHAR (10)       NULL,
    [gaaudpay_spl_no]              CHAR (4)        NULL,
    [gaaudpay_stl_amt]             DECIMAL (11, 2) NULL,
    [gaaudpay_wthhld_amt]          DECIMAL (11, 2) NULL,
    [gaaudpay_stl_rev_dt]          INT             NULL,
    [gaaudpay_defer_pmt_rev_dt]    INT             NULL,
    [gaaudpay_defer_pmt_cnt_no]    CHAR (8)        NULL,
    [gaaudpay_pd_yn]               CHAR (1)        NULL,
    [gaaudpay_man_auto_ind]        CHAR (1)        NULL,
    [gaaudpay_chk_no]              CHAR (8)        NULL,
    [gaaudpay_pmt_rev_dt]          INT             NULL,
    [gaaudpay_pmt_audit_no]        CHAR (4)        NULL,
    [gaaudpay_ivc_printed_yn]      CHAR (1)        NULL,
    [gaaudpay_ref_no]              CHAR (8)        NULL,
    [gaaudpay_ivc_rev_dt]          INT             NULL,
    [gaaudpay_audit_no]            CHAR (4)        NULL,
    [gaaudpay_cus_ref_no]          CHAR (15)       NULL,
    [gaaudpay_orig_type]           CHAR (1)        NULL,
    [gaaudpay_rail_ref_no]         INT             NULL,
    [gaaudpay_no_un]               DECIMAL (11, 3) NULL,
    [gaaudpay_un_prc]              DECIMAL (9, 5)  NULL,
    [gaaudpay_un_disc_adj]         DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_pd]          DECIMAL (9, 6)  NULL,
    [gaaudpay_un_stor_pd]          DECIMAL (9, 6)  NULL,
    [gaaudpay_ckoff_amt]           DECIMAL (7, 2)  NULL,
    [gaaudpay_origin_state]        CHAR (2)        NULL,
    [gaaudpay_ins_amt]             DECIMAL (7, 2)  NULL,
    [gaaudpay_ins_state]           CHAR (2)        NULL,
    [gaaudpay_tax3_amt]            DECIMAL (7, 2)  NULL,
    [gaaudpay_tax3_state]          CHAR (2)        NULL,
    [gaaudpay_fees_pd]             DECIMAL (7, 2)  NULL,
    [gaaudpay_un_frt_rt]           DECIMAL (9, 5)  NULL,
    [gaaudpay_un_cnt_fee]          DECIMAL (9, 5)  NULL,
    [gaaudpay_un_roll_fee]         DECIMAL (9, 5)  NULL,
    [gaaudpay_un_bot_basis]        DECIMAL (9, 5)  NULL,
    [gaaudpay_bot]                 CHAR (1)        NULL,
    [gaaudpay_bot_option]          CHAR (5)        NULL,
    [gaaudpay_tot_shrk_pct_wgt]    DECIMAL (7, 4)  NULL,
    [gaaudpay_disc_schd_no]        TINYINT         NULL,
    [gaaudpay_disc_cd_1]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_2]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_3]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_4]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_5]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_6]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_7]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_8]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_9]           CHAR (2)        NULL,
    [gaaudpay_disc_cd_10]          CHAR (2)        NULL,
    [gaaudpay_disc_cd_11]          CHAR (2)        NULL,
    [gaaudpay_disc_cd_12]          CHAR (2)        NULL,
    [gaaudpay_reading_1]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_2]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_3]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_4]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_5]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_6]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_7]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_8]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_9]           DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_10]          DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_11]          DECIMAL (7, 3)  NULL,
    [gaaudpay_reading_12]          DECIMAL (7, 3)  NULL,
    [gaaudpay_disc_calc_1]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_2]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_3]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_4]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_5]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_6]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_7]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_8]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_9]         CHAR (1)        NULL,
    [gaaudpay_disc_calc_10]        CHAR (1)        NULL,
    [gaaudpay_disc_calc_11]        CHAR (1)        NULL,
    [gaaudpay_disc_calc_12]        CHAR (1)        NULL,
    [gaaudpay_un_disc_amt_1]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_2]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_3]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_4]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_5]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_6]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_7]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_8]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_9]       DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_10]      DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_11]      DECIMAL (9, 6)  NULL,
    [gaaudpay_un_disc_amt_12]      DECIMAL (9, 6)  NULL,
    [gaaudpay_shrk_what_1]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_2]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_3]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_4]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_5]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_6]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_7]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_8]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_9]         CHAR (1)        NULL,
    [gaaudpay_shrk_what_10]        CHAR (1)        NULL,
    [gaaudpay_shrk_what_11]        CHAR (1)        NULL,
    [gaaudpay_shrk_what_12]        CHAR (1)        NULL,
    [gaaudpay_shrk_pct_1]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_2]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_3]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_4]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_5]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_6]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_7]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_8]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_9]          DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_10]         DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_11]         DECIMAL (7, 4)  NULL,
    [gaaudpay_shrk_pct_12]         DECIMAL (7, 4)  NULL,
    [gaaudpay_tic_comment]         CHAR (30)       NULL,
    [gaaudpay_dlvry_rev_dt]        INT             NULL,
    [gaaudpay_stor_schd_no]        TINYINT         NULL,
    [gaaudpay_stor_tie_breaker]    SMALLINT        NULL,
    [gaaudpay_cnt_no]              CHAR (8)        NULL,
    [gaaudpay_cnt_seq_no]          SMALLINT        NULL,
    [gaaudpay_cnt_sub_no]          SMALLINT        NULL,
    [gaaudpay_cnt_loc_wrtn]        CHAR (3)        NULL,
    [gaaudpay_advanced_yn]         CHAR (1)        NULL,
    [gaaudpay_as_is_disc]          DECIMAL (9, 5)  NULL,
    [gaaudpay_gl_acct_no]          DECIMAL (16, 8) NULL,
    [gaaudpay_frt_un]              DECIMAL (11, 3) NULL,
    [gaaudpay_frt_rt]              DECIMAL (9, 5)  NULL,
    [gaaudpay_adv_man_auto_ind]    CHAR (1)        NULL,
    [gaaudpay_adv_chk_no]          INT             NULL,
    [gaaudpay_adv_reg_bas_ind]     CHAR (1)        NULL,
    [gaaudpay_adj_ckoff_amt]       DECIMAL (7, 2)  NULL,
    [gaaudpay_adj_ins_amt]         DECIMAL (7, 2)  NULL,
    [gaaudpay_adj_tax3_amt]        DECIMAL (7, 2)  NULL,
    [gaaudpay_adv_cnt_no]          CHAR (8)        NULL,
    [gaaudpay_adv_to_cus_no]       CHAR (10)       NULL,
    [gaaudpay_adv_cnt_loc]         CHAR (3)        NULL,
    [gaaudpay_adj_csh_rcpt_yn]     CHAR (1)        NULL,
    [gaaudpay_adv_audit_no]        CHAR (4)        NULL,
    [gaaudpay_adv_tic_tie]         CHAR (3)        NULL,
    [gaaudpay_adj_pay_pat_yn]      CHAR (1)        NULL,
    [gaaudpay_rice_factor]         CHAR (1)        NULL,
    [gaaudpay_wmp_whole]           DECIMAL (9, 5)  NULL,
    [gaaudpay_wmp_broken]          DECIMAL (9, 5)  NULL,
    [gaaudpay_loan_whole]          DECIMAL (9, 5)  NULL,
    [gaaudpay_loan_broken]         DECIMAL (9, 5)  NULL,
    [gaaudpay_currency]            CHAR (3)        NULL,
    [gaaudpay_currency_rt]         DECIMAL (15, 8) NULL,
    [gaaudpay_currency_cnt]        CHAR (8)        NULL,
    [gaaudpay_cash_curr_rt]        DECIMAL (15, 8) NULL,
    [gaaudpay_user_id]             CHAR (16)       NULL,
    [gaaudpay_user_rev_dt]         CHAR (8)        NULL,
    [gaaudpay_dupl_cw_chk_yn]      CHAR (1)        NULL,
    [gaaudpay_gl_dep_cash]         DECIMAL (16, 8) NULL,
    [A4GLIdentity]                 NUMERIC (9)     IDENTITY (1, 1) NOT NULL,
    [gaaudpos_in_house]            DECIMAL (13, 3) NULL,
    [gaaudpos_offsite]             DECIMAL (13, 3) NULL,
    [gaaudpos_offsite_dp]          DECIMAL (13, 3) NULL,
    [gaaudpos_pur_in_transit]      DECIMAL (13, 3) NULL,
    [gaaudpos_sls_in_transit]      DECIMAL (13, 3) NULL,
    [gaaudpos_stor_1]              DECIMAL (13, 3) NULL,
    [gaaudpos_stor_2]              DECIMAL (13, 3) NULL,
    [gaaudpos_stor_3]              DECIMAL (13, 3) NULL,
    [gaaudpos_stor_4]              DECIMAL (13, 3) NULL,
    [gaaudpos_stor_5]              DECIMAL (13, 3) NULL,
    [gaaudpos_stor_6]              DECIMAL (13, 3) NULL,
    [gaaudpos_stor_7]              DECIMAL (13, 3) NULL,
    [gaaudpos_stor_8]              DECIMAL (13, 3) NULL,
    [gaaudpos_pur_basis_dlvry]     DECIMAL (13, 3) NULL,
    [gaaudpos_sls_basis_dlvry]     DECIMAL (13, 3) NULL,
    [gaaudpos_pur_cb_bas_dlv]      DECIMAL (13, 3) NULL,
    [gaaudpos_sls_cb_bas_dlv]      DECIMAL (13, 3) NULL,
    [gaaudpos_pur_prc_cnt]         DECIMAL (13, 3) NULL,
    [gaaudpos_pur_basis_cnt]       DECIMAL (13, 3) NULL,
    [gaaudpos_pur_hta_cnt]         DECIMAL (13, 3) NULL,
    [gaaudpos_pur_cb_cnt]          DECIMAL (13, 3) NULL,
    [gaaudpos_sls_prc_cnt]         DECIMAL (13, 3) NULL,
    [gaaudpos_sls_basis_cnt]       DECIMAL (13, 3) NULL,
    [gaaudpos_sls_hta_cnt]         DECIMAL (13, 3) NULL,
    [gaaudpos_sls_cb_cnt]          DECIMAL (13, 3) NULL,
    [gaaudpos_hedge]               DECIMAL (13, 3) NULL,
    [gaaudpos_net_pybl_amt]        DECIMAL (13, 2) NULL,
    [gaaudpos_pybl_un]             DECIMAL (13, 3) NULL,
    [gaaudpos_net_rcbl_amt]        DECIMAL (13, 2) NULL,
    [gaaudpos_rcbl_un]             DECIMAL (13, 3) NULL,
    [gaaudpos_pur_coll_rcpt]       DECIMAL (13, 3) NULL,
    [gaaudpos_sls_coll_rcpt]       DECIMAL (13, 3) NULL,
    [gaaudpos_stor_od]             DECIMAL (13, 3) NULL,
    [gaaudpos_in_in_house]         DECIMAL (13, 3) NULL,
    [gaaudpos_in_offsite]          DECIMAL (13, 3) NULL,
    [gaaudpos_in_offsite_dp]       DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_in_transit]   DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_in_transit]   DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_1]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_2]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_3]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_4]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_5]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_6]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_7]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_8]           DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_basis_dlvry]  DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_basis_dlvry]  DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_cb_bas_dlv]   DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_cb_bas_dlv]   DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_prc_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_basis_cnt]    DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_hta_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_cb_cnt]       DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_prc_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_basis_cnt]    DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_hta_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_cb_cnt]       DECIMAL (13, 3) NULL,
    [gaaudpos_in_hedge]            DECIMAL (13, 3) NULL,
    [gaaudpos_in_net_pybl_amt]     DECIMAL (13, 2) NULL,
    [gaaudpos_in_pybl_un]          DECIMAL (13, 3) NULL,
    [gaaudpos_in_net_rcbl_amt]     DECIMAL (13, 2) NULL,
    [gaaudpos_in_rcbl_un]          DECIMAL (13, 3) NULL,
    [gaaudpos_in_pur_coll_rcpt]    DECIMAL (13, 3) NULL,
    [gaaudpos_in_sls_coll_rcpt]    DECIMAL (13, 3) NULL,
    [gaaudpos_in_stor_od]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_in_house]        DECIMAL (13, 3) NULL,
    [gaaudpos_out_offsite]         DECIMAL (13, 3) NULL,
    [gaaudpos_out_offsite_dp]      DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_in_transit]  DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_in_transit]  DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_1]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_2]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_3]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_4]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_5]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_6]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_7]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_8]          DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_basis_dlvry] DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_basis_dlvry] DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_cb_bas_dlv]  DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_cb_bas_dlv]  DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_prc_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_basis_cnt]   DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_hta_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_cb_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_prc_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_basis_cnt]   DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_hta_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_cb_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_out_hedge]           DECIMAL (13, 3) NULL,
    [gaaudpos_out_net_pybl_amt]    DECIMAL (13, 2) NULL,
    [gaaudpos_out_pybl_un]         DECIMAL (13, 3) NULL,
    [gaaudpos_out_net_rcbl_amt]    DECIMAL (13, 2) NULL,
    [gaaudpos_out_rcbl_un]         DECIMAL (13, 3) NULL,
    [gaaudpos_out_pur_coll_rcpt]   DECIMAL (13, 3) NULL,
    [gaaudpos_out_sls_coll_rcpt]   DECIMAL (13, 3) NULL,
    [gaaudpos_out_stor_od]         DECIMAL (13, 3) NULL,
    [gaaudpos_adj_in_house]        DECIMAL (13, 3) NULL,
    [gaaudpos_adj_offsite]         DECIMAL (13, 3) NULL,
    [gaaudpos_adj_offsite_dp]      DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_in_transit]  DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_in_transit]  DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_1]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_2]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_3]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_4]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_5]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_6]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_7]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_8]          DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_basis_dlvry] DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_basis_dlvry] DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_cb_bas_dlv]  DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_cb_bas_dlv]  DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_prc_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_basis_cnt]   DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_hta_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_cb_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_prc_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_basis_cnt]   DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_hta_cnt]     DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_cb_cnt]      DECIMAL (13, 3) NULL,
    [gaaudpos_adj_hedge]           DECIMAL (13, 3) NULL,
    [gaaudpos_adj_net_pybl_amt]    DECIMAL (13, 2) NULL,
    [gaaudpos_adj_pybl_un]         DECIMAL (13, 3) NULL,
    [gaaudpos_adj_net_rcbl_amt]    DECIMAL (13, 2) NULL,
    [gaaudpos_adj_rcbl_un]         DECIMAL (13, 3) NULL,
    [gaaudpos_adj_pur_coll_rcpt]   DECIMAL (13, 3) NULL,
    [gaaudpos_adj_sls_coll_rcpt]   DECIMAL (13, 3) NULL,
    [gaaudpos_adj_stor_od]         DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_cash]            DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_cnt_fill]        DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_1]      DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_2]      DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_3]      DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_4]      DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_5]      DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_6]      DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_7]      DECIMAL (13, 3) NULL,
    [gaaudpos_ptd_stor_add_8]      DECIMAL (13, 3) NULL,
    [gaaudpos_last_eod_rev_dt]     INT             NULL,
    [gaaudpos_adj_comment]         CHAR (40)       NULL,
    [gaaudpos_state]               CHAR (2)        NULL,
    [gaaudxfr_comment]             CHAR (30)       NULL,
    [gaaudxfr_rev_dt]              INT             NULL,
    [gaaudxfr_no_un]               DECIMAL (11, 3) NULL,
    [gaaudxfr_frt_no]              CHAR (10)       NULL,
    [gaaudxfr_frt_no_un]           DECIMAL (11, 3) NULL,
    [gaaudxfr_frt_un_rt]           DECIMAL (9, 5)  NULL,
    [gaaudxfr_frt_gl_acct]         DECIMAL (16, 8) NULL,
    [gaaudxfr_un_prc]              DECIMAL (9, 5)  NULL,
    [gaaudxfr_cost]                DECIMAL (11, 2) NULL,
    [gaaudxfr_tic_comment]         CHAR (15)       NULL,
    [gaaudxfr_tot_shrk_pct_wgt]    DECIMAL (7, 4)  NULL,
    [gaaudxfr_disc_schd_no]        TINYINT         NULL,
    [gaaudxfr_disc_cd_1]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_2]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_3]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_4]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_5]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_6]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_7]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_8]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_9]           CHAR (2)        NULL,
    [gaaudxfr_disc_cd_10]          CHAR (2)        NULL,
    [gaaudxfr_disc_cd_11]          CHAR (2)        NULL,
    [gaaudxfr_disc_cd_12]          CHAR (2)        NULL,
    [gaaudxfr_reading_1]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_2]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_3]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_4]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_5]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_6]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_7]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_8]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_9]           DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_10]          DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_11]          DECIMAL (7, 3)  NULL,
    [gaaudxfr_reading_12]          DECIMAL (7, 3)  NULL,
    [gaaudxfr_un_disc_amt_1]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_2]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_3]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_4]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_5]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_6]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_7]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_8]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_9]       DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_10]      DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_11]      DECIMAL (9, 6)  NULL,
    [gaaudxfr_un_disc_amt_12]      DECIMAL (9, 6)  NULL,
    [gaaudxfr_shrk_what_1]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_2]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_3]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_4]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_5]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_6]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_7]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_8]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_9]         CHAR (1)        NULL,
    [gaaudxfr_shrk_what_10]        CHAR (1)        NULL,
    [gaaudxfr_shrk_what_11]        CHAR (1)        NULL,
    [gaaudxfr_shrk_what_12]        CHAR (1)        NULL,
    [gaaudxfr_shrk_pct_1]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_2]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_3]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_4]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_5]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_6]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_7]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_8]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_9]          DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_10]         DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_11]         DECIMAL (7, 4)  NULL,
    [gaaudxfr_shrk_pct_12]         DECIMAL (7, 4)  NULL,
    [gaaudxfr_from_bin_no]         CHAR (5)        NULL,
    [gaaudxfr_to_bin_no]           CHAR (5)        NULL,
    [gaaudxfr_audit_no]            CHAR (4)        NULL,
    [gaaudxfr_user_id]             CHAR (16)       NULL,
    [gaaudxfr_user_rev_dt]         INT             NULL,
    [gaaudstl_hst_type]            CHAR (1)        NULL,
    [gaaudstl_loc_no]              CHAR (3)        NULL,
    [gaaudstl_spl_cus_no]          CHAR (10)       NULL,
    [gaaudstl_spl_no]              CHAR (4)        NULL,
    [gaaudstl_stl_amt]             DECIMAL (11, 2) NULL,
    [gaaudstl_wthhld_amt]          DECIMAL (11, 2) NULL,
    [gaaudstl_stl_rev_dt]          INT             NULL,
    [gaaudstl_defer_pmt_rev_dt]    INT             NULL,
    [gaaudstl_defer_pmt_cnt_no]    CHAR (8)        NULL,
    [gaaudstl_pd_yn]               CHAR (1)        NULL,
    [gaaudstl_man_auto_ind]        CHAR (1)        NULL,
    [gaaudstl_chk_no]              CHAR (8)        NULL,
    [gaaudstl_pmt_rev_dt]          INT             NULL,
    [gaaudstl_pmt_audit_no]        CHAR (4)        NULL,
    [gaaudstl_ivc_printed_yn]      CHAR (1)        NULL,
    [gaaudstl_ivc_no]              CHAR (8)        NULL,
    [gaaudstl_ivc_rev_dt]          INT             NULL,
    [gaaudstl_audit_no]            CHAR (4)        NULL,
    [gaaudstl_cus_ref_no]          CHAR (15)       NULL,
    [gaaudstl_orig_type]           CHAR (1)        NULL,
    [gaaudstl_rail_ref_no]         INT             NULL,
    [gaaudstl_no_un]               DECIMAL (11, 3) NULL,
    [gaaudstl_un_prc]              DECIMAL (9, 5)  NULL,
    [gaaudstl_un_disc_adj]         DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_pd]          DECIMAL (9, 6)  NULL,
    [gaaudstl_un_stor_pd]          DECIMAL (9, 6)  NULL,
    [gaaudstl_ckoff_amt]           DECIMAL (7, 2)  NULL,
    [gaaudstl_origin_state]        CHAR (2)        NULL,
    [gaaudstl_ins_amt]             DECIMAL (7, 2)  NULL,
    [gaaudstl_ins_state]           CHAR (2)        NULL,
    [gaaudstl_tax3_amt]            DECIMAL (7, 2)  NULL,
    [gaaudstl_tax3_state]          CHAR (2)        NULL,
    [gaaudstl_fees_pd]             DECIMAL (7, 2)  NULL,
    [gaaudstl_un_frt_rt]           DECIMAL (9, 5)  NULL,
    [gaaudstl_un_cnt_fee]          DECIMAL (9, 5)  NULL,
    [gaaudstl_un_roll_fee]         DECIMAL (9, 5)  NULL,
    [gaaudstl_un_bot_basis]        DECIMAL (9, 5)  NULL,
    [gaaudstl_bot]                 CHAR (1)        NULL,
    [gaaudstl_bot_option]          CHAR (5)        NULL,
    [gaaudstl_tot_shrk_pct_wgt]    DECIMAL (7, 4)  NULL,
    [gaaudstl_disc_schd_no]        TINYINT         NULL,
    [gaaudstl_disc_cd_1]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_2]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_3]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_4]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_5]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_6]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_7]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_8]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_9]           CHAR (2)        NULL,
    [gaaudstl_disc_cd_10]          CHAR (2)        NULL,
    [gaaudstl_disc_cd_11]          CHAR (2)        NULL,
    [gaaudstl_disc_cd_12]          CHAR (2)        NULL,
    [gaaudstl_reading_1]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_2]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_3]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_4]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_5]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_6]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_7]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_8]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_9]           DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_10]          DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_11]          DECIMAL (7, 3)  NULL,
    [gaaudstl_reading_12]          DECIMAL (7, 3)  NULL,
    [gaaudstl_disc_calc_1]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_2]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_3]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_4]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_5]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_6]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_7]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_8]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_9]         CHAR (1)        NULL,
    [gaaudstl_disc_calc_10]        CHAR (1)        NULL,
    [gaaudstl_disc_calc_11]        CHAR (1)        NULL,
    [gaaudstl_disc_calc_12]        CHAR (1)        NULL,
    [gaaudstl_un_disc_amt_1]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_2]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_3]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_4]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_5]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_6]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_7]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_8]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_9]       DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_10]      DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_11]      DECIMAL (9, 6)  NULL,
    [gaaudstl_un_disc_amt_12]      DECIMAL (9, 6)  NULL,
    [gaaudstl_shrk_what_1]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_2]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_3]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_4]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_5]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_6]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_7]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_8]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_9]         CHAR (1)        NULL,
    [gaaudstl_shrk_what_10]        CHAR (1)        NULL,
    [gaaudstl_shrk_what_11]        CHAR (1)        NULL,
    [gaaudstl_shrk_what_12]        CHAR (1)        NULL,
    [gaaudstl_shrk_pct_1]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_2]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_3]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_4]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_5]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_6]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_7]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_8]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_9]          DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_10]         DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_11]         DECIMAL (7, 4)  NULL,
    [gaaudstl_shrk_pct_12]         DECIMAL (7, 4)  NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [Igaaudmst0]
    ON [dbo].[gaaudmst]([gaaud_pur_sls_ind] ASC, [gaaud_trans_type] ASC, [gaaud_key_filler1] ASC, [gaaud_in_type] ASC, [gaaud_key_filler2] ASC, [gaaud_tie_breaker] ASC);

