CREATE TABLE [dbo].[tblICBackupDetailLot]
(
	[intBackupDetailId]			INT NOT NULL IDENTITY(1, 1),
	[intBackupId]				INT NOT NULL,
	[intIdentityId]				INT NOT NULL,
	[intItemId]					INT NOT NULL,
	[intLocationId]				INT NOT NULL,
	[intItemLocationId]			INT NOT NULL,
	[intItemUOMId]				INT NOT NULL,			
	[strLotNumber]				NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, 
	[intSubLocationId]			INT NULL,
	[intStorageLocationId]		INT NULL,
	[dblQty]					NUMERIC(38,20) DEFAULT ((0)) NOT NULL,		
	[dblLastCost]				NUMERIC(38,20) DEFAULT ((0)) NULL,		
	[dtmExpiryDate]				DATETIME NULL,
	[strLotAlias]				NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[intLotStatusId]			INT NOT NULL DEFAULT ((1)),
	[intParentLotId]			INT NULL,
	[intSplitFromLotId]			INT NULL,
	[dblGrossWeight]			NUMERIC(38,20) NULL,
	[dblWeight]					NUMERIC(38,20) NULL DEFAULT ((0)),
	[intWeightUOMId]			INT NULL,
	[dblWeightPerQty]			NUMERIC(38,20) NULL DEFAULT ((0)),
	[intOriginId]				INT NULL,
	[strBOLNo]					NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
	[strVessel]					NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 		
	[strReceiptNumber]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strMarkings]				NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
	[strNotes]					NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL, 
	[intEntityVendorId]			INT NULL,		
	[strVendorLotNo]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strGarden]					NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL, 
	[strContractNo]				NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[dtmManufacturedDate]		DATETIME NULL,
	[ysnReleasedToWarehouse]	BIT DEFAULT((0)),
	[ysnProduced]				BIT DEFAULT((0)),
	[ysnStorage]				BIT DEFAULT((0)),
	[intOwnershipType]			INT NOT NULL DEFAULT ((1)),
	[intGradeId]				INT NULL,
	[intNoPallet]				INT NULL DEFAULT ((0)),
	[intUnitPallet]				INT NULL DEFAULT ((0)),
	[strTransactionId]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[strSourceTransactionId]	NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
	[intSourceTransactionTypeId] INT NULL,
	[dtmDateCreated]			DATETIME NULL,
	[intCreatedUserId]			INT NULL,
	[intCreatedEntityId]		INT NULL,

	[ysnLockedInventory]		BIT NULL DEFAULT(0),
	[intItemOwnerId]			INT NULL,
	[strContainerNo]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 		
	[strCondition]				NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 	
	[intSeasonCropYear]			INT NULL,
	[intCompanyId]				INT NULL, 
	[intBookId]					INT NULL,
	[intSubBookId]				INT NULL,
	[strCertificate]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 	
	[intProducerId]				INT	NULL,
	[strCertificateId]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 	
	[strTrackingNumber]			NVARCHAR(255) COLLATE Latin1_General_CI_AS NULL, 	
    [dtmDateModified]			DATETIME NULL,
    [intCreatedByUserId]		INT NULL,
    [intModifiedByUserId]		INT NULL,
	CONSTRAINT [PK_tblICBackupDetailLot] PRIMARY KEY CLUSTERED ([intBackupDetailId] ASC),
	CONSTRAINT [FK_tblICBackupDetailLot_tblICBackup] FOREIGN KEY ([intBackupId]) REFERENCES [tblICBackup]([intBackupId])
)