CREATE TABLE [dbo].[tblIPIDOCXMLArchive] (
	intIDOCXMLArchiveId INT NOT NULL IDENTITY(1, 1)
	,strXml NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL
	,strType NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL
	,dtmCreatedDate DATETIME CONSTRAINT [DF_tblIPIDOCXMLArchive_dtmCreatedDate] DEFAULT GETDATE()
	,CONSTRAINT [PK_tblIPIDOCXMLArchive_intIDOCXMLArchiveId] PRIMARY KEY (intIDOCXMLArchiveId)
	)
