CREATE TYPE [dbo].[PaymentIntegrationLogStagingTable] AS TABLE
(
	[Id]								INT NOT NULL  IDENTITY,
	[intIntegrationLogId]				INT NOT NULL,
	[dtmDate]							DATETIME  NULL,
    [intEntityId]						INT NULL,
	[intGroupingOption]					INT NULL,
	[strMessage]						NVARCHAR(500) COLLATE Latin1_General_CI_AS NULL,
	[strPostingMessage]					NVARCHAR(500) COLLATE Latin1_General_CI_AS NULL,
	[strBatchIdForNewPost]				NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intPostedNewCount]					INT NOT NULL DEFAULT ((0)),
	[strBatchIdForNewPostRecap]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intRecapNewCount]					INT NOT NULL DEFAULT ((0)),
	[strBatchIdForExistingPost]			NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intPostedExistingCount]			INT NOT NULL DEFAULT ((0)),
	[strBatchIdForExistingRecap]		NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intRecapPostExistingCount]			INT NOT NULL DEFAULT ((0)),
	[strBatchIdForExistingUnPost]		NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intUnPostedExistingCount]			INT NOT NULL DEFAULT ((0)),
	[strBatchIdForExistingUnPostRecap]	NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[intRecapUnPostedExistingCount]		INT NOT NULL DEFAULT ((0)),
	[intIntegrationLogDetailId]			INT	NULL,
	[intPaymentId]						INT NULL,
	[intEntityCustomerId]				INT NULL,
	[intCompanyLocationId]				INT NULL,
	[intCurrencyId]						INT NULL,
	[intPaymentDetailId]				INT NULL,
	[intId]								INT NULL,
	[strSourceTransaction]				NVARCHAR(250) COLLATE Latin1_General_CI_AS NULL,
	[intSourceId]						INT NULL,
	[strSourceId]						NVARCHAR(250) COLLATE Latin1_General_CI_AS NULL,
	[ysnPost]							BIT NULL,
	[ysnRecap]							BIT DEFAULT ((0)) NULL,
	[ysnInsert]							BIT NULL,
	[ysnHeader]							BIT DEFAULT ((0)) NOT NULL,
	[ysnSuccess]						BIT DEFAULT ((0)) NOT NULL,
	[ysnPosted]							BIT DEFAULT ((0)) NULL,
	[ysnUnPosted]						BIT DEFAULT ((0)) NULL,
	[strBatchId]						NVARCHAR(20) COLLATE Latin1_General_CI_AS NULL
)
