:r .\PostDeployment\CreateEncryptionCertificateAndSymmetricKey.sql
:r .\PostDeployment\EncryptionDataFix.sql

-- System Manager Default Data
:r .\PostDeployment\DefaultData\1_MasterMenu.sql
:r .\PostDeployment\DefaultData\2_UserRole.sql
:r .\PostDeployment\DefaultData\3_Currency.sql 
:r .\PostDeployment\DefaultData\4_StartingNumbers.sql
:r .\PostDeployment\DefaultData\5_CompanySetup.sql
:r .\PostDeployment\DefaultData\5_1_MultiCurrency.sql
:r .\PostDeployment\DefaultData\6_Preferences.sql
:r .\PostDeployment\DefaultData\7_EULA.sql
:r .\PostDeployment\DefaultData\8_Country.sql
:r .\PostDeployment\DefaultData\9_ZipCode.sql
:r .\PostDeployment\DefaultData\10_Screen.sql
:r .\PostDeployment\DefaultData\11_FreightTerms.sql
:r .\PostDeployment\DefaultData\12_ReminderList.sql
:r .\PostDeployment\DefaultData\13_ShortcutKey.sql
:r .\PostDeployment\DefaultData\14_CompanyPreference.sql
:r .\PostDeployment\DefaultData\15_Module.sql
:r .\PostDeployment\DefaultData\16_PaymentMethod.sql
:r .\PostDeployment\DefaultData\17_Notification.sql
:r .\PostDeployment\DefaultData\18_SecurityPolicy.sql
--:r .\SM\DefaultData\19_HomePanelDashboard.sql
:r .\PostDeployment\DefaultData\20_CustomFieldMigration.sql
:r .\PostDeployment\DefaultData\21_CommentMigration.sql
:r .\PostDeployment\DefaultData\22_TypeValue.sql
:r .\PostDeployment\DefaultData\23_ApproverConfigurationApprovalFor.sql
:r .\PostDeployment\DefaultData\25_ApprovalHistory.sql
:r .\PostDeployment\DefaultData\26_ActivitySource.sql
:r .\PostDeployment\DefaultData\27_Language.sql
:r .\PostDeployment\DefaultData\28_MultiCompany.sql
:r .\PostDeployment\DefaultData\29_TransportationMode.sql
:r .\PostDeployment\DefaultData\30_ImportFileHeader.sql
:r .\PostDeployment\DefaultData\31_Calendar.sql
:r .\PostDeployment\DefaultData\32_DynamicCSV.sql
:r .\PostDeployment\CustomField.sql
:r .\PostDeployment\1730_UpdateOriginSubMenusSorting.sql
:r .\PostDeployment\1730_PortalMenus.sql
:r .\PostDeployment\SMDataMigrations.SQL
:r .\PostDeployment\SMDataFixes.SQL
:r .\PostDeployment\1720_Statement_Footer_To_Report.sql
:r .\PostDeployment\1730_UpdatePatronageMenus.sql
:r .\PostDeployment\1730_EntityFavoriteMenu.sql
:r .\PostDeployment\1730_UpdateTicketManagementMenus.sql
:r .\PostDeployment\1730_UpdatePayrollMenus.sql
:r .\PostDeployment\1730_UpdateGeneralLedgerMenus.sql
:r .\PostDeployment\1710_to_1730_UpdateHomePanelDashboard.sql
:r .\PostDeployment\1730_UpdateManufacturingMenus.sql
:r .\PostDeployment\1740_UpdatePurchasingMenus.sql
:r .\PostDeployment\1740_UpdateSalesMenus.sql
:r .\PostDeployment\1740_RemoveLoadScheduleResources.sql
:r .\PostDeployment\1810_RenameCompanyToMultiCompany.sql
:r .\PostDeployment\1810_UpdatePortalMenus.sql
:r .\PostDeployment\1810_UpdateTransactionsApprovalFor.sql
:r .\PostDeployment\DefaultData\33_InterCompanyTransactionType.sql
:r .\PostDeployment\DefaultData\34_ReplicationTable.sql
:r .\PostDeployment\1810_Reset_Hours_Terms.sql
:r .\PostDeployment\1810_tblSMCompanyGridlayout_DeleteDuplicateRecords.sql
:r .\PostDeployment\DefaultData\35_Control.sql
:r .\PostDeployment\DefaultData\36_Control_Persmission.sql
:r .\PostDeployment\DefaultData\37_ReplicationConfiguration.sql
:r .\PostDeployment\DefaultData\38_ReplicationConfigurationTable.sql
:r .\PostDeployment\DefaultData\39_ReplicationConfigurationTable_InitOnly.sql
:r .\PostDeployment\1810_Reset_Hours_TaxCodeRate.sql
:r .\PostDeployment\1830_Arrange_Portal_Menus.sql

:r .\PostDeployment\VersionUpdate.sql
	 
:r .\PostDeployment\Offline\1_OfflineMenu.sql
:r .\PostDeployment\Offline\1_OfflineGuid.sql
	 
:r .\PostDeployment\Reports\1_ReportDisableConstraints.sql
:r .\PostDeployment\Reports\2_ReportDeleteOldData.sql
:r .\PostDeployment\Reports\3_ReportEnableConstraints.sql
:r .\PostDeployment\Reports\4_ReportData.sql
:r .\PostDeployment\Pxcyctag.sql