GO
	PRINT N'START DELETE OLD REPORT LABELS'
	IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'tblSMReportLabels') 
	BEGIN
		EXEC('DELETE tblSMReportLabels WHERE intLanguageId IS NULL')
	END
	PRINT N'END DEELTE OLD REPORT LABELS'
GO
