CREATE VIEW [dbo].[vyuEMEntity]
	AS 
	SELECT 
		A.intEntityId,
		A.strName,
		A.strEmail,
		A.strWebsite,
		A.strInternalNotes,
		A.ysnPrint1099,
		A.str1099Name,
		A.str1099Form,
		A.str1099Type,
		A.strFederalTaxId,
		A.dtmW9Signed,
		A.imgPhoto,
		A.strContactNumber,
		A.strTitle,
		A.strDepartment,
		A.strMobile,
		A.strPhone,
		A.strPhone2,
		A.strEmail2,
		A.strFax,
		A.strNotes,
		A.strContactMethod,
		A.strTimezone,
		A.strEntityNo,
		A.strContactType,
		A.intDefaultLocationId,
		A.ysnActive,
		A.ysnReceiveEmail,
		A.strEmailDistributionOption,
		A.dtmOriginationDate,
		A.strPhoneBackUp,
		A.intDefaultCountryId,
		A.strDocumentDelivery,
		A.strNickName,
		A.strSuffix,
		A.intEntityClassId,
		A.intConcurrencyId,
		B.strType
		FROM tblEMEntity A
			JOIN [tblEMEntityType] B
				ON A.intEntityId = B.intEntityId
