TRUNCATE TABLE tblTFOriginDestinationState
GO
SET IDENTITY_INSERT [dbo].[tblTFOriginDestinationState] ON 

INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (1, N'AL', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (2, N'AK', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (3, N'AZ', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (4, N'AR', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (5, N'CA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (6, N'CO', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (7, N'CT', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (8, N'DE', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (9, N'FL', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (10, N'GA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (11, N'HI', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (12, N'ID', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (13, N'IL', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (14, N'IN', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (15, N'IA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (16, N'KS', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (17, N'KY', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (18, N'LA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (19, N'ME', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (20, N'MD', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (21, N'MA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (22, N'MI', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (23, N'MN', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (24, N'MS', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (25, N'MO', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (26, N'MT', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (27, N'NE', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (28, N'NV', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (29, N'NH', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (30, N'NJ', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (31, N'NM', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (32, N'NY', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (33, N'NC', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (34, N'ND', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (35, N'OH', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (36, N'OK', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (37, N'OR', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (38, N'PA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (39, N'RI', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (40, N'SC', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (41, N'SD', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (42, N'TN', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (43, N'TX', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (44, N'UT', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (45, N'VT', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (46, N'VA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (47, N'WA', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (48, N'WV', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (49, N'WI', 0)
INSERT [dbo].[tblTFOriginDestinationState] ([intOriginDestinationStateId], [strOriginDestinationState], [intConcurrencyId]) VALUES (50, N'WY', 0)
SET IDENTITY_INSERT [dbo].[tblTFOriginDestinationState] OFF
