CREATE TYPE [dbo].[Entity] AS TABLE
(
	  Name NVARCHAR (100) COLLATE Latin1_General_CI_AS NOT NULL
	, Email NVARCHAR (75) COLLATE Latin1_General_CI_AS NOT NULL
	, Website NVARCHAR (100) COLLATE Latin1_General_CI_AS NOT NULL
	, InternalNotes NVARCHAR (MAX) COLLATE Latin1_General_CI_AS NOT NULL
	, Print1099 BIT
	, [1099Name] NVARCHAR (50) COLLATE Latin1_General_CI_AS NOT NULL
	, [1099Form] NVARCHAR (50) COLLATE Latin1_General_CI_AS NOT NULL
	, [1099Type] NVARCHAR (50) COLLATE Latin1_General_CI_AS NOT NULL
	, FederalTaxId NVARCHAR (50) COLLATE Latin1_General_CI_AS NOT NULL
	, W9Signed DATETIME
	, Photo VARBINARY(MAX) NULL
)
