CREATE TABLE [dbo].[tblHDRoughCountCapacity]
(
	[intRoughCountCapacityId] [int] IDENTITY(1,1) NOT NULL,
	[intSourceEntityId] [int] NOT NULL,
	[strSourceName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[intTicketId] [int] NOT NULL,
	[strTicketNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[intCustomerEntityId] [int] NOT NULL,
	[strCustomerName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[dblPlanFirstWeek] [numeric](18, 6) NULL,
	[dblPlanSecondWeek] [numeric](18, 6) NULL,
	[dblPlanThirdWeek] [numeric](18, 6) NULL,
	[dblPlanForthWeek] [numeric](18, 6) NULL,
	[dblPlanFifthWeek] [numeric](18, 6) NULL,
	[dblPlanSixthWeek] [numeric](18, 6) NULL,
	[dblPlanSeventhWeek] [numeric](18, 6) NULL,
	[dblPlanEighthWeek] [numeric](18, 6) NULL,
	[dblPlanNinthWeek] [numeric](18, 6) NULL,
	[dblPlanTenthWeek] [numeric](18, 6) NULL,
	[dblPlanEleventhWeek] [numeric](18, 6) NULL,
	[dblPlanTwelfthWeek] [numeric](18, 6) NULL,
	[dblEstimateFirstWeek] [numeric](18, 6) NULL,
	[dblEstimateSecondWeek] [numeric](18, 6) NULL,
	[dblEstimateThirdWeek] [numeric](18, 6) NULL,
	[dblEstimateForthWeek] [numeric](18, 6) NULL,
	[dblEstimateFifthWeek] [numeric](18, 6) NULL,
	[dblEstimateSixthWeek] [numeric](18, 6) NULL,
	[dblEstimateSeventhWeek] [numeric](18, 6) NULL,
	[dblEstimateEighthWeek] [numeric](18, 6) NULL,
	[dblEstimateNinthWeek] [numeric](18, 6) NULL,
	[dblEstimateTenthWeek] [numeric](18, 6) NULL,
	[dblEstimateEleventhWeek] [numeric](18, 6) NULL,
	[dblEstimateTwelfthWeek] [numeric](18, 6) NULL,
	[dblFirstWeek] [numeric](18, 6) NULL,
	[dblSecondWeek] [numeric](18, 6) NULL,
	[dblThirdWeek] [numeric](18, 6) NULL,
	[dblForthWeek] [numeric](18, 6) NULL,
	[dblFifthWeek] [numeric](18, 6) NULL,
	[dblSixthWeek] [numeric](18, 6) NULL,
	[dblSeventhWeek] [numeric](18, 6) NULL,
	[dblEighthWeek] [numeric](18, 6) NULL,
	[dblNinthWeek] [numeric](18, 6) NULL,
	[dblTenthWeek] [numeric](18, 6) NULL,
	[dblEleventhWeek] [numeric](18, 6) NULL,
	[dblTwelfthWeek] [numeric](18, 6) NULL,
	[dtmPlanDate] [datetime] NULL,
	[strFilterKey] [nvarchar](36) COLLATE Latin1_General_CI_AS NULL,
	[intConcurrencyId] [int] NOT NULL DEFAULT 1,
	CONSTRAINT [PK_tblHDRoughCountCapacity_intRoughCountCapacityId] PRIMARY KEY CLUSTERED ([intRoughCountCapacityId] ASC),
	CONSTRAINT [FK_tblHDRoughCountCapacity_tblEMENtity_intSourceEntityId] FOREIGN KEY ([intSourceEntityId]) REFERENCES [dbo].[tblEMEntity] ([intEntityId]),
    CONSTRAINT [FK_tblHDRoughCountCapacity_tblHDTicket_intTicketId] FOREIGN KEY ([intTicketId]) REFERENCES [dbo].[tblHDTicket] ([intTicketId]),
    CONSTRAINT [FK_tblHDRoughCountCapacity_tblEMENtity_intCustomerEntityId] FOREIGN KEY ([intCustomerEntityId]) REFERENCES [dbo].[tblEMEntity] ([intEntityId])
)
