CREATE TABLE [dbo].[tblIPIDOCXMLError] (
	intIDOCXMLErrorId INT NOT NULL IDENTITY(1, 1)
	,strXml NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL
	,strType NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL
	,strMsg NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL
	,dtmCreatedDate DATETIME CONSTRAINT [DF_tblIPIDOCXMLError_dtmCreatedDate] DEFAULT GETDATE()
	,CONSTRAINT [PK_tblIPIDOCXMLError_intIDOCXMLErrorId] PRIMARY KEY (intIDOCXMLErrorId)
	)
