CREATE TABLE [dbo].[tblPRElectronicFilingSUI]
(
	[intElectronicFilingSUIId] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[intYear] INT NOT NULL, 
    [intQuarter] INT NOT NULL, 
	[strState] NVARCHAR(2) COLLATE Latin1_General_CI_AS NULL, 
    [strFormat] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [strFileName] NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterEIN] NVARCHAR(9) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterAddress] NVARCHAR(40) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterCity] NVARCHAR(25) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterState] NVARCHAR(2) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterZipCode] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterZipCodeExt] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterContact] NVARCHAR(30) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterContactPhone] NVARCHAR(10) COLLATE Latin1_General_CI_AS NULL,
	[strSubmitterContactPhoneExt] NVARCHAR(4) COLLATE Latin1_General_CI_AS NULL,
	[strAuthorizationNumber] NVARCHAR(6) COLLATE Latin1_General_CI_AS NULL,
	[strC3Data] NVARCHAR(1) COLLATE Latin1_General_CI_AS NULL,
	[strSuffixCode] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL,
	[strAllocationLists] NVARCHAR(1) COLLATE Latin1_General_CI_AS NULL,
	[strServiceAgentID] NVARCHAR(9) COLLATE Latin1_General_CI_AS NULL,
	[strComputer] NVARCHAR(8) COLLATE Latin1_General_CI_AS NULL,
	[strInternalLabel] NVARCHAR(2) COLLATE Latin1_General_CI_AS NULL,
	[strDensity] NVARCHAR(2) COLLATE Latin1_General_CI_AS NULL,
	[strCharacterSet] NVARCHAR(3) COLLATE Latin1_General_CI_AS NULL,
	[intTracks] INT NULL,
	[intBlockingFactor] INT NULL,
	[strCompanyName] NVARCHAR(44) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyAddress] NVARCHAR(35) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyCity] NVARCHAR(20) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyState] NVARCHAR(2) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyZipCode] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL,
	[strCompanyZipCodeExt] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL,
	[strReasonForAdjustment] NVARCHAR(245) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerEIN] NVARCHAR(9) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerName] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerAddress] NVARCHAR(40) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerCity] NVARCHAR(25) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerState] NVARCHAR(2) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerZipCode] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerZipCodeExt] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL,
	[strEmploymentCode] NVARCHAR(1) COLLATE Latin1_General_CI_AS NULL,
	[strEstablishmentNumber] NVARCHAR(4) COLLATE Latin1_General_CI_AS NULL,
	[strSUIAccountNumber] NVARCHAR(15) COLLATE Latin1_General_CI_AS NULL,
	[strTaxTypeCode] NVARCHAR(1) COLLATE Latin1_General_CI_AS NULL,
	[strEmployerOtherEIN] NVARCHAR(9) COLLATE Latin1_General_CI_AS NULL,
	[dblSUITaxRate] NUMERIC(18, 6) NULL,
	[dblSUITaxDue] NUMERIC(18, 6) NULL,
	[dblUnderpayment] NUMERIC(18, 6) NULL,
	[dblInterest] NUMERIC(18, 6) NULL,
	[dblPenalty] NUMERIC(18, 6) NULL,
	[dblOverpayment] NUMERIC(18, 6) NULL,
	[dblEmployerAssessmentRate] NUMERIC(18, 6) NULL,
	[dblEmployerAssessmentAmount] NUMERIC(18, 6) NULL,
	[dblEmployeeAssessmentRate] NUMERIC(18, 6) NULL,
	[dblEmployeeAssessmentAmount] NUMERIC(18, 6) NULL,
	[dblTotalRemittance] NUMERIC(18, 6) NULL,
	[intConcurrencyId] INT NULL
)