
CREATE TABLE [dbo].[tblRKCommodityMarketMapping]
(
	[intCommodityMarketId] [INT]  IDENTITY(1,1) NOT NULL, 
    [intFutureMarketId] INT NOT NULL, 
    [intCommodityId] INT NOT NULL, 
	[strCommodityAttributeId] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL, 
	[strFutSymbol] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[intFutMonthsToOpen] [int] NULL,
	[intForecastWeeklyConsumption] INT NULL, 
	[intForecastWeeklyConsumptionUOMId] INT NULL, 
	[ysnOptions] [bit] NULL,
	[ysnActive] [bit] NULL,
	[dblContractSize] [numeric](18, 6) NULL,
	[intUnitMeasureId] [int] NULL,
	[intCurrencyId] [int] NULL,
	[ysnFutJan] [bit] NULL,
	[ysnFutFeb] [bit] NULL,
	[ysnFutMar] [bit] NULL,
	[ysnFutApr] [bit] NULL,
	[ysnFutMay] [bit] NULL,
	[ysnFutJun] [bit] NULL,
	[ysnFutJul] [bit] NULL,
	[ysnFutAug] [bit] NULL,
	[ysnFutSep] [bit] NULL,
	[ysnFutOct] [bit] NULL,
	[ysnFutNov] [bit] NULL,
	[ysnFutDec] [bit] NULL,
	[strOptMarketName] [nvarchar](30)COLLATE Latin1_General_CI_AS  NULL,
	[intOptMonthsToOpen] [int] NULL,
	[strOptSymbol] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[ysnOptJan] [bit] NULL,
	[ysnOptFeb] [bit] NULL,
	[ysnOptMar] [bit] NULL,
	[ysnOptApr] [bit] NULL,
	[ysnOptMay] [bit] NULL,
	[ysnOptJun] [bit] NULL,
	[ysnOptJul] [bit] NULL,
	[ysnOptAug] [bit] NULL,
	[ysnOptSep] [bit] NULL,
	[ysnOptOct] [bit] NULL,
	[ysnOptNov] [bit] NULL,
	[ysnOptDec] [bit] NULL,
    [intNoOfDecimal] INT NULL , 
    [intMarketExchangeId] INT NULL, 
    [strSymbolPrefix] NVARCHAR(5) COLLATE Latin1_General_CI_AS NULL, 
    [dblConversionRate] NUMERIC(18, 6) NULL DEFAULT 1, 
    [intReturnCurrency] INT NULL, 
    [intDisplayCurrency] INT NULL, 
    [strMarketSymbolCode] NVARCHAR(20) COLLATE Latin1_General_CI_AS NULL, 
	[strOptionSymbolPrefix] NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
    [intConcurrencyId] INT NOT NULL, 
    CONSTRAINT [PK_tblRKCommodityMarketMapping_intCommodityMarketId] PRIMARY KEY ([intCommodityMarketId]), 
    CONSTRAINT [FK_tblRKCommodityMarketMapping_intFutureMarketId] FOREIGN KEY ([intFutureMarketId]) REFERENCES [tblRKFutureMarket]([intFutureMarketId]) ON DELETE CASCADE, 
    CONSTRAINT [FK_tblRKCommodityMarketMapping_intCommodityId] FOREIGN KEY ([intCommodityId]) REFERENCES [tblICCommodity]([intCommodityId]) 
	)