CREATE TABLE [dbo].[tblRKM2MBasisDetail]
(
	[intM2MBasisDetailId] INT IDENTITY(1,1) NOT NULL,
	[intM2MBasisId] INT NOT NULL, 
    [intConcurrencyId] INT NOT NULL, 
    [intCommodityId] INT NOT NULL, 
    [intItemId] INT NULL, 
    [strOriginDest] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intFutureMarketId] INT  NULL, 
    [intFutureMonthId] INT  NULL, 
    [strPeriodTo] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intCompanyLocationId] INT NULL, 
    [intMarketZoneId] INT NULL, 
    [intCurrencyId] INT NULL, 
    [intPricingTypeId] INT NULL, 
    [strContractInventory] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL, 
    [intContractTypeId] INT NULL, 
    [dblCashOrFuture] NUMERIC(18, 6) NULL, 
	[dblRatio] NUMERIC(18, 6) NULL, 
    [dblBasisOrDiscount] NUMERIC(18, 6) NULL, 
    [intUnitMeasureId] INT NULL, 
    [strMarketValuation] NVARCHAR(250) COLLATE Latin1_General_CI_AS NULL,  
    CONSTRAINT [PK_tblRKM2MBasisDetail_intM2MBasisDetailId] PRIMARY KEY (intM2MBasisDetailId),
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblRKM2MBasis_intM2MBasisId] FOREIGN KEY([intM2MBasisId])REFERENCES [dbo].[tblRKM2MBasis] ([intM2MBasisId]) ON DELETE CASCADE,  
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblICCommodity_intCommodityId] FOREIGN KEY([intCommodityId])REFERENCES [dbo].[tblICCommodity] ([intCommodityId]),  
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblICItem_intItemId] FOREIGN KEY(intItemId)REFERENCES [dbo].[tblICItem] (intItemId),  
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblRKFutureMarket_intFutureMarketId] FOREIGN KEY(intFutureMarketId)REFERENCES [dbo].[tblRKFutureMarket] (intFutureMarketId),
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblRKFuturesMonth_intFutureMonthId] FOREIGN KEY(intFutureMonthId)REFERENCES [dbo].[tblRKFuturesMonth] (intFutureMonthId),
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblSMCompanyLocation_intCompanyLocationId] FOREIGN KEY(intCompanyLocationId)REFERENCES [dbo].[tblSMCompanyLocation] (intCompanyLocationId),
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblARMarketZone_intMarketZoneId] FOREIGN KEY(intMarketZoneId)REFERENCES [dbo].[tblARMarketZone] (intMarketZoneId),
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblSMCurrency_intCurrencyId] FOREIGN KEY(intCurrencyId)REFERENCES [dbo].[tblSMCurrency] (intCurrencyID),
	CONSTRAINT [FK_tblRKM2MBasisDetail_tblCTContractType_intContractTypeId] FOREIGN KEY(intContractTypeId)REFERENCES [dbo].[tblCTContractType] (intContractTypeId)
)