CREATE TABLE [dbo].[tblTMDeliveryFillReportStaging] (
    [intConcurrencyId]  INT DEFAULT 1 NOT NULL,
    [intDeliveryFillReportStagingId] INT IDENTITY (1, 1) NOT NULL,
    [intCustomerId] INT  NOT NULL,
    [strCustomerName]  NVARCHAR(100)    COLLATE Latin1_General_CI_AS    NOT NULL,
    [strCustomerPhone] NVARCHAR(50)  COLLATE Latin1_General_CI_AS NULL, 
	strCustomerNumber NVARCHAR(100)  COLLATE Latin1_General_CI_AS NOT NULL, 
	strCustomerTax NVARCHAR(50)  COLLATE Latin1_General_CI_AS NOT NULL, 
	dblCustomerPer1 NUMERIC(18,6)  NOT NULL,
	dblCustomerCreditLimit NUMERIC(18,6)  NOT NULL,
	dblCustomerLastStatement NUMERIC(18,6)  NOT NULL,
	dblCustomerTotalDue NUMERIC(18,6)  NOT NULL,
	dblCustomerFuture NUMERIC(18,6)  NULL,
	[intCustomerPriceLevel] INT  NULL,
	strTerms NVARCHAR(100)  COLLATE Latin1_General_CI_AS NULL, 
	dblCredits NUMERIC(18,6)  NULL,
	dblTotalPast NUMERIC(18,6)  NULL,
	dblARBalance NUMERIC(18,6)  NOT NULL,
	dblPastCredit NUMERIC(18,6)  NULL,
	intSiteNumber INT NOT NULL,
	dblSiteLastDeliveredGal NUMERIC(18,6)  NOT NULL,
	strSiteSequenceId NVARCHAR(50)  COLLATE Latin1_General_CI_AS NULL, 
	intSiteLastDeliveryDegreeDay INT NOT NULL,
	strSiteAddress NVARCHAR(MAX)  COLLATE Latin1_General_CI_AS NULL, 
	dtmOnHoldEndDate DATETIME NULL,
	ysnOnHold BIT NULL,
	strHoldReason NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	intFillMethodId INT NULL,
	strCity NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	strState NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	strZipCode NVARCHAR(100) COLLATE Latin1_General_CI_AS NULL,
	strComment NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	strInstruction NVARCHAR(MAX) COLLATE Latin1_General_CI_AS NULL,
	dblDegreeDayBetweenDelivery NUMERIC(18,6) NULL,
	dblTotalCapacity NUMERIC(18,6) NULL,
	dblTotalReserve NUMERIC(18,6) NULL,
	strSiteDescription NVARCHAR(200) COLLATE Latin1_General_CI_AS NULL,
	dblLastGalsInTank NUMERIC(18,6) NOT NULL,
	dtmLastDeliveryDate DATETIME NULL,
	intSiteId INT NOT NULL,
	dblEstimatedPercentLeft NUMERIC(18,6) NOT NULL,
	dtmNextDeliveryDate DATETIME NULL,
	intNextDeliveryDegreeDay INT NOT NULL,
	strSiteLabel NVARCHAR(4) COLLATE Latin1_General_CI_AS NOT NULL,
	strSiteDeliveryDD NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	dblDailyUse NUMERIC(18,6) NOT NULL,
	strFillGroupCode NVARCHAR(10) COLLATE Latin1_General_CI_AS NOT NULL,
	strFillGroupDescription NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	ysnFillGroupActive BIT NULL,
	intFillGroupId INT NULL,
	strDriverName NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	strDriverId NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	dtmRequestedDate DATETIME NULL,
	dblQuantity NUMERIC(18,6) NULL,
	strProductId NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
	strProductDescription NVARCHAR(250) COLLATE Latin1_General_CI_AS NULL,
	strRouteId NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,	
	strFillMethod NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,	
	strBetweenDlvry NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,	
	strLocation NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,	
	dtmForecastedDelivery DATETIME NULL,	
	ysnPending BIT NULL,	
	strItemClass NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,	
	dtmCallInDate DATETIME NULL,	
	dblCallEntryPrice NUMERIC(18,6) NULL,
	dblCallEntryMinimumQuantity NUMERIC(18,6) NULL,
	strCompanyName NVARCHAR(100) COLLATE Latin1_General_CI_AS NOT NULL,	
	intLocationId INT NULL,
	intDriverId INT NULL,
	intRouteId INT NULL,
	dblNextDeliveryGallons NUMERIC(18,6) NOT NULL,
	intGroupSiteCount INT NULL,
	intUserId INT NOT NULL,
	[strDateTimeId] NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL


    CONSTRAINT [PK_tblTMDeliveryFillReportStaging] PRIMARY KEY CLUSTERED ([intDeliveryFillReportStagingId] ASC), 
    [dblProductCost] NUMERIC(18, 6) NULL,
);


GO
